### ISSUE TITLE
Integrate with Lazy Librarian 

### ISSUE THREAD

**Issue by causefx** [tidusjar/PlexRequests.Net#103]
:)

**Comment by tidusjar** [comment]
What's Lazy Libarian? :)

**Comment by causefx** [comment]
auto-searcher for Books and Magazines :)

https://github.com/lazylibrarian/LazyLibrarian

**Comment by curlz620** [comment]
i've seen this, but i thought development on it stopped?

**Comment by tidusjar** [comment]
What's the difference between this and Mylar?

**Comment by causefx** [comment]
Mylar is strictly comics

**Comment by tidusjar** [comment]
Oh ok! 

I can add it to the backlog but unfortunately it isn't going to be done anytime soon, the next thing is Headphones and user integration

**Comment by causefx** [comment]
Take all the time in the world. No rush. You're the best!!!

**Comment by tidusjar** [comment]
@causefx I am not sure if we want to go down this route now. This is not what Plex Requests is, if we was going to do this we would need to change the name of the application since it has nothing to do with Plex.

If there is enough requests for this we will reconsider.

**Comment by ethanopp** [comment]
Would love to bring this back to life now that the name of the application has changed :)

DobyTang fork is very much alive:
https://github.com/DobyTang/LazyLibrarian

**Comment by claym** [comment]
Yep, would like to see this as well.

**Comment by b-rockx** [comment]
I would like to request that this be opened back up. The name of the app is no longer plex requests, so I see it fit that we add in book, comic and magazine requesting through LazyLibrarian! Thanks for the great work!

**Comment by tidusjar** [comment]
I'll think about it!

**Comment by Jafesu** [comment]
+1 I would love to use this for books as well

**Comment by KillerKongFu** [comment]
+1 This would be an amazing thing to add!

**Comment by nextnely** [comment]
this would be great!

**Comment by xthursdayx** [comment]
+1 for this (and Mylar) now that the name has changed to Ombi vs Plex Requests.

**Comment by cwilcoxc** [comment]
+1 from me!

**Comment by claym** [comment]
how did you link the RSS feeds?

**Comment by JordanReich** [comment]
+1 on this feature

**Comment by jfldsf** [comment]
+1

**Comment by dphildebrandt** [comment]
+1

**Comment by vimania** [comment]
+1

**Comment by markpeo** [comment]
Another vote here!

**Comment by auc0le** [comment]
+1

**Comment by starap11** [comment]
This would be amazing, hope to see this implemented some day

**Comment by jmurra21** [comment]
I'd like to join the party asking for a Mylar integration, I've spoken with the developer, and they would be fine, just need to make some minor api tweaks and it would work. It's really an amazing program, and something like Ombi could only make it even better. The Plex side of things are great, but this nerd loves his comics. 
Hope it happens! Thanks!

**Comment by oOStroudyOo** [comment]
+1 on the books. 
But I use Readarr

**Comment by TheDauthi** [comment]
+1 books.

On the one hand this is closed, on the other the closing message said "If there is enough requests for this we will reconsider."; I'm not sure what the preferred mechanism for those requests would be, so just +1-ing here.
