### ISSUE TITLE
More options for sorting of requests

### ISSUE THREAD

**Issue by EddiYo** [tidusjar/PlexRequests.Net#106]
Hi,

Any chance of some better control when sorting the requests? As it stands right now, "Default" and "Requested Date" does not really change much. For me, it is always preferable that the latest request is the one that shows at the top of the list, and not on the buttom of the list like it is now. If you have quite a few requests, the scrolling down part is a bit counterproductive.

And it seems I cant sort it that way by changing the options available right now.

**Comment by tidusjar** [comment]
Yes that's probably the best idea to have latest at the top by default. We will change that!

**Comment by Drewster727** [comment]
We've got this one added to 1.6.. We have 4 options now.

- Recent Requests (default)
- Older Requests
- Recent Releases
- Older Releases

**Comment by EddiYo** [comment]
Not sure if this really matters that much, but would calling the default one "Latest Requests" maybe make it easier for a user to distinguish? "Recent" is a relative term, "latest" makes it more specific. But I may be way off.

**Comment by Drewster727** [comment]
I see what you mean, you're probably right, "Latest Requests" is a little more user friendly. We'll fix that
