### ISSUE TITLE
System.Net.Sockets error, crashing PR

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#107]
Getting an error that is crashing Plex Requests, but doesn't show up in the log, only shows on the command prompt window. Here is the error: http://i.imgur.com/kwURyJI.png

None of it makes sense to me and maybe it's not Plex Request, but Windows erroring out. Seems to happen within 24 hours, but I don't watch it closely enough to tell the time table.

**Comment by tidusjar** [comment]
That's strange, it seems that it's attempting to connect to Plex to check if there are any updates on availability for the requests and it cannot connect and is bombing out. If it can't connect it usually just returns that nothing has been updated, but in your case there is something different going on. Do you have any logs in the `logs` folder in the install directory?

**Comment by Auwen** [comment]
I do have logs, but they don't contain any errors right before it dies like one would think.  

I'll clear the logs, let it run, and report back with them next time it happens.

**Comment by tidusjar** [comment]
It does seem quite unusual. 

I'll keep this open for a few days.

**Comment by Auwen** [comment]
PR crashed again, but slightly differently. Not sure if it's related, I'll be more than happy to split off into a different Issue if needed.

It crashed in the same way, but not a System.Net.Sockets error this time. This was a System.NullReferenceException. This happened when I tried to Remove the movie Happy Feet Two from PR.


Image of error in CMD promt: http://i.imgur.com/xCIS3vB.png
Pastebin of Log: http://pastebin.com/HXwrbPhp

The Trace Logs don't show anything to me, except for when I tried to Accept a movie that was already in CouchPotato, an unrelated issue.

**Comment by tidusjar** [comment]
It crashed this time when attempting to check if the current requests are in Plex (Does this every 5 minutes).

Do you have any logs of it saying anything about the `PlexAvailibiltyChecker` around this time?

**Comment by Auwen** [comment]
Through the two logs that I have from yesterday and today, I found no `PlexAvailibiltyChecker` anywhere.

**Comment by tidusjar** [comment]
@Auwen Looking through the code there is a race condition where it would be possible to get this error if you deleted a request while we are checking Plex to update the availability. I shall plus this hole, but did you delete a request at the time?

**Comment by Auwen** [comment]
It is extremely possible, but I am unsure at this time. I'll keep an eye out.  Though, I know there's been a few crashes that happened in the middle of the night, so maybe those aren't related?

**Comment by tidusjar** [comment]
@Auwen I don't understand why your version is crashing... It could be possibly something to do with either your data OR your environment. 

If you want me to keep digging into this are you able to send me your `plexrequests.sqlite` file to jamierees@outlook.com ?

To do this take a backup of your `plexrequests.sqlite`.
Then go back into the settings and do the following:

1. Remove all your API keys
1. Change the administrator password to `password1`

You can then send the database file.

Then delete the file you sent me and restore the `plexrequests.sqlite` file you took a backup of.

**Comment by tidusjar** [comment]
What version are you running? 

I think I got a rough idea where the problem is but I think your running version 1.5.1?
If so can you please upgrade to 1.5.2 as that will fix the logs not appearing issue.

It looks like that for some reason we are either losing connection to CP/Sonarr and it's also returning `{ "error": "Unauthorized" } ` which is unusual.

**Comment by Auwen** [comment]
PlexRequests is showing Version: 1.5.2 and no update available.

I can wipe it out and re-install if you think it'd help.

**Comment by tidusjar** [comment]
I don't think that will help.

I'm going to do some work to make the area that i'm pretty sure that is failing more robust tonight.

**Comment by nucshuco** [comment]
I am getting the random crashes also.
It happens a couple times a day.
I’m on windows 7 64

**Comment by tidusjar** [comment]
I think I know the problem area and have made it a lot more stable in the development branch. 1.6 will have these changes to hopefully fix this.
