### ISSUE TITLE
Unable to start on Debian

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/PlexRequests.Net#109]
I had to do a fresh install on my NAS, but now I can't get PlexRequests to run. 
<img width="1268" alt="screen shot 2016-03-27 at 2 16 04 pm" src="https://cloud.githubusercontent.com/assets/12055335/14066962/a55d1ed2-f426-11e5-8978-1547de0ec8e3.png">

**Comment by Drewster727** [comment]
I *think* I had something similar to this if you only have the runtime version of mono installed. Try installing the complete or developer version of mono to load all of the libraries.

**Comment by Codehhh** [comment]
Thank you so much! Installing mono-complete fixed the problem!
