### ISSUE TITLE
Can't connect to couch potato over SSL

### ISSUE THREAD

**Issue by heartisall** [tidusjar/PlexRequests.Net#112]
In the older versions I was actually able to connect just fine by putting https://  in the hostname box before the IP or using the check box. With version 1.5.2 I am not able to connect when I check the SSL check box. This is the Error I'm getting in the log:

`System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.1.15:5050 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request) --- End of inner exception stack trace --- at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 64 at PlexRequests.Api.CouchPotatoApi.GetStatus(Uri url, String apiKey) in C:\projects\requestplex\PlexRequests.Api\CouchPotatoApi.cs:line 94 at PlexRequests.UI.Modules.ApplicationTesterModule.CouchPotatoTest() in C:\projects\requestplex\PlexRequests.UI\Modules\ApplicationTesterModule.cs:line 72`

Any help would be great, Loving all of the other new features of 1.5 so far

**Comment by tidusjar** [comment]
@heartisall Why did you close it?

**Comment by heartisall** [comment]
Sorry, I found out it had to do with couch potato. For some reason the API key is different in couch potato now so when I copied it over and put it in my new install of 1.5 it didn't work. When I used the old API key from my 1.4.1 install it works. Literally makes no sense, but fairly certain it's a CP issue not Plex Requests
