### ISSUE TITLE
Allow choosing a quality profile upon approving

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#114]
I'd like to be able to pick the quality profile when I go to approve a movie/show. If the category is set to auto-approve, it should use the default. I tend to change the quality profile depending on the age of the show/movie.

I think this can be done from a UI standpoint easily via a bootstrap button dropdown.

**Comment by tidusjar** [comment]
Yeah pretty good idea. should be a setting for this. Some people might just want to download the quality selected in the settings.

**Comment by Drewster727** [comment]
this is done, but might need some tweaking. Definitely needs to be tested.
