### ISSUE TITLE
Admin Module is getting a bit big

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#117]
I suggest we split it out.

Opinions?

**Comment by Auwen** [comment]
Can you describe a bit more on what you think is the problem and solution? Are you talking about the Admin > Settings page?

**Comment by tidusjar** [comment]
Sorry, this is more of a technical implementation.

For each area of the application we have a `module`. All of the admin stuff is in a single module and it is quite big now and is going to continue growing (more settings + headphones etc).

**Comment by Drewster727** [comment]
perhaps a module for each settings section, maybe a base class that would provide us what we need in terms of injection? the URLs would all have a root path of /admin/... ?

**Comment by tidusjar** [comment]
@Drewster727 That is a good idea. I suggest we do this for 1.7.

**Comment by whitecollar17** [comment]
@tidusjar i can make a re-design if you like.

**Comment by tidusjar** [comment]
@whitecollar17 this issue is referring to the code, but if you want to redesign the UI for the admin pages then sure! (I didn't focus on them that much as the main UI as they are only used by the admin)
