### ISSUE TITLE
Remember Me not working for admin

### ISSUE THREAD

**Issue by heartisall** [tidusjar/PlexRequests.Net#121]
I have only tried in chrome but even when I tick the "remember me" check box I always have to login. The Username and PW is not being stored or prompted by chrome to be remembered.

**Comment by tidusjar** [comment]
@heartisall After looking at the code, the 'remember me' should keep your session for 7 days.

It will not remember you if you restart PlexRequests.Net

**Comment by tidusjar** [comment]
Are you still finding this a problem?

**Comment by heartisall** [comment]
It seems to be keeping my session now although chrome still doesn't prompt to save my credentials, I think the problem was that I was having to restart PlexRequests.net rather often which was killing it. I just updated to 1.6 today so I don't know if it will fix the lockups that I'm having yet.
