### ISSUE TITLE
Requested Date time is incorrect

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#122]
Requested a movie/show, then go check when it was requested, mine says "5 hours ago" even though it was requested less than a minute ago.

I think we're doing just a simple DateTime.Now when saving requests. We probably need to start storing this in UTC and convert as necessary.

**Comment by tidusjar** [comment]
We are doing a `DateTime.Now` which will return the local computer time that the code is running, I'm assuming your server doesn't have it's clock set correctly?

I agree using UTC and then converting it is the better way to do it, but If we are going to do this we will need to store the Users timezone and then also the requesting users timezone so it also appears correct for them.

**Comment by Drewster727** [comment]
The time clock is properly set to my time zone so I don't know how this could be. Reproduced on my dev windows box and prod linux box.

**Comment by Drewster727** [comment]
fixed
