### ISSUE TITLE
DB Lost After Upgrade

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#128]
#### Applicable Logs (from `/logs/` directory or the Admin page):
2016/04/01 17:33:58.558 PlexRequests.UI.Program Trace: Getting product version
2016/04/01 17:33:58.581 PlexRequests.UI.Program Info: Version: 1.5.2
2016/04/01 17:33:58.600 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/04/01 17:34:45.848 PlexRequests.UI.Program Trace: Getting product version
2016/04/01 17:34:45.885 PlexRequests.UI.Program Info: Version: 1.5.2
2016/04/01 17:34:45.903 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/04/01 17:34:48.923 PlexRequests.UI.Program Trace: Getting startup Port 
2016/04/01 17:34:49.160 PlexRequests.UI.Program Trace: Port: 3579 
2016/04/01 17:34:53.637 PlexRequests.UI.Program Trace: We are on Mono! 
2016/04/01 17:37:22.084 PlexRequests.UI.Modules.SearchModule Trace: Loading Index 

#### Reproduction Steps:

I upgraded from 1.4.1, first time I launched it stalled out at the Version line when ran. Second time I started it completed started but my DB was gone. This is likely because I stopped it in the middle of checking the DB. There was no message or anything provided to give one the impression it was doing anything, to wait, and to not stop while this process was occurring.

**Comment by tedrock** [comment]
Appears this was actually a result of the 1.5.0 update. Disregard

**Comment by tidusjar** [comment]
@tedrock Sorry, what was the issue here?

**Comment by tedrock** [comment]
I thought my DB was gone because I had to make a new admin. I discovered I was mistaken when I read the release notes. I do have a real issue now though #129
