### ISSUE TITLE
No search for TV when only searching for TV.

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/PlexRequests.Net#131]
#### Plex Requests.Net Version:
1.5.2

#### Operating System:
Ubuntu 14.04.4 LTS

#### Mono Version:
mono 3.2.8

#### Reproduction Steps:
Deselect "Search for Movies"
Go back to main page.
*Note:* You can still search by hitting the tab.
![ss 2016-04-02 at 06 49 56](https://cloud.githubusercontent.com/assets/12055335/14229541/c498922c-f903-11e5-9d68-5cb83d6dfc29.png)

**Comment by tidusjar** [comment]
Ah. The TV show tab is not active. You will need to click on it.
We should fix this.
