### ISSUE TITLE
Auto-approve for Admins

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#132]
Admins will probably also use this app to easily queue up movies/shows/albums/etc. It makes sense to auto-approve their requests (even when approval is required for that particular category) -- as they are the ones who will be doing the approving!

We should either enable this by default (my preference) or add a settings option for it.

@tidusjar

**Comment by tidusjar** [comment]
By default sounds good.

**Comment by Drewster727** [comment]
done!
