### ISSUE TITLE
Start adding to the Wiki

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#138]
We should start adding instructions for various operating systems, dependencies (i.e. mono) and perhaps some simple troubleshooting tips into the wiki.

Also, it might be good to add some dev instructions for people who want to contribute, instructing them on how to setup their dev environment.

**Comment by Codehhh** [comment]
Here is the startup script I used for my debian install. It assumes that monodevelop or mono-complete is installed to the default directory and PlexRequests.NET is installed to /opt/PlexRequests/

[PlexRequest init.d Script.txt](https://github.com/tidusjar/PlexRequests.Net/files/205147/PlexRequest.init.d.Script.txt)

**Comment by Drewster727** [comment]
thanks @Codehhh - I actually have some instructions written up using upstart. We also have to modify existing instructions to make sure users have the latest version of mono, 4.x

**Comment by Drewster727** [comment]
@Codehhh  check the dev branch main page and take a look at those instructions, see if it makes sense and is easier for users.

**Comment by Codehhh** [comment]
@Drewster727 I would have used upstart, but my NAS uses a special build of Debian, so have to make a daemon that way. Maybe have both in the wiki?

**Comment by Drewster727** [comment]
Sure, I don't see why not. We'll add when we move over to the wiki. Thanks!

**Comment by bootldrDNB** [comment]
@Codehhh Hi! I used your init.d script on my Ubuntu 14.04 server, and it seems that PlexRequests dies every couple hours or so, while running the program manually using mono, I have 100% uptime. Do you know what the culprit could be here?

**Comment by Codehhh** [comment]
@bootldrDNB Go to you app root and upload the log so we can get to the bottom of this!

**Comment by tidusjar** [comment]
@bootldrDNB Yeah, we need to see why it potentially died :)

**Comment by bootldrDNB** [comment]
Alright, got the log here.

http://pastie.org/private/elycijwe8gqwpdkpxguzdg

**Comment by tidusjar** [comment]
@bootldrDNB OS?

**Comment by tidusjar** [comment]
Well that is strange... I have never come across that issue with NLog before (Been using it for at least 3 years).

**Comment by bootldrDNB** [comment]
Nope, its been running now for 2 days with no crashes. With the init.d script, it crashes after a few hours. Might make a script based on my rtorrent script, running rtorrent in a screen session.

**Comment by Drewster727** [comment]
@bootldrDNB what port are you running PR on? I had an issue where I was running it on port 80 and some app/service in my ubuntu server box was booting it off that port after x amount of time, never did figure out what was causing it. However, I confirmed mono was still running after that happened. I reinstalled my whole box and the problem went away. Could be related, probably not...

**Comment by bootldrDNB** [comment]
I'm running it on its standard port, 3579. :)

**Comment by bootldrDNB** [comment]
UPDATE: The application crashed after 3 days in screen.

**Comment by tidusjar** [comment]
Same error in the logs?

**Comment by bootldrDNB** [comment]
Yes. :(
