### ISSUE TITLE
Admin account doesn't show any Requests if admin account name is a user's name

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#143]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.6.0

#### Operating System:
Windows 10 64bit

#### Reproduction Steps:

Set up the admin account with a user's name instead of something generic like "Admin", go into Requests, and see nothing. I originally thought this was due to the new "Users can view their own requests only" feature, but I turned that off and still cannot see previous requests.

As a side note, how can I re-setup the admin account without losing all the current requests?

#### Troubleshooting Steps Performed:

I saved my PlexRequets.sqlite and completely wiped the install directory with a fresh copy, setup the admin account with "Admin" instead. Everything worked as expected. I overwrote the PlexRequests.sqlite with the backup copy and the issues came back. Maybe this is related to the sqlite version instead of Admin account name instead?

**Comment by Auwen** [comment]
...Uhhh... nevermind. Dunno why, but it fixed itself.

**Comment by tidusjar** [comment]
I suspect this is due to your browser cache, we changed the way we filter requests, so the data was slightly different.
