### ISSUE TITLE
SickRage API fails

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/PlexRequests.Net#144]
#### Plex Requests.Net Version:

v1.6.0
#### Operating System:

ReadyNASOS 6.4.2 (based on Debian 7)
#### Mono Version:

mono 4.2.3

#### SickRage Version:
SickRage 2016.03.28-2

#### Reproduction Steps:
Request TV. The show is still added, but "Something went wrong" popped up.
![ss 2016-04-06 at 02 47 26](https://cloud.githubusercontent.com/assets/12055335/14328876/aae61fba-fc06-11e5-983b-bf59028d18a2.png)

**Comment by tidusjar** [comment]
@shiitake this look like its to do with your changes. Any idea?

**Comment by csy7550** [comment]
Just confirming this one also, exactly the same problem here.

**Comment by tidusjar** [comment]
I'll take a look when I get home. @shiitake if you have any ideas please let me know.

**Comment by tidusjar** [comment]
@Codehhh  @csy7550 I have fixed the issue where we couldn't covert the type, but I could never get it to appear with 'Something went wrong'.

Is anyone willing to try out the dev build with the fix to make sure it fixes the issue before I push a release?

**Comment by Codehhh** [comment]
I can test out the dev build. Just linkme and I'll let you know what
happens.

**Comment by tidusjar** [comment]
@Codehhh https://ci.appveyor.com/project/tidusjar/requestplex/build/1.6.225/artifacts

**Comment by Codehhh** [comment]
@tidusjar That fixed it for me!

**Comment by tidusjar** [comment]
@Codehhh Excellent. It settings the seasons selected correctly in Sickrage? (If you selected First season or Latest)?

**Comment by tidusjar** [comment]
Looking at the logs this is what we got back from SickRage:

      "message": "An existing indexerid already exists in database",

But that should have appeared in the notification for you.

Latest season will set the most recent season as 'Wanted'

Can you delete the log file and repo it and then upload the logs?

**Comment by Codehhh** [comment]
by repo it do you mean add it to git?

**Comment by tidusjar** [comment]
@Codehhh Sorry, reproduce the error.

**Comment by Codehhh** [comment]
The Bachelor: All Seasons
The Bachelor Australia: First Season
The Bachelor Canada: Latest Season
[2016-04-07.txt](https://github.com/tidusjar/PlexRequests.Net/files/208726/2016-04-07.txt)

**Comment by tidusjar** [comment]
I can't seem to find out what is going on. What timezone are you in? Can we do a remote session so I can take a look?

**Comment by Codehhh** [comment]
I'm in EST. I will be free in roughly 3 hours, have class until then. Let me know when you're free and how we can communicate more privately.

**Comment by tidusjar** [comment]
Ok I should be free around them. We can communicate privately on Gitter.

**Comment by tidusjar** [comment]
Fixed.
