### ISSUE TITLE
Empty search fields

### ISSUE THREAD

**Issue by magnum226** [tidusjar/PlexRequests.Net#145]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Mono Version:

![blank](https://cloud.githubusercontent.com/assets/18314117/14328788/db8dc7b6-fbfd-11e5-931a-c29561d57c02.PNG)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps: Not sure. This happened as soon as I started the newly downloaded version.

You can see in the attached image that when I type in the search field it searches properly, but does not show the typed text. This happens in movies, tv, or album search fields. I have tried both with and without my reverse proxy both locally and remotely and have cleared my cache on each set up.

Tried using both Windows 7 and 8.1 and Firefox 45.0.1 and IE 11 on both. Same results from all set ups.

**Comment by Codehhh** [comment]
I have this same issue in Firefox 45.0.1 on Windows 10.
It works on Chrome for me, so I just use that for requests.

**Comment by tidusjar** [comment]
Ok. I'll see what's going on.

**Comment by csy7550** [comment]
Just confirming, I got the exact same problem.

**Comment by tidusjar** [comment]
@csy7550 I'll take a look soon.

**Comment by Drewster727** [comment]
fixed, should get rolled out in the next point release. (hopefully soon)
