### ISSUE TITLE
No .exe in v1.6 release zip file. 

### ISSUE THREAD

**Issue by sch1308** [tidusjar/PlexRequests.Net#146]
![image](https://cloud.githubusercontent.com/assets/7896067/14333455/bf889c34-fc1c-11e5-811d-3ac29ba33819.png)

**Comment by Drewster727** [comment]
you must have grabbed the source code by accident, try this link for v1.6:
https://github.com/tidusjar/PlexRequests.Net/releases/download/v1.6.0/PlexRequests.zip
