### ISSUE TITLE
Test Email Notification not working on Mono

### ISSUE THREAD

**Issue by evilspectre** [tidusjar/PlexRequests.Net#147]
#### Plex Requests.Net Version:
1.6.0

#### Operating System:
Debian 8

#### Mono Version:
4.2.3

#### Applicable Logs (from `/logs/` directory or the Admin page):

2016/04/06 16:16:06.852 PlexRequests.UI.Modules.AdminModule Trace: {
  "EmailHost": "localsmtp",
  "EmailPort": 25,
  "Ssl": false,
  "RecipientEmail": "email@address.net",
  "EmailSender": "email@address.net",
  "EmailUsername": "localuser",
  "EmailPassword": "pass",
  "Enabled": true,
  "Id": 0
} 
2016/04/06 16:16:06.862 PlexRequests.UI.Modules.AdminModule Info: Saved email settings, result: True 
2016/04/06 16:16:07.888 PlexRequests.UI.Modules.AdminModule Info: Sent email notification test 

#### Reproduction Steps:

I am able to send test email notifications on Windows 2012R2 with .Net 4.6.1, but cannot send test email notifications running either Docker image or Debian VM using the same email settings.

**Comment by tidusjar** [comment]
And I assume that the email host is correct when you are running it through docker or debian?

**Comment by tidusjar** [comment]
@evilspectre  Also can you see it in your sent folder (Using some sort of email application) and you sure it's not in Spam/junk?

**Comment by Drewster727** [comment]
@tidusjar I can confirm this as well, same issue on ubuntu server w/ mono 4.2.3. Email settings are correct.

**Comment by evilspectre** [comment]
@tidusjar the email server I am using is an in network SMTP relay, looking at the logs it does not even speak to the STMP server.

**Comment by tidusjar** [comment]
Yeah, it's a problem in mono, we are going to switch out the SMTP bit for mono's reccomended SMTP client.

**Comment by krikv** [comment]
I've got the same problem as above, however the test email isn't my only problem. I've configured Plex Requests to use my mailserver, test email doesn't work and when a user requests an item, I don't receive an email either.
PlexRequests host: Debian 8 in an container using mono 4.2.3
Mailserver: imap using starttls over port 587

**Comment by tidusjar** [comment]
@krikv Correct, email's currently do not work

**Comment by krikv** [comment]
@tidusjar Thank you, I wan't sure if it was just the problem with the test mail or mailing in general. Thanks for clearing that up!

**Comment by tidusjar** [comment]
Fixed in release 1.6.1
