### ISSUE TITLE
CouchPotato API Fails

### ISSUE THREAD

**Issue by dfgsaerh** [tidusjar/PlexRequests.Net#148]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

1.6.0 Plex Requests.Net Version:

Windows 7 Operating System:

4.2.3 Mono Version:

Applicable Logs (from `/logs/` directory or the Admin page):

System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 2, position 3. at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args) at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2) at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl() at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options) at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options) at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw) --- End of inner exception stack trace --- at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 60 at PlexRequests.Api.CouchPotatoApi.GetStatus(Uri url, String apiKey) in C:\projects\requestplex\PlexRequests.Api\CouchPotatoApi.cs:line 94 at PlexRequests.UI.Modules.ApplicationTesterModule.CouchPotatoTest() in C:\projects\requestplex\PlexRequests.UI\Modules\ApplicationTesterModule.cs:line 75

**Comment by tidusjar** [comment]
This is usually because it cannot authenticate, are you sure it's correctly setup e.g. IP/Hostname correct, SSL box, Subdir (if using)?

**Comment by dfgsaerh** [comment]
Thanks for the fast reply and all the work that goes into this project. it's awesome
If i go to localhost:port/api/<myapikeyhere> that works, mind you the address changes to localhost:port/couchpotato/25DigitHexValue

**Comment by tidusjar** [comment]
Wait. So what is the URL you use for accessing couchpotato?

**Comment by dfgsaerh** [comment]
Normally just access CP with localhost:port
I just saw when I googled the error you asking someone to try browsing to localhost:port/api/APIKEY

**Comment by tidusjar** [comment]
Ah ok! So are you using some sort of reverse proxy? In the `SubDir` can you put in `couchpotato` ?

**Comment by dfgsaerh** [comment]
Nope not using a reverse proxy, but I put couchpotato into SubDir and it's all working now,
Thanks for that.

**Comment by tidusjar** [comment]
Yeah if it was redirecting you to `localhost:port/couchpotato/` when attempting to get the api we would need that. :+1:
