### ISSUE TITLE
 PlexRequests.UI crashed on fresh install

### ISSUE THREAD

**Issue by phairplay** [tidusjar/PlexRequests.Net#149]
Hi I've just tried to install your the latest version of plex request.net for the first time on my window 8 64bit machine and after ensuring its unblocked and unzipped I run plexrequests.exe and the plexrequests.ui crashes and I see this in the logs

http://pastebin.com/QP8yHaVv

could you please help me resolve this issue

**Comment by tidusjar** [comment]
You need to run it as an admin.

You can read [here](https://github.com/tidusjar/PlexRequests.Net/wiki/FAQ#how-can-i-run-plex-requestsnet-as-a-non-administrator) if you do not want to run as admin.
