### ISSUE TITLE
Cache plex, couchpotato, sonarr, and sickrage content and compare the search data

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#150]
We have an opportunity to provide more real-time feedback on search results (in terms of requested status) by checking against what's already in CP/Sonarr/Sickrage upon searching.

Instead of querying these apps every search, we should cache their wanted/queued items at some specified interval, and cache the results, then use the cache to compare against.

Couch is already done in dev.

**Comment by Drewster727** [comment]
Sonarr/SickRage caching added. @tidusjar  I put two small TODO marks in commit 5f67302. Any way you can do those two small items? I don't have sickrage setup. Should just need to add the model and return the IDs correctly from the cache.

**Comment by Drewster727** [comment]
Plex content caching added. Music part needs testing @tidusjar

**Comment by tidusjar** [comment]
Included in  build 1.6.1
