### ISSUE TITLE
New Episodes (SickRage)

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/PlexRequests.Net#151]
When selecting episodes, "Latest Season" should say "New Episodes" because it sets new episodes to wanted in SickRage

**Comment by tidusjar** [comment]
That's a good point. It gets the latest season and sets future seasons as wanted. 
If we put it as New Episodes it would still be misleading as it would grab the latest season (if the series has ended for example). 
Hmmm...

**Comment by tidusjar** [comment]
@Codehhh Does it not set the current season as wanted in SR?

**Comment by tidusjar** [comment]
@Codehhh So that's correct then, since the latest season is the current season :)
