### ISSUE TITLE
Pushover Notifications not working

### ISSUE THREAD

**Issue by shire210** [tidusjar/PlexRequests.Net#152]
#### Applicable Logs (from `/logs/` directory or the Admin page):

2016/04/09 07:58:20.112 PlexRequests.UI.Modules.AdminModule Info: Sent pushover notification test 

#### Reproduction Steps:

Entered my information for Pushover into the app and it does not work. I saw there was a previous issue (#93) that is now closed, but it is still not working for me.

**Comment by gaandu** [comment]
I am also facing the same issue

**Comment by tidusjar** [comment]
We have fixed this in the latest build. We will be releasing soon

**Comment by tidusjar** [comment]
Fixed in release 1.6.1
