### ISSUE TITLE
NSSM Steps Wrong Order. 

### ISSUE THREAD

**Issue by theg1nger** [tidusjar/PlexRequests.Net#153]
Hey Jamie, 

Thanks for putting my NSSM steps in the FAQ! 

I noticed something though, when I originally wrote it I actually got step 9 and 10 switch. It should read:
9. Click Install Service
10. In the same CMD admin window type "nssm start plexrequest"

This isn't a huge deal, but could be confusing to users trying to follow the steps to the T. 

Thought I'd share this with you. 
-Winston

**Comment by tidusjar** [comment]
Are you able to change them in the FAQ? :)

**Comment by theg1nger** [comment]
Not sure you have that turned on. I don't see where I can make the change. I'm happy to do it, just don't see the option.

**Comment by tidusjar** [comment]
All done!
