### ISSUE TITLE
Cpu 100% after using plex requests 

### ISSUE THREAD

**Issue by phairplay** [tidusjar/PlexRequests.Net#154]
Hi,
after making several requests through plex requests I found that plex media server was running at 326% pushing my cpu to 100%
 What could be the cause?

Windows 8
I5 Intel 
Latest version of plex requests

**Comment by tidusjar** [comment]
I think I have found the issue. It seems that there is quite a nasty bug in the plex checker. It checks plex for content every 10 minutes but I think I have found a scenario where multiple schedules are starting so it can check it every seconds for example. 

I am fixing that as we speak.

**Comment by phairplay** [comment]
Great!
Many thanks for the fast response and I'm really liking this program, my wife loves the suggestion section

**Comment by csy7550** [comment]
Had a friend add 20 movies to check, CPU = 100% and serverroom is like a sauna!

**Comment by tidusjar** [comment]
It was a misunderstanding on my part on how Nancy (The underlying framework) initializes everything. So a new 'scheduler' was being spun up on every HTTP request.

I've fixed this in the dev branch. We need to push a new version out soon, so it shouldn't be a long wait.

**Comment by phairplay** [comment]
Great many thanks
