### ISSUE TITLE
Can't Connect to Headphones

### ISSUE THREAD

**Issue by speedyflipper** [tidusjar/PlexRequests.Net#156]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Operating System: Windows 7 64 bit

When trying to setup Headphones, I receive a message "Something went wrong". I don't see anything in the logs and I've verified the information multiple times

**Comment by tidusjar** [comment]
What happens when you navigate to `http://ip:port/api?apikey=$apikey&cmd=getVersion` on the machine you are running PlexRequests?

**Comment by speedyflipper** [comment]
I get a blank screen but the problem is I use a URL base, so http://ip:port/**headphones**/api?apikey=$apikey&cmd=getVersion works

**Comment by tidusjar** [comment]
Put 'headphones' into the sub dir
