### ISSUE TITLE
CMD remains open after executing PlexRequests

### ISSUE THREAD

**Issue by gaandu** [tidusjar/PlexRequests.Net#157]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.60

#### Operating System:
Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Double click PlexrequestS.exe The cmd opens up and gives the following info. 

Version 1.6
Location of database (C:....)
Request Plex is running on the following : http
Press any key to exit

and it remains open. If I close the cmd window the application quits. If i press any key, the window doesn't close.

**Comment by tidusjar** [comment]
Sorry. The text should be a bit more clear. It's really press Enter.

**Comment by gaandu** [comment]
I pushed enter, and it closed the cmd window and also completely closed my plexrequest system. :(

**Comment by tidusjar** [comment]
@gaandu Take a look at this to run it as a service: https://github.com/tidusjar/PlexRequests.Net/wiki/FAQ#how-to-run-plexrequestsnet-with-nssm---thanks-theginger3469
