### ISSUE TITLE
How to setup nginx

### ISSUE THREAD

**Issue by phairplay** [tidusjar/PlexRequests.Net#159]
Hi
I'm really pleased to see proxy supported but a little confused on how to set it plexrequests up

Could you please give a quick how to?

**Comment by tidusjar** [comment]
Yeah that's fine.

You just need to go into the admin settings, under the Plex Requests settings there is a new option "Base URL".
Fill that in and then restart Plex Requests.

You can then use Ngnix or Apache etc. with Plex Requests.

**Comment by SaskiFX** [comment]
For reference, this is the way I'm running PlexRequests

/usr/bin/mono /opt/PlexRequests/Release/PlexRequests.exe -base plexrequests 3579

```
        location /plexrequests {
                proxy_pass http://192.168.1.27:3579;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                auth_basic off;
        }
```
Mine has code in there to disable my .htaccess, and pass the appropriate stuff for SSL.

**Comment by tidusjar** [comment]
Instead of using `-base` id recommend going to the settings and applying the base url

**Comment by phairplay** [comment]
Super!
Many thanks

**Comment by SaskiFX** [comment]
Ah, I set that and didn't even see it. :) I'll adjust my service.
