### ISSUE TITLE
Add a filter option in Requests page to only show released movies

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#160]
(Feature request)
My Request list is getting pretty much filled up with requests of movies that haven't even been released in Theaters yet. It'd be nice to hide those until they're released.

**Comment by tidusjar** [comment]
We do have the filters, so I guess you are suggesting a new filter option?

**Comment by Auwen** [comment]
That is correct, an additional filter. Though this filter option should be able to be active along with other ones as well (check boxes instead of drop down)

**Comment by tidusjar** [comment]
This has been done in @origamirobot 's PR
