### ISSUE TITLE
Can't save Sonarr settings

### ISSUE THREAD

**Issue by krispayne** [tidusjar/PlexRequests.Net#162]
When testing connectivity or simply hitting save for Sonarr I generate the following error on it's own on a new page.:

`{"result":false,"message":"You must specify a Quality Profile.","baseUrl":null,"hasBase":false}`

I can also throw a similar error when I delete the port number and hit save/test. Maybe it's in the Javascript on this particular page?
`{"result":false,"message":"You must specify a Port.","baseUrl":null,"hasBase":false}`

![screen shot 2016-04-17 at 6 57 38 pm](https://cloud.githubusercontent.com/assets/70580/14591946/5b0c2568-04ce-11e6-9e2f-a36ed3a68e6f.png)

#### Plex Requests.Net Version:
Version:  1.6.1

#### Operating System:
CentOS Linux release 7.2.1511 (Core)

#### Mono Version:
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue Mar 15 11:39:54 EDT 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

_hostname changed for privacy_
```
[requests@requests logs]$ tail 2016-04-17.log
2016/04/17 12:49:21.320 PlexRequests.UI.Program Trace: Getting product version
2016/04/17 12:49:21.329 PlexRequests.UI.Program Info: Version: 1.6.1
2016/04/17 12:49:21.343 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/04/17 12:49:21.351 PlexRequests.Store.DbConfiguration Trace: DB doesn't exist, creating a new one
2016/04/17 12:49:27.944 PlexRequests.Services.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token.
2016/04/17 12:49:27.996 PlexRequests.Services.PlexAvailabilityChecker Info: Validation of the plex settings failed.
[requests@requests logs]$ systemctl status plexrequests
● plexrequests.service - PlexRequests Service
   Loaded: loaded (/etc/systemd/system/plexrequests.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2016-04-17 13:23:35 PDT; 5h 11min ago
 Main PID: 886 (mono)
   CGroup: /system.slice/plexrequests.service
           └─886 /usr/bin/mono /opt/PlexRequests/Release/PlexRequests.exe

Apr 17 13:23:35 hostname systemd[1]: Started PlexRequests Service.
Apr 17 13:23:35 hostname systemd[1]: Starting PlexRequests Service...
Apr 17 13:24:09 hostname mono[886]: Version: 1.6.1
Apr 17 13:24:10 hostname mono[886]: Location of the database: /opt/PlexRequests/Release/PlexRequests.sqlite
Apr 17 13:24:27 hostname mono[886]: Request Plex is running on the following: http://+:3579/
[requests@requests logs]$ cat /etc/systemd/system/plexrequests.service
[Unit]
Description=PlexRequests Service
After=network-online.target

[Service]
Type=simple
User=root
Group=root

ExecStart=/usr/bin/mono /opt/PlexRequests/Release/PlexRequests.exe

Restart=on-failure
TimeoutStopSec=300


[Install]
WantedBy=multi-user.target
[requests@requests logs]$
```

#### Reproduction Steps:
I noticed an issue when I try to search a tv show from the main UI. Profile quality not retrieved. I have Couch Potato setup as well and do not have an issue with gaining the profiles there, so not sure if it's the way I made my `systemd` service. It's possible that it could be something with Sonarr, but this is a new installation of PlexRequests and older versions had no issue.

Thanks!

**Comment by tidusjar** [comment]
That's strange. It's like the JavaScript is not executing correctly. The message you are seeing drives the little notification pop ups.

**Comment by tidusjar** [comment]
@krispayne What browser are you using? Does this happen on all browsers?

**Comment by krispayne** [comment]
I was using Safari 9.1 on my two mac's. Also happens on Safari on iOS. Same issue on Firefox 42.
Tested also in Chrome 44 on Windows Server 2008 R2. Same result.

**Comment by tidusjar** [comment]
When you extracted PR from the .zip, did you 100% unblock the actual zip file? Or just the .exe?

**Comment by tidusjar** [comment]
I have fixed this in the latest dev build. I found out what was going on. The current dev build is very stable so please feel free to use it until we push out a new version:
https://ci.appveyor.com/project/tidusjar/requestplex/build/1.6.279/artifacts

**Comment by krispayne** [comment]
@tldusjar : not sure if I can unblock a zip on CentOS 7.2, or need to.

I'll try out the dev build tonight, don't have vpn to my home network setup at this time. Thanks!

**Comment by krispayne** [comment]
@tidusjar Installed the dev build. Issue resolved.

Thank you!

**Comment by tidusjar** [comment]
@krispayne I suggest staying on that version (dev build) until we release a new version :)
