### ISSUE TITLE
Add ability to request anyway if currently available.

### ISSUE THREAD

**Issue by heartisall** [tidusjar/PlexRequests.Net#163]
I often have people wanting to request a better version of a movie I already have for instance due to hardcoded subs, lack of subs, Standard Definition, etc. It would be great it you could click the available button and have an option to re-request based on a set of issues much like we already have for movies that you request that aren't in plex.

**Comment by Drewster727** [comment]
@tidusjar we may have to start storing quality levels

**Comment by tidusjar** [comment]
@Drewster727 Maybe not storing them, but caching them, I'm pretty sure the Plex api should give us this information of what the current quality is.

**Comment by SuperPotatoMen** [comment]
Can be a part of https://github.com/tidusjar/PlexRequests.Net/issues/47

**Comment by SuperPotatoMen** [comment]
Can be a part of https://github.com/tidusjar/PlexRequests.Net/issues/47
