### ISSUE TITLE
Add Slack Notification support

### ISSUE THREAD

**Issue by AmansRevenger** [tidusjar/PlexRequests.Net#164]
Basically the title, it's the only thing missing from the original plexrequest-meteor I can think of/ notice missing.

**Comment by tidusjar** [comment]
The question is, does anyone actually use it? I'm not going to bother implementing it, if no one wants it.

**Comment by mwill945** [comment]
It's the only thing keeping me from switching over from the meteor version. Both Pushbullet and Pushover fail to send notifications to me on a regular basis, whereas Slack always seems to work.

**Comment by tidusjar** [comment]
Ok, we will add slack notifications in!

**Comment by tidusjar** [comment]
@AmansRevender @mwill945 with the meteor version, do you have to manually create an Incoming WebHook ?
