### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by jkaberg** [tidusjar/PlexRequests.Net#165]
Could you guys please add an Docker container (with automated builds @ hub.docker.com), perferebly Alpine based one

Thanks!

**Comment by tidusjar** [comment]
Got any guides on where to start creating a docker container? :)

**Comment by jkaberg** [comment]
Yeah, here's one https://github.com/justin8/docker-sonarr-develop/blob/master/Dockerfile

And here's how you create automated builds, https://docs.docker.com/docker-hub/builds/

**Comment by rogueosb** [comment]
Try this one: [https://github.com/rogueosb/docker-plexrequestsnet-alpine](https://github.com/rogueosb/docker-plexrequestsnet-alpine)
