### ISSUE TITLE
undefined error when adding tv show

### ISSUE THREAD

**Issue by sydeburnz** [tidusjar/PlexRequests.Net#168]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.6.1

#### Operating System:
windows server 2008 r2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2016/04/18 12:02:04.416 PlexRequests.UI.Modules.SearchModule Trace: Searching for TV Show twin peaks 
2016/04/18 12:02:04.930 PlexRequests.Api.ApiRequest Trace: Api Content Response: 
2016/04/18 12:02:05.024 PlexRequests.Api.ApiRequest Trace: [{"score":2.6686199,"show":{"id":156,"url":"http://www.tvmaze.com/shows/156/twin-peaks","name":"Twin Peaks","type":"Scripted","language":"English","genres":["Drama","Crime","Horror","Thriller","Mystery"],"status":"Running","runtime":60,"premiered":"1990-04-08","schedule":{"time":"12:00","days":["Monday"]},"rating":{"average":8.2},"weight":1,"network":{"id":9,"name":"Showtime","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":6450,"thetvdb":70533,"imdb":"tt0098936"},"image":{"medium":"http://tvmazecdn.com/uploads/images/medium_portrait/27/67550.jpg","original":"http://tvmazecdn.com/uploads/images/original_untouched/27/67550.jpg"},"summary":"<p>Twin Peaks was created by David Lynch and Mark Frost. The show was set in the fictional town of Twin Peaks in northeast Washington state and tells the story of FBI Special Agent Dale Cooper and his investigation of the murder of a popular local teenage schoolgirl, Laura Palmer.</p>","updated":1455607449,"_links":{"self":{"href":"http://api.tvmaze.com/shows/156"},"previousepisode":{"href":"http://api.tvmaze.com/episodes/11365"}}}}] 
2016/04/18 12:02:05.102 PlexRequests.UI.Modules.SearchModule Trace: Returning TV Show results:  
2016/04/18 12:02:05.149 PlexRequests.UI.Modules.SearchModule Trace: [
  {
    "Id": 70533,
    "SeriesName": "Twin Peaks",
    "Aliases": null,
    "Banner": "http://tvmazecdn.com/uploads/images/medium_portrait/27/67550.jpg",
    "SeriesId": 156,
    "Status": "Running",
    "FirstAired": "1990-04-08",
    "Network": "Showtime",
    "NetworkId": "9",
    "Runtime": "60",
    "Genre": null,
    "Overview": "Twin Peaks was created by David Lynch and Mark Frost. The show was set in the fictional town of Twin Peaks in northeast Washington state and tells the story of FBI Special Agent Dale Cooper and his investigation of the murder of a popular local teenage schoolgirl, Laura Palmer.",
    "LastUpdated": 0,
    "AirsDayOfWeek": null,
    "AirsTime": null,
    "Rating": "2.6686199",
    "ImdbId": "tt0098936",
    "SiteRating": 0,
    "Approved": false,
    "Requested": false,
    "Available": false
  }
] 
2016/04/18 12:02:09.205 PlexRequests.Api.ApiRequest Trace: Api Content Response: 
2016/04/18 12:02:09.267 PlexRequests.Api.ApiRequest Trace: {"id":156,"url":"http://www.tvmaze.com/shows/156/twin-peaks","name":"Twin Peaks","type":"Scripted","language":"English","genres":["Drama","Crime","Horror","Thriller","Mystery"],"status":"Running","runtime":60,"premiered":"1990-04-08","schedule":{"time":"12:00","days":["Monday"]},"rating":{"average":8.2},"weight":1,"network":{"id":9,"name":"Showtime","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"externals":{"tvrage":6450,"thetvdb":70533,"imdb":"tt0098936"},"image":{"medium":"http://tvmazecdn.com/uploads/images/medium_portrait/27/67550.jpg","original":"http://tvmazecdn.com/uploads/images/original_untouched/27/67550.jpg"},"summary":"<p>Twin Peaks was created by David Lynch and Mark Frost. The show was set in the fictional town of Twin Peaks in northeast Washington state and tells the story of FBI Special Agent Dale Cooper and his investigation of the murder of a popular local teenage schoolgirl, Laura Palmer.</p>","updated":1455607449,"_links":{"self":{"href":"http://api.tvmaze.com/shows/156"},"previousepisode":{"href":"http://api.tvmaze.com/episodes/11365"}}} 
2016/04/18 12:02:09.517 PlexRequests.Api.ApiRequest Trace: Api Content Response: 
2016/04/18 12:02:09.595 PlexRequests.Api.ApiRequest Trace: [{"id":701,"url":"http://www.tvmaze.com/seasons/701/twin-peaks-season-1","number":1,"name":"","episodeOrder":null,"premiereDate":"1990-04-08","endDate":"1990-05-23","network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"image":null,"summary":"","_links":{"self":{"href":"http://api.tvmaze.com/seasons/701"}}},{"id":702,"url":"http://www.tvmaze.com/seasons/702/twin-peaks-season-2","number":2,"name":"","episodeOrder":null,"premiereDate":"1990-09-30","endDate":"1991-06-10","network":{"id":3,"name":"ABC","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"image":null,"summary":"","_links":{"self":{"href":"http://api.tvmaze.com/seasons/702"}}},{"id":21613,"url":"http://www.tvmaze.com/seasons/21613/twin-peaks-season-3","number":3,"name":"","episodeOrder":null,"premiereDate":null,"endDate":null,"network":{"id":9,"name":"Showtime","country":{"name":"United States","code":"US","timezone":"America/New_York"}},"webChannel":null,"image":null,"summary":"","_links":{"self":{"href":"http://api.tvmaze.com/seasons/21613"}}}] 
2016/04/18 12:02:09.704 PlexRequests.UI.Modules.SearchModule Info: Requesting tv show with id 70533 
```

#### Reproduction Steps:

Go to TV Shows, Search for Twin Peaks, request all sesons, got error.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by Drewster727** [comment]
@sydeburnz you need to follow the steps in the issue. We need logs, steps to reproduce, etc..  Please provide that info so we can troubleshoot.

**Comment by tidusjar** [comment]
@sydeburnz Thank you for the logs.

I have tried requesting it on my server and everything seems to be fine.

In your settings do you have `Require approval of TV show requests` enabled or disabled?

If it is enabled is the admin requesting this or a user in the list that do not require approval?

**Comment by sydeburnz** [comment]
require approval of TV show requests - not enabled (box not checked)

**Comment by tidusjar** [comment]
@sydeburnz Ok, is your Sonarr/Sickrage setup correctly? Since when you request it will automatically be approved and sent to Sonarr/Sickrage

**Comment by sydeburnz** [comment]
i have setup the sonaar page, finally got it to get the quality profiles and tested the connection with  with a success message and then I submitted the setup.  I am assuming that is what you mean by setup correctly?

is there anything from the old version (not .net) that may be conflicting?

**Comment by tidusjar** [comment]
@sydeburnz Yeah that's what I meant. 

I'm struggling to reproduce this issue of yours. Is it being added to Sonarr?
Do you have any more logs around that time?

**Comment by sydeburnz** [comment]
first off, is there a specific log type?  i see in your app you have several logs types and you have to set the log type in the admin, or does that even matter?  do the raw logs just keep everything and the admin allows you to filter?  strange thing is when i test this, it doesn't seem to be hitting the log.



![untitled](https://cloud.githubusercontent.com/assets/18535787/14615087/b26ee44e-0569-11e6-931a-3eb259bba987.png)

**Comment by sydeburnz** [comment]
2016/04/18 13:42:55.530 PlexRequests.UI.Program Info: Version: 1.6.1
2016/04/18 13:42:55.545 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/04/18 13:42:56.481 PlexRequests.Core.Setup Info: Executing GetSettings call to CouchPotato for quality profiles
2016/04/18 13:42:56.481 PlexRequests.Core.Setup Info: Executing GetSettings call to Sonarr for quality profiles
2016/04/18 13:42:56.887 PlexRequests.Core.Setup Info: Begin executing GetProfiles call to CouchPotato for quality profiles 
2016/04/18 13:42:58.137 PlexRequests.Core.Setup Info: Finished executing GetProfiles call to CouchPotato for quality profiles 
2016/04/18 13:45:01.691 PlexRequests.UI.Modules.SearchModule Info: Requesting tv show with id 70533 
2016/04/18 13:45:52.187 PlexRequests.UI.Modules.SearchModule Info: Requesting tv show with id 78020

**Comment by tidusjar** [comment]
Can you press F12 and tell me what browser errors you are getting?

**Comment by sydeburnz** [comment]
The request of TV Shows is not correctly set up. Please contact your admin.

**Comment by sydeburnz** [comment]
oh my word.  i double checked all my settings and  it appears that for some reason when i was trying to get the quality profiles to load right, in unchecked the 'enable' button at the top and forgot to check it when i got the settings right.  sorry.

**Comment by sydeburnz** [comment]
works now.

**Comment by tidusjar** [comment]
strange why you didn't get the error in the notification window. That's a bug. Glad it's sorted though
