### ISSUE TITLE
Allow for Report Issue from search results.

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#172]
(Enhancement)

I love PlexRequests showing if it's Available or Requested within the search. What would be nice, though, is if the Available button allowed for Report Issues as well.

That is, a user sees that a movie is unplayable, goes to PlexRequests, searches movie, clicks drop down for Available (Or a separate button for Report Issue, etc). Admin gets notified via PushBullet (etc.).

Currently, the only way to mark a movie with an Issue is if it has already been requested prior.

**Comment by tidusjar** [comment]
Sounds like a good idea. If a user does this, would you expect it to be in the requests page? Or just send a notification and that is the end of it?

**Comment by Auwen** [comment]
It would make sense to me for it to be in the Requests (or maybe a separate Issues page? if not too much work) that way I can keep track of which ones I've fixed and haven't yet.

Thanks!

**Comment by tidusjar** [comment]
So you would set the value on the actual approval of the request @Auwen ?

**Comment by Auwen** [comment]
Maybe an Issue Report doesn't need to be 'approved of' per-say by the admin, but rather Outstanding or Done/Delete? Just a standing list, as it were.

Maybe: User searches for movie. If movie is found in Plex, show Available and Report Issue button (similar to how it is on the Requests page, drop down for Report Issue, showing options). User clicks the issue, and it's put into Issues list. Admin gets notification. Admin fixes issue and marks as Done.

**Comment by tidusjar** [comment]
Closing and using #203 as master
