### ISSUE TITLE
Log level memory leak

### ISSUE THREAD

**Issue by csy7550** [tidusjar/PlexRequests.Net#174]
#### Plex Requests.Net Version:

1.6.1

#### Operating System:

Windows 8.1

#### Reproduction Steps:

1. Log level fatal = no significant memory leak. Sitting at 50MB memory usage after 1 day.

2. Log level trace = 1.7GB memory usage after 1 day.

Perhaps this is related to the plex availability checker? I've confirmed this over a few days now and the results are the same every time. Could be related to the fact that my library has ~12000 items (?)
Seems to be climbing every time availability check runs and log gets updated.

**Comment by tidusjar** [comment]
Wowzers, the `Trace` level is mainly for debugging purposes. I suggest keeping it at the `Info` level.
