### ISSUE TITLE
Feature request: Friendly names for users

### ISSUE THREAD

**Issue by yeyeoke** [tidusjar/PlexRequests.Net#179]
I'd love to have the ability to change the user-names into a more friendly and recognizable name i.e. margehateshorses666 can be edited into "mom".

**Comment by tidusjar** [comment]
Hmmm, this is a good idea, but not sure if we would want to manage this. If anyone else wants this functionality please post on here.

**Comment by Auwen** [comment]
It'd be nice, but very low priority for me.

**Comment by Ovicior** [comment]
Add another parameter to each user.


Instead of using the "username" to represent the user, add another field to input a "nickname". Nickname is shown. Each user has a list of nicknames corresponding to certain people, so only they see the changes.

**Comment by EddiYo** [comment]
Much like the way its done in PlexPy, I'd appriciate this function as well. But like @Auwen its very low priority here as well. A "nice to have" function.

**Comment by Spydie88** [comment]
I'm in the same boat as everyone else. Would be nice to have, but not a priority.

**Comment by Ruvetuve** [comment]
Nice feature, must have. Very useful in the Plexpy app.

**Comment by tidusjar** [comment]
I think I can tackle this in my current work (user management)

**Comment by tidusjar** [comment]
This will be done in the user management feature #218
