### ISSUE TITLE
Add a denied button on the requests page for the admin.

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#18]

**Comment by Rsslone** [comment]
Can this be a thing now. XD

**Comment by tidusjar** [comment]
@Rsslone , yes soon. Apologies. I've been very busy lately

**Comment by Rsslone** [comment]
Understandable! Everything is perfect except for this minor thing, outstanding work!

**Comment by tidusjar** [comment]
Preview:
![image](https://cloud.githubusercontent.com/assets/6642220/18090919/c9731ab6-6ebe-11e6-8629-ffaaeceaad85.png)

If you deny with a reason then there is a small (i) icon that if you over it will give you the reason

**Comment by Rsslone** [comment]
You're a god. I'll test it out later today!

**Comment by tidusjar** [comment]
Here is a build with it in (I've not pushed it to release yet)

https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts
