### ISSUE TITLE
C# admin mode instruction

### ISSUE THREAD

**Issue by dualznz** [tidusjar/PlexRequests.Net#188]
right click on Solution, click Add / New item, scroll down to "Application Manifest File"

this will add it to the solution, open it on your solution explorer,
you will see
`<requestedExecutionLevel  level="asInvoker" uiAccess="false" />`

change this to
`<requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />`

this will force the application to always run in admin mode
simple :+1:

**Comment by tidusjar** [comment]
Thanks! But we don't always need the application to run with admin privileges.
