### ISSUE TITLE
IIS compatible

### ISSUE THREAD

**Issue by Leroyvg** [tidusjar/PlexRequests.Net#191]
Hello,

Is it possible to host plexrequests in IIS. i manage all my websites in IIS that how i can create more a records for my website. I only need then 1 port for more websites.

**Comment by tidusjar** [comment]
I'm not sure that I want to add a dependency on IIS, we are using a specific technology called NancyFx, the reason for this is so we can easily Self Host.

Sorry. If I ever find out how to host under IIS and also have the ability to self host I will let you know.
