### ISSUE TITLE
Allow use of base url for reverse proxies

### ISSUE THREAD

**Issue by PhAzE-Variance** [tidusjar/PlexRequests.Net#194]
Can support be added to allow a base url to the gui so that a reverse proxy can be used.  An example is
Http://192.168.1.3:9077/request -> http://domain.com/requests

All of the Web pages will need to become a sub directory of the base url.

**Comment by PhAzE-Variance** [comment]
My mistake,  this is already implemented on the .net version.

**Comment by tidusjar** [comment]
:D
