### ISSUE TITLE
Allow users to request tv shows, movies, or both per user

### ISSUE THREAD

**Issue by PhAzE-Variance** [tidusjar/PlexRequests.Net#195]
Add ability for different users to have different options. Some users can only request movies while others can only request tv shows, or both movies and tv shows.

The main reson behind this is tv shows can be huge and i wouldnt want everyone i allow on to add shows while family members i would allow.

**Comment by tidusjar** [comment]
Good idea!

**Comment by tidusjar** [comment]
Can be part of User Management #218
