### ISSUE TITLE
Existing Movies in Plex not showing up as 'Available' during Search

### ISSUE THREAD

**Issue by ramsaytc** [tidusjar/PlexRequests.Net#197]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.6.1

#### Operating System:
Debian Wheezy (rogueosb's docker)

#### Mono Version:
4.2.3.4

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Searching for existing movies in my Plex library, PlexRequests does not display them on the search page as 'Available'.  Plex is set up correctly (Testing connectivity works), CP is set up (tested and functions for adding new movies).  There are no issues with existing TV shows; any existing TV series in Plex correctly show as 'Requested' on the search page.

**Comment by tidusjar** [comment]
See #200
