### ISSUE TITLE
Admin can not request tv shows

### ISSUE THREAD

**Issue by bjonness406** [tidusjar/PlexRequests.Net#198]
Admin can not request tv show, only moveis. Then you request as an admin, you will get an error message. 

#### Plex Requests.Net Version:
1.6.1

#### Operating System:
Docker from rogueosb

#### Reproduction Steps:
Log in as Admin, and then request a tv show. Then it will give a error message when you request a tv show, movies work just fine. 

I have not set up sonarr/sickrage yet, maybe that is why?
![plexreq](https://cloud.githubusercontent.com/assets/4106070/14940840/fa3554e0-0f85-11e6-81a5-37e5a693d5b1.jpg)

**Comment by tidusjar** [comment]
Ah that makes sense. As an admin we sent the request straight to sonarr/sickrage. 

Looks like this is a bug
