### ISSUE TITLE
Base URL for Reverse Proxy

### ISSUE THREAD

**Issue by jrdnlc** [tidusjar/PlexRequests.Net#199]
What is the proper url format? I'm entering /request in the base url but then plexrequests becomes unusable and I get a "404 - NotFound" error when I try to access the webui.

![Image of Error]
(http://puu.sh/oDaty/e901650a70.png)

**Comment by tidusjar** [comment]
Have you navigated to localhost:3579/request ?

**Comment by jrdnlc** [comment]
@tidusjar Yeah. It takes me to that 404 page

**Comment by tidusjar** [comment]
What is in your settings? 

Don't include a '/' in the settings if you have. Are you sure you also pressed save and then restarted plex requests?

**Comment by jrdnlc** [comment]
@tidusjar I tried /requests and requests without the "/" and same results. There is no save button only submit.

**Comment by jrdnlc** [comment]
Anyone??

**Comment by tidusjar** [comment]
Sorry for the late reply. I am on vacation currently. 

You issue is that you are using requests. 

You need to change this to 'request'. Since requests is a reserved page by the application. 

So just enter request in the settings field, restart plex requests and then navigate to http://localhost:3579/request (change the port if you have changed it in the settings)

**Comment by jrdnlc** [comment]
@tidusjar Nope, that does not fix the issue. Same error

**Comment by tidusjar** [comment]
Can you try starting plex requests with '-base request' as a parameter ?

**Comment by jrdnlc** [comment]
@tidusjar How do I do that? I'm running plex requests as a docker under unraid.

**Comment by tidusjar** [comment]
Oh. I have no idea then.  So you are getting the 404 when going to /request. What about if you just go to local host?

**Comment by jrdnlc** [comment]
@tidusjar Same error. It becomes pretty much useless - have to remove it and do a fresh install.

**Comment by tidusjar** [comment]
Any more information on this?

**Comment by area** [comment]
So I managed to get this to work with the following block in my Nginx:

```
    location /request {
        include /etc/nginx/conf.d/proxy.conf;
        proxy_pass http://localhost:3579/request;
    }
```

Not even really sure why I tried it - I've never set up a reverse proxy like this in the past (i.e. including the baseurl in the redirect), but there we are...

**Comment by tidusjar** [comment]
How else do you set it up? (I'm new to reverse proxies but everyone I have seen including myself is using it the way you have described).

**Comment by area** [comment]
Without the `/request` in the `proxy_pass` line.

**Comment by jrdnlc** [comment]
@tidusjar @area I'm using Apache as a reverse proxy.

**Comment by jrdnlc** [comment]
@tidusjar This issue has been fixed with todays update. Thanks a lot!! What was the issue?

**Comment by jrdnlc** [comment]
@tidusjar Disregard. I changed the url base from /requests to /request and all good now.

**Comment by jrdnlc** [comment]
Slack notifications page is not working...

**Comment by tidusjar** [comment]
@jrdnlc I've just seen the bugs. I'll fix them today and push out a new release.
