### ISSUE TITLE
Can not log out when on Logs page and sticky log level button

### ISSUE THREAD

**Issue by bjonness406** [tidusjar/PlexRequests.Net#201]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.6.1
#### Operating System:

Docker from rogueosb
#### Reproduction Steps:

When you are logged in as admin, and go to settings --> Logs you can not log out. When you click the "Admin" button on the top right corner to bring down the menu, it does not pop up. It works fine on all other of the menus, just this one. 

Also the log Level button should be sticky. So when I select "Info" (example) and submit it, it still shows "Info" like it should do, but if you refresh the page it shows "Trace" which is the default one. 
Although it shows the default one, it is still set to the one I last selected ("Info" in my example). It should show what it is currently set on instead, and not the default one when it loads the page.

**Comment by SuperPotatoMen** [comment]
@bjonness406 @tidusjar is this still a problem or is it already solved?

**Comment by bjonness406** [comment]
Sticky log level button is fixed, but you can still not log out when on the "logs" page.
