### ISSUE TITLE
[Feature Request] Issue button next to request/available

### ISSUE THREAD

**Issue by bjonness406** [tidusjar/PlexRequests.Net#203]
One thing I feel like is missing is a Issue button next to the request/available one. 
When a user want to report a issue with a tv show/movie that is already available, it is not possible to do if it is not on the requested list. 
So a report issue button right under the "available" one would be perfect.

**Comment by tidusjar** [comment]
That is a very good point. It has been discussed already, we just need to think how to implement it and manage it. I'm thinking we might need a separate page to manage all of the issues instead of managing them on the requests page.

**Comment by bjonness406** [comment]
That is a good idea.

**Comment by RacerBas** [comment]
That would be a very good idea, I feel like it's the one thing I'm missing on this right now!

Keep up the good job!

**Comment by tidusjar** [comment]
This has been completed in the latest release.
