### ISSUE TITLE
Feature Request - API

### ISSUE THREAD

**Issue by DereckR** [tidusjar/PlexRequests.Net#205]
I am using Slack.com for notifications right now and want to make a channel called requests and users can use /request and it would integrate with plex requests and send api commands to requests. Any chance this could happen?

Thanks,
Dereck

**Comment by tidusjar** [comment]
Things to add:

 - [ ] Get Requests
 - [ ] Add Request
 - [ ] Change user password
 - [ ] Change Sonarr Settings
 - [ ] Change Plex Settings
 - [ ] Change CP Settings
 - [ ] Change SR Settings
 - [ ] Change Headphones settings
 - [ ] Change notification settings
 - [ ] Change Plex Requests Settings
