### ISSUE TITLE
Ability to change posters' url to https

### ISSUE THREAD

**Issue by squaresmile** [tidusjar/PlexRequests.Net#210]
I got mixed content warning on Chrome because the posters are from `http://image.tmdb.org`. I believe the posters could be retrieved from `https://image.tmdb.org`. It would be nice if it's changed or at least there's an option in the settings.

**Comment by tidusjar** [comment]
Are you running the site over https? 

We can add a settings for this.

**Comment by squaresmile** [comment]
Yes the site is behind nginx served over https.

**Comment by squaresmile** [comment]
Thank you very much for the new update that changes the movies' posters' url. However, the TV posters are still served via http of tvmaze. It would be nice if that could be switched to https too.

**Comment by tidusjar** [comment]
Sorry! Must of missed it!  

Will do :)
