### ISSUE TITLE
base URL change

### ISSUE THREAD

**Issue by yalpski** [tidusjar/PlexRequests.Net#212]
So, assuming one did not come to Github and read the release notes before attempting to set the base URL to /requests - is there any way to recover the previous setting to get the service working properly again?

**Comment by tidusjar** [comment]
Unfortunately not. 

I am aware this is something that I overlooked initially and plan to sort this out. 

The reason is that we encrypt all of the settings so if anyone got hold of the database somehow it is all encrypted. 

Sorry about that.

**Comment by yalpski** [comment]
My own fault for not RTFM before making a change! Essentially then it comes down to stopping the service and reinstalling?

**Comment by yalpski** [comment]
So I just tried reinstalling but it seems to be preserving the settings somewhere. I have it running on OSX - does it place its settings file somewhere other than the directory I have it running from?

**Comment by Drewster727** [comment]
It's all stored in the sqlite file located in the directory. Are you sure you deleted that first?

**Comment by yalpski** [comment]
Looks like I neglected to empty the trash - seems it was pulling the settings from there for some reason. All fixed up now. Thanks for the help!

**Comment by tidusjar** [comment]
All you had to do was delete the .sqlite file. But reinstalling works too! 

glad it's sorted.
