### ISSUE TITLE
No .exe in zip

### ISSUE THREAD

**Issue by nickhdamico** [tidusjar/PlexRequests.Net#213]
is there any chance the .exe file was deleted from the repo?

**Comment by tidusjar** [comment]
We don't version control the .exe. Take a look at the releases.

**Comment by tidusjar** [comment]
https://github.com/tidusjar/PlexRequests.Net/releases

**Comment by nickhdamico** [comment]
Oh wow sorry, brain fart, thanks for the quick answer

**Comment by tidusjar** [comment]
No problem! :)
