### ISSUE TITLE
Albums requested all point to "0"

### ISSUE THREAD

**Issue by Jakesparrow** [tidusjar/PlexRequests.Net#215]
So whenever a user or me as a user requests an album, it finds the album they want, they click request, I get the notification. I log in, I approve it, and in Headphones, under wanted, a new item shows up called "None"  It shows None under artist, album, date released, and type.
When I go back to the requests page for albums, I click on the actually album, and this is where it takes me:

https://musicbrainz.org/release/0

####1.6.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
What appears on the requests page? Is all the information there?

What is the album name?

**Comment by Jakesparrow** [comment]
On the request page, everything looks correct. the name is correct, the album art is correct. The name of the album isn't just one. I have tried over a dozen with the same results.  If I click on the album name to go to the MusicBrainz entry, this is where it takes me:   https://musicbrainz.org/release/0
