### ISSUE TITLE
[FEATURE REQUEST] User Management seperate from Plex.tv

### ISSUE THREAD

**Issue by kingfenix** [tidusjar/PlexRequests.Net#218]
In settings could there be a option to use plex.tv users OR plexrequests.net managed users? If you select plexrequests users you should be able to setup and create users with passwords (authenticated) who can make requests. and essentially not require plex.tv users anywhere really. An alternative could be to allow plex.tv "Friends" who have access to your libraries...

**Comment by tidusjar** [comment]
This has been on my thought process.

**Comment by tidusjar** [comment]
This will be added with user management in 1.8

**Comment by psychoflame** [comment]
Is this feature still planned. It would be helpful to have to manage requests from people who don't have plex accounts.

**Comment by tidusjar** [comment]
It is still planned! some of the code is already there, it just needs polishing and a full implementation really.

**Comment by psychoflame** [comment]
Awesome, Looking forward to it. Thanks tidusjar

**Comment by SuperPotatoMen** [comment]
@tidusjar i linked some request what we can do the implentation also.

**Comment by tidusjar** [comment]
Things left to do

- [ ] Impliemnt per user Features (e.g. User notifications, recently added)
- [ ] Login Page
- [ ] Rename Admin on Navbar

**Comment by SuperPotatoMen** [comment]
New task: give new & existing plex users automatic permission to send issues and make requests

**Comment by tidusjar** [comment]
Added a default settings page

**Comment by tidusjar** [comment]
@SuperPotatoMen I think this is complete now, just needs testing really

**Comment by SuperPotatoMen** [comment]
@tidusjar testing now!

**Comment by SuperPotatoMen** [comment]
Live in dev branch.
