### ISSUE TITLE
[BUG] Incorrectly displaying search results Available vs Request (green vs orange)

### ISSUE THREAD

**Issue by kingfenix** [tidusjar/PlexRequests.Net#219]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.6.1

#### Operating System:
Windows 10

#### Mono Version:
unknown...running PlexRequests.exe as administrator on windows

#### Applicable Logs (from `/logs/` directory or the Admin page):

logs unnecessary, not a crash or exception type bug

#### Reproduction Steps:

When I search for "Star Wars" it should show that all are "Available" in green and not allow the request, however it only seems to list the first three results which Plex also shows when I search using Plex. However if I hit "Show all results" in the search from Plex then I can see all movies available. I think that plexrequests.net needs to somehow do a "show all results" to properly know whats available and whats not.

**Comment by kingfenix** [comment]
the more I play with this, the more I dont know if its a bug or I want to request a new feature. I believe you wrote that the app should query Plex to see if what is being searched is in the library, and the results are marked as either available or a request button is there...it seems to be very hit and miss on marking things available as it should...

One thing I think we need is the ability to specify multiple folders for tv in the sonarr section...I have multiple libraries of tv shows...for example adults vs kids

**Comment by Drewster727** [comment]
so, what it does, is it caches everything on a 15 minute interval. Every 15 minutes it talks to plex and obtains ALL of the movies, tv shows, music. When you do a movie search for example, the app connects out the tmdb to get your movie results, but before we pass them back to you, we look into that plex cache to determine if any of the results from tmdb exist. I've never seen it hit or miss unless it's not caching properly on some platforms. Do you have specific titles that are showing incorrectly?

**Comment by kingfenix** [comment]
well this specific example, my plex library contains all the star wars movies 1-7, and only 3 of them were marked as available in the search results for "Star Wars" not a huge deal..I just wanted to point it out since this is the first actual version of plexrequests that I actually want to use...KUDOS by the way.

**Comment by Drewster727** [comment]
hmm, ok I'll take a look. Our way of checking if it's in plex or not is via title and release year. It could very well be that the title is different from our results. I'll keep ya posted!

**Comment by kingfenix** [comment]
I was wondering about that myself, plex found and matched them, but the titles did vary from what was listed in teh search results...the search results did not always have the "Episode" listed in their titles but in my plex library they do...is there no way to match them via imdb or tvdb # rather than title? text is always clunky to program to and would explain the problem.

**Comment by Drewster727** [comment]
ah, found the culprit... here's what plex contains:
[0]: "Star Wars: Episode I - The Phantom Menace"
    [1]: "Star Wars: Episode II - Attack of the Clones"
    [2]: "Star Wars: Episode III - Revenge of the Sith"
    [3]: "Star Wars: Episode IV - A New Hope"
    [4]: "Star Wars: Episode V - The Empire Strikes Back"
    [5]: "Star Wars: Episode VI - Return of the Jedi"
    [6]: "Star Wars: The Force Awakens"

And, of course, TMDB returns "Star Wars" instead of "Star Wars IV - A New Hope".

We may need to check an alternate name.

**Comment by Drewster727** [comment]
yea, if plex contained an ID, we could use it. I was going to check that next.

**Comment by kingfenix** [comment]
what about using the number instead of text at all?

**Comment by kingfenix** [comment]
well you have it in hand now, so ty for checking on it :D

**Comment by kingfenix** [comment]
maybe this will help on teh ID question

http://forums.plex.tv/discussion/62442/getting-movie-id-from-server-api

**Comment by Drewster727** [comment]
I made a temporary tweak that will yield more accurate results, but I don't think it's a long-term, permanent solution. It does fix the issue at hand, but could yield some false positives. We'll do some digging!

**Comment by tidusjar** [comment]
This checkin should help:

```
We now have a new setting "Advanced Search". What this does is for each item  in the plex library we will get the ratingKey and perform another API call to get the MetaData for that ratingKey, inside the metadata it contains the "guid", the guid contains either a IMDBId or TheTVDBID. We will then use that to match the request. This does mean that we now need to capture the TvDbId for each TV Request.
```
