### ISSUE TITLE
Could not connect to Plex, please check your settings. Exception Message: The underlying connection was closed: An unexpected error occurred on a recieve.

### ISSUE THREAD

**Issue by heartisall** [tidusjar/PlexRequests.Net#22]
I just did a fresh install of PlexRequests.net and everything started fine. I was able to register an admin account and pull my plex token successfully when I enter my plex username and PW. My issue arises when I navigate to the Plex menu in admin settings. I put in the local IP of my Plex server and use the default Port and when I test connectivity I get "could not connect to Plex, please check your settings. Exception Message: The underlying connection was closed: An unexpected error occurred on a recieve." I have disabled the firewall in Windows but still am receiving the same error. I am also not able to select users to login from plex, when I refresh the list nothing happens. This install is on a fresh fully updated copy of server 2012R2 with nothing else installed. Any help would be great Thanks!

**Comment by tidusjar** [comment]
There should be a log file in the directory of your installation. Is there any more information in there?

**Comment by heartisall** [comment]
Here you go this looks to be where the error begins:
2016/03/17 14:28:21.122 PlexRequests.UI.Modules.ApplicationTesterModule Warn: Exception thrown when attempting to get Plex's status: 
2016/03/17 14:28:21.122 PlexRequests.UI.Modules.ApplicationTesterModule Warn: System.ApplicationException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Connection.SyncRead(HttpWebRequest request, Boolean userRetrievedStream, Boolean probeRead)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.GetRawResponse(HttpWebRequest request)
   at RestSharp.Http.GetResponse(HttpWebRequest request)
   --- End of inner exception stack trace ---
   at PlexRequests.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 79
   at PlexRequests.Api.PlexApi.GetStatus(String authToken, Uri uri) in C:\projects\requestplex\PlexRequests.Api\PlexApi.cs:line 132
   at PlexRequests.UI.Modules.ApplicationTesterModule.PlexTest() in C:\projects\requestplex\PlexRequests.UI\Modules\ApplicationTesterModule.cs:line 142
2016/03/17 14:30:12.591 PlexRequests.Services.PlexAvailabilityChecker Info: We have no requests to check if they are available on Plex.

**Comment by tidusjar** [comment]
Interesting. What format have you put into the host name/ip?

**Comment by heartisall** [comment]
192.168.1.15
default port of 32400

After deleting the meteor folder and rerunning the install my users now are populated, This issue still remains however

**Comment by tidusjar** [comment]
What version of Plex Requests are you running?

Can you navigate to a browser on the machine that PlexRequests is running on and enter this into the Url and paste back what you get please:

http://192.168.1.15:32400/

Again, any personal information you should delete and just put in xxxx or something.

**Comment by heartisall** [comment]
I'm running the new version you just posted 1.2.1, although when I go to status tab it tells me an update is available. When I click it is suggests the same version I'm on. 
When I navigate to that url over normal http I get the page cannot be displayed. When I go over https it gives me the unrecognized cert error, when I ignore that I get a 401 Unauthorized.

**Comment by heartisall** [comment]
Well, you got me moving in the right direction. I figured out the issue is because I require Secure connections on my server. I'm guessing this version doesn't support that as of yet. If I disable that option then I can connect fine.

**Comment by tidusjar** [comment]
The status page is a bug. I'll raise that now. 

It's because I'm talking to plex over Http. In the host can you try and put 'https://192.168.1.15'?

**Comment by tidusjar** [comment]
I'll add the option for a secure connection in the next release (tomorrow if I can get it done tonight)

**Comment by heartisall** [comment]
Do you mean the hosts file? Awesome thanks for all your help

**Comment by tidusjar** [comment]
In the settings page. I'm not sure if it will work but it's worth a try. Where you put the plex port, try https then port.

**Comment by heartisall** [comment]
Ok, When I do that I get " Could not connect to Plex, please check your settings, Exception Message: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

**Comment by tidusjar** [comment]
Ok. I'll fix that tonight.

**Comment by heartisall** [comment]
Ok great thanks again

**Comment by tidusjar** [comment]
@heartisall I'm just waiting for the latest code to go through the build validation, if that is all good then i'll push the next release out now and update the release notes.

**Comment by heartisall** [comment]
Ok great, I'll test it as soon as it gets pushed. Thanks

**Comment by tidusjar** [comment]
Reopen to confirm fix.

**Comment by tidusjar** [comment]
@heartisall I have also fixed the status page, it was because my latest release wasn't tagged correctly. The new build is now on the releases page: https://github.com/tidusjar/PlexRequests.Net/releases/tag/v1.3.0

**Comment by heartisall** [comment]
@tidusjar just upgraded to 1.3, Everything is working great now. Thanks for all your help -> Donation sent. (fix your donation link btw), Cheers!

**Comment by tidusjar** [comment]
@heartisall Oh wow! thank you very much! I didn't even know it was broken, I shall fix it!

Thank you very much, i'm going to have to make a donation wall now!
