### ISSUE TITLE
Consider removing Signum.SIGHUP from the signals to terminate list

### ISSUE THREAD

**Issue by janabimustafa** [tidusjar/PlexRequests.Net#220]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
Master branch.

#### Operating System:
FreeBSD-FreeNAS 9.10 STABLE

#### Mono Version:
4.2.2

#### Reproduction Steps:
Start the PlexRequests.exe on FreeBSD using
```
mono PlexRequests.exe &
```
notice how the application shuts down as soon as it starts. This is important because of the way FreeBSD's init scripts work and how they cannot allow foreground blocking services. 
Removing 
```csharp
new UnixSignal(Signum.SIGHUP) 
```
from 
```csharp
UnixSignal.WaitAny( new[] { new UnixSignal(Signum.SIGINT), new UnixSignal(Signum.SIGTERM), new UnixSignal(Signum.SIGQUIT), new UnixSignal(Signum.SIGHUP) });
```
fixes the issue. I think.

**Comment by tidusjar** [comment]
Why have you closed this?

**Comment by janabimustafa** [comment]
Because I realized that SIGHUP is responsible for proper notification and shutdown when the kill {pid} is used. So my solution won't really be a proper fix and instead it will just cause more issues for other users.

**Comment by tidusjar** [comment]
Please excuse my lack of knowledge of Linux systems, but wouldn't removing `SIGHUP` not correctly shutdown the application when you kill the process?

**Comment by janabimustafa** [comment]
It depends on how you attempt to kill it. By default, if you are using the kill {pid} command, the SIGTERM signal is sent. 
This is the definition of SIGHUP from Wikipedia:

>The SIGHUP signal is sent to a process when its controlling terminal is closed. It was originally designed to notify the process of a serial line drop (a hangup). In modern systems, this signal usually means that the controlling pseudo or virtual terminal has been closed.[3] Many daemons will reload their configuration files and reopen their logfiles instead of exiting when receiving this signal.[4] nohup is a command to make a command ignore the signal.
