### ISSUE TITLE
Delete All Requests

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#221]
Idea came from: https://www.reddit.com/r/PleX/comments/4jnt7p/plex_requests_clear_requests_list

Though I'm sure they're not using this version of PlexRequests, it's not a bad idea to include either. This would need to be per type of media as well, just like Approve All. So, Delete All Movies, ...All TV Shows, ...All Music, etc.

**Comment by tidusjar** [comment]
rename this to include delete all, as I think #216 covers it.

**Comment by Auwen** [comment]
Updated. thanks.

**Comment by tidusjar** [comment]
We have missed the Delete all music
