### ISSUE TITLE
PlexRequests.net Plex Mediacenter layout.

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/PlexRequests.Net#225]
This is not a bug and I did not know where else to post it. I modified the Bootstrap.css of this amazing tool and I would like to share it with you guys. Maybe this could be implemented in a future release?

Please head up to my repository and download it from there. There are some screenshots too to look at.

https://github.com/MiuiSwitzerland/Plexrequests.net-CSS

**Comment by tidusjar** [comment]
Wow that looks fantastic! Can you create a pull request for this in the Dev branch?

**Comment by MiuiSwitzerland** [comment]
done!

**Comment by tidusjar** [comment]
@MiuiSwitzerland I merged the PR in and then realised that it broke some stuff currently in dev and the modals are also not styled, are you able to tackle these? (modals Requests>Issues>Other).
The user notifications should be on the right side etc, you can see what it should look like in the latest dev build https://ci.appveyor.com/project/tidusjar/requestplex/build/1.6.353/artifacts

**Comment by MiuiSwitzerland** [comment]
Hi Jamie, I'm sure I have the lastest version since I've installed yesterday. Can I mail you my link with username and password so that you can try my live version?

**Comment by tidusjar** [comment]
jamierees@outlook.com

**Comment by MiuiSwitzerland** [comment]
You can close this one as well :+1:

**Comment by MiuiSwitzerland** [comment]
Hello,


At long last my prayers were answered and they have published my book, you  can find more info abou it here <http://check.peruchitos.com/lnnbv>

Thx, marco@miui.ch
