### ISSUE TITLE
403 Forbidden on Entry Approval

### ISSUE THREAD

**Issue by Proplex** [tidusjar/PlexRequests.Net#238]
#### Plex Requests.Net Version:
1.7.1

#### Operating System:
Windows Server 2012 R2

#### Mono Version:
N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):
From Chrome's Console:
```
jquery-2.2.1.min.js:4 POST http://192.168.1.139:3579/plexrequests/approval/approve 403 (Forbidden)send @ jquery-2.2.1.min.js:4ajax @ jquery-2.2.1.min.js:4approveRequest @ requests-1.7.js:415(anonymous function) @ requests-1.7.js:304dispatch @ jquery-2.2.1.min.js:3r.handle @ jquery-2.2.1.min.js:3
requests-1.7.js:435 Object {readyState: 4, responseText: "", status: 403, statusText: "Forbidden"}
```

#### Reproduction Steps:

Log in as administrator, go to "Requests", and "Approve" an entry. The modal "Something went wrong!" in red appears, and the Chrome console outputs the above error. Nothing appears in the Plex Requests logs.

The only "out-of-the-ordinary" setup I have is that I am using a baseurl for reverse proxying.

**Comment by jrdnlc** [comment]
@Proplex The base URL has to be /request

**Comment by tidusjar** [comment]
It doesn't have to be request. 

I'll take a look
