### ISSUE TITLE
Slack notifications error

### ISSUE THREAD

**Issue by yeyeoke** [tidusjar/PlexRequests.Net#239]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.1

#### Operating System:
Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

Error Details

Nancy.RequestExecutionException: Oh noes! ---> Nancy.ViewEngines.ViewNotFoundException: Unable to locate view 'SlackNotifications'
Currently available view engine extensions: sshtml,html,htm,cshtml,vbhtml
Locations inspected: views/request/admin/AdminNotifications/SlackNotifications-en-US,views/request/admin/AdminNotifications/SlackNotifications,request/admin/AdminNotifications/SlackNotifications-en-US,request/admin/AdminNotifications/SlackNotifications,views/request/admin/SlackNotifications-en-US,views/request/admin/SlackNotifications,request/admin/SlackNotifications-en-US,request/admin/SlackNotifications,views/AdminNotifications/SlackNotifications-en-US,views/AdminNotifications/SlackNotifications,AdminNotifications/SlackNotifications-en-US,AdminNotifications/SlackNotifications,views/SlackNotifications-en-US,views/SlackNotifications,SlackNotifications-en-US,SlackNotifications
Root path: C:\PlexRequestsNet\Release
If you were expecting raw data back, make sure you set the 'Accept'-header of the request to correct format, for example 'application/json'
   vid Nancy.ViewEngines.DefaultViewFactory.GetRenderedView(String viewName, Object model, ViewLocationContext viewLocationContext)
   vid System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   vid CallSite.Target(Closure , CallSite , DefaultViewFactory , Object , Object , ViewLocationContext )
   vid Nancy.ViewEngines.DefaultViewFactory.RenderView(String viewName, Object model, ViewLocationContext viewLocationContext)
   vid System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   vid CallSite.Target(Closure , CallSite , IViewFactory , String , Object , ViewLocationContext )
   vid Nancy.Responses.Negotiation.ViewProcessor.Process(MediaRange requestedMediaRange, Object model, NancyContext context)
   vid System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
   vid CallSite.Target(Closure , CallSite , IResponseProcessor , String , Object , NancyContext )
   vid Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(IEnumerable`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   vid Nancy.Responses.Negotiation.DefaultResponseNegotiator.CreateResponse(IList`1 compatibleHeaders, NegotiationContext negotiationContext, NancyContext context)
   vid Nancy.Responses.Negotiation.DefaultResponseNegotiator.NegotiateResponse(Object routeResult, NancyContext context)
   vid Nancy.Routing.DefaultRouteInvoker.<>c__DisplayClassa.b__6(Task`1 completedTask)
   --- Slut på stackspårning för interna undantag ---
   vid Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

#### Reproduction Steps:

Trying to access slack notifications via web-ui

**Comment by jrdnlc** [comment]
I can confirm this. Same error i'm having

**Comment by yeyeoke** [comment]
Sorry to have to be a pain in the ass but I just updated and I'm getting the exact same error still.

**Comment by tidusjar** [comment]
Using the new build? 1.7.2?

**Comment by yeyeoke** [comment]
Yeah, I just noticed the error-message isnt the same, it just point to nancy still.  

Current error code (some in swedish though): 

Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentNullException: Värde får inte vara null.
Parameternamn: key
   vid System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   vid Nancy.ViewEngines.DefaultViewCache.GetOrAdd[TCompiledView](ViewLocationResult viewLocationResult, Func`2 valueFactory)
   vid Nancy.ViewEngines.Razor.RazorViewEngine.GetOrCompileView(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Type passedModelType)
   vid System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   vid CallSite.Target(Closure , CallSite , RazorViewEngine , ViewLocationResult , IRenderContext , Assembly , Object )
   vid Nancy.ViewEngines.Razor.RazorViewEngine.GetViewInstance(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Object model)
   vid System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   vid CallSite.Target(Closure , CallSite , RazorViewEngine , ViewLocationResult , IRenderContext , Assembly , Object )
   vid Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   vid Nancy.ViewEngines.Razor.HtmlHelpers.Partial(String viewName, Object modelForPartial)
   vid Nancy.ViewEngines.Razor.HtmlHelpers.Partial(String viewName)
   vid RazorOutput.RazorView.Execute()
   vid Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   vid CallSite.Target(Closure , CallSite , Object , Object , Object )
   vid System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   vid CallSite.Target(Closure , CallSite , Object , Object , Object )
   vid Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   vid Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- Slut på stackspårning för interna undantag ---
   vid Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by yeyeoke** [comment]
And yes, I'm running 1.7.2.

**Comment by yeyeoke** [comment]
Just updated, still nothing. 

New error: 

Error Details

Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentNullException: Värde får inte vara null.
Parameternamn: key
   vid System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   vid Nancy.ViewEngines.DefaultViewCache.GetOrAdd[TCompiledView](ViewLocationResult viewLocationResult, Func`2 valueFactory)
   vid Nancy.ViewEngines.Razor.RazorViewEngine.GetOrCompileView(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Type passedModelType)
   vid System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   vid CallSite.Target(Closure , CallSite , RazorViewEngine , ViewLocationResult , IRenderContext , Assembly , Object )
   vid Nancy.ViewEngines.Razor.RazorViewEngine.GetViewInstance(ViewLocationResult viewLocationResult, IRenderContext renderContext, Assembly referencingAssembly, Object model)
   vid System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   vid CallSite.Target(Closure , CallSite , RazorViewEngine , ViewLocationResult , IRenderContext , Assembly , Object )
   vid Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   vid Nancy.ViewEngines.Razor.HtmlHelpers.Partial(String viewName, Object modelForPartial)
   vid Nancy.ViewEngines.Razor.HtmlHelpers.Partial(String viewName)
   vid RazorOutput.RazorView.Execute()
   vid Nancy.ViewEngines.Razor.NancyRazorViewBase`1.ExecuteView(String body, IDictionary`2 sectionContents)
   vid CallSite.Target(Closure , CallSite , Object , Object , Object )
   vid System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   vid CallSite.Target(Closure , CallSite , Object , Object , Object )
   vid Nancy.ViewEngines.Razor.RazorViewEngine.<>c__DisplayClass2b.b__2a(Stream stream)
   vid Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
   --- Slut på stackspårning för interna undantag ---
   vid Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)

**Comment by tidusjar** [comment]
What?! :sob:

**Comment by tidusjar** [comment]
@yeyeoke I cannot reproduce this with build 1.7.3 now? You 100% you replaced everything?

**Comment by yeyeoke** [comment]
Yeah, I just tried with a fresh install and now it works perfectly, but as soon as I but my plexrequests.sqlite in there it stops working. Weird.

**Comment by tidusjar** [comment]
@yeyeoke  your existing db? Can you send it to jamierees@outlook.com and i'll take a look.

**Comment by yeyeoke** [comment]
Sent!

**Comment by tidusjar** [comment]
Strange, not seeing any issues. What actually stops working?

**Comment by yeyeoke** [comment]
With my plex.sqlite in the new directory I can no longer access Slack notifications. If I remove it, everything works. I have no problem rebuilding it but I just figured if anyone else has this problem you'd know atleast how to fix it.

**Comment by yeyeoke** [comment]
Just checked with another browser on another computer, its not a cache issue. Just had to rule that out.

**Comment by tidusjar** [comment]
I'll take another look. I run it in debug mode so I'll run it in release mode and see what happens

**Comment by yeyeoke** [comment]
I should probably mention that I'm running it behind nginx and using "request" as base url. But even if I bypass nginx and manually enter the IP-address:port it fails.

**Comment by tidusjar** [comment]
@yeyeoke Ok I have fixed it (I think), can you give a dev build a try?

**Comment by tidusjar** [comment]
@yeyeoke Build: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.7.396/artifacts

**Comment by yeyeoke** [comment]
Yeah everything works in dev-build, I copied my plexrequests.sqlite to the dev-build and was able to log in without having to create a new admin account. Nothing else except the admin-account is saved though. Is it supposed to be like that?

**Comment by tidusjar** [comment]
@yeyeoke What do you mean? none of your settings are appearing when you copy your database over?

**Comment by yeyeoke** [comment]
Yeah my bad, I used an original database with none of my settings except for an admin account. I tried just now with my actual database and everything works!

**Comment by tidusjar** [comment]
Ok. I'll push this out
