### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/PlexRequests.Net#241]
#### Plex Requests.Net Version:

**1.7.1**

#### Operating System:

**Ubuntu 15.04**

#### Mono Version:

**4.2.3**

#### Reproduction Steps:

I've installed the new Version from scratch (no update or replaced the old one). I was able to create a new Admin account and I'm able to login. However in the Admin page when I click on the "Authentication" menu, I receive a modal error message **"Something went wrong!"**. I'm not able to save my Plex information and this way my users are not able to make requests. If I switch to the old Version **1.6.1** then there is no problem with the authentication.

**Comment by csy7550** [comment]
Same here, but on windows.

Updated from 1.6.1 and no matter what I do, I get "Something went wrong!" when clicking on the Authentication page. Userlist on that page says "Error!"

**Comment by csy7550** [comment]
Confirmed fixed.

**Comment by tidusjar** [comment]
@csy7550 I've not pushed the release out, where did you confirm it? :confounded:

**Comment by csy7550** [comment]
@tidusjar Uhm, from here? https://ci.appveyor.com/project/tidusjar/requestplex/build/1.7.383/artifacts

**Comment by tidusjar** [comment]
@csy7550 Ah ok! Yeah it's fixed in the dev build. I'm going to push out a Release soon with the fix.
