### ISSUE TITLE
Multiple language

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#243]
Hi,

I want to translate the UI to my own language. Is this possible? do you have a language file i can translate?

Kind regards

**Comment by tidusjar** [comment]
Not yet, I do plan to translate the whole website.

**Comment by Ruvetuve** [comment]
Let me know, would be cool for the users who requests items.

**Comment by Ruvetuve** [comment]
Great, don't forget: Dutch (Nederlands / NL)

**Comment by tidusjar** [comment]
I've got that in :) (now anyway)

Supported Languages are:

English
Dutch
Spanish
German
Danish
Portuguese
Swedish
Italian

**Comment by tidusjar** [comment]
@Ruvetuve I don't know Dutch, so once I have a lot of the translations in place, are you able to confirm that they make sense?

**Comment by Ruvetuve** [comment]
Sure, where can i find the translation? how do you want me to upload changes?

**Comment by tidusjar** [comment]
The translations are currently in a difficult to manually read XML file... The best way is probably just to install the translated build.

Unless you have any other suggestions?

**Comment by Ruvetuve** [comment]
I can just download the english xml and translate it the dutch version?

**Comment by tidusjar** [comment]
Sure. I can put it into an excel sheet and send it to you once I have done more

**Comment by Ruvetuve** [comment]
Great, let me know :)

**Comment by RacerBas** [comment]
Will you be able to change the language per user, or is it for everyone at once?

**Comment by tidusjar** [comment]
There is a new dropdown in the navigation bar, you can select the language there.

When you first land on the page I try and detect the language for you using your browsers settings (Similar to what Google does), otherwise we default to English.

**Comment by tidusjar** [comment]
@Ruvetuve here is a link to what has currently been translated:
https://1drv.ms/x/s!Ar0TPpCxBSHZqwOpVGm_4J01vjj1

**Comment by RacerBas** [comment]
I see a few issues in the Dutch translation, I can fix them if you want?

**Comment by tidusjar** [comment]
Yes please do, Let me change the permissions on it.

**Comment by RacerBas** [comment]
bvanlangevelde@gmail.com

**Comment by Ruvetuve** [comment]
Ill have a look at it after @RacerBas

**Comment by saitoh183** [comment]
I see fr in the folder yet there is no french to choose from?

**Comment by tidusjar** [comment]
Oh really?! I must have missed it from the Menu.

 

I’ll add it in, sorry about that.

**Comment by saitoh183** [comment]
thanks...im gussing its a quick fix? or will we have to wait for another full update

**Comment by tidusjar** [comment]
It’s a very quick fix.

**Comment by saitoh183** [comment]
cool , i will check back later for the fix

**Comment by SuperPotatoMen** [comment]
@Ruvetuve are you going to translate this? I have planning to do it anyway

**Comment by SuperPotatoMen** [comment]
See: https://github.com/tidusjar/PlexRequests.Net/issues/402
