### ISSUE TITLE
Allow users to request TV shows without Sonarr/SickRage

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#244]
#### Plex Requests.Net Version:
v1.7.2

#### Operating System:
Windows 10

#### Mono Version:
?

#### Applicable Logs (from `/logs/` directory or the Admin page):

Requesting tv show with id 293382	PlexRequests.UI.Modules.SearchModule	Info	25-5-2016 11:41:08
[{"id":42021,"url":"http://www.tvmaze.com/seasons/42021/herman-martijn-op-de-proef-gesteld-season-1","number":1,"name":"","episodeOrder":null,"premiereDate":"2015-03-03","endDate":"2015-04-21","network":{"id":112,"name":"RTL4","country":{"name":"Netherlands","code":"NL","timezone":"Europe/Amsterdam"}},"webChannel":null,"image":null,"summary":"","_links":{"self":{"href":"http://api.tvmaze.com/seasons/42021"}}},{"id":42022,"url":"http://www.tvmaze.com/seasons/42022/herman-martijn-op-de-proef-gesteld-season-2","number":2,"name":"","episodeOrder":null,"premiereDate":"2016-04-19","endDate":"2016-05-24","network":{"id":112,"name":"RTL4","country":{"name":"Netherlands","code":"NL","timezone":"Europe/Amsterdam"}},"webChannel":null,"image":null,"summary":"","_links":{"self":{"href":"http://api.tvmaze.com/seasons/42022"}}}]	PlexRequests.Api.ApiRequest	Trace	25-5-2016 11:41:08
Api Content Response:	PlexRequests.Api.ApiRequest	Trace	25-5-2016 11:41:08
{"id":15881,"url":"http://www.tvmaze.com/shows/15881/herman-martijn-op-de-proef-gesteld","name":"Herman & Martijn: Op de proef gesteld","type":"Documentary","language":"Dutch","genres":[],"status":"Running","runtime":60,"premiered":"2015-03-03","schedule":{"time":"21:30","days":["Tuesday"]},"rating":{"average":null},"weight":0,"network":{"id":112,"name":"RTL4","country":{"name":"Netherlands","code":"NL","timezone":"Europe/Amsterdam"}},"webChannel":null,"externals":{"tvrage":null,"thetvdb":293382,"imdb":null},"image":{"medium":"http://tvmazecdn.com/uploads/images/medium_portrait/53/133606.jpg","original":"http://tvmazecdn.com/uploads/images/original_untouched/53/133606.jpg"},"summary":"","updated":1463924255,"_links":{"self":{"href":"http://api.tvmaze.com/shows/15881"},"previousepisode":{"href":"http://api.tvmaze.com/episodes/797594"}}}	PlexRequests.Api.ApiRequest	Trace	25-5-2016 11:41:08
Api Content Response:	PlexRequests.Api.ApiRequest	Trace	25-5-2016 11:41:08

#### Reproduction Steps:

Request a random TV serie and hit the button Request (all seasons, or other option doesnt matter)

**Comment by tidusjar** [comment]
Have you setup Sonarr or SickRage?

**Comment by Ruvetuve** [comment]
No, neither. Don;t use those.

**Comment by tidusjar** [comment]
They are currently a requirement to request TV Shows. We can make this non mandatory.

**Comment by jrdnlc** [comment]
Ah, no wonder my users can't request TV shows. I was trying to figure out what the issue was..
