### ISSUE TITLE
Looking for people to give feedback/test new features before release

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#246]
Hi Guys,

I am looking for anyone that wants to test new features before we push them out the door, this way I hope to reduce the amount of bugs I get on a new release (So many different setups!).

It would also be good to get feedback from you guys, if you don't like how a feature has been implemented then you can tell me before we push out a release, get your input into the design of the application.

If anyone is interested in assisting with this please let me know.

Thanks,
Jamie

**Comment by yeyeoke** [comment]
I'd be happy to help!

**Comment by kingfenix** [comment]
same here, happy to help

**Comment by tidusjar** [comment]
@yeyeoke @kingfenix  can you guys please join Gitter, we have made a channel specifically for this.

**Comment by jrdnlc** [comment]
@tidusjar I'd love to help. Count me in!

**Comment by tidusjar** [comment]
@jrdnlc Added you to the gitter room

**Comment by Auwen** [comment]
Not sure how much use I can be, but I'll do some beta testing!

**Comment by gold007eye** [comment]
I'm willing to beta test if you are still looking for people.

**Comment by tidusjar** [comment]
@gold007eye can you please join Gitter.
