### ISSUE TITLE
Startup Script for Ubuntu Systemd

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/PlexRequests.Net#249]
I was struggling with a PlexRequests startup script for my Ubuntu 15.04 and I've decided to create one because my Version of Ubuntu does not have an upstart but a Systemd. Please add this to the Wiki page if possible:

`sudo nano /etc/systemd/system/plexrequests.service`

**Copy and paste this code:**

```
[Unit]
Description=PlexRequest
After=network.target

[Service]
User=root
Type=simple
WorkingDirectory=/opt/plexrequests
ExecStart=/usr/bin/mono /opt/plexrequests/Release/PlexRequests.exe -p 3579
Restart=always
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
```
**Change the Port 3579 if you need to**

**Enable the Service**

`sudo systemctl enable plexrequests`

You can now use **sudo service plexrequests start stop status**

**Note:**

Since mono takes a while to kill, i've added a **30sec timeout**. You might notice it while stoping the service with **sudo service plexrequests stop**

**Comment by zenjabba** [comment]
don't forget to enable the service!

**Comment by tidusjar** [comment]
I think `ExecStart=/usr/bin/mono /opt/plexrequests/Release/PlexRequests.exe 3579` will now be:

```
ExecStart=/usr/bin/mono /opt/plexrequests/Release/PlexRequests.exe -p 3579
```
with the latest release, correct?

**Comment by MiuiSwitzerland** [comment]
with the latest release **1.7.3** is works the way I wrote! and yes you need to enable the service as @zenjabba said with **sudo systemctl enable plexrequests** after creating the script.

**Comment by saitoh183** [comment]
Well i tried this and i see in my Sysyem monitor mono appears and disappears and i cant get to the webpage

**Comment by MiuiSwitzerland** [comment]
Which Distro are you in?

Did you enabled the service after creating the script? sudo systemctl enable plexrequests

**Comment by tidusjar** [comment]
If this works, can someone please add it to the wiki? (available for everyone to edit)

**Comment by MiuiSwitzerland** [comment]
@tidusjar it was posted already. You may close this Issue.

**Comment by MiuiSwitzerland** [comment]
Hi,
This info  may be very useful for  you, you won't regret, just take  a look at <http://change.rafikihotels.com/lnoizi>


Kind regards, marco@miui.ch
