### ISSUE TITLE
Email asks be to approve items, when no approval needed

### ISSUE THREAD

**Issue by zenjabba** [tidusjar/PlexRequests.Net#250]
Hello! The user 'username' has requested Café Society! Please log in to approve this request. Request Date: Wednesday, May 25, 2016 8:40 AM

I don't require approval, so you should probably code out "Please log in...."

**Comment by tidusjar** [comment]
So `username` is in your whitelist?

**Comment by zenjabba** [comment]
I just have it "blanket" no need for approval

<img width="764" alt="screen shot 2016-05-25 at 8 49 29 am" src="https://cloud.githubusercontent.com/assets/679864/15540497/ac2842ac-2255-11e6-88e5-3aff6a31d7a4.png">

**Comment by tidusjar** [comment]
Ah ok! I get you. Good point.

**Comment by tidusjar** [comment]
Dupe of #279
