### ISSUE TITLE
Movie Approval not working anymore

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/PlexRequests.Net#252]
#### Plex Requests.Net Version:

1.7.3

#### Operating System:

Ubuntu 15.04

#### Mono Version:

4.2.3

There is a problem Approving Movies on my side. I have nothing but Plex for my movie Database and approving a movie by clicking on Mark Available results in a modal error: **Something went wrong!** if I click on the **Approve Movies** button on the top, then I receive another modal error: **There are no movie requests to approve. Please refresh.**

**Comment by tidusjar** [comment]
So you don't have CouchPotato setup?

**Comment by MiuiSwitzerland** [comment]
no, is it mandatory now?

**Comment by tidusjar** [comment]
No, I found it.

**Comment by tidusjar** [comment]
This was down to me changing how the user permissions work ready for multiple admins/users. I have cleaned up all of that now with this change so it should work.

**Comment by MiuiSwitzerland** [comment]
Hi,

I just wantet to tell you how much I  appreciate all  you're doing  for me,  and I'd like  to share with you  something  really important,  please read it here <http://chance.nichesolutionsllc.info/lnxrlmkp>

In haste, marco@miui.ch

**Comment by diendanyoi54** [comment]
Hi Tidusjar,

PlexRequests.Net version 1.9.1, Ubuntu Server 16.04.1, Mono 4.4.2.  I have CouchPotato setup and tested connection successfully.  Same issue, **There are no movie requests to approve. Please refresh**.  Also, changing the port does not seem to work.

**Comment by MiuiSwitzerland** [comment]
Guys, the comment above was not written by me, don't click the link!!!

**Comment by tidusjar** [comment]
Have you populated the quality profiles in the Couchpotato settings?

**Comment by diendanyoi54** [comment]
Thanks for the quick reply! Yes, Couchpotato settings are set and Couchpotato works and integrates with Deluge seamlessly.  The port issue was because I copy and pasted the systemd file which set the port in that rather than using the default or specified port so when removing that I was able to access it on the proper port.  It also hangs when attempting to stop the service causing me to kill it, but the main issue is the approval process.

**Comment by diendanyoi54** [comment]
I'm a "knows enough to be dangerous" guy with Linux but I'm assuming it's not a privilege problem since I'm able to see the movie in the list before clicking **+Approve Movies** leading me to believe it's able to read from the database.
