### ISSUE TITLE
User email notification marked as spam

### ISSUE THREAD

**Issue by csy7550** [tidusjar/PlexRequests.Net#253]
#### Plex Requests.Net Version:

1.7.3

#### Operating System:

Windows 8.1

#### Reproduction Steps:

Not exactly sure why, but for some reason user email notification ends up in spamfolder when sent to gmail.com and mail.com (only 2 I've tested). The test email and notification to admin when user requests does not end up in spam when sending to gmail.com and mail.com

Probably something to do with the email template for user notifications?

I've tested this using 2 different smtp providers.

**Comment by MiuiSwitzerland** [comment]
This has nothing to do with the application as it sends emails in plain text. Why don't you Whitelist that address in Gmail?

**Comment by tidusjar** [comment]
Interesting... The reason why the test and admin notifications work is because the username and 'friendly' name is sending an email to the same account. It could be due to us doing something with the username when sending. I'll have to investigate.

**Comment by zenjabba** [comment]
I did some investigation.

Because it's being sent as Plain Text (rather than via TLS) to the SMTP relay, Google is flagging it as potentially insecure and lowering the score.

Also you need to make sure your SPF records are correct for the domain otherwise the score is lowered even more.

**Comment by csy7550** [comment]
TLS is in use as the provider I use (namecheap/privateemail) is TLS/StartTLS only

**Comment by MiuiSwitzerland** [comment]
Hey,

Have you ever seen that super cool  stuff? You just have to give it a try, I swear! Take  a look  here <http://chance.robonbass.org/lnnyzm>


Hope this helps, marco@miui.ch

**Comment by tidusjar** [comment]
Still being marked as spam?

**Comment by zenjabba** [comment]
Still being marked as spam, but I'm wondering if it's something local. Please close for now.

**Comment by libussa** [comment]
I'm having the same issue.
I'm using a gapps account, through the smtp relay. SPF and DKIM records are set up and correct.
Test emails are going through just fine, but notifications emails are being marked as spam.

**Comment by xunil75** [comment]
Test Mails uses the same method as they also go out are being sent to someone. Who is being marked as SPAM? Can you post the SPAM email? Mail Error codes?

**Comment by 05thomasj** [comment]
is there a fix for this?
