### ISSUE TITLE
Update Notification

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/PlexRequests.Net#255]
#### Plex Requests.Net Version:

**1.7.4**

#### Operating System:

**Ubuntu 15.04**

#### Mono Version:

**4.2.3**

I've downloaded the lastest version from your repository at https://ci.appveyor.com/project/tidusjar/requestplex and I have it up and running which fixed the Movie appoval issue (sorry if it is not yet officially released). However, I now have a notification to update to the latest version **1.7.3** when I'm already on **1.7.4**

**Comment by tidusjar** [comment]
This is because the dev build version hasn't been released so the application gets a bit confused. I have just released 1.7.4 so it should be fine now.
