### ISSUE TITLE
[WIKI] Startup command screen stays visable in Windows

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#257]
How can we start the PlexRequest.exe in Windows without seeing the command screen open all the time?

Please add it to the Wiki, thanks in advance!

**Comment by tidusjar** [comment]
https://github.com/tidusjar/PlexRequests.Net/wiki/FAQ#how-to-run-plexrequestsnet-with-nssm---thanks-theginger3469 already there ;)

**Comment by Ruvetuve** [comment]
Sorry NSSM didn't day anything to me. Ill read and try, thanks
