### ISSUE TITLE
Users notified when Items are added

### ISSUE THREAD

**Issue by jrdnlc** [tidusjar/PlexRequests.Net#258]
How does this exactly this work? How are they being notified? I don't see any settings for this. Am I missing something?

![screen shot 2016-05-25 at 8 07 35 am](https://cloud.githubusercontent.com/assets/15741144/15545045/c5c668d4-224f-11e6-80a5-63c37ea582af.png)

**Comment by tidusjar** [comment]
Ok, I should really add some documentation around this.

So basically what you need:
User Authentication enabled.
Email Notifications setup and the User Notifications checked in the admin page

What happens is when a user logs in and checks the box and saves he/she tells the system that they want to be notified when a request ends up in Plex.

When we check if any new items are in Plex, if there are we check to see if any users want to be notified, if they do we then grab their email address from their Plex account and send them a email.

Does that clear it up?

**Comment by jrdnlc** [comment]
@tidusjar Ok, so I have to enable ONLY user email notifications or do I have to check both boxes?

![screen shot 2016-05-25 at 8 15 34 am](https://cloud.githubusercontent.com/assets/15741144/15545377/f62dd8a8-2250-11e6-9c53-1b8c11e10531.png)

**Comment by tidusjar** [comment]
They currently need to be both checked, but I'm going to change that soon.

**Comment by jrdnlc** [comment]
@tidusjar Email sender/recipient would be my email on both right or does recipient need to be left blank?

**Comment by tidusjar** [comment]
You can fill in the recipient as your email, but in the user notifications scenario, the recipient is from their Plex account

Date: Wed, 25 May 2016 08:28:32 -0700

**Comment by jrdnlc** [comment]
@tidusjar Is there a way to stop receiving these request emails? I already get a Pushover notification which is enough for me. 

![image](https://cloud.githubusercontent.com/assets/15741144/15564498/c56fb336-22c7-11e6-9388-7a5e69024c3c.jpeg)

**Comment by tidusjar** [comment]
There is already a task open for this. So I am going to close this for now.

#240
