### ISSUE TITLE
[Feature Request] Annoucement message feature

### ISSUE THREAD

**Issue by ElYoM** [tidusjar/PlexRequests.Net#260]
Hello, thank you for this wonderful tool. Would it be possible to add an announcement board? It would be great since PlexRequests is often the first / only thing users see! For example, it could afford to advertise the server maintenance periods displaying a still visible message for users on top of the page. The announcement would be configurable and customizable in the administration options. Of course, I understand that this request may not be suitable but it seems to me consistent with the objective of PlexRequests. Thank you in advance.

**Comment by Collisionc** [comment]
+1 for this. I've been doing this by editing the Index.cshtml file inside of /Views/Search, but a way to do so in the web interface itself would be great.

**Comment by tidusjar** [comment]
It doesn't really fit, But I do really like the idea! Sounds fun :smile:

**Comment by ElYoM** [comment]
Obviously this is not a priority but it could really add a gain.

**Comment by jrdnlc** [comment]
@Collisionc Do you mind sending me your index.cshtml file so I can add it to mine? A pull request would be great also so @tidusjar can add it.

**Comment by tidusjar** [comment]
Well I'd create a 'maintenance' page so we can set a time for how long the notification would appear etc.

**Comment by Collisionc** [comment]
Yeah, my "fix" is just adding html code into the Views/Search/index.cshtml file. It's not really a clean solution.

For example:
<h4>Server will be down on on 5/27/16 for upgrades</h4>

**Comment by tidusjar** [comment]
Would #298 be good for this?

**Comment by ElYoM** [comment]
this seems ok, will it be possible however to customize the messages?

**Comment by tidusjar** [comment]
Yes. I'll let you put your own message! :)

**Comment by ElYoM** [comment]
Perfect. ;)

**Comment by tidusjar** [comment]
I'll close this issue and #298 will be the master.
