### ISSUE TITLE
User div height not easy to handle

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#262]
#### Plex Requests.Net Version:
1.7.4

#### Operating System:
Windows 10

#### Mono Version:
?

#### Applicable Logs (from `/logs/` directory or the Admin page):
N/A

#### Reproduction Steps:

**Page: /admin/authentication > form-group div**
- Expand the div height for easier scrolling

**Comment by tidusjar** [comment]
Sorry, what is the suggestion here?

**Comment by Ruvetuve** [comment]
Make the div taller :) i have 10+ persons and see only 4 persons at the same time.

**Comment by Drewster727** [comment]
I assume you mean... admin settings > authentication > authenticated users list ? Ok, I made it taller 👍

**Comment by tidusjar** [comment]
Damn @Drewster727 You are on a roll!
