### ISSUE TITLE
TV Show not found as Available

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#263]
#### Plex Requests.Net Version:
1.7.4

#### Operating System:
Windows 10

#### Mono Version:
?

#### Applicable Logs (from `/logs/` directory or the Admin page):
N/A

#### Reproduction Steps:

**Page: /search > TVShows**
- Looking for query "Dexter" gives multiple results. The TV Show Dexter is already in my Plex database so it marks it as Available. Scrolling down i see the result "Dexter's Laboratory (1995)". This one is also in my Plex database with the name "Dexter's Laboratory" (no "(1995) after it"). It shows Request instead of Available.

**Comment by tidusjar** [comment]
This is a current limitation of the way we are querying Plex. We are attempting to make this better.

**Comment by tidusjar** [comment]
Closed, #219 is master
