### ISSUE TITLE
Open requested movie/tv/music links in a new window instead of the same window

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#264]
#### Plex Requests.Net Version:
1.7.4

#### Operating System:
Windows 10

#### Mono Version:
?

#### Applicable Logs (from `/logs/` directory or the Admin page):
N/A

#### Reproduction Steps:

**Page: /requests**
- When clicking on a requested movie title, the imdb link opens in the same window instead of a new window (_blank)

**Comment by ElYoM** [comment]
+1, it's a detail but it will be great.
