### ISSUE TITLE
Don't mark TV Shows as Available when episodes or seasons are still missing

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#266]
#### Plex Requests.Net Version:
1.7.4

#### Operating System:
Windows 10

#### Mono Version:
?

#### Applicable Logs (from `/logs/` directory or the Admin page):
N/A

#### Reproduction Steps:

**Page: /search**
- For example. I have only one season of the show "Fear the Walking Dead". I want it to still be possible to request the rest. Now the whole TV Show is marked as Available but 2 more seasons are upcoming.

**Comment by Collisionc** [comment]
To add on to this, if the show is already on plex/sonarr, but season 3 of (whatever) is actually in spanish, there's no way to add the show so that it can be reported as having the wrong language.

**Comment by chris243** [comment]
Yeah this would be amazing. Maybe show "X Seasons Available" and then when you click on select season have the seasons that are already available have their box checked permanently or something like that. Have no idea if any of this is even possible tbh lol.

**Comment by tidusjar** [comment]
Yeah almost anything is possible!

**Comment by theCheek** [comment]
this would also be fantastic for my setup, as I have family members using it to avoid them messing up my sonarr install (wish sonarr would allow for sub-users!). If they could request previous episodes or seasons of my plex enabled seedbox it would solve that issue completely!

**Comment by roquemore92** [comment]
This would be much appreciated. It would also be useful to show as a request is being filled, which seasons are available. For example I'm downloading a show now, but can't find season 3. It would be nice to show that seasons 1,2,4-8 are available, but 3 is not. Right now it just shows "available" as soon as a single episode is on Plex.

**Comment by tidusjar** [comment]
Yeah, I'm planning to work on these types of features (around TV shows) very very soon.

**Comment by roquemore92** [comment]
Awesome! Thanks!

**Comment by tidusjar** [comment]
This is part of #254

**Comment by tidusjar** [comment]
This will only be marked as Available once every episode in every season is available

**Comment by captainnapalm** [comment]
If I'm reading this all correctly, I'm not sure what I'm looking for is covered, but seems related. I would like for my users to be able to request additional seasons for shows that are already "Available". So if they've requested season 1, and now they want season 2, they can go and request it. Currently I don't believe that's possible.

**Comment by tidusjar** [comment]
In the Dev build it is possible. We are just waiting for some people to start using it and testing it then I can release

**Comment by chris243** [comment]
How do you get the dev build? Been waiting on this feature for a while would love to test it.

**Comment by tidusjar** [comment]
Here you go! 

If you find any issues please let me know either on Gitter or raise an issue on here and prefix the title with Dev https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts
