### ISSUE TITLE
Synology possible?

### ISSUE THREAD

**Issue by theCheek** [tidusjar/PlexRequests.Net#267]
Very interested in this, but only have a Synology as an target install device. Do you have any advice on how to install onto this Linux based device?

**Comment by csy7550** [comment]
There is a mono package for synology you could try, if your model supports it

**Comment by theCheek** [comment]
Yep its got mono as Sonarr needs it. Will have a play and revert. Thanks.

**Comment by csy7550** [comment]
There is also a docker package and I'm pretty sure there is a guide floating around here somewhere

**Comment by tidusjar** [comment]
https://github.com/rogueosb/docker-plexrequestsnet

**Comment by EddiYo** [comment]
I'd strongly recommend the docker package a head of the mono package for your Synology. I have tested both quite extensively, and had quite a bit of trouble with mono on my ds2415+.
