### ISSUE TITLE
Allow users to enable notifications

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#27]
Allow a user to receive an notification once the request has been approve and then once the request is available.

**Comment by curlz620** [comment]
I love this feature. This would be amazing since a lot of users request something and they never watch it since they forget and don't see it being released.

**Comment by tidusjar** [comment]
There's quite a few things that need to be done to make this happen. We would need to store the users details e.g. Email address. It is planned. Just don't know when it will be done (sooner rather than later)

**Comment by Drewster727** [comment]
can we query the user's plex email address from the plex api? I'm going to assume no... but figured I'd ask.

**Comment by tidusjar** [comment]
That's a good point. I think it does contain that.

**Comment by Drewster727** [comment]
if that's the case, we can enable this option in the email settings start and do it pretty easily.

**Comment by tidusjar** [comment]
We still need to allow the user to enable it. They may not want the notifications.

**Comment by Drewster727** [comment]
o right, of course. :+1:

**Comment by EddiYo** [comment]
How about making that a checkbox when they do add the requests @tidusjar ?

Maybe even add the possibility of checking and unchecking notifications for requests made for other users as well? Probably not as easy as it sounds to implement tho..

**Comment by tidusjar** [comment]
@EddiYo I think that will complicate things, All we need is a page where the user can enable notifications, and they can turn it off and on :) We don't need their email as we can get it from the Plex Api. But if they want pushbullet or pushover notifications then we will need their api keys.

**Comment by Drewster727** [comment]
I say we keep it super simple to start with, and just show a check box on the main search page above the tabs. this assumes we have emailing setup, so we'd need to check if that's enabled before showing this option for the user.
