### ISSUE TITLE
TV Requests (nothing but Plex)

### ISSUE THREAD

**Issue by MiuiSwitzerland** [tidusjar/PlexRequests.Net#276]
#### Plex Requests.Net Version:

1.7.4

#### Operating System:

Ubuntu 15.04

#### Mono Version:

4.3.2

#### Reproduction Steps:

Can you please remove the need of **Sonarr**, **SickRage**, etc for TV Shows requests? I'm a bit stuck as I don't use these systems and my users are not able to make TV Show requests. Thanks.

**Comment by tidusjar** [comment]
Already done https://github.com/tidusjar/PlexRequests.Net/issues/244 

I'll release a new build (small increment 1.7.5) this weekend.
