### ISSUE TITLE
Add a mobile view

### ISSUE THREAD

**Issue by heartisall** [tidusjar/PlexRequests.Net#28]
It would be a nice feature if there was a mobile template for when the site if viewed from a phone.

**Comment by tidusjar** [comment]
Yes, this is currently a bug, It does have a mobile view but it's not scaling correctly! I shall fix that for the next release.

**Comment by shiitake** [comment]
submitted a pull request which should fix the responsive components.

**Comment by tidusjar** [comment]
Looks like it fixes it! It will be in the next release (TBC)
