### ISSUE TITLE
Email Notifications Help

### ISSUE THREAD

**Issue by cwhitlow101** [tidusjar/PlexRequests.Net#281]
I wish there was another way I would be able to ask this, but I am having difficulties setting up Email Notifications with Gmail.

Any guide/suggestions of how I should do it? I've tried this to no avail - https://support.google.com/a/answer/176600?hl=en&ref_topic=1354753

**Comment by tidusjar** [comment]
What issues are you having? I've been able to set it up with no problem. 

Username, recipient email and to email just put your email address

**Comment by cwhitlow101** [comment]
[http://postimg.org/image/q7xf2c6x7/](url)

Are these settings correct? I would assume they are. The Username, Recipient, and sender are all the same. I'm just not receiving any email. Checking spam, etc. But there is nothing I've received.

**Comment by tidusjar** [comment]
Is there any errors in the logs? do you have 2 step auth?

**Comment by cwhitlow101** [comment]
Oh. Yes, I do have 2-step auth. 

Here is the result when I sent the test email:

MailKit.Security.AuthenticationException: Authentication failed. at MailKit.Net.Smtp.SmtpClient.Authenticate(Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) at MailKit.MailService.Authenticate(String userName, String password, CancellationToken cancellationToken) at PlexRequests.Services.Notification.EmailMessageNotification.d__14.MoveNext() in C:\projects\requestplex\PlexRequests.Services\Notification\EmailMessageNotification.cs:line 169

**Comment by tidusjar** [comment]
If you have 2 step authentication. You need to add an app password or something.

**Comment by cwhitlow101** [comment]
I'll just turn it off. I don't exactly know to add an app password.

**Comment by tidusjar** [comment]
https://support.google.com/accounts/answer/185833?hl=en
