### ISSUE TITLE
Requesting TV Show gives Bad Request (1) as title

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#285]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.5

#### Operating System:
Windows 10

#### Mono Version:
N/A

#### Applicable Logs (from `/logs/` directory or the Admin page):

Not available for this timestamp.

#### Reproduction Steps:

Request a TV Show: **Dexter: Early Cuts**. Title has been added as Bad Request (1). Also when i view the requested TV Shows it shows the title Bas Request (1).

**Comment by tidusjar** [comment]
This is a bug within the TVMaze database. For this show it returns us:

```
      "externals": {
        "tvrage": null,
        "thetvdb": null,
        "imdb": null
      },
```

So we have no id's! 

Posted on TVMaze's forums: http://www.tvmaze.com/threads/432/edit-requests?page=211#17011
