### ISSUE TITLE
GetMovies failed after update (Version:  1.7.5)

### ISSUE THREAD

**Issue by whitecollar17** [tidusjar/PlexRequests.Net#286]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

Version:  1.7.5
#### Operating System:

windows 10 pro

#### Mono Version:

no

#### Applicable Logs (from `/logs/` directory or the Admin page):

Logs: 
http://pastebin.com/TxP5Vp5j

#### Reproduction Steps:

After update, i see this error evertime in my logs.

**Comment by tidusjar** [comment]
Is couchpotato setup correctly with the quality profiles?

**Comment by whitecollar17** [comment]
I Yes, i have reset it now. i can check it in about 30 minuts if it helps :)

**Comment by whitecollar17** [comment]
No, still a problem. i have change the selected quality profile in plex requests. But still the same problem.

**Comment by tidusjar** [comment]
Can you change the log level to `Trace` and then get the error and send me the logs?

I'm looking for the error to be below this entry:

```
"Api Content Response:"
```

**Comment by tidusjar** [comment]
anything @whitecollar17 ?

**Comment by whitecollar17** [comment]
Hi,

I'm on holiday. Can you give more logs in a few days.
Op 4 jun. 2016 6:51 PM schreef "Jamie" <notifications@github.com>:

anything @whitecollar17 <https://github.com/whitecollar17> ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/tidusjar/PlexRequests.Net/issues/286#issuecomment-223765885>,
or mute the thread
<https://github.com/notifications/unsubscribe/ACzuwHU9yQogg-JXNyvfcslsgzBtBFgyks5qIa0ogaJpZM4IpYmF>
.

**Comment by whitecollar17** [comment]
Hi, i'm back.
i  have the error not anymore. So we can close this one?
