### ISSUE TITLE
Search two movie folders

### ISSUE THREAD

**Issue by zenjabba** [tidusjar/PlexRequests.Net#288]
Currently I have two movie sections (Movies and Family Movies). PlexRequests never seems to check Family Movies for currently available, and allows people to request movies that already exist.

Couchpotato can see the movies (it's searching both directories).

Any Suggestions or is this a feature request?

**Comment by tidusjar** [comment]
This is probably a limitation of the way we are doing things. Would need to rework the availability checker to look at more libraries on the api.

**Comment by Drewster727** [comment]
@zenjabba I find this odd that it's not working. Couple questions:

- Do you have both folders added to plex? We query all plex libraries to determine availability.
- If the above is true, are they both marked as type "Movies" in plex? 

Thanks

**Comment by zenjabba** [comment]
Ok Consider this closed as it seems to be looking it up correctly now.
