### ISSUE TITLE
New Feature *

### ISSUE THREAD

**Issue by zenjabba** [tidusjar/PlexRequests.Net#289]
Allow searching for "anime" in a seperate tab. 

It's still a TV Show, and PlexRequest can still find it, but I would like it to have a seperate tab so it can goto a different directory than TV shows. 

Same with "Family Movies" rather than just Movies.

All that needs to be done with sonarr is changing the "Root save directory for TV shows" to "Root save directory for anime" or what ever other placeholders you can create.

Thanks

**Comment by tidusjar** [comment]
Hmmm, not sure about this one. What about on approval allow you to specify a root directory?

**Comment by tidusjar** [comment]
Same as #287

**Comment by b-rockx** [comment]
I would love this feature, also if we could add the ability to use the tags from sonarr, under the advanced in settings, indexers, restrictions

**Comment by tidusjar** [comment]
i'll take a look!

**Comment by zenjabba** [comment]
Thanks, would make us OCD people happy.

**Comment by tidusjar** [comment]
@b-rockx how does the tags work?
And @zenjabba , I am reluctant to add another tab (or dynamically add tabs) and there is quite a lot in the frontend to drive this functionality. Before I even started to think about this, I would want to rewrite the frontend to cope with this so there is no technical debt. But that is quite a big job.

I think adding another dropdown (see #287 ) would fulfill this request?

**Comment by zenjabba** [comment]
The issue is that requires the external user to know to change the path.

**Comment by tidusjar** [comment]
But why would the external user know about your internal settings? Just get them to request as per usual and you can assign a 'category' that will change Sonarr's path on approval?

**Comment by zenjabba** [comment]
Oh that would work fine!

Basically if they “select” the type, that would work.

**Comment by tidusjar** [comment]
Well in my vision, the user wouldn't "select" the type, the admin would on approval of the request?

**Comment by zenjabba** [comment]
on my system, I don’t approve it… but if that’s whats needed, I’ll enable approvals.

**Comment by tidusjar** [comment]
Ah ok! When the approve is disabled we could allow the users to select a category.

**Comment by zenjabba** [comment]
perfect!

**Comment by tidusjar** [comment]
Closing this request and using #287 as the master.
