### ISSUE TITLE
Update the PlexRequests automatically as soon as there is a new release available

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#29]

**Comment by WinstonP** [comment]
I like it. Maybe even an update button next to the "New Update" in the admin panel.

**Comment by tidusjar** [comment]
Excellent idea.

**Comment by tidusjar** [comment]
New update button added! It will automatically update PlexRequests! 

(Ignore the version, this is in the development environment)
![chrome_2016-05-20_13-52-20](https://cloud.githubusercontent.com/assets/6642220/15428251/24904af4-1e92-11e6-996c-20a1a353fa2e.png)
