### ISSUE TITLE
Add ability to select searching agents

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/PlexRequests.Net#294]
Similar to Plex being able to select which Agent(s) that users will search from.  I believe currently you are using TVMaze, but some shows aren't pulling up.  Good example "battlebots" when you search it will only show the (2015) version.  But what I was actually looking for was the (2000) version which does show up in a tvdb search.

Maybe the option for IMDB, TVDB, TMDB, TVMaze

Also to boost this improvement the ability to search by ID if for some reason a name search doesn't bring up the desired result.

Example: entering  "tvdb:71028" (minus the quotes) in the tv search box would yield the result "battlebots"

**Comment by tidusjar** [comment]
Being able to search which agents would be a lot of work due to how tightly bound we are with the API and each API returning different data. This is not ideal but I don't see us changing that at anypoint in the future. But allowing searching of the ID is a good idea but not sure if it would be used.

Listing this as a possible feature, if anyone else wants this functionality please comment on this issue.

**Comment by gold007eye** [comment]
Not sure if it would make it easier instead to have each api as a seperate module and then could be user selectable from the existing drop down box next to the search feature?   Just trying to think outside the box.  Not sure if that would make anything easier.

**Comment by Ruvetuve** [comment]
Maybe a dumb question, but if you have multiple API's you request, is it that difficult to make a selection in it? Or is it one "big" API?

**Comment by tidusjar** [comment]
It's not difficult, just very time consuming. I would need to write the access to the other apis and all the mapping code, then testing it all.

Just time consuming that I currently don't have enough time to take on.

**Comment by gold007eye** [comment]
I appreciate all your work and dedication.  My friends and family are loving it so far and it has definitely made my life easier instead of getting texts all the time. lol  

Maybe a "Future Feature" when you get time?

**Comment by tidusjar** [comment]
@gold007eye I think this is a very good idea. I just don't have time to do it at the moment, I think currently I can implement a few other requests that I think would benefit you guys more.
I'm not saying I won't do this, i'm just saying i'm not going to do it yet! :)

**Comment by loeschj** [comment]
I'm assuming this issue is why some of my users are receiving this error when they try to request something.

"Our TV Provider (TVMaze) doesn't have a TheTVDBId for this TV Show :( We cannot add the TV Show automatically sorry! Please report this problem to the server admin so he can sort it out!"

**Comment by tidusjar** [comment]
Correct :(

**Comment by loeschj** [comment]
If i understand this correctly, TVMaze is whom is used to search for shows, but they also need to have a correlation to TheTVDB due to Sonarr using that as it's source?

**Comment by tidusjar** [comment]
Correct, but not on everything unfortunately. 

Most things they have TheTvDbId but on newer stuff sometimes that info isnt present and I report a lot of it on the forum and they fix it

**Comment by SuperPotatoMen** [comment]
Maybe we can make a option you can request things based on tvdb ids? For the error 

> Our TV Provider (TVMaze) doesn't have a TheTVDBId for this TV Show :( We cannot add the TV Show automatically sorry! Please report this problem to the server admin so he can sort it out!"

 we going to make a queue system, if tvmaze don't have thetvdbid's its try to add it to sonarr ever day

**Comment by SuperPotatoMen** [comment]
we are making a new option to handle issues with tvmaze
