### ISSUE TITLE
PlexRequests sometimes completely unresponsive

### ISSUE THREAD

**Issue by my95z34** [tidusjar/PlexRequests.Net#295]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.5

#### Operating System:
FreeNAS 9.10

#### Mono Version:

Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Fri May 20 06:36:13 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

System.InvalidCastException: Specified cast is not valid. at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80b69ba80 + 0x00083> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80b696380 + 0x007ea> in :0 at RestSharp.Deserializers.JsonDeserializer.Map (System.Object target, IDictionary`2 data) <0x80b69c500 + 0x004ab> in :0 at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80b69ba80 + 0x000ea> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80b696380 + 0x007ea> in :0 at RestSharp.Deserializers.JsonDeserializer.Map (System.Object target, IDictionary`2 data) <0x80b69c500 + 0x004ab> in :0 at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80b69ba80 + 0x000ea> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80b696380 + 0x007ea> in :0 at RestSharp.Deserializers.JsonDeserializer.BuildList (System.Type type, System.Object parent) <0x80b69e830 + 0x004cc> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80b696380 + 0x0070f> in :0 at RestSharp.Deserializers.JsonDeserializer.Map (System.Object target, IDictionary`2 data) <0x80b69c500 + 0x004ab> in :0 at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80b69ba80 + 0x000ea> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80b696380 + 0x007ea> in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (IRestResponse response) <0x80b691470 + 0x0006c> in :0 at RestSharp.RestClient.Deserialize[T] (IRestRequest request, IRestResponse raw) <0x80b68f2d0 + 0x001e9> in :0

PlexRequests.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.InvalidCastException: Specified cast is not valid. at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80abf4150 + 0x00083> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80abf0560 + 0x007e1> in :0 at RestSharp.Deserializers.JsonDeserializer.Map (System.Object target, IDictionary`2 data) <0x80abf42f0 + 0x004ab> in :0 at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80abf4150 + 0x000ea> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80abf0560 + 0x007e1> in :0 at RestSharp.Deserializers.JsonDeserializer.Map (System.Object target, IDictionary`2 data) <0x80abf42f0 + 0x004ab> in :0 at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80abf4150 + 0x000ea> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80abf0560 + 0x007e1> in :0 at RestSharp.Deserializers.JsonDeserializer.BuildList (System.Type type, System.Object parent) <0x80abf5a90 + 0x004cc> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80abf0560 + 0x00706> in :0 at RestSharp.Deserializers.JsonDeserializer.Map (System.Object target, IDictionary`2 data) <0x80abf42f0 + 0x004ab> in :0 at RestSharp.Deserializers.JsonDeserializer.CreateAndMap (System.Type type, System.Object element) <0x80abf4150 + 0x000ea> in :0 at RestSharp.Deserializers.JsonDeserializer.ConvertValue (System.Type type, System.Object value) <0x80abf0560 + 0x007e1> in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (IRestResponse response) <0x80abee760 + 0x0006c> in :0 at RestSharp.RestClient.Deserialize[T] (IRestRequest request, IRestResponse raw) <0x80abed370 + 0x001e9> in :0 --- End of inner exception stack trace --- at PlexRequests.Api.ApiRequest.Execute[T] (IRestRequest request, System.Uri baseUri) <0x809bce340 + 0x00223> in :0 at PlexRequests.Api.CouchPotatoApi+<>c__DisplayClass9_0.b__0 () <0x80d6da130 + 0x00034> in :0 at Polly.Policy+<>c__DisplayClass8_0`1[TResult].b__0 () <0x809bce1a0 + 0x0001e> in :0 at Polly.Retry.RetryEngine.Implementation (System.Action action, IEnumerable`1 shouldRetryPredicates, System.Func`1 policyStateFactory) <0x809bcd490 + 0x0004c> in :0	PlexRequests.Api.CouchPotatoApi	Error	06/01/2016 23:02:36
Error when attempting to GetMovies.	PlexRequests.Api.CouchPotatoApi	Error	06/01/2016 23:02:36

#### Reproduction Steps:
I can't find any rhyme or reason but sometimes PR just becomes completely unresponsive.  Many times it happens within a minute or two of starting.  I have to actually kill the screen/tmux session to get it to exit just to restart it.  I have no idea if the above logs have anything to do with it or not, but that's what was there.

I have noticed that since the last update I did, my sqlite file has become much larger, without adding many requests.  It went from 660,000 bytes, to 5,128,000 bytes, seemingly overnight.  Not sure if that has anything to do with it or not.

**Comment by tidusjar** [comment]
Hmmm... There should be nothing making it larger other than the logs, what logging level do you have set?  

The above log is an issue so if you are seeing that, it might be related to it crashing. I'll fix the above.

**Comment by tidusjar** [comment]
Looking at the code, it would not have crashed/froze the application. Are you sure your CP settings are setup correctly?

**Comment by my95z34** [comment]
Ah. It could be the logs then. Looks like they're set to Warn. But I don't
think that's what I set them to. I remember seeing a bug report awhile back
about log levels not sticking. I seem to be having a similar issue.

Is there any way to clear out some of the logs?

As for couch potato, AFAIK everything is right. Everything seems to work
correctly.

Looking at the code, it would not have crashed/froze the application. Are
you sure your CP settings are setup correctly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tidusjar/PlexRequests.Net/issues/295#issuecomment-223220866>,
or mute the thread
<https://github.com/notifications/unsubscribe/ADtr16EqkYwUvkutUMrJa2XrVGcQM-Ygks5qHov9gaJpZM4IsLOA>
.

**Comment by tidusjar** [comment]
Warn should be fine. They are in this order

```
Trace 
Debug
Info
Warn
Error
Fatal
```

Where Trace is the most verbose and Fatal will not log out anything unless it's a fatal (non recoverable) error.

**Comment by LastStarFighter** [comment]
Didn't want to create new issue but i'm having similar situation with the log level not sticking and always reverting back to debug.  Only noticed because Plexrequests was taking up over 1 GB of memory and happened upon the memory leak thread.

**Comment by tidusjar** [comment]
Ok I'll take another look and profile it to see if I can see anything.

**Comment by tidusjar** [comment]
@LastStarFighter can you send me your DB (`plexrequests.sqlite`) so I can check your logging levels? (don't worry everything is encrypted securely )

jamierees@outlook.com

**Comment by LastStarFighter** [comment]
@tidusjar i can but it's grown to over 400 MB so don't know how feasible it will be to send to you. I can try to put it up on my dropbox if you want?

**Comment by tidusjar** [comment]
Thanks. Just received it. I'll check when I get home. Can I suggest making sure your log level is set to info?

**Comment by LastStarFighter** [comment]
No matter if i change the log level ever time i log on it seems to always
be defaulted to debug, could that just be a visual glitch where it's set to
info but the box always show debug? Seems like i only see the spike of high
memory usage is when i login, when my computer restarts in the morning
plexrequests never shows high memory usage until i login to do something.

**Comment by tidusjar** [comment]
really? I'll take a look at that soon. Got plenty of things to do tonight!

**Comment by LastStarFighter** [comment]
No worries nothing major so no hurry. I will backup and see what happens if i start with a fresh install.

**Comment by tidusjar** [comment]
There are two actions I have taken from this. Update the NLog package as there is a bug when setting to `Info` and also we clean up the DB every day and keep the last 7 days worth of logs. But that is a lot still, so i've changed it to 2 days.

**Comment by tidusjar** [comment]
This will fix the crashes.

**Comment by tidusjar** [comment]
Also @LastStarFighter the memory was spiking because we was attempting to load 70k worth of logs!

**Comment by my95z34** [comment]
What about making it user selectable?

**Comment by tidusjar** [comment]
@my95z34 I'm not sure it's worth the effort really. would anyone actually use it?

**Comment by LastStarFighter** [comment]
Oh wow 70K, Haha! Awesome thanks for the quick fix!

**Comment by tidusjar** [comment]
I'd give you the dev build, but it's not 100% stable as i'm working on the issues page, so Issues are currently broken!

**Comment by tidusjar** [comment]
Set your log level to Warn and you should be good.

**Comment by LastStarFighter** [comment]
Will do thanks!
