### ISSUE TITLE
Exception thrown when connecting to Sonarr on local machine with subdirectory

### ISSUE THREAD

**Issue by JohnLahr** [tidusjar/PlexRequests.Net#297]
I run Sonarr on the same machine as PlexRequests. Has a subdirectory of /sonarr, SSL disabled. I've tried disabling authentication completely. I've tried renewing the API key. I can access Sonarr just fine via browser at localhost:8989/sonarr.

However, connecting with PlexRequests throws this error:

http://pastebin.com/VyzyS4pp

It works fine with Sonarr's URL base disabled, but that defeats the purpose of the reverse proxy. I am however able to connect with my external hostname (plex.mydomain.com/sonarr), but I really don't want to have to open it to the Internet just for PlexRequests' sake. CouchPotato connects just fine with localhost as the IP, 5050 as the port, and couchpotato as the subdirectory, and it doesn't need the external FQDN like Sonarr seems to.

Is this a PlexRequest fault or a Sonarr fault?

**Comment by tidusjar** [comment]
Looking at the logs, it can find Sonarr fine, but it's struggling to authenticate. Can you double check your API key?

**Comment by JohnLahr** [comment]
I even triple checked. I tried changing API keys a few times. Like I said, the exact same API that's rejected while the subdirectory is enabled will work just fine when the subdirectory is disabled. It seems to specifically be with Sonarr while a subdirectory is set and trying to connect with localhost/127.0.0.1.

**Comment by tidusjar** [comment]
Can you show me an image of your settings (hiding the apikey)

**Comment by JohnLahr** [comment]
Sure thing. Here you go:

http://i.imgur.com/M7Rpxzz.png

**Comment by tidusjar** [comment]
Can you try the following from the server that PlexRequests is running on:

    http://localhost:8989/sonarr/api/system/status?apikey={apikey}

**Comment by JohnLahr** [comment]
I'm asked to login. I'll login, it'll take me to home page, I'll try to follow that link again, and I'm just sent to a login page again despite already being logged in.

**Comment by tidusjar** [comment]
This sounds like a Sonarr Issue. Can you raise a bug with those guys that accessing the url above with a base url and a valid api key is taking you to the login page?

**Comment by JohnLahr** [comment]
Will do. Thanks for the quick responses.
