### ISSUE TITLE
Add an optional landing page

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#298]
Add an optional landing page that will display the status of Plex's availability and a notice board for any downtime etc.

**Comment by MiuiSwitzerland** [comment]
I have something like this on my server for the Plex Status:

http://www.linux05.com/

**Comment by tidusjar** [comment]
That was the plan! :)

**Comment by whitecollar17** [comment]
@MiuiSwitzerland Can you share the code of http://www.linux05.com/ ? I like it so mutch. Can i use it too?

**Comment by tidusjar** [comment]
@MiuiSwitzerland It's called Plex Redirect. 

This is the mockup of our version:

![](https://files.gitter.im/Drewster727/d8Hz/blob)

**Comment by MiuiSwitzerland** [comment]
@tidusjar that looks sick! Great!!

**Comment by tidusjar** [comment]
It's @Drewster727 's mockup!

**Comment by whitecollar17** [comment]
@tidusjar, is it possible to show this page after login?
The login would be "next"

**Comment by tidusjar** [comment]
@Drewster727 also suggested this.I would have thought people would want to see it before they log in. I can make it a setting ?

**Comment by tidusjar** [comment]
Here is the page : 
![image](https://cloud.githubusercontent.com/assets/6642220/15910899/0b3b980a-2dc5-11e6-9df1-497fa0cc82f8.png)

It can be before or after the login page too!

**Comment by whitecollar17** [comment]
Can it a little bit to the left liek the first picture?

**Comment by tidusjar** [comment]
@whitecollar17 I noticed that after I posted it. I've moved it across, there is still some tweaking to do.

**Comment by whitecollar17** [comment]
And the background collar is different. can you change it back?

**Comment by tidusjar** [comment]
@whitecollar17 There is still a lot of tweaking :) This is not the final version :)

**Comment by jrdnlc** [comment]
What platform do you have Plex Email running on? @MiuiSwitzerland

**Comment by MiuiSwitzerland** [comment]
@jrdnlc everything (Plex Server, Plex Requests and Plex Email) runs on a Ubuntu 15.04 server.

**Comment by MiuiSwitzerland** [comment]
@whitecollar17 you can get it here: https://github.com/ITRav4/PlexRedirect

**Comment by jrdnlc** [comment]
I'm having a hard time setting it up. I can't get it to create an index.html file neither reverse proxy working. @MiuiSwitzerland

**Comment by MiuiSwitzerland** [comment]
@jrdnlc 

What are you trying to set up now actually?
Which Distro are you using?
Do you have Apache or Nginx?

**Comment by tidusjar** [comment]
I don't mean to be a pain, but can you guys discuss this somewhere other than this issue? Gitter maybe?

Thanks.

**Comment by jrdnlc** [comment]
@MiuiSwitzerland I'll send you an email using the contact form on your site. 
Sorry @tidusjar

**Comment by jrdnlc** [comment]
What's your email address I can contact you a? @MiuiSwitzerland

**Comment by MiuiSwitzerland** [comment]
@jrdnlc marco@miui.ch

**Comment by Collisionc** [comment]
Can you make it so that basic html can be added into the notice? Maybe as an advanced feature. I would use it to add in a link to my plexpy as well as a short video on how to properly add issues. My parents aren't very good at the internets, so videos help. :D

**Comment by tidusjar** [comment]
That's a good idea. Yeah I'll take a look at doing that.

**Comment by ElYoM** [comment]
Thanks to PlexRedirect, I have done a custom Plex landing page waiting to the Plex Requests's one.
![2016-06-16_14-47-41](https://cloud.githubusercontent.com/assets/18171050/16117295/a7f80e96-33d1-11e6-9af3-2ee6860db60c.png)

**Comment by MiuiSwitzerland** [comment]
Looks good!
