### ISSUE TITLE
Mark movies is wanted (Couchpotato) requested

### ISSUE THREAD

**Issue by damiantje99** [tidusjar/PlexRequests.Net#300]
If I request a movie thats already is in my wanted list from Couchpotato, it still could be requested. Is there a way so that PlexRequest sees whats in the wanted list from Couchpotato? This way the Request tab will not be full with movies thats already been wanted.

PS. If i'm unclear, let me know. I'm dutch and i'm trying :)

**Comment by tidusjar** [comment]
If it's in couchpotato we should be detecting the movie! Let me check later when I get home.

**Comment by tidusjar** [comment]
There seems to be a bug in the logic. I'm fixing this now.
