### ISSUE TITLE
[Bug] Tv Show Selection Any Passed to Sonarr as 720p

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/PlexRequests.Net#303]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.5

#### Operating System:
Windows 7x64

#### Mono Version:
??

#### Applicable Logs (from `/logs/` directory or the Admin page):
```
{ 
"addOptions": null, 
"title": "Undeclared", 
"seasons": [ { "seasonNumber": 1, "monitored": true, "statistics": null } ],
 "rootFolderPath": "T:\\TV Shows", 
"qualityProfileId": 3, 
"seasonFolder": true, 
"monitored": false, 
"tvdbId": 73557, 
"tvRageId": 0, 
"cleanTitle": null, 
"imdbId": null, 
"titleSlug": "Undeclared", 
"id": 0
 }	PlexRequests.Api.SonarrApi	Debug	6/4/2016 2:03:57 PM
```

#### Reproduction Steps:

User requested TV Show "Undeclared"
I logged into Admin page selected "Any" from the Dropdown
Request Approved
Log into Sonarr and view the Series settings. and it lists as the followingL

- Monitored = Yes
- Use Season Folder = Yes
- Profile = 720p  <-- This should have been "Any"

**Comment by gold007eye** [comment]
Thought some screen shots replicating the issue might help you visualize.
![image](https://cloud.githubusercontent.com/assets/4365462/15835553/23ef7f18-2bf6-11e6-968d-f45926eba39d.png)
![image](https://cloud.githubusercontent.com/assets/4365462/15835587/43a5b73c-2bf6-11e6-99ad-99ac7a9323eb.png)

![image](https://cloud.githubusercontent.com/assets/4365462/15835698/bf12d760-2bf6-11e6-80ac-e587fefb95b0.png)

I don't have the log cause I had it set back to "Warn" before I just did this test, but I think this is where the problem lies.

`"qualityProfileId": 3, `

Pretty sure it should have selected "qualityPfofileId:1" instead of "3".  3 on my Sonarr Quality dropdown is "720p".

**Comment by tidusjar** [comment]
Fixed in the dev build, Release TBA
