### ISSUE TITLE
[Bug] / [Feature Request] Filter Not Working / Make "Not Approved" Default Option for Admin

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/PlexRequests.Net#304]
#### Plex Requests.Net Version:

1.7.5
#### Operating System:

Windows 7 x64
#### Reproduction Steps:

[Bug 1]
-  Request Tab --> Then TV Shows Tab --> Filter (Select "Not Approved")
- Click the Movies Tab --> Filter ("Not Approved") Is still selected, but all Movie Requests are still showing.

[Bug 2]
-  Request Tab --> Then Movies Tab --> Filter (Select "Not Approved")
- Click the TV Shows Tab --> Then Movies Tab
  Filter no is not sticking and although "Filter" dropdown still snows "Not Approved" checked all movie requests re-appear.

[Enhancement]
I think it would be nice to default the Requests tab filters to "Not Approved" for Admins so that it is quicker to approve requests without needing to filter first.

**Comment by tidusjar** [comment]
Yeah that's a good point. Also thanks for reporting the bugs

**Comment by tidusjar** [comment]
Sorted out the default tab, i'm not going to bother fixing those bugs, seems like it's quite complicated to fix for my use and i'm going to be rewriting this page from the ground up soon anyway.
