### ISSUE TITLE
[Possible Bug] - Some users unable to login from iPhone

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/PlexRequests.Net#305]
#### Plex Requests.Net Version:

1.7.5
#### Operating System:

iOS
#### Reproduction Steps:

Not sure if anyone else has noticed this issue.

I now have 3 users that are unable to log into the PC from their iPhone.  I am able to my iPhone with no problems and they are able to from their PCs so not an authentication issue.

I have admin settings to only allow users on my Plex server friend list to login with no password required.

Me: iPhone 6S iOS v 9.2
User 1: iPhone 6 v 9.3.1
User 1: iPhone 6S v 9.3.2
User 1: iPhone (not sure) v 8.2

Here is what happens from testing from my wife's phone (user1):
- I can get to the login screen no problem.
- Type in her user name or my user name doesn't matter tried them all.
- Click submit button
- Screen flashes after a few seconds and then goes back to the login screen with the username field now blank.

No matter how many times you try same thing happens.  I have tried different cases, different usernames, at home on wi-fi off wi-fi  same results.  

Same goes with my phone that has no problem logging into the site using the same scenarios above.

**Comment by tidusjar** [comment]
Hmmm... When it flashes and goes back, what's in the URL? Also what is in the URL when they hit the login page?

What browser are they using? I'm assuming safari?

**Comment by gold007eye** [comment]
Ok. so weird thing.. I tested on my wife's phone going direct with IP/port and it worked fine.  So I tried through my DDNS redirect and it worked this time, but once I logged her out and then closed the Safari iOS browser and went back in it had the same effect. 

When using the ddns redirect (user friendly name for them to go to) it doesn't change anything in the address bar when clicking submit;  just screen flashes white for a second (almost like you took a screenshot) and then back to the user login page

I'm wondering if when using a redirect, it's not changing the URL's correctly after they click submit.  

The really weird part is though; that if i try those same scenarios on my iphone it makes no difference, I am still able to login regardless.

**Comment by tidusjar** [comment]
How are you hosting it? Are you using any sort of reverse proxy?

**Comment by gold007eye** [comment]
hosting it on my local PC but then using DDNS.net with a port redirect so that users can just go to xxx.ddns.net and it will take them to the IP:port but keeps the address bar hidden so it doesn't show IP and port.

**Comment by tidusjar** [comment]
Is this still happening?

**Comment by naq90** [comment]
Yes, I'm having issues with safari as well. They will sign in and then it will go directly back to the landing page. They hit continue and then sign in again and the process repeats.

**Comment by tidusjar** [comment]
@naq90 how are you hosting it?
Are you run it it with a base URL?

**Comment by naq90** [comment]
I have it hosted on Ubuntu 14.04 on digital ocean. And I'm using a url redirect from a domain from namecheap.

**Comment by gold007eye** [comment]
Still happening here as well.  Direct ip and the can login fine. Going to the easy to remember name with Url redirect and can't login.  But redirect method still works fine from PC

**Comment by tidusjar** [comment]
Still happening on the latest version?
