### ISSUE TITLE
PR Crashes every two to three days

### ISSUE THREAD

**Issue by curlz620** [tidusjar/PlexRequests.Net#306]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Recently started noticing that PR is down after a few days. I checked logs, but nothing stands out as an error to me. No reasoning for why it crashes. sometimes when logging into the server it says PR has stopped responding, other times it looks like it is running, but the interface is down and the page never loads. After a restart it works fine for a few days and then repeats.

**Comment by tidusjar** [comment]
Change your logging level to 'warn ' I'm aware of this and have fixed it in the Dev build.

**Comment by zenjabba** [comment]
How do we install the DEV build?

**Comment by MiuiSwitzerland** [comment]
Confirmed, turning the Log Level into "Warn" solved the problem for me as well even on 1.7.5

**Comment by tidusjar** [comment]
@zenjabba The dev build is currently not stable. I wouldn't recommend running it in a production environment as i'm still mid developing a feature.

I'd recommend changing the log level to `Warn`

**Comment by zenjabba** [comment]
Sorry to open a closed one, but when I select it to warn, I get this error.

_Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func
`2 predicate) at PlexRequests.Store.Repository.SettingsJsonRepository.<>c__DisplayClass17_0
.<Get>b__0() in C:\projects\requestplex\PlexRequests.Store\Repository\SettingsJs
onRepository.cs:line 104 at PlexRequests.Helpers.MemoryCacheProvider.GetOrSet[T](String key, Func`1 itemCallback, Int32 cacheTime) in C:\projects\requestplex\PlexRequests.Helpers\Mem
oryCacheProvider.cs:line 56 at PlexRequests.Store.Repository.SettingsJsonRepository.Get(String pageName) in C:\projects\requestplex\PlexRequests.Store\Repository\SettingsJsonRepository.
cs:line 100 at PlexRequests.Core.SettingsServiceV2`1.GetSettings() in C:\projects\request
plex\PlexRequests.Core\SettingsServiceV2.cs:line 54 at PlexRequests.UI.Program.SetupLogging() in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 149 at PlexRequests.UI.Program.Main(String[] args) in C:\projects\requestplex\PlexRequests.UI\Program.cs:line 79_

**Comment by tidusjar** [comment]
Really? What about setting it to error?

**Comment by zenjabba** [comment]
I cannot get into the program to change it now, it crashes on startup.

**Comment by tidusjar** [comment]
Send me your DB and i'll see if i can see what is going on and fix it

Date: Mon, 6 Jun 2016 07:01:39 -0700

**Comment by tidusjar** [comment]
jamierees@outlook.com

**Comment by zenjabba** [comment]
Sent via Box (as it's 1.5GB)

**Comment by tidusjar** [comment]
Damn! that's big (due to the logs...). 

Since it's so big i'll have to take a look when I get home.

Date: Mon, 6 Jun 2016 07:15:31 -0700

**Comment by zenjabba** [comment]
I have a large Plex server with a stupid amount of stuff and a crazy number of users.

**Comment by tidusjar** [comment]
Yeah, if you had your logs set to Trace it would explain the DB size and why it crashed.

Date: Mon, 6 Jun 2016 07:32:14 -0700

**Comment by zenjabba** [comment]
No problems, look forward to hearing back from you

**Comment by tidusjar** [comment]
@zenjabba Didn't get to look last night, ran out of time. I'll take a look tonight

**Comment by zenjabba** [comment]
Understood, I completely understand, I have those nights sometimes as well.

**Comment by tidusjar** [comment]
@zenjabba can you use one of the DB's in the backup folder?

**Comment by zenjabba** [comment]
Tried that.. even tried removing the logs from the database… gave up, started again fresh.

**Comment by tidusjar** [comment]
Since you have started again, can you make sure your log level is set to either Warn or Error, until the next release.

**Comment by zenjabba** [comment]
did that, set it at warn.
