### ISSUE TITLE
[Bug] Admin "Add Note" Not clearing from item to item

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/PlexRequests.Net#308]
#### Plex Requests.Net Version:
1.7.5

#### Operating System:
Windows 7 x64

#### Reproduction Steps:
1. Login as Admin
2. Go to Requests tab --> TV Shows Tab
3. Select Report Issue from any of the results
4. Select "Add Note" and create a note.
5. Select Report Issue from any of the other results
6. Select "Add Note
7. The previous note from step 4 is still showing even though this should be blank as it is a new note/different item.

**Comment by tidusjar** [comment]
This area has been completely reworked in the development version for the next release, we have removed the issues from the requests to a whole new oage
