### ISSUE TITLE
[Bug] Marking Not Yet Approved item as Available still leaves approval dropdown active.

### ISSUE THREAD

**Issue by gold007eye** [tidusjar/PlexRequests.Net#309]
#### Plex Requests.Net Version:
1.7.5

#### Operating System:
Windows 7 x64

#### Reproduction Steps:

1. User requests movie or tv show
2. Admin realizes the item is already in the library but not showing as available
3. Admin clicks "mark available"
4. Left side of screen (no interactive portion) shows Approved & Available as checked
5. Right side still has the "+approve" dropdown option available to click instead of hiding as the admin has already said that this is available so no approval would be needed.
6. Clicking the "approve" option would then send a new request to CP/Sonarr which isn't needed.

![image](https://cloud.githubusercontent.com/assets/4365462/15834406/fdd02c1a-2bf0-11e6-8701-873295bca41a.png)

**Comment by tidusjar** [comment]
@gold007eye if you refresh the page what happens? For myself the "Approve" is no longer present

**Comment by gold007eye** [comment]
When I was testing i click to go back to the home page and then went back and it to requests and it stayed the same.  If I logged out and back in that cleared the issue up.

**Comment by tidusjar** [comment]
Sounds more like a caching issue. I'll keep an eye on it. If you see it happening more please comment on this issue.
