### ISSUE TITLE
RAM Usage

### ISSUE THREAD

**Issue by LindsayCole** [tidusjar/PlexRequests.Net#310]
#### Plex Requests.Net Version:
1.7.5

#### Operating System:
Server 2012 R2

Not sure if this is normal or not, but after about 12 hours of use, PR is using 2.5GB of memory. My install had zero users at the time. And does not have a ton of requests pending.

Is this normal? Is there anyway I can designate it a certain amount of RAM? At one point, it was actually crashing Plex.

Thanks,

**Comment by tidusjar** [comment]
Set your log level to Warn, I have fixed this in the dev build. Release TBA

Date: Tue, 7 Jun 2016 05:32:04 -0700

**Comment by LindsayCole** [comment]
Thanks for the prompt response. 

 I changed to Warn, and I got this popup after submitting:

DataTables warning: table id=example - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by tidusjar** [comment]
Really? :/ Can you send me your database please? `plexrequests.sqlite` to jamierees@outlook.com.

Thanks.

**Comment by LindsayCole** [comment]
uhh, that file is 528MB.

 I can provide remote access for you if you would like?

**Comment by LindsayCole** [comment]
![rpnet](https://cloud.githubusercontent.com/assets/15201976/15859776/d5a39ca2-2c9c-11e6-8fd2-0e5fd3adb6b7.PNG)

**Comment by LindsayCole** [comment]
![528](https://cloud.githubusercontent.com/assets/15201976/15859808/f70fec06-2c9c-11e6-9fb4-42d1cb7783a0.PNG)

**Comment by zenjabba** [comment]
Wait till it grows to 1.5GB, and watch your system cry :)

**Comment by tidusjar** [comment]
It's the log files :rage:

**Comment by zenjabba** [comment]
tis all good. This program is making my life so much easier... Glad I can be here to help you make it better.

**Comment by LindsayCole** [comment]
How would you like to proceed tidusjar?

**Comment by tidusjar** [comment]
Can I suggest to restore one of the backed up database files and just set the log level to error maybe?

**Comment by LindsayCole** [comment]
Those backs are from the previous version. How would that affect this
install?

**Comment by tidusjar** [comment]
Should be fine, the databases usually stay mostly backwards compatible with the smaller increments.

**Comment by tidusjar** [comment]
I'm going to close this and use #313 as the master. I have already made lots of fixes in the dev build to resolve this issue (Including automatically setting the log level to `Warn` when you open the new version)
