### ISSUE TITLE
Movie requests do not load when logged in as admin

### ISSUE THREAD

**Issue by DejaVu** [tidusjar/PlexRequests.Net#312]
On my local network, loading the requests page, the movies requested do not show

I think it's to do with the nice CCS Zoom added recently.

**Comment by tidusjar** [comment]
What does it look like? Does the TV requests show?

**Comment by MiuiSwitzerland** [comment]
@DejaVu I'm sorry but you should be more specific:

1. what kind of Android are you talking about? Phone or a TV Box?
2. Android Version
3. Browser name?

I have a Nexus 6p and I can access the **plexrequests** page without any issues. I have no issues as well nn my Nvidia Shield TV. On both devices I use the **Chrome Browser.**

`<iframe width="560" height="315" src="https://www.youtube.com/embed/vq7MXoBUV2Q" frameborder="0" allowfullscreen></iframe>`

**Comment by DejaVu** [comment]
My bad! Sorry. 

On my Samsung S7 Edge... and I've also noticed on my PC using Chrome now too, that once logged in as admin, I cannot see the requests made for Movies using v1.7.5.

If I login as a user, I can. 

Not sure if android specific now TBH. 

![untitled2](https://cloud.githubusercontent.com/assets/481679/15909142/e1061a9a-2dbc-11e6-8cdd-8084981dd0e9.png)![untitled](https://cloud.githubusercontent.com/assets/481679/15909141/e103b124-2dbc-11e6-9264-24cb2ea8edc9.png)

**Comment by tidusjar** [comment]
In the first image, it seems that it's still loading (notice the yellow bar at the very top of the page?)

**Comment by DejaVu** [comment]
Yeah, that stays around for a while, then this - 
![untitled](https://cloud.githubusercontent.com/assets/481679/15941171/cf62f546-2e76-11e6-85eb-b324b4538330.png)

**Comment by tidusjar** [comment]
How many requests do you have?

**Comment by tidusjar** [comment]
Also, are there any console errors? (F12)

**Comment by DejaVu** [comment]
Error from the console is - 

`GET http://**********.com/requests/movies 500 (Internal Server Error)
send @ jquery-2.2.1.min.js:4
ajax @ jquery-2.2.1.min.js:4movie
Load @ requests-1.7.js:543init
Load @ requests-1.7.js:530
(anonymous function) @ requests-1.7.js:34`

I am using a reverse proxy, could that be the fault? Seems strange that it works fine for TV Shows though.

**Comment by tidusjar** [comment]
Can you click on the red text "movies" in the list please and click the preview tab

**Comment by tidusjar** [comment]
Did you click the movies request and press preview? Since there should be some error messages in there?

**Comment by DejaVu** [comment]
Nope. Fresh database and its still doing it. I can PM you my admin details and you can take a look for yourself if you like.

**Comment by tidusjar** [comment]
Please jamierees@outlook.com

**Comment by DejaVu** [comment]
Well. Thanks to tidusjar going the extra mile, we realised I'm a numpty and sorted it out.

Base URL should not be used if you haven't configured to use it!

**Comment by tidusjar** [comment]
You got it! ;) i've fixed it not loading when it cannot connect to CP anyway!

Date: Fri, 10 Jun 2016 08:40:03 -0700
