### ISSUE TITLE
memory usage extremely high

### ISSUE THREAD

**Issue by phairplay** [tidusjar/PlexRequests.Net#313]
![capture](https://cloud.githubusercontent.com/assets/9025847/15874288/5b10b264-2cfa-11e6-93ec-733997abfd9c.JPG)
hi im running the latest build 1.75 on windows 8.1 and for some reason since upgrading the memory usage is extremely high. since taking the screen shot its increased to 423MB.

could you please help me understand why?

**Comment by tidusjar** [comment]
It's down to the logging. Change it to Error of you can. I've fixed this for the next release (should be soon)

**Comment by tidusjar** [comment]
It's defiantly a problem with the logging. This is what happened to my server last night when I set it to Trace: 
![chrome_2016-06-08_10-31-26](https://cloud.githubusercontent.com/assets/6642220/15889737/462ff728-2d64-11e6-860f-52cca4265293.png)

Then I set to Warn and restarted, I'll keep monitoring.

**Comment by phairplay** [comment]
Okay 
I've shut it down for now but really look forward to getting a fix 
Cheers

**Comment by tidusjar** [comment]
It's 100% the Trace logging level: 
![image](https://cloud.githubusercontent.com/assets/6642220/15894837/05b599ca-2d80-11e6-93e5-ea9a5cd0948b.png)

Looking at the graph i'm sure it's in the services, so I'll take a look

**Comment by phairplay** [comment]
Hi 
Is there any eta ? :+1:

**Comment by tidusjar** [comment]
Not yet, There is not a lot to do, just small tweaks really now and one more task. I'd like to say early next week. 

You are welcome to run the Dev build as that is pretty stable now (More stable than the release I would say).

**Comment by phairplay** [comment]
I can hold off a little longer cheers for the update

**Comment by astlaurent** [comment]
Hi I am also seeing this issue as well. any word on the fix. 
![2016-06-13 17_39_41-](https://cloud.githubusercontent.com/assets/11797070/16050926/89fbe45a-322b-11e6-9d9e-e667c2826af0.png)

**Comment by tidusjar** [comment]
Change your log level to Error.
I have fixed this, we just need to release it (There are still a few more changes that need to be made before we release).

Date: Tue, 14 Jun 2016 09:28:53 -0700

**Comment by astlaurent** [comment]
will do. thank you

**Comment by phairplay** [comment]
hi,
is there any update on the next release or could you please tell me how to install the Dev branch :+1:

**Comment by tidusjar** [comment]
I'm thinking about releasing today, but if there is any fallout (e.g. bugs) i'm not going to be able to fix them this weekend...

I'd rather release when I know I have time to answer any questions and fix any bugs (Hopefully there will not be many, but from my experience so far, release day there is always something :( )

You can get the dev branch here: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.8.493/artifacts

**Comment by phairplay** [comment]
Fairpoint 
Thanks for the info
