### ISSUE TITLE
Timing out on every search

### ISSUE THREAD

**Issue by tylersheridan** [tidusjar/PlexRequests.Net#317]
When searching for any TV show, the search just hangs. I believe this is due to a large TV library on my network. Can we make the root directory optional and just query Sonarr to find out if the show exists? Or just scan it once every x hours?

#### Operating System: Mac OSX

**Comment by tidusjar** [comment]
Really? I know quite a lot of people with very large library and it's working fine. So what exactly happens? Does any errors appear in the browser's console (F12)?

**Comment by zenjabba** [comment]
How big is your library. PlexRequests is currently scanning through around 55000 tv episodes on my system without an issue.

**Comment by tylersheridan** [comment]
Library is just over 10000 episodes in the TV section. I have the Library on a Drobo5N and everything is connected in a gigabit network. I believe it is using SMB protocol, and I have noticed it takes about 10 seconds to browse it. Happy to reproduce and upload a log file if it helps, but yes, every search just hangs and doesn't complete.

**Comment by tidusjar** [comment]
What's your log level set to?

**Comment by tidusjar** [comment]
I have also added in the ability to specify your own times the jobs run in the next release #318

**Comment by tylersheridan** [comment]
Adding my logs, PlexRequests is currently hung at the moment and it appears to be due to an api request to couch potato
[2016-06-07.log.zip](https://github.com/tidusjar/PlexRequests.Net/files/312702/2016-06-07.log.zip)

**Comment by tidusjar** [comment]
Can you change your log level to Error? (In the admin pages)

**Comment by tidusjar** [comment]
Have you tried it @tylersheridan ?

**Comment by tylersheridan** [comment]
I didn't realize there was an update,  however I may have resolved some
issues. My server was getting too hot and many things were failing.

The only consistent search issues are with headphones now which I know is
in Beta. I have adjusted my log levels and will tweak the job times once I
have a chance to update.

Kupo!
Tyler

**Comment by tylersheridan** [comment]
https://soundcloud.com/snapjudgment/listen-to-the-entire-snap-judgment-episode-campfire-tales-iii

-- 
Tyler Sheridan
949-385-0205

**Comment by tylersheridan** [comment]
https://player.fm/series/npr-snap-judgment-podcast/snap-727-campfire-tales-iii

-- 
Tyler Sheridan
949-385-0205

**Comment by tylersheridan** [comment]
http://www.msnbc.com/msnbc-live

-- 
Tyler Sheridan
949-385-0205

**Comment by tidusjar** [comment]
Locked due to spam from @tylersheridan email account
