### ISSUE TITLE
Integrate with Headphones

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#32]
Headphones uses music brainz api

API: https://github.com/rembo10/headphones/blob/master/API.md
Cover Art: https://musicbrainz.org/doc/Cover_Art_Archive/API

- [x] New Settings page
- [x] Options to enable and disable on Plex Requests Settings
- [x] Application Tester
- [x] Search
- [x] Requests
- [x] Appoval
- [x] Issues
- [x] Notes
- [x] Plex Checker

**Comment by tidusjar** [comment]
@shiitake I added you to this card, Since you would be able to have a better understanding what the requirement are for the API side of things.

**Comment by tidusjar** [comment]
Last bit to do is the sorting/filtering on the Requests UI for albums does not work.

**Comment by HamilcarH** [comment]
I don't know if it's in the works, but can we have artists request ?
