### ISSUE TITLE
Logs saved where mono command was run

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#327]
#### Plex Requests.Net Version: Version:

1.7.5  
#### Operating System:

FreeNAS-9.10-STABLE-201606072003 (696eba7)
#### Mono Version:

Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue May 10 05:31:54 UTC 2016)  
#### Applicable Logs (from `/logs/` directory or the Admin page):

n/a
#### Reproduction Steps:

running:
`mono /path/to/exe/PlexRequests.exe`
results in the logs being saved where the command was run

changing to /path/to/exe/ and then running
`mono PlexRequests.exe`
results in the logs being saved in /path/to/exe/logs/ (where they are expected to be).

**Comment by tidusjar** [comment]
This is not actually an issue anymore

**Comment by SuperPotatoMen** [comment]
Fixed in the next release!
