### ISSUE TITLE
How to connect from outside the network

### ISSUE THREAD

**Issue by cdrracing** [tidusjar/PlexRequests.Net#331]
I'm sorry for such a noob question but I can't seem to make this work.  How can I gain access outside of the computer PlexRequests is running on?  I had it set up and accessible with PlexRequests running on meteor but with .net I can't seem to get it working.  I can't even get into it from within the local network, the only way in is through localhost.  
What am I doing wrong?

Windows 10
PlexRequests v:1.7.5

**Comment by tidusjar** [comment]
There is a section on the FAQ in the wiki, have you tried it?

**Comment by cdrracing** [comment]
If you're speaking of the firewall issue then no, apparently I'm not smart enough to understand it.
I have tried starting it up on different ports but that didn't seem to effect the problem.

**Comment by tidusjar** [comment]
Does it work fine when you turn off Windows firewall?

**Comment by cdrracing** [comment]
Sorry for the late response.
Yes, it does work with the firewall off.  I really should've tried that first.  
I don't really understand any of the language on how to allow it to get through the firewall.  I'm happy to read about it, is there an article or How-To you could recommend?

**Comment by tidusjar** [comment]
Take a look at this: https://github.com/tidusjar/PlexRequests.Net/wiki/FAQ#i-am-having-issues-allowing-plex-requestsnet-through-my-firewall
