### ISSUE TITLE
CouchPotato cache scheduler not working

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#334]
#### Reproduction Steps:

Reset your database so there are no "Requests" anymore. Load up 1.8.0 and setup couchpotato. I have already got Independence Day: Resurgence requested in CP:
![image](https://cloud.githubusercontent.com/assets/4528753/16232698/320fd63c-3791-11e6-9985-bb02bbb2d34f.png)

Give PR some time to do the caching, check the Scheduled Jobs page and verify it ran the cacher for CP. Then search for Independence Day. You'll see a "Request" button when it should show requested. 

![image](https://cloud.githubusercontent.com/assets/4528753/16232839/ac8ecc4c-3791-11e6-85e3-a3536f1485bd.png)

This may be happening with Sonarr/SickRage as well, not sure.

**Comment by tidusjar** [comment]
Thats strange, as I didn't make any changes around those areas...

**Comment by tidusjar** [comment]
i'll pull the release and investigate

**Comment by Drewster727** [comment]
![image](https://cloud.githubusercontent.com/assets/4528753/16233085/b54ad0e6-3792-11e6-9c95-3eac7009da79.png)

I'm seeing that when it tries to connect to CP. Are you seeing that as well?

**Comment by tidusjar** [comment]
I have not seen that. I'll have to see what's going on when I get home from work.

**Comment by Drewster727** [comment]
It appears to be successfully connecting to CP and obtaining the data, but it cannot deserialize the json array properly (using RestSharp)

**Comment by tidusjar** [comment]
Either we have changed a type, or there is a new/changed type that we are not expecting...

**Comment by Drewster727** [comment]
yea, I'm guessing the CP json changed?

**Comment by tidusjar** [comment]
Unlikely if an older version works. 
I do remember changing one of the types slightly as someone's CP json was structured a bit differently, but i'm pretty sure it still worked

Date: Tue, 21 Jun 2016 07:39:53 -0700

**Comment by Drewster727** [comment]
I narrowed it down to the "Info" property of our CP object, not sure which property, but commenting all of them but the tmdb_id fixes the issue:

![image](https://cloud.githubusercontent.com/assets/4528753/16233794/2dbd0952-3795-11e6-80f6-a3050453f112.png)

**Comment by tidusjar** [comment]
Can you send me the Json response you get?

Date: Tue, 21 Jun 2016 07:47:35 -0700

**Comment by Drewster727** [comment]
looks like the release_date property is the culprit

**Comment by Drewster727** [comment]
Here's an interesting item I found in the JSON... 

sometimes the release_date is: "release_date": []
and sometimes it is: "release_date": {"dvd": 0, "expires": 1468174162, "theater": 0, "bluray": false}

so it can be an array or an object...

**Comment by Drewster727** [comment]
this may be a solution
http://stackoverflow.com/questions/11513935/gracefully-handling-an-empty-json-object-in-restsharp#answer-27724300

**Comment by tidusjar** [comment]
Hmmm... The issue would be that we would then do that for everything... I am working on refactoring the Api stuff because it's horrible to work with.

It's either an empty array or an object... well this sounds fun...

**Comment by Drewster727** [comment]
I'm going to add that as a temp workaround for CP in the meantime. check my latest commit, it works like a charm.

**Comment by tidusjar** [comment]
Oh it's done in the request and not the response. Yeah looks good!

**Comment by Drewster727** [comment]
yea, and of course my git screwed up again and committed the entire file(s) instead of just my line changes... so weird.
