### ISSUE TITLE
Status page not working

### ISSUE THREAD

**Issue by astlaurent** [tidusjar/PlexRequests.Net#336]
![image](https://cloud.githubusercontent.com/assets/11797070/16234476/8d0e3958-379f-11e6-85f0-ce81a9f10c5b.png)

Windows 10 64 bit
I believe it is the latest commit from today because the DB size is smaller that the 500mb it was yesterday.

something broke during the upgrade process?

**Comment by tidusjar** [comment]
Hold on, this should be fixed soon

**Comment by tidusjar** [comment]
Use this: https://github.com/tidusjar/PlexRequests.Net/releases/tag/v1.8.0
