### ISSUE TITLE
Feature Request: Auto Delete option

### ISSUE THREAD

**Issue by astlaurent** [tidusjar/PlexRequests.Net#338]
It would be nice to have a auto delete option on each request to say delete this from your plex library after x amount of days.

I continuously tell people not to request stuff they do not plan on watching but it still happens so now i say if you request and i feel no one else would enjoy it I will delete it in 60 days.

**Comment by Drewster727** [comment]
This would be a tough one. You'd have to have the Plex option enabled that allows deleting media (I for sure don't F with that one) or we'd have to find where the media is in the file system/network and delete it, which brings up potential permission issues. Lots of variables to this one I would think.

**Comment by Drewster727** [comment]
If couchpotato, sonarr, and/or sickrage had an "expire" option of some sort, we could easily do this via the API, but I don't believe that exists.

**Comment by astlaurent** [comment]
I dont think those exist and i know you can delete on sonarr (and maybe its api) but not through couch potato. I wonder if there is a way to delete through the plex api. i know you can do it through the server interface so maybe the api supports it. What would be tough is that you would need to start the retention off plex's date added metadata or off when plex requests notices that the movie is available. Then there would need to be a way to remove the retention option if you decided that you wanted to keep that particular request. Might be a pain in the ass and perhaps not worth the effort but still might be cool none the less if you are looking for features. Then again i might be the only one with the problem of people requesting dozens of movies based on the fact that they have cool cover art :)

**Comment by Drewster727** [comment]
haha, yea I have people who do the same thing. It's a great idea. Something to add to the down-the-road list.

**Comment by SuperPotatoMen** [comment]
I discussed this idea with @tidusjar but unfortunately we don't going to implementation this one. 
Maybe in the feature.
Feel free to do more request with nice idea's!

**Comment by CallMeRev** [comment]
oh fucki was hopping you guys were going to add this , cant you use the option to delite media from plex, alot of us would enable it if this existed or already have enabled it . you could add a time for each request to delite after x days right ?

**Comment by PotatoQuality** [comment]
@callmerev pleas open a feathub topic instead of bumping a issue from 7 months ago

**Comment by CallMeRev** [comment]
github topic ? you mean a new issue ?

**Comment by PotatoQuality** [comment]
No feathub. See the main page of this github. (click on the nice green button)

**Comment by CallMeRev** [comment]
Done : http://feathub.com/tidusjar/Ombi/+151
Please if anyone reaches this issue come and upvote this .
