### ISSUE TITLE
settings error after update 1.8

### ISSUE THREAD

**Issue by phairplay** [tidusjar/PlexRequests.Net#339]
hi after updating to 1.8 neither plex sonarr or couch will connect, when i press test i get the below error.
i run everything on one machine

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 192.168.0.21:32400 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)

**Comment by tidusjar** [comment]
And this works fine on 1.7.5?

**Comment by phairplay** [comment]
Sorry
My bad!
I forgot to unblock the zip file before extracting. It's working fine now 

Thanks
