### ISSUE TITLE
'Profile Id' must be greater than '0'. Sonarr

### ISSUE THREAD

**Issue by phairplay** [tidusjar/PlexRequests.Net#340]
Hi,
Sorry this one I believe is an true error problem.

Version 1.8 
Windows 8.1

When trying to add a tv series I get the following error Profile Id' must be greater than '0'.
Profile doesn't exist

Error log 

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at PlexRequests.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 123 at PlexRequests.Api.SonarrApi.<>c__DisplayClass7_1.b__2() in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 116 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.Retry.RetryEngine.Implementation(Action action, IEnumerable`1 shouldRetryPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass13_0.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at PlexRequests.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl) in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 116

**Comment by tidusjar** [comment]
Have you selected a quality profile in your settings?

**Comment by phairplay** [comment]
Yes, my options are
Any
HD
Any profile has the same result

**Comment by karbowiak** [comment]
I'm seeing the same issue, even if i have more than 4 profiles added, and i select the latest created, it still tells me that it's a wrong profile id :\

**Comment by Drewster727** [comment]
confirmed, seeing the same thing upon requesting. I've got the correct quality profile chosen in settings. However, no issues on admin side when saving sonarr settings.

**Comment by Drewster727** [comment]
![image](https://cloud.githubusercontent.com/assets/4528753/16245107/e83c7734-37c4-11e6-89a5-65e552b4c07a.png)

quality profile is not being obtained correctly it seems.

**Comment by tidusjar** [comment]
Yeah, if you look a few lines above we are passing a empty string :S Not sure why that is, any idea?

**Comment by Drewster727** [comment]
I think it defaults to that when you don't choose a quality. Remember how we added the ability to either "Approve" or choose a quality/approve? Committing a fix now.

**Comment by Drewster727** [comment]
ok i fixed the quality profile issue, but there's still some random error from the sonarr api

**Comment by Drewster727** [comment]
nvm, that fixed it, I just didn't setup my root path. @tidusjar should be good to merge that one up and re-release.

**Comment by tidusjar** [comment]
Ok will do, thanks @Drewster727 !
