### ISSUE TITLE
The database disk image is malformed

### ISSUE THREAD

**Issue by porksandwich** [tidusjar/PlexRequests.Net#347]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

2016/06/21 21:41:41.477 PlexRequests.UI.Program Trace: Getting product version
2016/06/21 21:41:41.477 PlexRequests.UI.Program Info: Version: 1.8.0
2016/06/21 21:41:41.477 PlexRequests.Store.DbConfiguration Trace: Checking DB

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

[CMD Prompt window](https://i.imgur.com/aYykXhZ.png)

1.7.4 was working fine, 1.7.5 had the memory issue so I held off on the update.

I tried 1.8.1, then 1.8.0 and both of them refused to launch with the database disk image malformation.

Should I just start with a fresh DB and set it back up again?

**Comment by Drewster727** [comment]
I don't think we've ever seen that issue before. I'd definitely start fresh and report back with results.

**Comment by porksandwich** [comment]
Yeah I figured repairing a database would but a PITA. 

Deleted it and started over, everything is operational again.  Thanks.

**Comment by Drewster727** [comment]
cool -- going to close this out for now. reopen if the problem shows up again and we'll investigate further. Thanks!

**Comment by tidusjar** [comment]
http://stackoverflow.com/questions/13675615/svn-cleanup-sqlite-database-disk-image-is-malformed

We could possibly try and detect this in the application and attempt to repair. I am unsure why this would have happened though.
