### ISSUE TITLE
Plex Availability Checker not marking requested items as available

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#348]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Reproduction Steps:
I debugged this in my windows environment and it worked fine, but running under my ubuntu/mono environment it never seems to mark previously requested items as available even though they are certainly exists in Plex. 

The issue seems to be perhaps the batchupdate call (or related to that) -- because when I do a search for a show that is available in plex, it shows "Available" in the search results, but just never gets updated/marked as available in the requests page/table.

**Search Page**
![screen shot 2016-06-21 at 9 34 21 pm](https://cloud.githubusercontent.com/assets/4528753/16252945/13794cfa-37f8-11e6-9ed2-01bce0f3b181.png)

**Requests Page**
![screen shot 2016-06-21 at 9 34 45 pm](https://cloud.githubusercontent.com/assets/4528753/16252967/38252376-37f8-11e6-8f09-3d9342041bd3.png)

**Comment by tidusjar** [comment]
Strange why it's not working on Ubuntu...
Can you confirm that the Plex schedule has run? There is a new settings page that tells you the last run time.

**Comment by Drewster727** [comment]
It looks like it ran over night. Not sure what's up. I will keep an eye on it and reopen this issue if it comes up again.
