### ISSUE TITLE
Cannot test connectivity when not logged in as a user

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#351]
#### Plex Requests.Net Version:
1.8.1

#### Operating System: 
FreeNAS-9.10-STABLE-201606072003 (696eba7)

#### Mono Version:
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue May 10 05:31:54 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Nothing logged about issue
```

#### Reproduction Steps:

Go to Plex Requests.
Click admin and login (if you're not already).
Go to settings via Admin Menu and test connectivity for any of the services (Plex, CouchPotato, Sonarr, SickRage, Headphones (Beta)), they should all succeed.
Click Logout in the upper right.
Click on Admin Menu
Test connectivity again, they will all report "Something went wrong".

**Comment by tidusjar** [comment]
Yeah this is because you are authenticated as an admin but have lost your session... This area will be reworked with the introducing the ability to create users.
