### ISSUE TITLE
Reporting issues from search page does nothing

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#352]
#### Plex Requests.Net Version:
1.8.1

#### Operating System: 
FreeNAS-9.10-STABLE-201606072003 (696eba7)

#### Mono Version:
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue May 10 05:31:54 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Nothing logged about issue (Even with Trace on)
```

#### Reproduction Steps:
I search for any movie or show and attempt to report an issue, prewritten or Other and nothing happens. The issue is not logged under the issue page nor is any of the interaction logged in the logs.

**Comment by tidusjar** [comment]
I can't seem to reproduce this issue, every time I report an issue from the search it gives me the success and then I go to the issues and it's there.

**Comment by tedrock** [comment]
Resolved by clearing browser cache
