### ISSUE TITLE
Landing page logo image location does not include URL base

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#355]
#### Plex Requests.Net Version:
1.8.1

#### Operating System: 
FreeNAS-9.10-STABLE-201606072003 (696eba7)

#### Mono Version:
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue May 10 05:31:54 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
N/A
```

#### Reproduction Steps:
If you are using a URL base the landing page shows a broken image.
Viewing the page source reveals it's using `<img class="landing-header" src="/Content/images/logo.png" width="300" />` ignoring my URL base.

**Comment by tidusjar** [comment]
@tedrock Do you have time to confirm some of these issues are fixed in the dev build?

**Comment by tedrock** [comment]
@tidurjar I do, I did a clone of the dev branch but I'm not sure how I'm supposed to start it as there is no exe.

**Comment by tidusjar** [comment]
It's in 1.8.2 now :)

**Comment by tedrock** [comment]
Well that's good. But I wouldn't mind testing the dev build for fixes in the future if you'd like. I just don't know how to run it from source is what I was saying.

**Comment by tidusjar** [comment]
That's fine, for every checkin we queue a build on the build system to check for integrity and run all of our tests. I usually link the build from the build system. I'll add you into the gitter testers group.

Date: Wed, 22 Jun 2016 07:52:18 -0700
