### ISSUE TITLE
Automatic Update failing

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#360]
#### Plex Requests.Net Version:
1.8.1

#### Operating System: 
FreeNAS-9.10-STABLE-201606072003 (696eba7)

#### Mono Version:
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue May 10 05:31:54 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):
Nothing in log but browser console reports
```
http://192.168.1.81:3579/request/admin/autoupdate 500 (Internal Server Error)
```

#### Reproduction Steps:
I  go to the Status section and try to automatically update, i get the progress indicator for a bit while with the "Updating..." status then it stops and nothing happened. This was an issue in the previous version so I just manually updated.

**Comment by karbowiak** [comment]
I'm having an issue with the automatic update aswell, albeit a bit differently

```
Jun 22 20:52:22 NAS mono-sgen[10664]: Plex Requests is running on the following: http://+:3579/
Jun 22 20:52:22 NAS mono-sgen[10664]: All setup, Plex Requests is now ready!
Jun 22 20:53:11 NAS mono-sgen[10664]: xdg-open: unexpected argument 'https://github.com/tidusjar/PlexRequests.Net/releases/download/v1.8.2/PlexRequests.zip'
Jun 22 20:53:11 NAS mono-sgen[10664]: Try 'xdg-open --help' for more information.
Jun 22 20:53:16 NAS mono-sgen[21880]: Starting Up! Please wait, this can usually take a few seconds.
Jun 22 20:53:16 NAS mono-sgen[21880]: Version: 1.8.0
Jun 22 20:53:16 NAS mono-sgen[21880]: Location of the database: /opt/plexrequests/PlexRequests.sqlite
Jun 22 20:53:21 NAS mono-sgen[21880]: no configuration section <common/logging> found - suppressing logging output
Jun 22 20:53:21 NAS mono-sgen[21880]: Plex Requests is running on the following: http://+:3579/
Jun 22 20:53:21 NAS mono-sgen[21880]: All setup, Plex Requests is now ready!
```

that's what i get from `journalctl -fu plexrequests`

**Comment by tidusjar** [comment]
It still needs a bit more work (The autoupdater) to get it consistently stable with mono

**Comment by tidusjar** [comment]
Closing as #326 is the master
