### ISSUE TITLE
No fav icon when using a URL base/reverse proxy

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#363]
#### Plex Requests.Net Version:

1.8.2
#### Operating System:

FreeNAS-9.10-STABLE-201606072003 (696eba7)
#### Mono Version:

Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue May 10 05:31:54 UTC 2016)
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
```
#### Reproduction Steps:

If I go to the app using my reverse proxy (internal or external attempts) I do not see a fav icon for the app. I do see it for other apps behind the proxy so it's app specific. I assume this is something to do with the URL base setting like the logo issue in #355

**Comment by tidusjar** [comment]
Are you sure? Every time I load it up it has it's fav icon... Can you navigate to it directly and see if it appears? e.g. http://localhost:3579/baseurl

**Comment by tedrock** [comment]
ok so yes http://localhost:3579/baseurl works but http://WebserverInternalIP/baseurl http://WebserverExternalIP/baseurl http://domain/baseurl both do not work. They all other apps (Sonarr, CouchPotato, etc) do not have this problem.

**Comment by RacerBas** [comment]
I'm running this on a revers proxy myself (requests.domain.com) and I don't have this issue at all.

FYI I'm running Ubuntu Server 14.04.3 with Apache

**Comment by tedrock** [comment]
Are you using https?

**Comment by RacerBas** [comment]
yes

**Comment by tidusjar** [comment]
@tedrock , is this still an issue?

**Comment by SuperPotatoMen** [comment]
No answer after 28 days :(

**Comment by tidusjar** [comment]
I made changes to the Fav icon in the dev branch that should resolve this anyawy
