### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by DereckR** [tidusjar/PlexRequests.Net#365]
Version 1.8.2

Windows 10 64bit

Request that has been removed shows that it has already been requested when removed? Don't see a way to get it to click again.

Thanks,
Dereck

**Comment by tidusjar** [comment]
So, you remove a request and on the search it's still requested?

**Comment by DereckR** [comment]
Yes it was requested then deleted and it still shows as requested and user can't request it again.

**Comment by DereckR** [comment]
I just did it again to make sure if I click remove from request and got back try to re add says requested.

**Comment by tidusjar** [comment]
Sorry for the late reply on this. Is this still an issue?

**Comment by DereckR** [comment]
Will check it out in just a minute:)

**Comment by tidusjar** [comment]
@DereckR Any update?

**Comment by SuperPotatoMen** [comment]
Closed after more then 10 days waiting :(
