### ISSUE TITLE
500 InternalServerError

### ISSUE THREAD

**Issue by halorrr** [tidusjar/PlexRequests.Net#368]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.2

#### Operating System:
Mac OS X 10.11.5

#### Mono Version:
4.4

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:
Go to url for PlexRequests, press the "Continue" button on the landing page and get the error.

![untitled](https://cloud.githubusercontent.com/assets/1358708/16315473/75d6f5e2-3950-11e6-8278-26b3c1eaa70d.jpg)

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

> 500 - InternalServerError
> Something went horribly, horribly wrong while servicing your request.
> 
> We're sorry :-(
> 
> Error Details
> 
> Nancy.RequestExecutionException: Oh noes! ---> System.IO.IOException: Too many open files
>   at System.Diagnostics.Process.CreatePipe (System.IntPtr& read, System.IntPtr& write, Boolean writeDirection) <0x5574f08 + 0x0018f> in :0 
>   at System.Diagnostics.Process.Start_noshell (System.Diagnostics.ProcessStartInfo startInfo, System.Diagnostics.Process process) <0x5574110 + 0x00257> in :0 
>   --- End of inner exception stack trace ---
>   at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) <0x55c5910 + 0x0025f> in :0

**Comment by halorrr** [comment]
This has happened twice. Each time I can fix it by restarting PlexRequests

**Comment by tidusjar** [comment]
Wow I have never seen that before.

**Comment by tidusjar** [comment]
Looks like it's a bug in mono for OSX. 

Can you try the following command? (It's a workaround)

export MONO_MANAGED_WATCHER=disabled
k kestrel

**Comment by halorrr** [comment]
I can do the 

> export MONO_MANAGED_WATCHER=disabled


but when I enter

> k kestrel

I get 

> -bash: k: command not found

**Comment by tidusjar** [comment]
Did the export command fix it?

**Comment by halorrr** [comment]
I'll wait and see if it happens again. If it doesn't happen again in 24 hours I'll let you know on this thread that it is most likely fixed.

**Comment by halorrr** [comment]
Error hasn't happened again so I think we can consider this fixed for now.
