### ISSUE TITLE
Feature Request: Nicknames

### ISSUE THREAD

**Issue by halorrr** [tidusjar/PlexRequests.Net#369]
It would be a nice feature if as admin I could give my users "nicknames", which in my case would just be the user's real names to make it easier for me to remember who is who when I'm looking at who submitted requests.

I got the idea from seeing this implemented in PlexPy.

**Comment by tidusjar** [comment]
We are looking to completely rework the way we deal with users, proving you with a users page and such. There is a enhancement raised a few days ago about it.

**Comment by tidusjar** [comment]
See #359
