### ISSUE TITLE
PlexRequests is going unresponsive.

### ISSUE THREAD

**Issue by SaskiFX** [tidusjar/PlexRequests.Net#374]
For some reason, PlexRequests is going unresponsive after a period of time on my server. Eventually, it just hangs and doesn't accept any HTTP requests. Top doesn't show anything odd or running away that I can see. I also don't see anything in the logs I have that looks suspicious. (Aside form the log files getting rather large. 40-70 MB.) When I am trying to hit the site while the service is "hung" I never get a timeout or error, until I restart the service then it goes to unable to connect.

If I restart the service, things come back without any issues. 

What logging etc, can I do to help track this down?

#### Plex Requests.Net Version:
1.8.2

#### Operating System:
```
root@debian:/logs# cat /etc/issue
Debian GNU/Linux 8 \n \l
```

#### Mono Version:
```
root@debian:/logs# mono --version
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

#### Applicable Logs (from `/logs/` directory or the Admin page):
Not sure...

#### Reproduction Steps:
Just let the software run.

```
root@debian:/home/craig# service plexrequests status
● plexrequests.service - Plex Requests
   Loaded: loaded (/etc/systemd/system/plexrequests.service; enabled)
   Active: active (running) since Thu 2016-06-23 10:27:53 EDT; 1 day 3h ago
 Main PID: 10363 (mono)
   CGroup: /system.slice/plexrequests.service
           └─10363 /usr/bin/mono /opt/PlexRequests/Release/PlexRequests.exe 3579

Jun 23 10:27:53 debian mono[10363]: Starting Up! Please wait, this can usually take a few seconds.
Jun 23 10:27:53 debian mono[10363]: Version: 1.8.2
Jun 23 10:27:53 debian mono[10363]: Location of the database: /opt/PlexRequests/Release/PlexRequests.sqlite
Jun 23 10:27:56 debian mono[10363]: no configuration section <common/logging> found - suppressing logging output
Jun 23 10:27:56 debian mono[10363]: Plex Requests is running on the following: http://+:3579/
Jun 23 10:27:56 debian mono[10363]: All setup, Plex Requests is now ready!
```

**Comment by tidusjar** [comment]
What are your log level set at?

**Comment by SaskiFX** [comment]
It was set to trace. Likely from the times we were messing with the base URL stuff. I flipped it to Debug just now.

**Comment by tidusjar** [comment]
Put it to error. Trace shouldn't be used in production really. It can make things unstable still.

**Comment by SaskiFX** [comment]
Done. Wonder if it was the log level itself causing the issue by ballooning the logs and making this slow/hang.

**Comment by tidusjar** [comment]
It would have been.

**Comment by SaskiFX** [comment]
Gotcha. I'll update in 24 hours to let you know if it's still having issues.

**Comment by tidusjar** [comment]
@SaskiFX Any issues?

**Comment by SaskiFX** [comment]
Actually, it seems ok. Still responsive today. So this one can get closed I guess. Trace log level seems to have been the culprit.

Random side question, when it finishes downloading a movie request for example, how does PlexRequests know it's available? Is that CouchPotato notifying PlexRequests, or is it Plex? I ask cause I'm not getting stuff marked as available unless I do it by hand. If this is something broken, I'll open a new issue to keep things tracked ok.

**Comment by tidusjar** [comment]
We query couchpotato and Plex to see if it's available. Go into the settings and check the new advanced search option under Plex. It will find it then.

**Comment by SaskiFX** [comment]
Gotcha, thanks. I checked it. I have some downloads in progress, I'll see if they go available automatically.

**Comment by ethanopp** [comment]
I seem to be having this issue with the log level set to Error ...any other ideas?

Starting Up! Please wait, this can usually take a few seconds.                                                                                                  
Version: 2.2.1678                                                                                                                                               
Location of the database: /opt/ombi/Ombi.sqlite                                                                                                                 
no configuration section <common/logging> found - suppressing logging output                                                                                    
Ombi is running on the following: http://+:3579/                                                                                                                
All setup, Ombi is now ready!
