### ISSUE TITLE
"Something Went Wrong" 2008 R2 SP1

### ISSUE THREAD

**Issue by thenicnet** [tidusjar/PlexRequests.Net#375]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

2016/06/26 12:24:36.360 PlexRequests.Services.Jobs.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token. 

2016/06/26 12:24:36.532 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: Validation of the plex settings failed. 

2016/06/26 12:34:36.341 PlexRequests.Services.Jobs.PlexAvailabilityChecker Warn: A setting is null, Ensure Plex is configured correctly, and we have a Plex Auth token. 

2016/06/26 12:34:36.902 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: Validation of the plex settings failed. 

#### Reproduction Steps:

**Running as an admin**
1) Clean install of Plex Requests 1.8.2.
2) Set up admin user.
3) Configure Authentication (Enable User Authentication, Request Token) All of this happens successfully.
4) Attempt to configure anything else (Plex, CouchPotato, Sonarr, PlexRequest, PushBullet) All of these throw "something went wrong" with no further explanation.

Just to see if it would make a difference I've tired configuring PlexRequests on a Windows 10 box without issue, then I copied the DB over to the 2008 R2 server.  Same issue.  The configuration changes stick, but test connectivity or submit throws an error.

Edit #1: Attempted running in compatibility mode for windows 7.  No luck.  Same error.
Edit #2: I can't even change the port number.  I continue to get "something went wrong."

**Comment by tidusjar** [comment]
Did you unblock the .zip file before extracting?

**Comment by thenicnet** [comment]
I suppose I should read the directions, huh?  
I'm going to very quietly close this and go cry... in the corner.

In my defense I've been deploying this on a RasPi, and never reviewed the Windows instructions.  I've just been using 7zip and assumed (like a chump) that'd it just work.

Strangely though, I didn't have this issue on Windows 7, Windows 10, or Windows Server 2012 R2.  Just the Windows Server 2008 R2.  I'm not sure if that's useful information or not. 

Thanks for the help and Plex Requests is fantastic.
