### ISSUE TITLE
razor compilation error

### ISSUE THREAD

**Issue by sch1308** [tidusjar/PlexRequests.Net#378]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.5 trying to update

#### Operating System:

win 10
#### Applicable Logs (from `/logs/` directory or the Admin page):

![image](https://cloud.githubusercontent.com/assets/7896067/16365870/9e916864-3bda-11e6-8f55-34cb45fc2a28.png)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Can you press details and show me what's in the details?

**Comment by sch1308** [comment]
I tried to update to the newest version but not sure what i did besides using the update link within the admin page. 
Razor Compilation Error
We tried, we really did, but we just can't compile your view.

We're sorry :-(

Graphics courtesy of the awesome Matthew Inman

Details
Error Details

Error compiling template: Views/Shared/_Layout.cshtml

Errors:
[CS1061] Line: 20 Column: 12 - 'Nancy.ViewEngines.Razor.HtmlHelpers' does not contain a definition for 'LoadAnalytics' and no extension method 'LoadAnalytics' accepting a first argument of type 'Nancy.ViewEngines.Razor.HtmlHelpers' could be found (are you missing a using directive or an assembly reference?) (show)
[CS1501] Line: 42 Column: 22 - No overload for method 'GetNavbarUrl' takes 5 arguments (show)

Details:
@using Nancy.Security
@using Nancy.Session
@using PlexRequests.UI.Helpers
@using PlexRequests.UI.Models
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase
@{
    var baseUrl = Html.GetBaseUrl();
    var url = string.Empty;
    if (!string.IsNullOrEmpty(baseUrl.ToHtmlString()))
    {
        url = "/" + baseUrl.ToHtmlString();
    }
}
<html>
<div hidden="hidden" id="baseUrl">@baseUrl.ToHtmlString()</div>
<head>
    <title>Plex Requests</title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Html.LoadAnalytics()
    @Html.LoadAssets()
</head>
<body>


    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@url/search">Plex Requests</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @Html.GetNavbarUrl(Context, "/search", "Search", "search")
                    @Html.GetNavbarUrl(Context, "/requests", "Requests", "plus-circle")
                    @Html.GetNavbarUrl(Context, "/issues", "Issues", "exclamation", "<span id=\"issueCount\"></span>")

                </ul>
                <ul class="nav navbar-nav navbar-right">


                    @if (!Context.CurrentUser.IsAuthenticated()) // TODO replace with IsAdmin
                    {

                        <li><a href="@url/login?redirect=@Context.Request.Path"><i class="fa fa-user"></i> Admin</a></li>
                    }
                    else
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user"></i> Admin <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="@url/admin"><i class="fa fa-cog"></i> Settings</a></li>
                                <li><a href="@url/changepassword"><i class="fa fa-key"></i> Change password</a></li>
                                <li class="divider"></li>
                                <li><a href="https://www.paypal.me/PlexRequestsNet" target="_blank"><i class="fa fa-heart" style="color:red"></i> Donate!</a></li>
                                <li class="divider"></li>
                                <li><a href="@url/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
                            </ul>
                        </li>
                    }
                    @if (Context.Request.Session[SessionKeys.UsernameKey] != null)
                    {
                        <li><a href="@url/userlogin/logout"><i class="fa fa-sign-out"></i> Logout</a></li>
                    }
                </ul>
            </div>
        </div>
        <div id="updateAvailable" hidden="hidden"></div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>
    <div class="scroll-top-wrapper ">
        <span class="scroll-top-inner">
            <i class="fa fa-2x fa-arrow-circle-up"></i>
        </span>
    </div>
</body>
</html>
<script>

    $(function () {

        var urlBase = '@Html.GetBaseUrl()';

        // Check for update
        var url = createBaseUrl(urlBase, '/updatechecker');
        $.ajax({
            type: "GET",
            url: url,
            dataType: "json",
            success: function (response) {
                if (response.updateAvailable) {
                    var status = createBaseUrl(urlBase, '/admin/status');
                    $('#updateAvailable').html("<i class='fa fa-cloud-download' aria-hidden='true'></i> There is a new update available! Click <a style='color: white' href='" + status + "'>Here!</a>");
                    $('#updateAvailable').removeAttr("hidden");
                    $('body').addClass('update-available');
                }
            },
            error: function (e) {
                console.log(e);
            }
        });
        // End Check for update


        // Scroller
        $(document).on('scroll', function () {

            if ($(window).scrollTop() > 100) {
                $('.scroll-top-wrapper').addClass('show');
            } else {
                $('.scroll-top-wrapper').removeClass('show');
            }
        });

        $('.scroll-top-wrapper').on('click', scrollToTop);
        // End Scroller


        // Get Issue count
        var issueUrl = createBaseUrl(urlBase, '/issues/issuecount');
        $.ajax({
            type: "GET",
            url: issueUrl,
            dataType: "json",
            success: function (response) {
                if (response) {
                    if(response > 0)
                        $('#issueCount').addClass("badge");
                        $('#issueCount').html(+response);
                }
            },
            error: function (e) {
                console.log(e);
            }
        });
        // End issue count


    });

    function scrollToTop() {
        verticalOffset = typeof (verticalOffset) != 'undefined' ? verticalOffset : 0;
        element = $('body');
        offset = element.offset();
        offsetTop = offset.top;
        $('html, body').animate({ scrollTop: offsetTop }, 500, 'linear');
    }
</script>

Compilation Source:
//------------------------------------------------------------------------------
Line 1:	// <auto-generated>
Line 2:	//     This code was generated by a tool.
Line 3:	//     Runtime Version:4.0.30319.42000
Line 4:	//
Line 5:	//     Changes to this file may cause incorrect behavior and will be lost if
Line 6:	//     the code is regenerated.
Line 7:	// </auto-generated>
Line 8:	//------------------------------------------------------------------------------
Line 9:	
Line 10:	namespace RazorOutput {
Line 11:	    using Microsoft.CSharp.RuntimeBinder;
Line 12:	    using System;
Line 13:	    using System.IO;
Line 14:	    
Line 15:	    #line 1 "roo"
Line 16:	    using Nancy.Security;
Line 17:	    
Line 18:	    #line default
Line 19:	    #line hidden
Line 20:	    
Line 21:	    #line 2 "roo"
Line 22:	    using Nancy.Session;
Line 23:	    
Line 24:	    #line default
Line 25:	    #line hidden
Line 26:	    
Line 27:	    #line 3 "roo"
Line 28:	    using PlexRequests.UI.Helpers;
Line 29:	    
Line 30:	    #line default
Line 31:	    #line hidden
Line 32:	    
Line 33:	    #line 4 "roo"
Line 34:	    using PlexRequests.UI.Models;
Line 35:	    
Line 36:	    #line default
Line 37:	    #line hidden
Line 38:	    using System.Dynamic;
Line 39:	    
Line 40:	    
Line 41:	    public class RazorView : Nancy.ViewEngines.Razor.NancyRazorViewBase {
Line 42:	        
Line 43:	#line hidden
Line 44:	        
Line 45:	        public RazorView() {
Line 46:	        }
Line 47:	        
Line 48:	        public override void Execute() {
Line 49:	            
Line 50:	            #line 6 "roo"
Line 51:	  
Line 52:	    var baseUrl = Html.GetBaseUrl();
Line 53:	    var url = string.Empty;
Line 54:	    if (!string.IsNullOrEmpty(baseUrl.ToHtmlString()))
Line 55:	    {
Line 56:	        url = "/" + baseUrl.ToHtmlString();
Line 57:	    }
Line 58:	
Line 59:	            
Line 60:	            #line default
Line 61:	            #line hidden
Line 62:	WriteLiteral("\r\n<html>\r\n<div");
Line 63:	
Line 64:	WriteLiteral(" hidden=\"hidden\"");
Line 65:	
Line 66:	WriteLiteral(" id=\"baseUrl\"");
Line 67:	
Line 68:	WriteLiteral(">");
Line 69:	
Line 70:	            
Line 71:	            #line 15 "roo"
Line 72:	                             Write(baseUrl.ToHtmlString());
Line 73:	
Line 74:	            
Line 75:	            #line default
Line 76:	            #line hidden
Line 77:	WriteLiteral("</div>\r\n<head>\r\n    <title>Plex Requests</title>\r\n    \r\n    <meta");
Line 78:	
Line 79:	WriteLiteral(" name=\"viewport\"");
Line 80:	
Line 81:	WriteLiteral(" content=\"width=device-width, initial-scale=1\"");
Line 82:	
Line 83:	WriteLiteral(">\r\n");
Line 84:	
Line 85:	WriteLiteral("    ");
Line 86:	
Line 87:	            
Line 88:	            #line 20 "roo"
Line 89:	Write(Html.LoadAnalytics());
Line 90:	
Line 91:	            
Line 92:	            #line default
Line 93:	            #line hidden
Line 94:	WriteLiteral("\r\n");
Line 95:	
Line 96:	WriteLiteral("    ");
Line 97:	
Line 98:	            
Line 99:	            #line 21 "roo"
Line 100:	Write(Html.LoadAssets());
Line 101:	
Line 102:	            
Line 103:	            #line default
Line 104:	            #line hidden
Line 105:	WriteLiteral("\r\n</head>\r\n<body>\r\n\r\n\r\n    <nav");
Line 106:	
Line 107:	WriteLiteral(" class=\"navbar navbar-default\"");
Line 108:	
Line 109:	WriteLiteral(">\r\n        <div");
Line 110:	
Line 111:	WriteLiteral(" class=\"container-fluid\"");
Line 112:	
Line 113:	WriteLiteral(">\r\n            <div");
Line 114:	
Line 115:	WriteLiteral(" class=\"navbar-header\"");
Line 116:	
Line 117:	WriteLiteral(">\r\n                <button");
Line 118:	
Line 119:	WriteLiteral(" type=\"button\"");
Line 120:	
Line 121:	WriteLiteral(" class=\"navbar-toggle collapsed\"");
Line 122:	
Line 123:	WriteLiteral(" data-toggle=\"collapse\"");
Line 124:	
Line 125:	WriteLiteral(" data-target=\"#bs-example-navbar-collapse-1\"");
Line 126:	
Line 127:	WriteLiteral(">\r\n                    <span");
Line 128:	
Line 129:	WriteLiteral(" class=\"sr-only\"");
Line 130:	
Line 131:	WriteLiteral(">Toggle navigation</span>\r\n                    <span");
Line 132:	
Line 133:	WriteLiteral(" class=\"icon-bar\"");
Line 134:	
Line 135:	WriteLiteral("></span>\r\n                    <span");
Line 136:	
Line 137:	WriteLiteral(" class=\"icon-bar\"");
Line 138:	
Line 139:	WriteLiteral("></span>\r\n                    <span");
Line 140:	
Line 141:	WriteLiteral(" class=\"icon-bar\"");
Line 142:	
Line 143:	WriteLiteral("></span>\r\n                </button>\r\n                <a");
Line 144:	
Line 145:	WriteLiteral(" class=\"navbar-brand\"");
Line 146:	
Line 147:	WriteAttribute("href", Tuple.Create(" href=\"", 1183), Tuple.Create("\"", 1201)
Line 148:	            
Line 149:	            #line 35 "roo"
Line 150:	, Tuple.Create(Tuple.Create("", 1190), Tuple.Create<System.Object, System.Int32>(url
Line 151:	            
Line 152:	            #line default
Line 153:	            #line hidden
Line 154:	, 1190), false)
Line 155:	, Tuple.Create(Tuple.Create("", 1194), Tuple.Create("/search", 1194), true)
Line 156:	);
Line 157:	
Line 158:	WriteLiteral(">Plex Requests</a>\r\n            </div>\r\n\r\n            <div");
Line 159:	
Line 160:	WriteLiteral(" class=\"collapse navbar-collapse\"");
Line 161:	
Line 162:	WriteLiteral(" id=\"bs-example-navbar-collapse-1\"");
Line 163:	
Line 164:	WriteLiteral(">\r\n                <ul");
Line 165:	
Line 166:	WriteLiteral(" class=\"nav navbar-nav\"");
Line 167:	
Line 168:	WriteLiteral(">\r\n");
Line 169:	
Line 170:	WriteLiteral("                    ");
Line 171:	
Line 172:	            
Line 173:	            #line 40 "roo"
Line 174:	               Write(Html.GetNavbarUrl(Context, "/search", "Search", "search"));
Line 175:	
Line 176:	            
Line 177:	            #line default
Line 178:	            #line hidden
Line 179:	WriteLiteral("\r\n");
Line 180:	
Line 181:	WriteLiteral("                    ");
Line 182:	
Line 183:	            
Line 184:	            #line 41 "roo"
Line 185:	               Write(Html.GetNavbarUrl(Context, "/requests", "Requests", "plus-circle"));
Line 186:	
Line 187:	            
Line 188:	            #line default
Line 189:	            #line hidden
Line 190:	WriteLiteral("\r\n");
Line 191:	
Line 192:	WriteLiteral("                    ");
Line 193:	
Line 194:	            
Line 195:	            #line 42 "roo"
Line 196:	               Write(Html.GetNavbarUrl(Context, "/issues", "Issues", "exclamation", "<span id=\"issueCount\"></span>"));
Line 197:	
Line 198:	            
Line 199:	            #line default
Line 200:	            #line hidden
Line 201:	WriteLiteral("\r\n\r\n                </ul>\r\n                <ul");
Line 202:	
Line 203:	WriteLiteral(" class=\"nav navbar-nav navbar-right\"");
Line 204:	
Line 205:	WriteLiteral(">\r\n\r\n\r\n");
Line 206:	
Line 207:	            
Line 208:	            #line 48 "roo"
Line 209:	                    
Line 210:	            
Line 211:	            #line default
Line 212:	            #line hidden
Line 213:	            
Line 214:	            #line 48 "roo"
Line 215:	                     if (!Context.CurrentUser.IsAuthenticated()) // TODO replace with IsAdmin
Line 216:	                    {
Line 217:	
Line 218:	
Line 219:	            
Line 220:	            #line default
Line 221:	            #line hidden
Line 222:	WriteLiteral("                        <li><a");
Line 223:	
Line 224:	WriteAttribute("href", Tuple.Create(" href=\"", 1901), Tuple.Create("\"", 1949)
Line 225:	            
Line 226:	            #line 51 "roo"
Line 227:	, Tuple.Create(Tuple.Create("", 1908), Tuple.Create<System.Object, System.Int32>(url
Line 228:	            
Line 229:	            #line default
Line 230:	            #line hidden
Line 231:	, 1908), false)
Line 232:	, Tuple.Create(Tuple.Create("", 1912), Tuple.Create("/login?redirect=", 1912), true)
Line 233:	            
Line 234:	            #line 51 "roo"
Line 235:	, Tuple.Create(Tuple.Create("", 1928), Tuple.Create<System.Object, System.Int32>(Context.Request.Path
Line 236:	            
Line 237:	            #line default
Line 238:	            #line hidden
Line 239:	, 1928), false)
Line 240:	);
Line 241:	
Line 242:	WriteLiteral("><i");
Line 243:	
Line 244:	WriteLiteral(" class=\"fa fa-user\"");
Line 245:	
Line 246:	WriteLiteral("></i> Admin</a></li>\r\n");
Line 247:	
Line 248:	            
Line 249:	            #line 52 "roo"
Line 250:	                    }
Line 251:	                    else
Line 252:	                    {
Line 253:	
Line 254:	            
Line 255:	            #line default
Line 256:	            #line hidden
Line 257:	WriteLiteral("                        <li");
Line 258:	
Line 259:	WriteLiteral(" class=\"dropdown\"");
Line 260:	
Line 261:	WriteLiteral(">\r\n                            <a");
Line 262:	
Line 263:	WriteLiteral(" href=\"#\"");
Line 264:	
Line 265:	WriteLiteral(" class=\"dropdown-toggle\"");
Line 266:	
Line 267:	WriteLiteral(" data-toggle=\"dropdown\"");
Line 268:	
Line 269:	WriteLiteral(" role=\"button\"");
Line 270:	
Line 271:	WriteLiteral(" aria-expanded=\"false\"");
Line 272:	
Line 273:	WriteLiteral("><i");
Line 274:	
Line 275:	WriteLiteral(" class=\"fa fa-user\"");
Line 276:	
Line 277:	WriteLiteral("></i> Admin <span");
Line 278:	
Line 279:	WriteLiteral(" class=\"caret\"");
Line 280:	
Line 281:	WriteLiteral("></span></a>\r\n                            <ul");
Line 282:	
Line 283:	WriteLiteral(" class=\"dropdown-menu\"");
Line 284:	
Line 285:	WriteLiteral(" role=\"menu\"");
Line 286:	
Line 287:	WriteLiteral(">\r\n                                <li><a");
Line 288:	
Line 289:	WriteAttribute("href", Tuple.Create(" href=\"", 2408), Tuple.Create("\"", 2425)
Line 290:	            
Line 291:	            #line 58 "roo"
Line 292:	, Tuple.Create(Tuple.Create("", 2415), Tuple.Create<System.Object, System.Int32>(url
Line 293:	            
Line 294:	            #line default
Line 295:	            #line hidden
Line 296:	, 2415), false)
Line 297:	, Tuple.Create(Tuple.Create("", 2419), Tuple.Create("/admin", 2419), true)
Line 298:	);
Line 299:	
Line 300:	WriteLiteral("><i");
Line 301:	
Line 302:	WriteLiteral(" class=\"fa fa-cog\"");
Line 303:	
Line 304:	WriteLiteral("></i> Settings</a></li>\r\n                                <li><a");
Line 305:	
Line 306:	WriteAttribute("href", Tuple.Create(" href=\"", 2510), Tuple.Create("\"", 2536)
Line 307:	            
Line 308:	            #line 59 "roo"
Line 309:	, Tuple.Create(Tuple.Create("", 2517), Tuple.Create<System.Object, System.Int32>(url
Line 310:	            
Line 311:	            #line default
Line 312:	            #line hidden
Line 313:	, 2517), false)
Line 314:	, Tuple.Create(Tuple.Create("", 2521), Tuple.Create("/changepassword", 2521), true)
Line 315:	);
Line 316:	
Line 317:	WriteLiteral("><i");
Line 318:	
Line 319:	WriteLiteral(" class=\"fa fa-key\"");
Line 320:	
Line 321:	WriteLiteral("></i> Change password</a></li>\r\n                                <li");
Line 322:	
Line 323:	WriteLiteral(" class=\"divider\"");
Line 324:	
Line 325:	WriteLiteral("></li>\r\n                                <li><a");
Line 326:	
Line 327:	WriteLiteral(" href=\"https://www.paypal.me/PlexRequestsNet\"");
Line 328:	
Line 329:	WriteLiteral(" target=\"_blank\"");
Line 330:	
Line 331:	WriteLiteral("><i");
Line 332:	
Line 333:	WriteLiteral(" class=\"fa fa-heart\"");
Line 334:	
Line 335:	WriteLiteral(" style=\"color:red\"");
Line 336:	
Line 337:	WriteLiteral("></i> Donate!</a></li>\r\n                                <li");
Line 338:	
Line 339:	WriteLiteral(" class=\"divider\"");
Line 340:	
Line 341:	WriteLiteral("></li>\r\n                                <li><a");
Line 342:	
Line 343:	WriteAttribute("href", Tuple.Create(" href=\"", 2910), Tuple.Create("\"", 2928)
Line 344:	            
Line 345:	            #line 63 "roo"
Line 346:	, Tuple.Create(Tuple.Create("", 2917), Tuple.Create<System.Object, System.Int32>(url
Line 347:	            
Line 348:	            #line default
Line 349:	            #line hidden
Line 350:	, 2917), false)
Line 351:	, Tuple.Create(Tuple.Create("", 2921), Tuple.Create("/logout", 2921), true)
Line 352:	);
Line 353:	
Line 354:	WriteLiteral("><i");
Line 355:	
Line 356:	WriteLiteral(" class=\"fa fa-sign-out\"");
Line 357:	
Line 358:	WriteLiteral("></i> Logout</a></li>\r\n                            </ul>\r\n                       " +
Line 359:	" </li>\r\n");
Line 360:	
Line 361:	            
Line 362:	            #line 66 "roo"
Line 363:	                    }
Line 364:	
Line 365:	            
Line 366:	            #line default
Line 367:	            #line hidden
Line 368:	WriteLiteral("                    ");
Line 369:	
Line 370:	            
Line 371:	            #line 67 "roo"
Line 372:	                     if (Context.Request.Session[SessionKeys.UsernameKey] != null)
Line 373:	                    {
Line 374:	
Line 375:	            
Line 376:	            #line default
Line 377:	            #line hidden
Line 378:	WriteLiteral("                        <li><a");
Line 379:	
Line 380:	WriteAttribute("href", Tuple.Create(" href=\"", 3204), Tuple.Create("\"", 3232)
Line 381:	            
Line 382:	            #line 69 "roo"
Line 383:	, Tuple.Create(Tuple.Create("", 3211), Tuple.Create<System.Object, System.Int32>(url
Line 384:	            
Line 385:	            #line default
Line 386:	            #line hidden
Line 387:	, 3211), false)
Line 388:	, Tuple.Create(Tuple.Create("", 3215), Tuple.Create("/userlogin/logout", 3215), true)
Line 389:	);
Line 390:	
Line 391:	WriteLiteral("><i");
Line 392:	
Line 393:	WriteLiteral(" class=\"fa fa-sign-out\"");
Line 394:	
Line 395:	WriteLiteral("></i> Logout</a></li>\r\n");
Line 396:	
Line 397:	            
Line 398:	            #line 70 "roo"
Line 399:	                    }
Line 400:	
Line 401:	            
Line 402:	            #line default
Line 403:	            #line hidden
Line 404:	WriteLiteral("                </ul>\r\n            </div>\r\n        </div>\r\n        <div");
Line 405:	
Line 406:	WriteLiteral(" id=\"updateAvailable\"");
Line 407:	
Line 408:	WriteLiteral(" hidden=\"hidden\"");
Line 409:	
Line 410:	WriteLiteral("></div>\r\n    </nav>\r\n\r\n    <div");
Line 411:	
Line 412:	WriteLiteral(" class=\"container\"");
Line 413:	
Line 414:	WriteLiteral(">\r\n");
Line 415:	
Line 416:	WriteLiteral("        ");
Line 417:	
Line 418:	            
Line 419:	            #line 78 "roo"
Line 420:	   Write(RenderBody());
Line 421:	
Line 422:	            
Line 423:	            #line default
Line 424:	            #line hidden
Line 425:	WriteLiteral("\r\n    </div>\r\n    <div");
Line 426:	
Line 427:	WriteLiteral(" class=\"scroll-top-wrapper \"");
Line 428:	
Line 429:	WriteLiteral(">\r\n        <span");
Line 430:	
Line 431:	WriteLiteral(" class=\"scroll-top-inner\"");
Line 432:	
Line 433:	WriteLiteral(">\r\n            <i");
Line 434:	
Line 435:	WriteLiteral(" class=\"fa fa-2x fa-arrow-circle-up\"");
Line 436:	
Line 437:	WriteLiteral("></i>\r\n        </span>\r\n    </div>\r\n</body>\r\n</html>\r\n<script>\r\n\r\n    $(function " +
Line 438:	"() {\r\n\r\n        var urlBase = \'");
Line 439:	
Line 440:	            
Line 441:	            #line 91 "roo"
Line 442:	                  Write(Html.GetBaseUrl());
Line 443:	
Line 444:	            
Line 445:	            #line default
Line 446:	            #line hidden
Line 447:	WriteLiteral("\';\r\n\r\n        // Check for update\r\n        var url = createBaseUrl(urlBase, \'/upd" +
Line 448:	"atechecker\');\r\n        $.ajax({\r\n            type: \"GET\",\r\n            url: url," +
Line 449:	"\r\n            dataType: \"json\",\r\n            success: function (response) {\r\n   " +
Line 450:	"             if (response.updateAvailable) {\r\n                    var status = c" +
Line 451:	"reateBaseUrl(urlBase, \'/admin/status\');\r\n                    $(\'#updateAvailable" +
Line 452:	"\').html(\"<i class=\'fa fa-cloud-download\' aria-hidden=\'true\'></i> There is a new " +
Line 453:	"update available! Click <a style=\'color: white\' href=\'\" + status + \"\'>Here!</a>\"" +
Line 454:	");\r\n                    $(\'#updateAvailable\').removeAttr(\"hidden\");\r\n           " +
Line 455:	"         $(\'body\').addClass(\'update-available\');\r\n                }\r\n           " +
Line 456:	" },\r\n            error: function (e) {\r\n                console.log(e);\r\n       " +
Line 457:	"     }\r\n        });\r\n        // End Check for update\r\n\r\n\r\n        // Scroller\r\n " +
Line 458:	"       $(document).on(\'scroll\', function () {\r\n\r\n            if ($(window).scrol" +
Line 459:	"lTop() > 100) {\r\n                $(\'.scroll-top-wrapper\').addClass(\'show\');\r\n   " +
Line 460:	"         } else {\r\n                $(\'.scroll-top-wrapper\').removeClass(\'show\');" +
Line 461:	"\r\n            }\r\n        });\r\n\r\n        $(\'.scroll-top-wrapper\').on(\'click\', scr" +
Line 462:	"ollToTop);\r\n        // End Scroller\r\n\r\n\r\n        // Get Issue count\r\n        var" +
Line 463:	" issueUrl = createBaseUrl(urlBase, \'/issues/issuecount\');\r\n        $.ajax({\r\n   " +
Line 464:	"         type: \"GET\",\r\n            url: issueUrl,\r\n            dataType: \"json\"," +
Line 465:	"\r\n            success: function (response) {\r\n                if (response) {\r\n " +
Line 466:	"                   if(response > 0)\r\n                        $(\'#issueCount\').ad" +
Line 467:	"dClass(\"badge\");\r\n                        $(\'#issueCount\').html(+response);\r\n   " +
Line 468:	"             }\r\n            },\r\n            error: function (e) {\r\n             " +
Line 469:	"   console.log(e);\r\n            }\r\n        });\r\n        // End issue count\r\n\r\n\r\n" +
Line 470:	"    });\r\n\r\n    function scrollToTop() {\r\n        verticalOffset = typeof (vertic" +
Line 471:	"alOffset) != \'undefined\' ? verticalOffset : 0;\r\n        element = $(\'body\');\r\n  " +
Line 472:	"      offset = element.offset();\r\n        offsetTop = offset.top;\r\n        $(\'ht" +
Line 473:	"ml, body\').animate({ scrollTop: offsetTop }, 500, \'linear\');\r\n    }\r\n</script>");
Line 474:	
Line 475:	        }
Line 476:	    }
Line 477:	}
Line 478:

**Comment by tidusjar** [comment]
Did you unblock the `.zip` file before extracting?

**Comment by sch1308** [comment]
not 100% sure, how can i stop the service to overwrite the files? its not installed with nssm.

**Comment by tidusjar** [comment]
`Ctrl + C` should do it.

**Comment by sch1308** [comment]
id rather just start over with a fresh install, how do i stop the program so not get the "this file is in use" error?

**Comment by tidusjar** [comment]
I'm not sure what you are referring to? Unblock the zip and extract it

**Comment by sch1308** [comment]
![image](https://cloud.githubusercontent.com/assets/7896067/16432096/a14d4b0e-3d51-11e6-9056-7fccde7d7df8.png)

**Comment by tidusjar** [comment]
Kill the process?

**Comment by sch1308** [comment]
yes but im asking how since i cant get to the web ui, im on win 10.

On Tue, Jun 28, 2016 at 5:00 PM, Jamie <notifications@github.com> wrote:

> Kill the process?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tidusjar/PlexRequests.Net/issues/378#issuecomment-229181798>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHh8Ay9ry040wG0nYvdQpNCRdG7Inwaaks5qQYtcgaJpZM4I-raT>
> .
>



-- 
Scott Holmes
(954) 594-0355
*scottholmes.me <http://scottholmes.me>*

**Comment by tidusjar** [comment]
Ah ok, Task manager and kill PlexRequests.UI.exe
