### ISSUE TITLE
Don't allow requesting when the tv or movie has no provider ID

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#379]
example:
Go to Search page > TV Shows > search for "Dude Perfect"
Try to add "The Dude Perfect Show (2016)" -- it won't work because for whatever reason it has an invalid tvID (it's just coming in as 0)

So, because we can't control what's coming in from external APIs, we should add some handling logic.

**Comment by Drewster727** [comment]
Found another show "Ride With Norman Reedus (2016)"

Strangely enough, one of my users was able to successfully request it, but it just showed up as "Bad Request" in the requests section...

**Comment by tidusjar** [comment]
Yeah, I usually report the ones I found on the TV Maze forums. How do you suggest we handle these cases?
