### ISSUE TITLE
Clear availabe movies/shows

### ISSUE THREAD

**Issue by damiantje99** [tidusjar/PlexRequests.Net#382]
Is it possible to create an option to delete only movies or shows that are available after requesting? This way you won't get a request page with movies that are already available, so you can keep it clean.

For now we can only delete all requested movies.

**Comment by tidusjar** [comment]
Hmmm... it's possible, but I thought people without notifications might want to see if it's available now.
Anyone else got an opinion on this?

Date: Tue, 28 Jun 2016 08:32:40 -0700

**Comment by damiantje99** [comment]
That's a good point, maybe you could add it as an second option so that the owner of the page could chose for himself if he want's to keep it or not.

**Comment by LastStarFighter** [comment]
What about having another tab/link under the Movies & TV Shows that separates the list into something like: Requested, Available, Pending....?

**Comment by tidusjar** [comment]
@LastStarFighter That's what the filters are for.

**Comment by LastStarFighter** [comment]
Yikes maybe i need to turn auto approve off so it forces me to use the interface more...  then how about saving the filter list preference instead of defaulting to "All"? In theory when you navigate to the requests page it'll automatically just show you the items your interested in and you don't necessarily need to delete them just to declutter your list.

**Comment by tidusjar** [comment]
True! We can add that :)

**Comment by LastStarFighter** [comment]
@tidusjar I just turned on require approval for Movie and TV Shows but no matter what when i go to the request page it shows as already approved? Also the movie never gets added to couch.  I did a clean install of the latest v1.8.3 and still seeing the same issue, the logs don't really show anything and wondering if your experiencing this?
