### ISSUE TITLE
Can't connect to couchpotato

### ISSUE THREAD

**Issue by RacerBas** [tidusjar/PlexRequests.Net#387]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.2

#### Operating System:
Ubuntu Server 14.04

#### Mono Version:
4.2.3

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
Exception when calling GetProfiles for CP, Retrying 00:00:02	PlexRequests.Api.CouchPotatoApi	Error	6/29/2016 8:44:42 PM
System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x40de6090 + 0x001a7> in :0 at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) <0x40de2d20 + 0x0059f> in :0 --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x40de3c50 + 0x001ab> in :0 at System.Net.HttpWebRequest.GetResponse () <0x40ddc9b0 + 0x0005a> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x40ddc5e0 + 0x00043> in :0 	PlexRequests.Api.ApiRequest	Error	6/29/2016 8:44:42 PM
Begin executing GetProfiles call to CouchPotato for quality profiles	PlexRequests.Core.Setup	Info	6/29/2016 8:44:42 PM
```

#### Reproduction Steps:

I can't seem to be able to connect to couchpotato no matter what I try

I filled in the server, port and api key but it still says: something went wrong
the api key is correct.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Well the error tells me that the Connection refused. Is there a firewall between them?

**Comment by RacerBas** [comment]
The only thing I have running is IPTables on which port 5050 is open, plus they're both running on the same machine.

**Comment by RacerBas** [comment]
I just found something new while checking the logs, basically the api key works but it needs a username and password to work (no I can't disable this since couchpotato is facing the internet too)
![capture](https://cloud.githubusercontent.com/assets/1407767/16978062/304aedfc-4e5a-11e6-8588-a082c9a34f96.PNG)

**Comment by tidusjar** [comment]
We get that screen when we cannot correctly authenticate with CP, so because we couldn't auth then we get redirected to the login page which is what is happening here.

Do you have your BaseUrl set in CouchPotato? If you do you need to set the `Sub Directory` to the Base Url.

**Comment by RacerBas** [comment]
I don't have it set

**Comment by tidusjar** [comment]
No base url in CP? 

So if your CP api key correct?

Can you send me a screenshot of your settings (Just blank out the api key)

**Comment by RacerBas** [comment]
so I noticed there was a space in front of the key, I removed it and now it works.

Excuse me while I go slam my head against my desk

**Comment by tidusjar** [comment]
Hmmm that sucks.
I'll trim the spaces from all API keys from now on.

**Comment by RacerBas** [comment]
side question: If Í don't set a root directory for sonarr it will take the default right?

**Comment by tidusjar** [comment]
If there is no Sub Dir for Sonarr, then it will be http://localhost:port/ 
If there is a sub dir then it will be http://localhost:port/subdir/

**Comment by SoftBrok** [comment]
This is not fixed in 1.8.4. The API key has no whitespace around it, but the daemon will fail to connect to CouchPotato and SickRage seemingly at random. No firewalls are in place. No network blocks. No resource issues.

The meteor variant works without any errors at all.

**Comment by tidusjar** [comment]
And your still getting the error from the first post? Are you sure there are no other related errors?

**Comment by filoor** [comment]
I still not able to connect to couchpotato can sombody help me
