### ISSUE TITLE
TV and Movies are being auto approved for users not on the whitelist and not actually being sent to CP or Sonarr

### ISSUE THREAD

**Issue by Doonga** [tidusjar/PlexRequests.Net#389]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page): 

2016/06/29 22:37:24.684 PlexRequests.UI.Modules.UserLoginModule Debug: Username "********" attempting to login 
2016/06/29 22:37:24.747 PlexRequests.UI.Modules.UserLoginModule Debug: Need to auth 
2016/06/29 22:37:25.153 PlexRequests.UI.Modules.UserLoginModule Debug: Friends list result = True 
2016/06/29 22:37:25.184 PlexRequests.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session. 
2016/06/29 22:37:39.669 PlexRequests.Api.ApiRequest Trace: Api Content Response: 
2016/06/29 22:37:39.684 PlexRequests.Api.ApiRequest Trace: {"status":1,"request":"My CP API Key"} 
2016/06/29 22:37:39.715 PlexRequests.Api.ApiRequest Trace: Deserialzing Object 
2016/06/29 22:37:39.731 PlexRequests.Api.ApiRequest Trace: Finished Deserialzing Object 

#### Reproduction Steps:

I should note that the user I'm using was on the whitelist, but I removed it to test. I confirmed that they are indeed no longer showing. I'm using a reverse proxy, but it's hostname based, not via base url. (https://requests.myhostname.com/). I also noticed that the API key field isn't saving while playing around with this.

I log in as a user not on the whitelist, then request either a TV show or a movie. It then says that it was requested. When I go into admin to approve it, it shows as already approved (which it shouldn't), and it doesn't appear in either CP or Sonarr (depending on whether or not it was a TV show or a movie.) If it was actually approved I'd expect to see it sent over, but now I'm stuck and can't approve it because it's already approved and there's no way to progress.

**Comment by tidusjar** [comment]
Fixing now.
Apologies

**Comment by Doonga** [comment]
Thanks! Looks like it's working properly now. There's an issue with the version number, but that's been reported in another issue.

**Comment by tidusjar** [comment]
Working on that one now.

**Comment by tidusjar** [comment]
@Doonga Redownload the .zip file. Sorry about that
