### ISSUE TITLE
How to Manual Update? 

### ISSUE THREAD

**Issue by rickcab1** [tidusjar/PlexRequests.Net#393]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Operating System:Windows 7 64Bit

Hey guys new to app and loving it,  Just wondering since the auto updater isnt working for me right now I was wondering if anyone has a update guide?  Or is it the same as a new install? Thanks for information in advance.

**Comment by tidusjar** [comment]
Same as a new install, just overwrite all the files (Your settings will not be lost).

**Comment by kilabyte** [comment]
everytime i do that all my settings are lost

**Comment by tidusjar** [comment]
The settings are in the Ombi. SQLite file. That file is created by the application and is not present in the .zip. So if you extract and overwrite that file will still be there untouched. 

So you must be doing something different. Please make a thread on the forums.

**Comment by kilabyte** [comment]
ok great that was the file i was looking for. Seems when you go to "replace" the directory it removes everything and then replaces it. It should be a merge not replace. Got it updated. thanks.
