### ISSUE TITLE
Helping you with French translation

### ISSUE THREAD

**Issue by ElYoM** [tidusjar/PlexRequests.Net#395]
Hello,

To help you with the French translation (which is my native language), I made a Google Sheet to translate all the elements of the interface by taking into consideration the context of each word depending on where it is located. You can view it here : https://docs.google.com/spreadsheets/d/1b6pOJR2MXztjZ1gY-mHC5Q1efbV49NF1Aw4m4DLOKxA/edit?usp=sharing

There is also an encoding problem with accented characters not displaying properly on all pages, maybe UTF8 encoding will resolve it ?

And sorry for my English which is not as good as my French. ^^

PS : Thank you again for your amazing work. ;)

**Comment by tidusjar** [comment]
Oh Wow! 
That is excellent. I'll sort out the encoding problem, Yes UTF8 will resolve the issue.
I'll make these changes :)

Date: Thu, 30 Jun 2016 06:49:16 -0700

**Comment by ElYoM** [comment]
Perhaps I forgot some translations, don't hesitate to point it out as needed.

**Comment by tidusjar** [comment]
Thanks for your help

**Comment by ElYoM** [comment]
You're welcome, it's nice if it can help you.

**Comment by tedrock** [comment]
Might be a good idea to setup a spreadsheet/template like this to allow others to easily translate for other languages.

Also @ElYoM you don't need to apologize for your English, I would have never guessed it's not your native language :)

**Comment by saitoh183** [comment]
im guessing this will be corrected

![image](https://cloud.githubusercontent.com/assets/1534197/16511371/5604d3a6-3f1d-11e6-9e3d-ac495d9df3de.png)

There should be no "d' "

**Comment by saitoh183** [comment]
And this is isnt translated for the admin login

![image](https://cloud.githubusercontent.com/assets/1534197/16511386/8faef726-3f1d-11e6-8bdc-ec47734b3e7c.png)

**Comment by saitoh183** [comment]
@ElYoM added some comments to your spreadsheet

@tidusjar im gussing not all sections of PR are translated yet?

**Comment by tidusjar** [comment]
Not everything is translated yet. I did mention it in the release notes. It's quite time consuming and in trying to one page at a time

**Comment by saitoh183** [comment]
Yeah i missied that :)

**Comment by Ruvetuve** [comment]
@ElYoM can you add a Dutch column? i think this is a perfect way of editing the translations. @tidusjar what do you think?

**Comment by ElYoM** [comment]
Like explained in https://github.com/tidusjar/PlexRequests.Net/issues/396, I think it will be more convenient for @tidusjar to edit directly his translation's file in Onedrive. Before, you have to ask him access to this file. ;)

**Comment by tidusjar** [comment]
I'm going to open 1 issue regarding translations so we can manage them in one place!
