### ISSUE TITLE
I'd like to help you translate in Italian

### ISSUE THREAD

**Issue by giacomofabbri** [tidusjar/PlexRequests.Net#396]
Hi! You may remember me, I solved my problem with the daemon, etc, now I'm willing to help you translate in a better Italian, right now it's not correct at all. Give me some kind of file with all the word and as soon as I can I will give you!! Thanks man

**Comment by tidusjar** [comment]
Sorry about the bad translations. I've used a tool and it sucks it seems!

Here is a list: https://1drv.ms/x/s!Ar0TPpCxBSHZqwOpVGm_4J01vjj1

**Comment by giacomofabbri** [comment]
Here my Live mail jack970@hotmail.it, if you'd like to add me so I will be able to modify the file directly! Thanks bro

**Comment by ElYoM** [comment]
I can also include translations in French in this file if you find it more convenient.

**Comment by tidusjar** [comment]
@ElYoM I don't mind, it is a bit easier since I can just import it into the code straight away. Drop me your email and i'll send a editable link across

**Comment by ElYoM** [comment]
OK, my email is elyom@hotmail.fr. ;)

**Comment by ElYoM** [comment]
Thanks for access to the file. French translation done. ;)

**Comment by tidusjar** [comment]
Awesome, I'll import the translations. They will be available in the next release (not sure when that is).


  
  


I'm trying to release smaller features more often, rather than have 1 massive release full with lots of features.

**Comment by ElYoM** [comment]
No problem, we will be patient.

**Comment by giacomofabbri** [comment]
I translate everything as well!! Thanks for all,

**Comment by saitoh183** [comment]
Just a small not on the fr translation:

Série tv should be Série télé  because tv is not a actual french word

**Comment by tidusjar** [comment]
OK thanks. All translations is now in #402
