### ISSUE TITLE
Server randomly stops

### ISSUE THREAD

**Issue by zack-hable** [tidusjar/PlexRequests.Net#397]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.7.5

#### Operating System:
Windows 10 Pro X64

#### Mono Version:
latest

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

The issue seems to happen randomly. nothing I can find in the logs fixes it exactly.  From what I see a simple nssm stop/start PlexRequests.Net fixes it.

**Comment by tidusjar** [comment]
What's your log level set to?

**Comment by zack-hable** [comment]
Trace

**Comment by tidusjar** [comment]
That's the issue, Trace should only be used during the development process. I should really remove the option from the UI. Set it to Error and it will stop crashing.

**Comment by zack-hable** [comment]
I'll let you know if it crashes again, trying to get it to update (and it won't).

**Comment by tidusjar** [comment]
The auto updater doesn't seem to be working for everyone, i've got a task to fix it.
You will have to manually update for now (A straight replace will update it, your application settings will not get overwrote).

**Comment by FrankFromHR** [comment]
Just as an FYI I think the trace might be being enabled by default as I have never changed that setting and was having the same issue and it was set to trace..

**Comment by SoftBrok** [comment]
This happens a LOT and it is **NOT** caused by trace. The software just stops responding after 23 hours or so and won't respond again until restart. I've got it restarting the docker container on cron for now, but this really needs to be fixed.

**Comment by FrankFromHR** [comment]
That has not been my experience with it at all. I'm not running it in a docker container, it was constantly dying without the service failing or throwing any errors and I would have to restart the service. Once I found this post and changed the log level from trace to error I haven't had a single hiccup with it. 

This is anecdotal evidence obviously, just adding more information to the post.

**Comment by tidusjar** [comment]
@zack-hable still happening?

**Comment by Keelan** [comment]
I see this is closed but i also get this issue. Not sure how often it happens but im running on ubuntu 15.10

I usually get told by someone it is off (1-2 a week). I check status via terminal and says its running. However i try to hit the site and it doesn't load.

My logs were defualt trace, so i have changed to error only. See if that helps.
