### ISSUE TITLE
IMDb url

### ISSUE THREAD

**Issue by csy7550** [tidusjar/PlexRequests.Net#400]
When searching for a movie, title links to tmdb.
When movie is requested, title links to imdb.

Possible to link search results to imdb also?

I understand that it might be a bit tricky as I understand tmdb 'coming soon', 'now playing'-lists doesn't include imdb id. Personally I use tmdb all the time but it's not that userfriendly if you're not from an english speaking country as 90% of the time you will get "Sorry this isn't translated to language X yet" because of tmdb geolocation. It's not that mobile friendly either.

**Comment by tidusjar** [comment]
Hmmmm, We can take a look to see what can be done.

**Comment by tidusjar** [comment]
Waiting on feedback from the TheMovieDb library I am using.

**Comment by tidusjar** [comment]
Sorry, it seems that TheMovieDB doesn't provide an IMDB Id on a search result. We could lookup each show individually to get the IMDB Id but that would slow the search results down a lot so I wouldn't want to do that.
