### ISSUE TITLE
Can Not Connect to Sonarr

### ISSUE THREAD

**Issue by slamanna212** [tidusjar/PlexRequests.Net#405]
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
2016/07/01 23:01:15.014 PlexRequests.Api.ApiRequest Trace: Deserialzing Object
2016/07/01 23:01:15.081 PlexRequests.Api.ApiRequest Trace: Finished Deserialzing Object
2016/07/01 23:02:30.945 PlexRequests.Api.ApiRequest Trace: Api Content Response:
2016/07/01 23:02:31.048 PlexRequests.Api.ApiRequest Trace: {
  "error": "Unauthorized"
}
2016/07/01 23:02:31.128 PlexRequests.Api.ApiRequest Trace: Deserialzing Object
2016/07/01 23:02:31.204 PlexRequests.Api.ApiRequest Trace: Finished Deserialzing Object

```

#### Reproduction Steps:

Installed plexrequests.net , i setup couchpotato, it worked, but i get this error in the logs whenever i try to setup sonarr i get this error. I have tried localhost, the public IP of the server, the public hostname of the server, all times i get the same error

**Comment by tidusjar** [comment]
Is the Api key correct?

Also are you running it with some sort of base URL (sonarr)

**Comment by slamanna212** [comment]
Positive API key is correct , i even regenerated it for this service since its the only thing that uses it

I used to use plexrequests-meteor and that worked fine with the sonarr api

sonarr is hosted on port 8989 on my server, IE, i can get to it by going to server_ip:8989

**Comment by slamanna212** [comment]
I am on Sonarr version Sonarr Ver. 2.0.0.4146

I have restarted sonarr as well

**Comment by slamanna212** [comment]
The restart fixed it!
