### ISSUE TITLE
Server unresponsive after several days

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#406]
#### Plex Requests.Net Version:
Version: 1.8.4  

#### Operating System:
FreeNAS-9.10-STABLE-201606270534 (dd17351)

#### Mono Version:
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Tue May 10 05:31:54 UTC 
2016) 

#### Applicable Logs (from `/logs/` directory or the Admin page):

Last line of logs
```
2016/07/02 09:07:35.747 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0 
```

But my log was full of this error repeating, I will admit I had the wrong Sonarr API in (I had to reinstall Sonarr). See #407 for this issue.

```
2016/07/02 09:02:34.769 PlexRequests.Api.SonarrApi Error: Exception when calling GetSeries for Sonarr, Retrying 00:00:05 Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[PlexRequests.Api.Models.Sonarr.Series]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'error', line 2, position 10.
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x809470000 + 0x00dc3> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x80946e470 + 0x000d5> in <filename unknown>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x809469d70 + 0x00223> in <filename unknown>:0 
```

#### Reproduction Steps:
N/A

My logging is set to debug

**Comment by tidusjar** [comment]
Let me know if it still happens after a week now you have sorted the sonarr Api

**Comment by niayh** [comment]
Version: 1.8.2 (upgrade throws an uncaught exception attempting to upgrade to 1.8.4)
Mono version: 4.2.3
OS: Ubuntu 16.04

This has also been happening to me as well. I just restarted the PlexRequests service as it was down after about 3 days of uptime. Only error messages in my log are related to CouchPotato unable to get quality profiles regardless of the fact that my connection to CP is showing fine.

```
Exception when calling GetProfiles for CP, Retrying 00:00:02	
```
```
System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010f at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (IAsyncResult asyncResult) <0x405bcb80 + 0x0010b> in :0 at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (IAsyncResult ar, Boolean ignoreEmpty) <0x405bbbf0 + 0x0002b> in :0 at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (IAsyncResult result) <0x405b2450 + 0x0021f> in :0 --- End of inner exception stack trace --- at System.Net.WebConnection.EndWrite (System.Net.HttpWebRequest request, Boolean throwOnError, IAsyncResult result) <0x405d6550 + 0x00207> in :0 at System.Net.WebConnectionStream+c__AnonStorey1.<>m__0 (IAsyncResult r) <0x405d5e00 + 0x0014f> in :0 --- End of inner exception stack trace --- --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x40598b00 + 0x001ab> in :0 at System.Net.HttpWebRequest.GetResponse () <0x40593b60 + 0x0005a> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x40593790 + 0x00043> in :0
```

**Comment by tedrock** [comment]
Interesting, mine just went down today too, about an hour ago. And the only thing in my log is lines of that debugging message:

`2016/07/05 19:12:25.765 PlexRequests.Services.Jobs.PlexAvailabilityChecker Debug: Requests that will be updated count 0`

**Comment by tidusjar** [comment]
@niayh Your issue is due with not having all of the mono certs or not being trusted on your OS.

    mozroots --import --ask-remove 

> Info about [mozroots](http://linux.die.net/man/1/mozroots)

**Comment by tidusjar** [comment]
@tedrock I am very unsure of why it is crashing, @Drewster727 is also having a similar issue...

**Comment by DejaVu** [comment]
I guess related to this, mine also after several days will hang and checking Task Manager explains why....
![untitled](https://cloud.githubusercontent.com/assets/481679/16680955/fc1eb046-44e9-11e6-893c-150484ed0583.jpg)

**Comment by tidusjar** [comment]
@DejaVu  Wow, we shouldn't be using that much memory, what's your log level set to?

I'm still pretty sure there is a memory leak in the logging library we are using.

**Comment by DejaVu** [comment]
Log level is set to Trace

**Comment by tidusjar** [comment]
Yeah that's the reason why it's so high. Trace should only be used in the development environment. Set it to error.

**Comment by geekcroft** [comment]
I'm also having issues with Plexrequests.net crashing after a few days (sometimes not even 24 hours).

What do I need to do to gather the correct logs to help you diagnose? Running Ubuntu for what it's worth.

**Comment by halorrr** [comment]
I have the same thing, last line 4 days ago:

`Getting the settings	PlexRequests.Services.Jobs.SickRageCacher	Trace	7/8/2016 1:44:43 AM`

I had it set to Trace and after reading this thread changed it to error. Let me know if there is any other info I can provide.

**Comment by halorrr** [comment]
So after switching it to only log error instead of trace, I haven't had it happen at all again, and it was happening quite frequently. So I guess the solution would be to change the default log level to error instead of trace, because Trace was what my was set to by default when I installed it.

**Comment by SoftBrok** [comment]
I noticed this too.

If Trace is a problem, the default install shouldn't use Trace as the default log level.
