### ISSUE TITLE
Not finding some shows in Search

### ISSUE THREAD

**Issue by bnevets27** [tidusjar/PlexRequests.Net#408]
#### Plex Requests.Net Version:
1.8.4

#### Operating System:
linux

#### Applicable Logs (from `/logs/` directory or the Admin page):
[{"score":1.6139127,"show":{"id":4764,"url":"http://www.tvmaze.com/shows/4764/border-security-americas-front-line","name":"Border Security: America's Front Line","type":"Reality","language":"English","genres":["Crime"],"status":"Running","runtime":30,"premiered":"2012-09-06","schedule":{"time":"19:00","days":["Sunday"]},"rating":{"average":8.5},"weight":0,"network":{"id":67,"name":"Global","country":{"name":"Canada","code":"CA","timezone":"Canada/Atlantic"}},"webChannel":null,"externals":{"tvrage":35993,"thetvdb":261999,"imdb":"tt2518480"},"image":{"medium":"http://tvmazecdn.com/uploads/images/medium_portrait/62/155847.jpg","original":"http://tvmazecdn.com/uploads/images/original_untouched/62/155847.jpg"},"summary":"

Border Security: America's Front Line follows the work of US Customs and Border Protection (CBP) officers and agents as they clear travelers at land, air and marine ports of entry, inspect cargo and secure America's borders. In search of illegal travelers, weapons, and contraband, there's never a dull moment for the men and women who work for CBP.
","updated":1467308680,"_links":{"self":{"href":"http://api.tvmaze.com/shows/4764"},"previousepisode":{"href":"http://api.tvmaze.com/episodes/832698"},"nextepisode":{"href":"http://api.tvmaze.com/episodes/842978"}}}},{"score":1.612383,"show":{"id":4765,"url":"http://www.tvmaze.com/shows/4765/border-security-australias-front-line","name":"Border Security: Australia's Front Line","type":"Reality","language":"English","genres":["Travel"],"status":"Running","runtime":30,"premiered":"2004-10-13","schedule":{"time":"19:30","days":[]},"rating":{"average":8.5},"weight":0,"network":{"id":251,"name":"7","country":{"name":"Australia","code":"AU","timezone":"Australia/Sydney"}},"webChannel":null,"externals":{"tvrage":16771,"thetvdb":81563,"imdb":"tt0439351"},"image":{"medium":"http://tvmazecdn.com/uploads/images/medium_portrait/61/152684.jpg","original":"http://tvmazecdn.com/uploads/images/original_untouched/61/152684.jpg"},"summary":"

Border Security: Australia's Front Line is a fascinating insight into the daily workings of the thousands of officers who dedicate their lives to protecting Australia's border.

With unprecedented access to all areas of national security we patrol the front line with the men and woman of Customs and Border Protection, Immigration and Biosecurity.

No more than now has Australia's border been at such risk and Border Security is there capturing all the real-life drama at Australia's busiest airports, sea ports, cargo facilities, mail centres, and on operations in the community.
","updated":1465953730,"_links":{"self":{"href":"http://api.tvmaze.com/shows/4765"},"previousepisode":{"href":"http://api.tvmaze.com/episodes/823998"}}}}]	PlexRequests.Api.ApiRequest	Trace	7/2/2016 3:18:32 PM
Api Content Response:	PlexRequests.Api.ApiRequest	Trace	7/2/2016 3:18:32 PM

#### Reproduction Steps:
Search for:
Border Security: Canada's Front Line
Results in nothing
Search for 
Border Security
Gets the above results
#####

From looking at the trace, PR uses tvmaze as the search source. This TV Show is found  on thetvdb. This might end up being a request for using thetvdb as a search source. Is there a reason it is not used? (I do seem some reference to it in the code...)

Thank you

**Comment by tidusjar** [comment]
So we use TVMaze as its faster and also doesn't require an Api key. TVMaze also supports 'fuzzy' searching. We did use TheTVDb in version 1.2 or something but TVMaze turned out to be better. 

So what is the issue? TVMaze not finding something?

**Comment by bnevets27** [comment]
correct not finding the show I mentioned: Border Security: Canada's Front Line. 

How does PR work then? Seeing as that show is already in my library, I was going to submit an issue for that show. So as a user coming to the site to report an issue its a little weird when the show can't be found when it obviously exists.

I'm also wondering if there is going to be an issue if there is an discrepancy on episode numbering between thetvdb and tvmaze.

Actually I looked into this more and that's exactly the problem:
thetvdb:
Border Security: Canada's Front Line
(example, season 4 episode 1)
http://thetvdb.com/?tab=episode&seriesid=261999&seasonid=652870&id=5483583&lid=7

tvmaze
BORDER SECURITY: AMERICA'S FRONT LINE
(example, season 4 episode 1)
http://www.tvmaze.com/episodes/578361/border-security-americas-front-line-4x01-episode-1

I'm all for using a source other then thetvdb as they can be a pain but sickrage,sonarr,plex,kodi all you thetvdb.

What happens if I actually request BORDER SECURITY: AMERICA'S FRONT LINE? What will sickrage do with a show it can't find?

**Comment by tidusjar** [comment]
If you request it we look up the TvDbId for that show (That is contained into the TVMaze api call) which results in: `261999`.
We will send that to Sickrage and it will correctly find the TV series.

I have just searched for `Border Security` and it has returned this: http://www.tvmaze.com/shows/4764/border-security-americas-front-line

**Comment by bnevets27** [comment]
Ah, I should have looked harder at the returned api result that I posted. I see that it returns thetvdb id. Also in this case it looks like thetvdb might actually have the show miss labeled (depends if they agree and will fix it though).

For the record, yes searching for  Border Security will give you the result 
http://www.tvmaze.com/shows/4764/border-security-americas-front-line

But its listed as Border Security: Canada's Front Line in sickrage. Definitely no fault of PR. But tvmaze and thetvdb definitely aren't a 1:1 copy.

Thanks for looking into this, I'm going to go bug thetvdb now.

**Comment by l1ge** [comment]
I have a similar issue searching for the new Netflix show "sex education" it gives me only an old show called The Sex education , and that's it. When i search directly on tvmaze it finds both though
