### ISSUE TITLE
Notification always says movie

### ISSUE THREAD

**Issue by csy7550** [tidusjar/PlexRequests.Net#409]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.4

#### Operating System:
Windows 8.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Regardless of what is reqested, notification says a movie is reqested. (Email and pushover tested)

**Comment by Nvious1** [comment]
Confirming this also happens with pushbullet as well.

**Comment by tidusjar** [comment]
Fixed this, my bad, It happened when I was cleaning up some code. Stupid mistake.
