### ISSUE TITLE
After initial login, users never see the landing page.

### ISSUE THREAD

**Issue by Collisionc** [tidusjar/PlexRequests.Net#412]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.4

#### Operating System:
Ubuntu 16.04 - 64

#### Mono Version:
Nightly 4.4.1.0 /4747417 Wed Jun 22 2016

#### Applicable Logs (from `/logs/` directory or the Admin page):
n/a
#### Reproduction Steps:
Login as a user, see the landing page, then close the browser, go back to requests site and never see the landing page again until logging out and back in.

**Comment by tidusjar** [comment]
Yeah... Hmmmm good point.

**Comment by tidusjar** [comment]
@Collisionc Are you able to confirm I have fixed the issues?

Dev build here: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.8.614/artifacts

**Comment by dellipse** [comment]
I am using the docker version, so hard to tell.  However, it would be nice to click on the **Plex Requests** text on the top left to display the Landing Page Notice Messages without logging out.  Another option would be to have a "Notices" tab at the top.

**Comment by Collisionc** [comment]
Tested with latest git revision, fixed. :)
