### ISSUE TITLE
Donate button does not function.

### ISSUE THREAD

**Issue by Collisionc** [tidusjar/PlexRequests.Net#414]
#### Plex Requests.Net Version:
1.8.4

#### Operating System:
Ubuntu 16.04

#### Mono Version:
4.4.1

#### Applicable Logs (from `/logs/` directory or the Admin page):
n/a

#### Reproduction Steps:
Login as admin to see the donate button, click it, and notice that nothing happens.

Tested in Chrome, Edge and Internet Explorer, just in case it's a browser-specific issue.

**Comment by tidusjar** [comment]
@Collisionc If you clear your browsers cache (force refresh Ctrl + F5) does it still not function?

**Comment by Collisionc** [comment]
Fixed.
