### ISSUE TITLE
Button to go to requested media within Plex if available

### ISSUE THREAD

**Issue by Auwen** [tidusjar/PlexRequests.Net#415]
Feature request.

After a user searches for some media and it does exist, have the Available button direct the user to the www.plex.tv/web page for that media.

Not sure how feasible this is with Plex's API (whether it gives the URL for each media or not) but would be nice.

Idea stolen from https://www.reddit.com/r/PleX/comments/4rg4hj/plex_mods_and_plugins/d51lc2h

**Comment by JonnyWong16** [comment]
It's possible. PlexPy has a click through from the media page to https://plex.tv/web.
