### ISSUE TITLE
Requests not chaining to Available

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/PlexRequests.Net#416]
#### Reproduction Steps:

I don't know where to start with the logs so sorry for this incomplete report.
I installed the this yesterday set everything up and it works kinda good.

Users can login and request and it downloads what they requested, here comes the funny part

After the download is complete and movie is moved to Plex folder, Plexrequests does not change status to "Available" but the strange thing is, it did on 2 out of 8 movies i tested with.

I don't know where to start looking and that's why the lack of logs if you can point me in the right direction i will provide them. Couchpotato removes the movies from Wanted list and add them to "owned movies" So not sure why PlexRequests does not change to Available.

http://prntscr.com/bq9di3

**Comment by tidusjar** [comment]
Hi,

There is sometimes a problem where the name from TheMovieDb is different to what is in Plex.

There is a setting to enable an "Advanced Plex Search". This is a bit more of an intensive search but will find the correct match (matches on the IMDB Id rather than Title and Year).

Give that a go.

**Comment by Garderoben** [comment]
This solved my problem, Thank you!
