### ISSUE TITLE
Error in API call to CouchPotato

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/PlexRequests.Net#417]
#### Applicable Logs (from `/logs/` directory or the Admin page):

No error logs in Plex Requests

#### Reproduction Steps:

At first i tough it was problem with CouchPotato so i just restarted CP but i tracked it down to be some thing wrong with the API call that PlexRequests sends. (NOTE i used the Python version of PlexRequest before and did not have this problem)

If i request a movie, it comes up in CouchPotato but the search stops. If i then restart CP it can search for it.
In CouchPotatos logs i find this:

`07-08 10:31:41 ERROR [31m[   couchpotato.core.event] Error in event "movie.searcher.single", that wasn't caught: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\event.py", line 15, in runHandler
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\media\movie\searcher.py", line 160, in single
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\CodernityDB\database_super_thread_safe.py", line 43, in _inner
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\CodernityDB\database.py", line 942, in get
RecordNotFound: Location 'undefined' not found
encoding=cp1252 debug=False args=['--quiet'] app_dir=C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32 data_dir=C:\Users\Administrator\AppData\Roaming\CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x33600c8> > options=Namespace(config_file='C:\\Users\\Administrator\\AppData\\Roaming\\CouchPotato\\settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='C:\\Users\\Administrator\\AppData\\Roaming\\CouchPotato\\couchpotato.pid', quiet=True) [0m
07-08 10:32:58 ERROR [31m[chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.plugins.min.js?1441050780', 'message': u'chrome 51: \nUncaught TypeError: profile.get is not a function', 'line': u'1351', 'page': u'http://HOST/movies/', '_request': <couchpotato.api.ApiHandler object at 0x032B8710>}[0m`

The interesting here is probably the last part if i'm not wrong, looks like PlexRequests sends the wrong request?

`07-08 10:32:58 ERROR [31m[chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.plugins.min.js?1441050780', 'message': u'chrome 51: \nUncaught TypeError: profile.get is not a function', 'line': u'1351', 'page': u'http://HOST/movies/', '_request': <couchpotato.api.ApiHandler object at 0x032B8710>}[0m`

**Comment by tidusjar** [comment]
So what PlexRequests does is just uses the CP api to add a movie. Using the API documentation that has been provided by CP.

Can you go into your settings and check your quality profiles?

**Comment by Garderoben** [comment]
Yhea sure.

"Best" is also selected in PlexRequests under CouchPotatos Quality Profiles

http://i.imgur.com/D30AOR3.png

**Comment by tidusjar** [comment]
So in the Plex Requests CouchPotato settings you have "Best" selected?
What Movie did you try and send over?

Date: Fri, 8 Jul 2016 04:18:12 -0700

**Comment by Garderoben** [comment]
Yes, This is my settings in PlexRequests
http://prntscr.com/bqc5la

For exampel, now i added Dracula Untold **FROM Couch potato**, it finds the movie and downloads
http://prntscr.com/bqc6gt
I then remove the movie completely and try to request it with PlexRequests

PlexRequests tells me its successfully added and i move over to CP to take a look.
This is what i see
http://prntscr.com/bqc7c9

If i now move over to the logs we can see that its the same error as before.
`7-08 13:41:10 ERROR [31m[   couchpotato.core.event] Error in event "movie.searcher.single", that wasn't caught: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\event.py", line 15, in runHandler
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\media\movie\searcher.py", line 160, in single
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\CodernityDB\database_super_thread_safe.py", line 43, in _inner
  File "C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\CodernityDB\database.py", line 942, in get
RecordNotFound: Location 'undefined' not found
encoding=cp1252 debug=False args=['--quiet'] app_dir=C:\Users\Administrator\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32 data_dir=C:\Users\Administrator\AppData\Roaming\CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x33600c8> > options=Namespace(config_file='C:\\Users\\Administrator\\AppData\\Roaming\\CouchPotato\\settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='C:\\Users\\Administrator\\AppData\\Roaming\\CouchPotato\\couchpotato.pid', quiet=True) [0m
07-08 13:41:46 ERROR [31m[chpotato.core.plugins.log] API log: {'file': u'http://HOST/static/scripts/combined.plugins.min.js?1441050780', 'message': u'chrome 51: \nUncaught TypeError: profile.get is not a function', 'line': u'1351', 'page': u'http://HOST/movies/', '_request': <couchpotato.api.ApiHandler object at 0x08468E70>}[0m`

**Comment by tidusjar** [comment]
Yeah, it seems that CP is not receiving the quality profile we are sending.

Can your press Get Quality Profiles and then Save in Plex Requests please? Then try again?

**Comment by Garderoben** [comment]
Yes now it works thanks!

**Comment by tidusjar** [comment]
Interesting... It's like the quality profile never saved. I'll make a code change to make sure it saves.
