### ISSUE TITLE
SickBeard Support?

### ISSUE THREAD

**Issue by Brentnall27** [tidusjar/PlexRequests.Net#420]
Apologies in advance if this has already been asked - I tried searching but found no results.

Just a quick query to see whether there are any plans to add support for the now EOL but still fully functional SickBeard? I imagine it should be almost trivial to add, being so similar to SickRage.

I should really make the move over to SickRage but the old "if it aint broke, don't fix it!" is alive and well.

Completely understand if this is something that wont be added of course - there are certainly lots of other excellent feature requests here which should be given priority.

**Comment by tidusjar** [comment]
Hi @Brentnall27 Sorry for the late reply.

There are no current plans to add SickBeard, Sorry about that! (You can still request things without SickRage/Sonarr, but it wont get sent to anything).
