### ISSUE TITLE
Something went wrong! Message Couchpotato

### ISSUE THREAD

**Issue by levy4858** [tidusjar/PlexRequests.Net#422]
Plex Requests.Net Version:

1.8.4

Operating System:

Windows Server 2012 R2

----------------------------------
Hello, when I connect with Sonarr and Headphones everything works perfect, but when I try to connect with Couchpotato, I get the following message: 

Something went wrong!    and after that: 

Could not connect to CouchPotato, please check your settings. Exception Message: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 2, position 3.

I updated Plexrequests to the newest version and then I got this message, I have also been removed and reinstalled everything but the problem remains.

The "Something went wrong!" message i also get when i click on "Get Quality Profiles"

**Comment by tidusjar** [comment]
This usually is that we cannot authenticate, due to either a bad API key or incorrect endpoint.

Does your CP have a base URL?

**Comment by levy4858** [comment]
Yes,  and my api key is the same that I use for Sonarr

**Comment by tidusjar** [comment]
Does your CP have a base URL?
Can you show me a screenshot of your settings in PlexRequests?

**Comment by levy4858** [comment]
I used the same API key in the meteor version of plexrequest and even there the API key does not work. When I always used no base URL was still working well, you might know what this is?

It is an error in CP, or am I doing something wrong.

Because I use a reverse proxy is my base url  /couchpotato

**Comment by tidusjar** [comment]
Ok set your subdirectory to couchpotato in Plex requests

**Comment by levy4858** [comment]
Yeah that's it, thanks for your help!! :)
