### ISSUE TITLE
RAM usage is still a problem

### ISSUE THREAD

**Issue by Chubbysumo** [tidusjar/PlexRequests.Net#423]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.4

#### Operating System:
Windows Server 2012 R2

#### Reproduction Steps:

If PR runs for 4 days, ram usage climbs steadily from ~75MB on initial open to 3.5gb.  I have so far just run a scheduled task to close it, and reopen it, but its increase rate is unstead, and sometimes it goes up to 2+GB within a day, and sometimes does not.  I have not let it run longer than 4 days.  The server only has so much RAM, and the rate it climbs is not constant.  I restarted it this morning, about 10 hours ago, and its already 2.5 times its initial open, and growing.

**Comment by jaycedk** [comment]
Set log level to Error.
And see if that helps.

**Comment by tidusjar** [comment]
Did it help?

**Comment by Chubbysumo** [comment]
I set the log level to error about 24 hours ago.  So far, it has not started climbing(only goes up when in use). I am going to let it run for another couple of days before I mark this closed.  Will close in 2 days if no issue persists.

**Comment by tidusjar** [comment]
@Chubbysumo Any issue?

**Comment by Chubbysumo** [comment]
Sorry, been busy on the house.  No, with logging set to minimal, it does not climb in RAM usage.  Server has been running for 3 days since the last updates.  Closing.  Thanks for the great job in software!
