### ISSUE TITLE
Cannot find .exe file

### ISSUE THREAD

**Issue by Qosmo** [tidusjar/PlexRequests.Net#425]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page): No Logs because it hasn't been installed yet.

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps: I'm getting an error saying - Failed to start service PlexRequests.net.  Program C:\PlexRequests.net\PlexRequests.exe couldn't be launched. CreateProcess() failed: The system cannot find the file specified.

When I extract the zip folder after doing the "Unblock" setting, there's not .exe file contained in the folder.  Not sure what I'm missing, but I'm trying to install this on a fresh Windows VM.  I did run through the directions found at [HTPC Guides](http://www.htpcguides.com/install-plex-requests-net-windows-system-service/).

Thanks

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Are you downloading the release?
https://github.com/tidusjar/PlexRequests.Net/releases/latest

**Comment by Qosmo** [comment]
I'm an idiot... Thanks tidusjar.
