### ISSUE TITLE
iPhone Login

### ISSUE THREAD

**Issue by naq90** [tidusjar/PlexRequests.Net#426]
When trying to login in via iPhone, I get a white page with the message.

`{"result":true,"message":"search"}`

This just started happening, it was working fine on mobile prior to this week. It works on desktop, however.

**Comment by tidusjar** [comment]
Strange, what browser?

**Comment by naq90** [comment]
It happens on safari. I have not checked other mobile browsers yet to see if it's replicable.

**Comment by tidusjar** [comment]
Have you modified anything on your iPhone? e.g. disabled Javascript?

**Comment by Drewster727** [comment]
I have also seen this issue on the iPhone in the Chrome browser. It doesn't seem to do it anymore for whatever reason, but I had a build or two there where it was show that white page with json on it right after logging in.

**Comment by tidusjar** [comment]
@Drewster727 Yeah, just trying to work out why this would happen, I'm not sure what happens under the hood in the Nancy Redirect, but that is the only place we use a Nancy Redirect so I'm thinking that might be the cause.

**Comment by veritas2884** [comment]
Mobile browser Safari on iPhone does not allow log in. On tap the login button highlights green and then the page reloads at the login screen.
