### ISSUE TITLE
Cannot use SMTP server that doesn't require authentication

### ISSUE THREAD

**Issue by FrankFromHR** [tidusjar/PlexRequests.Net#429]
Plex Requests.Net Version: 1.8.4
Operating System: Ubuntu 16.04 x64
Mono Version: 4.2.1

Applicable Logs (from `/logs/` directory or the Admin page):

System.NotSupportedException: The SMTP server does not support authentication. at MailKit.Net.Smtp.SmtpClient.Authenticate (System.Text.Encoding encoding, ICredentials credentials, CancellationToken cancellationToken) <0x4200c6a0 + 0x00747> in :0 at MailKit.MailService.Authenticate (System.String userName, System.String password, CancellationToken cancellationToken) <0x4200c380 + 0x00094> in :0 at PlexRequests.Services.Notification.EmailMessageNotification+d__14.MoveNext () <0x41ff88b0 + 0x0020b> in :0

I did a quick search but I didn't see anything else mentioning this kind of error. This also stops me from using SSMTP which I've configured on the server as my default SMTP server because of the same issue, no authentication required.

**Comment by tidusjar** [comment]
Just to clarify, you are using the correct ports and host etc?

**Comment by FrankFromHR** [comment]
Yes, but it won't let me save the settings without entering a username/password combination.

**Comment by tidusjar** [comment]
Oh wait, so your problem is that you have to enter a username and password, but you are saying that should be optional?

That makes more sense now.
I'll add an authenticate checkbox and enable/disable the username and password fields based on that. If there is no username or password then we wont try and authenticate with the smtp server. Sound good?

**Comment by FrankFromHR** [comment]
Exactly :) 

Thank you sir that should work perfectly.

**Comment by tidusjar** [comment]
TODO: Need to test the new changes (especially the new UI logic).

@FrankFromHR once i've tested are you willing to try the dev build to confirm it fixes your issue?

**Comment by tidusjar** [comment]
@FrankFromHR The dev build with the fixed SMTP authentication is here: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.8.654/artifacts

Please can you confirm that this fixes your issue?

**Comment by FrankFromHR** [comment]
@tidusjar let me give it a try.

**Comment by FrankFromHR** [comment]
It doesn't appear to be working. 

Message	Area	Log Level	Date
Sent email notification test	PlexRequests.UI.Modules.AdminModule	Info	7/25/2016 8:05:56 PM

I've tried it using the localhost running SSMTP and also my ISP provider.. I never get anymore logs and nothing ever ends up in my email.

**Comment by tidusjar** [comment]
You not getting any logs is a good thing, it means that nothing went wrong in the code... Are you 100% sure there is no email, check junk/spam?

**Comment by FrankyFromHR** [comment]
Nothing in Spam. Are you outputting the SMTP output to the log at all? I'm wondering if it's being rejected by my ISP for some reason.

**Comment by FrankFromHR** [comment]
Nothing in Spam. Are you outputting the SMTP output to the log at all? I'm wondering if it's being rejected by my ISP for some reason.

Sorry posted my reply under my work account.

**Comment by tidusjar** [comment]
We only output things to the log when something goes wrong e.g. We get a bad response from the SMTP server (Since we are technically creating a SMTP client we will get responses)

We will log an `Error`.

**Comment by FrankFromHR** [comment]
Okay, I'm not sure what's happening then. I'm able to seen email using both the localhost SSMTP configuration and my ISP from the server using mail.

**Comment by tidusjar** [comment]
It's working now?
