### ISSUE TITLE
Beta Releases

### ISSUE THREAD

**Issue by kamikasky** [tidusjar/PlexRequests.Net#430]
Would you be able to upload beta releases? I would be interested in trying out your new commits involving #254 and had some trouble getting the source to compile. Thank you for all of your hard work!

**Comment by tidusjar** [comment]
I can let you know when something is available for this release. The commits so far is just hooking up the frontend with the api to get the series. There is still some work to do so there is no point in trying it out yet.

**Comment by tidusjar** [comment]
@kamikasky I added you into the "Testers" gitter group. Here is where I post early builds.
