### ISSUE TITLE
Allow RSS feed instead of Movie Title in request field to allow high speed selection of movies that don't already exist in library

### ISSUE THREAD

**Issue by zenjabba** [tidusjar/PlexRequests.Net#431]

**Comment by zenjabba** [comment]
My idea is instead of putting the name of a movie, the admin can put a RSS feed and "mass request" the movies from a RSS feed and that way we can pre-check if they exist in the library already... when you have >5000 movies, pre-checking gets hard.

**Comment by tidusjar** [comment]
So you want some sort of way to give PR.Net a RSS feed and then it will request all movies on the RSS feed that have not yet been requested?

Do you have an example of a feed that you would use? (Since all RSS feeds will contain different data, it would need to be specific to this RSS feed...)

**Comment by tidusjar** [comment]
Any idea @zenjabba?

**Comment by zenjabba** [comment]
http://www.imdb.com/list/ls074019326?ref_=tt_rls_1

I was thinking something like this

**Comment by tidusjar** [comment]
@zenjabba wouldn't this type of feature be better in couchpotato or Sonarr (I know they already have this)?

**Comment by zenjabba** [comment]
I wasn’t aware Couch did this, let me look into it via couch.
