### ISSUE TITLE
Text formatting within the Landing Page Notice Message

### ISSUE THREAD

**Issue by dellipse** [tidusjar/PlexRequests.Net#432]
It would be nice to be able to use text formatting to do things like **bold** or _itallize_ characters, especially carriage returns, to separate parts of the Notice Message on the Landing Page.

Any standard would be nice

Are they there and I am just missing it?

**Comment by tidusjar** [comment]
You can. It's not obvious but the notification box takes html. So you can make it bold via '<b>bold</b>'
