### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by ghost** [tidusjar/PlexRequests.Net#434]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

1.8.4

#### Operating System:

Docker image

#### Mono Version:

From Docker Image.

#### Applicable Logs (from `/logs/` directory or the Admin page):

System.Net.WebException: The request timed out at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x40efa4a0 + 0x00193> in :0 at System.Net.HttpWebRequest.GetResponse () <0x40ef6be0 + 0x0005a> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x40ef6810 + 0x00043> in :0 

#### Reproduction Steps:

Try to connect to CouchPotato or other resources. This randomly comes up connecting to them with no warning. Daemons are operating correctly. No firewall, no resource issues, and no further errors in logs. It just refuses to connect for seemingly no reason at random.

The daemon will also completely stop running and won't run at all on CentOS7/mono without Docker. Am I reporting these issues right? It doesn't seem any of them actually ever get fixed.

**Comment by tidusjar** [comment]
Hi,

The error is telling me that it timed out when trying to connect to something. Are you 100% sure it can connect?

What doesn't seem to actually get fixed?
Also please keep in mind that this is all done in my spare time for **free**. I have a full time job with a baby on the way. So if I'm not able to fix and issue straight away then that's the reason.

**Comment by rlijkendijk86** [comment]
I am getting the same "Something went wrong" error as well. I get the error when I try to approve or delete a requested tv series or movie.

Plexrequest Version:  1.8.4 

I get these messages in the logging section:

Exception when calling AddMovie for CP, Retrying 00:00:02 PlexRequests.Api.CouchPotatoApi Error 7/25/2016 8:23:42 PM 

System.ArgumentException: Cannot build uri when url segment parameter 'imdbid' value is null. Parameter name: request at RestSharp.RestClient.BuildUri (IRestRequest request) <0x405791b0 + 0x00243> in :0 at RestSharp.RestClient.ConfigureHttp (IRestRequest request, IHttp http) <0x405773c0 + 0x0045b> in :0 at RestSharp.RestClient.Execute (IRestRequest request, System.String httpMethod, System.Func`3 getResponse) <0x40574a40 + 0x0009f> in :0  PlexRequests.Api.ApiRequest Error 7/25/2016 8:23:42 PM 

System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x40592fa0 + 0x001cb> in :0 at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) <0x4058f510 + 0x005f3> in :0 --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x4058ddf0 + 0x001ab> in :0 at System.Net.HttpWebRequest.GetResponse () <0x40589f00 + 0x0005a> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x40589b20 + 0x00043> in :0  PlexRequests.Api.ApiRequest Error 7/25/2016 8:23:36 PM 
Exception when calling GetProfiles for Sonarr, Retrying 00:00:10 PlexRequests.Api.SonarrApi Error 7/25/2016 8:23:26 PM 

System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) <0x40592fa0 + 0x001cb> in :0 at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) <0x4058f510 + 0x005f3> in :0 --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x4058ddf0 + 0x001ab> in :0 at System.Net.HttpWebRequest.GetResponse () <0x40589f00 + 0x0005a> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x40589b20 + 0x00043> in :0  PlexRequests.Api.ApiRequest

**Comment by tidusjar** [comment]
Interesting. You error is telling me that we don't have an IMDb id for that request. What movie was it?

Also it's failing to connect to CP to get the quality profiles. Are there any errors in CP?

**Comment by rlijkendijk86** [comment]
It happens both with movies and TV shows.
TV show I try to remove request: Breaking Band. TV show request I try to approve: Flashpoint.
I don't see any errors in CP when I try to remove a movie request. I have deleted the default "Best" quality profile in CP, perhaps Plex Request does not like that?
But deleting profiles in CP shouldn't break remove / approving TV show requests I assume....

**Comment by tidusjar** [comment]
Ok it also happens when you remove a request? 

For both approving and deleting can you please do the following. 

On this issue: https://github.com/tidusjar/PlexRequests.Net/issues/440

A few posts down I describe how to report some information back to myself using the browsers development tools (F12). Please follow that and post the results here for both approval and deletion. 

Thanks.

**Comment by tidusjar** [comment]
@rlijkendijk86 Any luck?

**Comment by rlijkendijk86** [comment]
I'm sorry I missed your request. I've pressed F12 and switched to the networking TAB, then deleted a movie and this is the error that came up:

{statusCode: 500, message: "Something went horribly, horribly wrong while servicing your request.",…}
details
:
"Nancy.RequestExecutionException: Oh noes! ---> System.ArgumentException: Cannot Delete null Object↵Parameter name: entityToDelete↵  at Dapper.Contrib.Extensions.SqlMapperExtensions+<DeleteAsync>d__44`1[T].MoveNext () <0x423a50a0 + 0x000cb> in <filename unknown>:0 ↵--- End of stack trace from previous location where exception was thrown ---↵  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fdbb8da62a0 + 0x00029> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fdbb8da4170 + 0x000a7> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fdbb8da40f0 + 0x0006b> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fdbb8da40a0 + 0x0003a> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fdbb9079820 + 0x00012> 24683 in <filename unknown>:0 ↵  at PlexRequests.Store.Repository.RequestJsonRepository+<DeleteAsync>d__14.MoveNext () <0x423a4910 + 0x0025f> in <filename unknown>:0 ↵--- End of stack trace from previous location where exception was thrown ---↵  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fdbb8da62a0 + 0x00029> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fdbb8da4170 + 0x000a7> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fdbb8da40f0 + 0x0006b> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fdbb8da40a0 + 0x0003a> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fdbb9079820 + 0x00012> 24683 in <filename unknown>:0 ↵  at PlexRequests.Core.JsonRequestModelRequestService+<DeleteRequestAsync>d__11.MoveNext () <0x423a4100 + 0x002fb> in <filename unknown>:0 ↵--- End of stack trace from previous location where exception was thrown ---↵  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fdbb8da62a0 + 0x00029> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fdbb8da4170 + 0x000a7> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fdbb8da40f0 + 0x0006b> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fdbb8da40a0 + 0x0003a> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () <0x7fdbb8da4080 + 0x00012> in <filename unknown>:0 ↵  at PlexRequests.UI.Modules.RequestsModule+<DeleteRequest>d__42.MoveNext () <0x42399040 + 0x0044b> in <filename unknown>:0 ↵--- End of stack trace from previous location where exception was thrown ---↵  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7fdbb8da62a0 + 0x00029> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7fdbb8da4170 + 0x000a7> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7fdbb8da40f0 + 0x0006b> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7fdbb8da40a0 + 0x0003a> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7fdbb8da44a0 + 0x00017> in <filename unknown>:0 ↵  at PlexRequests.UI.Modules.RequestsModule+<<-ctor>b__0_4>d.MoveNext () <0x423988b0 + 0x002ee> in <filename unknown>:0 ↵  --- End of inner exception stack trace ---↵  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) <0x42381d60 + 0x002d7> in <filename unknown>:0 "
message
:
"Something went horribly, horribly wrong while servicing your request."
statusCode
:
500
Name
delete

**Comment by tidusjar** [comment]
And that happens every time you try and delete something?

Can you Send me your database at jamierees@outlook.com
