### ISSUE TITLE
[FR] Make navigation sticky

### ISSUE THREAD

**Issue by delphiactual** [tidusjar/PlexRequests.Net#436]
Make the navigation banner sticky when browsing PlexRequests.

**Comment by tidusjar** [comment]
It should be? What are you seeing?

**Comment by delphiactual** [comment]
Plex Requests 1.8.4
Ubuntu 16.04.1 LTS
Mono 4.2.3
accessed from Chrome 51

ScreenGrab Attached
![screenshot 2016-07-25 11 59 53](https://cloud.githubusercontent.com/assets/4798491/17111645/b7028770-525f-11e6-976a-34d82f908a50.png)

**Comment by tidusjar** [comment]
Oh you mean you want the navbar to scroll with you and to stay at the top?

**Comment by delphiactual** [comment]
Yes
