### ISSUE TITLE
500 Error when changing base URL, ZIP unblocked

### ISSUE THREAD

**Issue by CKyle22** [tidusjar/PlexRequests.Net#437]
Hi. I get a 500 internal server error when I try to access PlexRequests.Net after changing the base URL, ie /requests for a reverse proxy. The zip file is unblocked.

Also for whatever reason, I can't access this from any other comp on my network. They all time out if I go to IP:3579. Any idea why?

**Comment by tidusjar** [comment]
You need to go to localhost:up/requests

**Comment by CKyle22** [comment]
I feel like such an idiot. I'll try this as soon as I can, thank you.

**Comment by tidusjar** [comment]
You set it to `requests` ? That's interesting, the application should have allowed you to set it to that (Since requests is an internal page for the application).

Send me your DB (jamierees@outlook.com) and i'll fix it and also i'll fix this bug.

your db is the `plexrequests.sqlite` file, all of your personal settings including password etc are all one way encrypted so I cannot access them (Just to let you know).

**Comment by tidusjar** [comment]
Self Note: https://github.com/tidusjar/PlexRequests.Net/blob/master/PlexRequests.UI/Validators/PlexRequestsValidator.cs#L37 Is the line in the validator

**Comment by CKyle22** [comment]
Oh, that might be the issue then! I believe I uninstalled it but I can certainly replicate it for you and give you what you need. :) I won't be able to until late, so can you keep this issue open until then? I'll let you know if that fixes this, or if I have any issue with accessing PlexRequest.Net from other computers in the network.

Thank you!

**Comment by tidusjar** [comment]
ok!

**Comment by CKyle22** [comment]
Hi, I just reinstalled it freshly on my HTPC using the included windows guide.

I can access it from http://localhost:3579 and http://<localip>:3579 on the host computer only. If I go to http://<hostip>:3579 on any other machine on my network, it times out. Could it be a Windows Firewall issue?

**Comment by tidusjar** [comment]
Read this: https://github.com/tidusjar/PlexRequests.Net/wiki/FAQ#i-am-having-issues-allowing-plex-requestsnet-through-my-firewall
