### ISSUE TITLE
Bug: Weekly limit number above 1 only counts as 1.

### ISSUE THREAD

**Issue by Rsslone** [tidusjar/PlexRequests.Net#438]
I have a weekly limit set to 3 but the user can only request 1 title before being given the message about weekly limit has been reached. I've checked the database and it shows only 1 request.
http://puu.sh/qdYID/6085c2cd61.png
I've tried other values above 1 and it still counts as 1.

#### Plex Requests.Net Version:
1.8.4

#### Operating System:
Win 8.1

**Comment by tidusjar** [comment]
Well that sucks!
I'll take a look when I get home from work.

Date: Mon, 25 Jul 2016 09:26:24 -0700

**Comment by Rsslone** [comment]
You're the man. Is there anything I can preemptively provide you to help you solve the problem?

**Comment by tidusjar** [comment]
If you are willing, could take a copy of your Plex requests database (change the admin password so I can log in) and send it to me? 

That way I have your exact settings?

jamierees@outlook.com

**Comment by Rsslone** [comment]
Sent.

**Comment by tidusjar** [comment]
Found it. Was a silly mistake in the logic.

**Comment by Rsslone** [comment]
Sweet! ETA on release? Am I able to patch it myself?

**Comment by tidusjar** [comment]
Not sure about the next release, soonish. Just need to get the ability to select your own TV Episodes finished up. 

You can run the dev build if you wish? But the selecting TV Episodes might not be 100% stable

**Comment by Rsslone** [comment]
How do I switch to the dev branch? I tried using git to checkout but it didn't work.

Excuse my noobness.

**Comment by tidusjar** [comment]
You will need the compiled version, it's here: https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by Rsslone** [comment]
So the previous issue is fixed but a new one popped up. Not sure if you're aware of it but the request limit is that number +1. So a request limit of 3 would allow 4 requests, Limit of 2 would allow 3.. and so on.

**Comment by tidusjar** [comment]
Ah ok. I'll fix that when I get home.

**Comment by tidusjar** [comment]
Fixed! Plus added some unit test to make sure the code that does the check doesn't break in the future.

**Comment by Rsslone** [comment]
Confirmed fixed. Great work!

**Comment by tidusjar** [comment]
Haha that was fast! I'll push out a full release as soon as I can finish the Episode stuff and get someone to test it.

**Comment by Rsslone** [comment]
Yeah XD If you can't find someone to test it, I'm a good guinea pig.

**Comment by tidusjar** [comment]
I'll add you into the Gitter testers channel :dancers:
