### ISSUE TITLE
help with plexrequest to access outside network

### ISSUE THREAD

**Issue by pistol2016** [tidusjar/PlexRequests.Net#439]
totally new here but i have plexrequest.net up and running and linked into sickrage etc my question is can my mates access this service on there web browser. if so is it as simple as opening the ports and using my no.ip server domain. ?

cheers

**Comment by tidusjar** [comment]
So yeah, open the port (make sure the firewall is allowing it through: https://github.com/tidusjar/PlexRequests.Net/wiki/FAQ#i-am-having-issues-allowing-plex-requestsnet-through-my-firewall) and then get them to go to `yourserver.no-ip.org:port`

**Comment by pistol2016** [comment]
My noip address is xxxxx.ddns.net   My port is 8390. I've allowed it through the modem and firewall and still not working. :( quite confusing champ

**Comment by tidusjar** [comment]
Did you allow system through? PlexRequests is built upon HTTPListener.sys

It's in the link I posted above

**Comment by pistol2016** [comment]
So that httplistener file has to be given file wall axs to correct ? With the assigned port I have yeah ?

**Comment by tidusjar** [comment]
If you read this: https://github.com/tidusjar/PlexRequests.Net/wiki/FAQ#i-am-having-issues-allowing-plex-requestsnet-through-my-firewall

It will explain what you need to add to the firewall
