### ISSUE TITLE
Sonarr requests - "message": "constraint failed\r\nNOT NULL constraint failed: Series.Images"

### ISSUE THREAD

**Issue by godsplague** [tidusjar/PlexRequests.Net#440]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):
![capture](https://cloud.githubusercontent.com/assets/17170891/17124234/569b1370-52af-11e6-8c84-91cf9457fee4.PNG)

#### Reproduction Steps:
Attempting to request tv series through sonarr. In the admin setup everything seems to be connected properly and test connectivity succeeds and is able to pull my unique quality profiles just fine. But when I go to request I get the oops something went wrong error. Tried showing you the debug log but it looks like everything is working ok though it is not. I have no issue accessing sonarr or plexrequests from inside my network or outside. Sorry if you need a different log just let me know. Thanks in advance

**Comment by sch1308** [comment]
getting the same error on 1.8.4 
![image](https://cloud.githubusercontent.com/assets/7896067/17127072/c9c37402-52d0-11e6-9099-2f63a4f1f06d.png)

**Comment by tidusjar** [comment]
@godsplague If you are able to reproduce it and get the Something went wrong error. Can do please do the following:

Open up the developers console (F12 on Chrome), go to the Network Tab
![image](https://cloud.githubusercontent.com/assets/6642220/17134412/2a91299a-5322-11e6-9fee-01ed94b16627.png)

Then press request to get the error message.
You should see a red entry in the network area now, something like this:
![image](https://cloud.githubusercontent.com/assets/6642220/17134450/59be9414-5322-11e6-9a4c-2909bb232220.png)

(There should only be 1 red entry).
If you then click on that and press the preview tab and post the content on here?

@sch1308 I'll take a look at where that error is happening in the code and plug it.

**Comment by tidusjar** [comment]
@sch1308 There should be more logs that I require, one with "Adding Series" and also "Seasons = X, out of X seasons"

also "Sonarr API Options:"

**Comment by godsplague** [comment]
hopefully this is what you need.
![capture](https://cloud.githubusercontent.com/assets/17170891/17140765/3eb52fb0-530f-11e6-85ac-a6f1eff07f5b.PNG)

I clicked that error and here is the text it gave me
http://pastebin.com/PpYw4P3K

**Comment by tidusjar** [comment]
Thanks that helped. It seems that it failed to send something to Sonarr (It was being Auto Approved). It tried to put the Sonarr error messages on screen for you but it didn't contain any error messages (which is really strange).

I have fixed the exception being thrown, but I am not sure why Sonarr failed to accept the TV show (Anything in your Sonarr logs?).

**Comment by Collisionc** [comment]
This happened to me once and it was due to Sonarr not being able to find the show, even when I searched for it by name inside sonarr. The only way I could add the show was by using the tvbd: prefix instead of the show name.

**Comment by godsplague** [comment]
Bizarre, checked the sonarr logs, which makes sense. Here is what I got (I cleared it and just did a request for a random title) http://pastebin.com/jyPPpdgh
seems like in the logs everything is working as it should be but it never gets added to the series in sonarr as it should, but I can go into sonarr and searcch the series myself and it finds it using the exact same search text. I might open up a support on sonarr's site as well and see what they think. Thanks for your help here, let me know if you think of anything else

**Comment by godsplague** [comment]
is there any way to see the full JSON payload for the add series request from PlexRequests? I'm working with sonarr support as well to see what's going on https://forums.sonarr.tv/t/sonarr-having-issues-adding-series-requested-from-other-programs/11497

**Comment by tidusjar** [comment]
Id have to give you a custom build so we can output it to the log. You okay with that?

**Comment by godsplague** [comment]
I'd be willing to try it, this is the only break in the chain on my whole media operation. I'd hate to have to find an alternative for plexrequests.net or sonarr. Seems odd I'm the only one having this issue though.

**Comment by tidusjar** [comment]
I agree, 

looking at the code, if you set your log level to `Trace` we should be able to see your options and the response from Sonarr.

Options is near the `Sonarr API Options:` log.

Response from Sonarr is near the `Api Content Response:` log

**Comment by godsplague** [comment]
does this shed any light? trace log on sonarr right after a request. http://pastebin.com/NBUKkKTE
Also is this an issue? Looks like it has extra backslashes in the path?
![capture](https://cloud.githubusercontent.com/assets/17170891/17175967/17159712-53d0-11e6-887d-955227ae360a.PNG)

**Comment by tidusjar** [comment]
This is the issue: 
`{ "message": "constraint failed\r\nNOT NULL constraint failed: Series.Images" }`

That's what we are getting back from Sonarr. I've updated the Sonarr thread post. Let's see if they are able to shed any light

**Comment by tidusjar** [comment]
Issue raised on Sonarr https://github.com/Sonarr/Sonarr/issues/1403

**Comment by godsplague** [comment]
Thank you very much for your support, seems odd I'm the first to bring up this issue. Am I doing things in a weird way or what? hahah

**Comment by tidusjar** [comment]
I don't think so. I think you are just on an earlier release than everyone else. Everyone will end up with this issue... Which sucks.

**Comment by Collisionc** [comment]
Yeah, it's happening everytime for me now. I didn't realize it because most people were requesting movies, not tv shows.

**Comment by godsplague** [comment]
Did it work previously? Wondering if going back one version would fix for the time being, or one version back on sonarr. You using sonarr too?

**Comment by Collisionc** [comment]
Sonarr. I believe it's a change on Sonarr's end, as meteor plex requests has been rock solid for about 6 months until recently, and they haven't changed anything in a few months.

**Comment by tidusjar** [comment]
Correct, it's an issue in Sonarr

**Comment by godsplague** [comment]
Makes sense, maybe I'll try going back one version on sonarr and see if it fixes when I have some more time. Not to sound rude at all but they have a lot going on I'm sure and who knows how long until it sees a fix

**Comment by tidusjar** [comment]
Yeah, I raised a bug with them as I couldn't add an unmontiored series using the API (Which i need for the feature to request individual episodes). They fixed it but it could be a while until it's released, then it could be even longer for people to update, so im working around it for now.

**Comment by Collisionc** [comment]
I run sonarr on the development branch and that was already pushed, it doesn't fix the error that we are seeing in PlexRequests.

**Comment by tidusjar** [comment]
I'm not aware of any change I can do to fix it. It's an internal Sonarr error. 

I'll speak to Markus (Sonarr Dev) at some point today. But I suggest you downgrade Sonarr for now.

**Comment by godsplague** [comment]
Thanks for your help


Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by tidusjar** [comment]
@godsplague I have a potential workaround. Can you try out this build? 

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.676/artifacts

**Comment by godsplague** [comment]
I'll give it a try as soon as I am able, thanks!



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by tidusjar** [comment]
@godsplague That's cool, no rush. It should fix it, just want to confirm.

@Collisionc this build should fix the issue: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.676/artifacts

**Comment by Collisionc** [comment]
I had to delete my sqlite file to get plexrequestsnet to startup without errors, but when I did that and re-setup sonarr it still gives me "Something went wrong" when requesting a tv show.

**Comment by tidusjar** [comment]
You had to delete your database?!?! 

Can you please send me your latest backup (in the backup folder) at jamierees@outlook.com 

What error are you getting in the browsers console?

**Comment by Collisionc** [comment]
The database had been sitting at 364 MB for a few days (Somehow trace logging was enabled), but didn't seem to bother plexrequestsnet until this build. I had cleared the logs from the database, but it didn't automatically shrink it. I compacted/vacuumed the database down to 164 kb and was able to get plexrequestsnet to load it again. 

Object
details
:
"Nancy.RequestExecutionException: Oh noes! ---> Newtonsoft.Json.JsonSerializationException: Error converting value 70366 to type 'PlexRequests.UI.Models.EpisodeRequestModel'. Path '', line 1, position 5. ---> System.ArgumentException: Could not cast or convert from System.Int64 to PlexRequests.UI.Models.EpisodeRequestModel.↵  at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable (System.Object value, System.Type initialType, System.Type targetType) <0x411c03c0 + 0x001bb> in <filename unknown>:0 ↵  at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast (System.Object initialValue, System.Globalization.CultureInfo culture, System.Type targetType) <0x41addd70 + 0x000a7> in <filename unknown>:0 ↵  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) <0x4151a2f0 + 0x002bb> in <filename unknown>:0 ↵  --- End of inner exception stack trace ---↵  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType (Newtonsoft.Json.JsonReader reader, System.Object value, System.Globalization.CultureInfo culture, Newtonsoft.Json.Serialization.JsonContract contract, System.Type targetType) <0x4151a2f0 + 0x0034f> in <filename unknown>:0 ↵  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) <0x41513730 + 0x00127> in <filename unknown>:0 ↵  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, Boolean checkAdditionalContent) <0x41511930 + 0x001db> in <filename unknown>:0 ↵--- End of stack trace from previous location where exception was thrown ---↵  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f9335d3b2a0 + 0x00029> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f9335d39170 + 0x000a7> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f9335d390f0 + 0x0006b> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f9335d390a0 + 0x0003a> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7f9335d394a0 + 0x00017> in <filename unknown>:0 ↵  at PlexRequests.UI.Modules.SearchModule+<<-ctor>b__0_8>d.MoveNext () <0x41db5360 + 0x004ac> in <filename unknown>:0 ↵  --- End of inner exception stack trace ---↵  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) <0x41dab8c0 + 0x002c3> in <filename unknown>:0 "
message
:
"Something went horribly, horribly wrong while servicing your request."
statusCode
:
500

Is the error that is in the console.

**Comment by tidusjar** [comment]
Ah ok strange...

That's a new bug from the tv episode request work I am doing. It's not fully finished yet (as you can see). 

If I get time tomorrow I'll create a new branch off master (latest release) and add the fix into there.

**Comment by Collisionc** [comment]
No rush.

Another thing that I've noticed, cpu usage and memory usage on the program have skyrocketed in the build you linked. On my ubuntu VPS it's currently using 2 GB of ram and sitting at 30% cpu usage, and the ram usage is slowly creeping up over time. 

Also, in the log this error message is being spammed:

System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () <0x402af720 + 0x000b7> in :0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7f9335eef5d0 + 0x000a1> in :0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, XmlDeserializationEvents events) <0x41bf7ac0 + 0x00823> in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) <0x41bf7a20 + 0x0007f> in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) <0x41bf7600 + 0x00097> in :0 at PlexRequests.Api.ApiRequest.DeserializeXml[T] (System.String input) <0x410de5f0 + 0x000c3> in :0

**Comment by tidusjar** [comment]
Ah ok interesting, That's to do with the new Episode cacher job I added in (I haven't fully tested that yet, so that's probably where the memory leak is coming from).

What it does is goes through your Plex library and caches the episodes you have locally so we then know what to stop you from requesting in the UI.

**Comment by tidusjar** [comment]
Here is a build that has been taken from Master (There is no new functionality) with the workaround

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.8.680/artifacts

@Collisionc @godsplague

**Comment by Collisionc** [comment]
I pulled the latest dev commit and built it, it works fine on that branch too. I'm able to add series on sonarr with no issues so far.

**Comment by godsplague** [comment]
Awesome, I'll try it later today as well. Thanks!

**Comment by godsplague** [comment]
damn, no dice for me. http://pastebin.com/QKe8srwr Just tells me Something went wrong at the top right error. For the installation I just made a copy of the entire old plexrequest folder and then I copied in all the new files to overwrite.

**Comment by tidusjar** [comment]
Yeah the unblock is a PITA!

**Comment by cjdbury** [comment]
Hey @tidusjar I've been having the same "Something went wrong" problem and that new build fixed it.  Thanks!

**Comment by tidusjar** [comment]
@cjdbury Yeah it's probably due to the bug in Sonarr
