### ISSUE TITLE
Issues Page in the App

### ISSUE THREAD

**Issue by slamanna212** [tidusjar/PlexRequests.Net#441]
#### Plex Requests.Net Version:
1.84

#### Operating System:
Docker

#### Mono Version:
Docker

#### Reproduction Steps: NA

Does the issues page have a use yet? I cant find any area where someone would submit an issue

**Comment by tidusjar** [comment]
Users can report issued on available content by searching or on a request from the requests page :smile:

**Comment by slamanna212** [comment]
Well dont i feel silly now! thanks!
