### ISSUE TITLE
Advanced Search Not Working - Duplicate Movies Being Requested

### ISSUE THREAD

**Issue by qazero** [tidusjar/PlexRequests.Net#444]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.4

#### Operating System:
Windows Server 2012 R2 x64

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:
In Settings>Plex I have "Use Advanced Search" checked but when i try and request a move that is already on my Plex it will still add it to CouchPotato. It doesn't detect any of the movies in my Plex library anymore. Everything was working fine about a week ago and then it suddenly stopped working. Perhaps something broke with the latest Plex update? I clicked the "Test Connectivity" button and it connects to Plex successfully. Any ideas what the issue is? Thanks

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Really? That's unusual. I wouldn't have thought the Plex update would have changed the way their API works. 

I'll update my Plex tonight and give it a go and see what is happening.

**Comment by tidusjar** [comment]
I cannot reproduce this issue. are there any logs?

**Comment by qazero** [comment]
Interesting, I tried several times throughout the day yesterday and it wasn't working at all. I even tried rebooting my server but that didn't help either. I just tried again today and it seems to be working fine now and I didn't change any of the settings. My server wasn't lagging during either of the tests either. Any ideas what may be causing the inconsistency?

As for logs, I have my Log Level set to the default setting "Trace" I see 0 entries in the table below. It just says "Loading...". Any idea why that is?

![image](https://cloud.githubusercontent.com/assets/10906010/17278702/35c2452a-5731-11e6-87c8-bddbdc57c784.png)

**Comment by tidusjar** [comment]
I wouldn't use trace, there are some bug with it... Clear your logs and set it to Debug

**Comment by qazero** [comment]
I've now set it to Debug but still won't load the table. When I click on Clear Logs it says:

> Error parsing column 4 (Message=PlexRequests.Api.ApiRequest - String)>

**Comment by tidusjar** [comment]
Awesome...

So you enabled `Advanced Search` and then restarted Plex Requests.

How long did you wait before seeing if it works? Depending on the size of your Plex Library it could take some time, (For me it take 3-4 minutes to cache everything, that's 30 series, 250 movies ish).

If you disable Advanced Search what is the result then?

**Comment by tidusjar** [comment]
Any update @qazero ?

**Comment by Collisionc** [comment]
Current dev branch builds are extremely resource hungry (still) with advanced searching on with large libraries. Constant 30% cpu usage + 2~ GB memory and when searching  it takes 5-8 seconds for anything to show up. This is after an hour of uptime. 

The entire interface is laggy, not unusable, just annoying.

**Comment by tidusjar** [comment]
@collisionc thanks for the feedback. The Dev branch is still in progress and there is still quite a bit of work to do (development wise) which includes optimisation. 

Can you do me a favour, restart Plex requests, take note of the time it started up and check the scheduled jobs admin page 5 minutes later and what is the time on the Plex Episode Cacher? I'm just wondering how long it's taking to run on your server.

**Comment by tidusjar** [comment]
@Collisionc Do you want to try out the latest dev build? There should be some performance improvements.

**Comment by Collisionc** [comment]
Yeah, I'll compile it and try it out... sorry for lack of response, in the USA so I just woke up. 

The program is currently soaking up 4.2 gb of ram. :eek:

I'll check how quickly it deteriorates today.

**Comment by Collisionc** [comment]
Looks like it took roughly 15~ minutes for the plex episode cacher to run.

**Comment by Collisionc** [comment]
It's still using a lot of memory, but  it's allocating that memory a lot faster now. I guess that's an improvement! :)

**Comment by tidusjar** [comment]
How much is a lot?
Date: Thu, 4 Aug 2016 08:07:31 -0700

**Comment by Collisionc** [comment]
After an hour it was 2 GB, after 3~ hours it's up to 2.89 GB

**Comment by Collisionc** [comment]
Had to restart the service as it was getting up to 5 GB memory usage and I only have 8 GB on my VPS.

**Comment by tidusjar** [comment]
Really? And what's your log level?

**Comment by Collisionc** [comment]
Error. There are only 25~ log lines total.
