### ISSUE TITLE
Only Access to PlexRequest from localhost.

### ISSUE THREAD

**Issue by wndh** [tidusjar/PlexRequests.Net#446]
Hi,

I'm running the newest PlexRequest.NET version on a Windows 10 client.

Running fine, but i cannot access plexrequest from other computers on the network nor outside the network.

Currently running on basic port 3579 with access on the host. I've tried forwarding ports and changing ports. 

What should i do to make PlexRequest visible on my network machines/external clients ?
Seems like something is blocking it.

**Comment by wndh** [comment]
Fixed by adding port inbound rules in windows firewall.

**Comment by tidusjar** [comment]
Glad you sorted it.

**Comment by ezraholm50** [comment]
How would this be done on a Headless Ubuntu machine? 

Simply adding UFW rules doesnt work..

sudo ufw allow 3579/tcp

then using machineip:3579 gives me a ERR_CONNECTION_REFUSED

**Comment by tidusjar** [comment]
Can you raise a separate issue please

**Comment by ezraholm50** [comment]
Sure just give me a moment, first trying it on another machine!

**Comment by crafty35a** [comment]
Can I get some details on exactly what setting are needed in the inbound Windows firewall rule? I specified PlexRequests.exe and allowed all traffic/ports, but it doesn't seem to work. The related FAQ item doesn't make sense to me. Thanks!
