### ISSUE TITLE
Notifications and pushbullet 

### ISSUE THREAD

**Issue by CKyle22** [tidusjar/PlexRequests.Net#447]
First I want to thank the dev for helping me with my last issue very quickly. 

Every time I try to turn on notifications with the bell on the homepage, it says the admin hasn't enabled it yet. But I have. Via Pushbullet. Why is that message coming up? 

Also, the test notification for pushbullet works but I have no idea when it's "supposed" to push.

**Comment by tidusjar** [comment]
Hi no problem. 
User notifications are currently only supported via email. Since we know the users email address as they have it associated with Plex. 

The test notification should push a notification instantly

**Comment by CKyle22** [comment]
Oh, I meant that the test notification pushes just fine as soon as I press it, but I have no idea when pushbullet is supposed to push because I haven't gotten a single notification from plexrequests.net besides that. 

I guess I'll set up a mail server though! Thanks again

**Comment by tidusjar** [comment]
You should get notifications when someone (Not in the whitelist or admin) requests a TV Show or Movie OR reports an issue

**Comment by CKyle22** [comment]
Oh that explains it. I thought it was going to notify the requestee that their request was done once I marked it as available. No wonder you only have support for only one API key and not Pushbullet channels! :smile: Plus the user was whitelisted. Everything makes complete sense now.

Thanks again.

**Comment by tidusjar** [comment]
No problem!!
