### ISSUE TITLE
Headphones turned on and connected, can't request from PlexRequests.Net

### ISSUE THREAD

**Issue by CKyle22** [tidusjar/PlexRequests.Net#449]
Nevermind: Am silly.

**Comment by delphiactual** [comment]
Turn on the highlighted options as you see fit...

![screenshot 2016-08-01 15 25 25](https://cloud.githubusercontent.com/assets/4798491/17309523/87ffc8dc-57fc-11e6-8f1c-4943e1481f4d.jpg)
