### ISSUE TITLE
PlexRequest.UI has stopped working

### ISSUE THREAD

**Issue by DejaVu** [tidusjar/PlexRequests.Net#45]
After running PlexRequests for about 5 minutes and setting everything up, I'm presented with this...

![PlexRequests](https://cloud.githubusercontent.com/assets/481679/13900862/4009a60a-ee08-11e5-8611-ae23898e3909.jpg)

It's looking for something on my D: - which is obviously non-existent on my system.

**Comment by tidusjar** [comment]
Ok I know what that error is. I shall fix it tonight

**Comment by tidusjar** [comment]
@DejaVu Can you post your log file, It will be in the install directory? What was you doing at the time?

**Comment by tidusjar** [comment]
Fixed in the latest release.
