### ISSUE TITLE
Systemd Startup Script Not Working

### ISSUE THREAD

**Issue by mizled** [tidusjar/PlexRequests.Net#451]
#### Plex Requests.Net Version:
v1.8.4

#### Operating System:
Ubuntu 15.10

#### Mono Version:
v4.4.2

##### plexrequests.service
> [Unit]
> Description=Systemd script to run PlexRequests as a service
> After=network-online.target
> 
> [Service]
> User=plex
> Group=plex
> Type=simple
> Environment=statedir=/opt/plexrequests/Release
> ExecStart=/usr/bin/mono ${statedir}/PlexRequests.exe -p 3000
> 
> [Install]
> WantedBy=multi-user.target

##### Output of:  sudo systemctl status plexrequests
> plex@mediaserver:/opt/plexrequests/Release$ sudo systemctl status plexrequests
> ● plexrequests.service - Systemd script to run PlexRequests as a service
>    Loaded: loaded (/lib/systemd/system/plexrequests.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Thu 2016-08-04 10:02:37 EDT; 5s ago
>   Process: 16352 ExecStart=/usr/bin/mono ${statedir}/PlexRequests.exe -p 3000 (code=exited, status=255)
>  Main PID: 16352 (code=exited, status=255)
> 
> Aug 04 10:02:37 mediaserver systemd[1]: Started Systemd script to run PlexRequests as a service.
> Aug 04 10:02:37 mediaserver mono[16352]: Starting Up! Please wait, this can usually take a few seconds.
> Aug 04 10:02:37 mediaserver mono[16352]: Version: 1.8.4
> Aug 04 10:02:37 mediaserver mono[16352]: Location of the database: /opt/plexrequests/Release/PlexRequests.sqlite
> Aug 04 10:02:37 mediaserver systemd[1]: plexrequests.service: Main process exited, code=exited, status=255/n/a
> Aug 04 10:02:37 mediaserver systemd[1]: plexrequests.service: Unit entered failed state.
> Aug 04 10:02:37 mediaserver systemd[1]: plexrequests.service: Failed with result 'exit-code'.

##### Output of journalctl -b
> Aug 04 10:02:37 mediaserver sudo[16345]:     plex : TTY=pts/2 ; PWD=/opt/plexrequests/Release ; USER=root ; COMMAND=/bin/systemctl start plexrequests
> Aug 04 10:02:37 mediaserver sudo[16345]: pam_unix(sudo:session): session opened for user root by plex(uid=0)
> Aug 04 10:02:37 mediaserver polkitd(authority=local)[714]: Registered Authentication Agent for unix-process:16346:3061978 (system bus name :1.31 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freede
> Aug 04 10:02:37 mediaserver systemd[1]: Started Systemd script to run PlexRequests as a service.
> Aug 04 10:02:37 mediaserver sudo[16345]: pam_unix(sudo:session): session closed for user root
> Aug 04 10:02:37 mediaserver polkitd(authority=local)[714]: Unregistered Authentication Agent for unix-process:16346:3061978 (system bus name :1.31, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale
> Aug 04 10:02:37 mediaserver mono[16352]: Starting Up! Please wait, this can usually take a few seconds.
> Aug 04 10:02:37 mediaserver mono[16352]: Version: 1.8.4
> Aug 04 10:02:37 mediaserver mono[16352]: Location of the database: /opt/plexrequests/Release/PlexRequests.sqlite
> Aug 04 10:02:37 mediaserver mono[16352]: Unhandled Exception:
> Aug 04 10:02:37 mediaserver mono[16352]: System.UnauthorizedAccessException: Access to the path "/logs" is denied.
> Aug 04 10:02:37 mediaserver mono[16352]: at System.IO.Directory.CreateDirectoriesInternal (System.String path) <0x7f355b702d70 + 0x00120> in <filename unknown>:0
> Aug 04 10:02:37 mediaserver mono[16352]: at System.IO.Directory.CreateDirectory (System.String path) <0x7f355b702bc0 + 0x000a0> in <filename unknown>:0
> Aug 04 10:02:37 mediaserver mono[16352]: at NLog.Internal.FileAppenders.BaseFileAppender.CreateFileStream (Boolean allowFileSharedWriting) <0x41495960 + 0x001a7> in <filename unknown>:0
> Aug 04 10:02:37 mediaserver mono[16352]: at NLog.Internal.FileAppenders.RetryingMultiProcessFileAppender.Write (System.Byte[] bytes) <0x41495670 + 0x00027> in <filename unknown>:0
> Aug 04 10:02:37 mediaserver mono[16352]: at NLog.Targets.FileTarget.WriteToFile (System.String fileName, NLog.LogEventInfo logEvent, System.Byte[] bytes, Boolean justData) <0x41493430 + 0x000a4> in <filename unknown>
> Aug 04 10:02:37 mediaserver mono[16352]: at NLog.Targets.FileTarget.ProcessLogEvent (NLog.LogEventInfo logEvent, System.String fileName, System.Byte[] bytesToWrite) <0x41492700 + 0x0016f> in <filename unknown>:0
> Aug 04 10:02:37 mediaserver mono[16352]: at NLog.Targets.FileTarget.FlushCurrentFileWrites (System.String currentFileName, NLog.LogEventInfo firstLogEvent, System.IO.MemoryStream ms, System.Collections.Generic.List`1
> Aug 04 10:02:37 mediaserver systemd[1]: plexrequests.service: Main process exited, code=exited, status=255/n/a
> Aug 04 10:02:37 mediaserver systemd[1]: plexrequests.service: Unit entered failed state.
> Aug 04 10:02:37 mediaserver systemd[1]: plexrequests.service: Failed with result 'exit-code'.
> Aug 04 10:02:42 mediaserver sudo[16362]:     plex : TTY=pts/2 ; PWD=/opt/plexrequests/Release ; USER=root ; COMMAND=/bin/systemctl status plexrequests
> Aug 04 10:02:42 mediaserver sudo[16362]: pam_unix(sudo:session): session opened for user root by plex(uid=0)
> Aug 04 10:02:42 mediaserver sudo[16362]: pam_unix(sudo:session): session closed for user root

#### Issue:

I can run  plexrequests using "mono /opt/plexrequests/Release/PlexRequests.exe -p 3000" without issue. When I use the Systemd script it will not start. Looking at the journalctl -b output it seems it can't write to path "/logs" even though it is set to 755 and owned by the user plex. Any help would be appreciated.

**Comment by mizled** [comment]
I discovered that the logs for the systemd startup script are attempting to write to "/logs" and not "/opt/plexrequests/Release/logs". When I set the script for "User=root" then PlexRequests starts but the logs are going to "/logs". Is there any way to correct this? I would prefer to not run an internet facing web app as root.

**Comment by tidusjar** [comment]
This might actually be a bug.

**Comment by mizled** [comment]
Thanks for the quick response! I'm going to change "/logs" to be owned by user "plex" until the fix is implemented. Thanks again!

**Comment by tidusjar** [comment]
It's been implemented and will be in the next release ;)

**Comment by delphiactual** [comment]
Still writing to /logs on 1.9.1 using systemd script, had the same issue as @mizled, and just chown /logs to fix this issue tonight...
