### ISSUE TITLE
Error In Logs

### ISSUE THREAD

**Issue by halorrr** [tidusjar/PlexRequests.Net#452]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.4

#### Operating System:
OS X 10.11.6

#### Mono Version:
4.4.0

#### Applicable Logs (from `/logs/` directory or the Admin page):
System.InvalidOperationException: There is an error in XML document (1, 2). ---> System.InvalidOperationException: was not expected. at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexLibraries.Read4_MediaContainer () <0x546d740 + 0x000a3> in :0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x1a7c260 + 0x000a1> in :0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, XmlDeserializationEvents events) <0x546b940 + 0x006df> in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) <0x546b8c8 + 0x00063> in :0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) <0x546b560 + 0x00093> in :0 at PlexRequests.Api.ApiRequest.DeserializeXml[T] (System.String input) <0x53a1480 + 0x0009f> in :0	PlexRequests.Api.ApiRequest	Error	8/4/2016 9:38:28 AM
```

#### Reproduction Steps:
Noticed this is being spammed in my error log when I was checking some settings. Not sure what this is doing.

**Comment by tidusjar** [comment]
Hmmm, Looks like we cannot deserialize the libraries correctly!

That's not good.

Can you do the following for me:

in the browser type in:

http://**ip**:**PlexPort**/library/sections?X-Plex-Token=**PLEXAUTHTOKEN**&X-Plex-Client-Identifier=test&X-Plex-Product=PlexRequest&X-Plex-Version=1

Can you post the result here?

**Comment by jdenson** [comment]
So, ever since I migrated PlexRequests to a different server, I've been having this same issue. Using this 

> http://ip:PlexPort/library/sections?X-Plex-Token=PLEXAUTHTOKEN&X-Plex-Client-Identifier=test&X-Plex-Product=PlexRequest&X-Plex-Version=1

with my info filled gives me a 401 unauthorized error. Running the latest (as of today) PlexPass version of PMS on Ubuntu 14.04.

**Comment by tidusjar** [comment]
Sorry, I need the response from Plex.

Do you need to do this:

http://ip:PlexPort/library/sections?X-Plex-Token=PLEXAUTHTOKEN&X-Plex-Client-Identifier=test&X-Plex-Product=PlexRequest&X-Plex-Version=1

But replace where it says **PLEXAUTHTOKEN** with your Plex token (you can find this in Plex Requests settings).

**Comment by halorrr** [comment]
I get a 401 unauthorized when I try that with my info in there. (sorry for the delayed response, been busy and forgot to answer)

**Comment by tidusjar** [comment]
That means that the API key is probably invalid. It should return a response. 

It's what Plex Requests uses to communicate with Plex

**Comment by jdenson** [comment]
> Sorry, I need the response from Plex.
> 
> Do you need to do this:
> 
> http://ip:PlexPort/library/sections?X-Plex-Token=PLEXAUTHTOKEN&X-Plex-Client-Identifier=test&X-Plex-Product=PlexRequest&X-Plex-Version=1
> 
> But replace where it says PLEXAUTHTOKEN with your Plex token (you can find this in Plex Requests settings).
> 

I did that, I filled in all my info including my current token. It came back as 401 unauthorized.

**Comment by halorrr** [comment]
I requested a new tokens and it all seems good now! Thanks!

**Comment by jdenson** [comment]
I'll be damned. Requesting a new token didn't work the first time I tried but it worked this time. I'm back up and running as well.
