### ISSUE TITLE
doesn't send email alert after change username plex

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#456]
Problem: After username change in plex, Plexrequests still try to search for a email adres on the old username for sending a email message. Also a refresh users doesn't help in the admin panel.
That is failing because the username doesn't exist anymore.
#### Plex Requests.Net Version:

1.8.3
#### Operating System:

Windows 10 pro
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
There is no email address for this Plex user, cannot send notification  PlexRequests.Services.Jobs.PlexAvailabilityChecker  Info    8/5/2016 5:32:51 PM
Notifying user info@XXXX.nl PlexRequests.Services.Jobs.PlexAvailabilityChecker  Info    8/5/2016 5:32:51 PM

```
#### Reproduction Steps:

Change username on plex.tv
refresh users on Current users that are allowed to authenticate: .
Request something and wait for trying to send a mail

**Comment by tidusjar** [comment]
That's a good point. I never thought about that scenario...
Is this for the user notifications?

I guess I'll need to store the Plex User Id and look them up every time instead.

**Comment by whitecollar17** [comment]
thats correct is about the user notifications.
