### ISSUE TITLE
Something went wrong, All the time!!

### ISSUE THREAD

**Issue by morpheus2n2** [tidusjar/PlexRequests.Net#458]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

1.8.4
#### Operating System:

Windows 10
#### Mono Version:
?

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:
No matter what I try I can't get the app to work! I have followed every step to the letter and even redid it all but still the same.

When I go to settings first its not very clear for a first timer and a novice, I try to change the port to match the rest of my media app's setup and get a message saying "Something went wrong" go to the logs and there's nothing there at all, change to all the different log types while retrying to change port and nothing is being reported at all!!

Next I go to the Plex setting and again when I set the hostname and port for plex with SSL I get the "Something went wrong" again no logs of any sort, this goes for every single setting always get the "Something went wrong" with nothing being reported.

Also whats the Subdirectory thing under Plex and Sonarr etc I don't understand. I can not for the life of me get this to work or work out what some of the settings are at all :(

**Comment by tidusjar** [comment]
Did you unblock the zip before extracting it?

**Comment by morpheus2n2** [comment]
Yep, Like I said I followed the guide to the letter lol

**Comment by tidusjar** [comment]
Strange!

I agree, the settings are not that straight forward to get the application working. I am planning to add a user wizard on the first time setup.

>  I try to change the port to match the rest of my media app's setup

What port did you try and change?

> Subdirectory

Subdirectory has been renamed in the dev branch, it's the BaseUrl

> "Something went wrong"

Open up the developers console (F12 on Chrome), go to the Network Tab
![image](https://cloud.githubusercontent.com/assets/6642220/17134412/2a91299a-5322-11e6-9fee-01ed94b16627.png)

Then press request to get the error message.
You should see a red entry in the network area now, something like this:
![image](https://cloud.githubusercontent.com/assets/6642220/17134450/59be9414-5322-11e6-9a4c-2909bb232220.png)

(There should only be 1 **red** entry).
If you then click on that and press the preview tab and post the content on here?

**Comment by morpheus2n2** [comment]
Ok I restarted the PC and this is what I get now,
![2016-08-08](https://cloud.githubusercontent.com/assets/14253602/17474308/2bae79ba-5d4d-11e6-9f11-c69e3d3c1a6d.png)
![2016-08-08 1](https://cloud.githubusercontent.com/assets/14253602/17474311/3024fd0c-5d4d-11e6-9344-4b9bc8cec44d.png)

**Comment by tidusjar** [comment]
You have set `localhost` as the base url for the application. That's incorrect, you only want to use the base url when you are using some sort of reverse proxy.

I suggest you delete the `PlexRequests.sqlite` file and start over

**Comment by delphiactual** [comment]
@tidusjar Maybe hide settings under an advanced option (like couchpotato and sonarr), so that newer users do not change values that should not be edited without further knowledge.

**Comment by tidusjar** [comment]
@delphiactual Good idea

**Comment by SilverSix311** [comment]
Any idea what generally causes this issue? I'm experiencing it right now.

**Comment by tidusjar** [comment]
@SilverSix311 What are you trying to do? Delete a request? If you refresh the page is it gone?

**Comment by SilverSix311** [comment]
No it's still there. Trying to approve produces another error as well.
`{result: false, available: false,…}
available
:
false
message
:
"Could not update the availability, please try again or check the logs"
result
:
false`

**Comment by tidusjar** [comment]
And you have everything (Settings) set up? Including having your quality profiles populated in Sonarr/Couchpotato?

**Comment by SilverSix311** [comment]
Yea, Im pretty sure it is all setup. I don't see anything else that I would need to setup.

**Comment by tidusjar** [comment]
@SilverSix311  Sorry for the late reply, it seems that there is something wrong with your DB, does the latest still produce this issue?
