### ISSUE TITLE
Read only users, some users I do not want them to be able to request

### ISSUE THREAD

**Issue by Grimshad** [tidusjar/PlexRequests.Net#461]
Please add the ability to whitelist users so that only users on the whitelist can request anything AND/OR allow request limit to be set to -1 for none (since 0 is unlimited) unless on the whitelist.

Also allow changing of timeframe for requests limit. weekly/monthly/yearly limit.

**Comment by tidusjar** [comment]
Whitelist is already present and should do the things you have stated.

The 2nd is also possible. Under schedule jobs there is the user limit resetter. Change that to run once a week and you then have a weekly limit.

**Comment by Grimshad** [comment]
Thanks for the reply.

The scheduler works as stated, however, this isn't as apparent or intuitive as a quick dropdown selection in the settings next to other relevant settings. Without in depth study or finding out like I did. I don't see the average user finding out about this.

As for the whitelist. While there is one, it does not function the way I described. Currently the whitelist automatically approves users requests as well as gives them unlimited requests.

I want to allow no users to make requests except for the ones on the whitelist. I also don't want the users who can make requests automatically approved. There is also currently no way that I am aware of to prevent users from making requests all together. There is only unlimited and limited.

**Comment by tidusjar** [comment]
Ah ok, So what you need to do is enter in all the users that you do not want to request into the Denied Users list on the Authentication settings.

I understand what you mean.

**Comment by Grimshad** [comment]
I can't do that though, Everything I have is behind your authentication system. I still need to allow them access, just not allow requests.

**Comment by tidusjar** [comment]
Oh. I see what you mean, why would you want them to access it but not request anything? So they can see what has been requested?

**Comment by Grimshad** [comment]
I want them to be able to see what has been requested, be able to report issues, and get to the landing page (which is behind auth) and also get to all of the pages the landing page links to (which are all also behind PR.net auth).

**Comment by tidusjar** [comment]
Yeah that's a good idea.

**Comment by SuperPotatoMen** [comment]
This is part of the brand new User Management!

It is already live in the dev branch
https://github.com/tidusjar/PlexRequests.Net/issues/218
