### ISSUE TITLE
Bug: Request view and filtering/sorting stop functioning

### ISSUE THREAD

**Issue by Grimshad** [tidusjar/PlexRequests.Net#462]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.4

#### Operating System:
Win10

#### Applicable Logs (from `/logs/` directory or the Admin page):
Nothing in the logs abou it

#### Reproduction Steps:
Install PR.net
Make a bunch of movie/tv requests
Go to the requests tab
It will display movies, click tv shows
it will display tv shows, click the filters and click not approved
it will display not approved tv shows
restart the PR.net service
go back to the requests tab
it will display movies, click tv shows
it will append tv show requests to the bottom of the movies, click filters and click not approved
it will do nothing

Problem:
After the first time, the requests display no longer switches between movies and tv, it just shows movies until you click the tv tab and then it shows movies with tv appended to the bottom. the filters no longer have any affect.

**Comment by Grimshad** [comment]
A Quotation closing was missing from the requests index.cshtml for some reason.

**Comment by tidusjar** [comment]
What line?

**Comment by Grimshad** [comment]
The problem isn't present in your release. I must have edited the requests view and then reverted and somehow missed a quotation closing.

My fault, not yours.

**Comment by tidusjar** [comment]
Ah ok!
