### ISSUE TITLE
Bug: Incorrect Release Time

### ISSUE THREAD

**Issue by Grimshad** [tidusjar/PlexRequests.Net#464]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.8.4
#### Operating System:
win10

#### Applicable Logs (from `/logs/` directory or the Admin page):
None 

#### Reproduction Steps:
Request the show "The Blacklist: Redemption"

Problem: PR.net detects this show as coming out in year "1" which then states it came out 2016 years ago. I believe it's because the show is yet to come out (2017).

**Comment by tidusjar** [comment]
This is a data issue on TVMaze. That show doesn't have a premiered date. We have to report this as an issue:
http://www.tvmaze.com/threads/1618/edit-requests?page=2

**Comment by Grimshad** [comment]
Even if this is an issue on their end, why would you not include handling for this situation? In this case you could easily add "Not yet released" or something similar.

**Comment by tidusjar** [comment]
Good point, it's difficult to know what to handle before hand. I had no idea it was possible for their data not to have a premiered date. I could handle every single scenario, but that would be time consuming and unfortunately I cannot dedicate 100% of my time to this project (Need to pay the bills too!).

I can add something in for this.

**Comment by Grimshad** [comment]
I would love to help. I code in C# and C++, but I don't know how to setup a .net enviroment for this. I already downloaded the source and attempted to get familiar, but it's pretty confusing.

**Comment by tidusjar** [comment]
If you are not familiar with MVC/Asp.Net then it can be a bit confusing. 
https://github.com/tidusjar/PlexRequests.Net/blob/dev/PlexRequests.UI/Views/Requests/Index.cshtml#L173

That is probably where it needs to check if it's equal to  C#'s `DateTime.MinValue` and if it is then we need to add a localised string for "No Release Information Available" or something similar

**Comment by Grimshad** [comment]
All the localization in resources?

**Comment by tidusjar** [comment]
Yes
