### ISSUE TITLE
[Dev] Available tv show issues.

### ISSUE THREAD

**Issue by chris243** [tidusjar/PlexRequests.Net#466]
#### Plex Requests.Net Version:
1.9.0

#### Operating System:
Windows 10

#### Reproduction Steps:

When I try to search for a new season of a show that already has some episodes on plex I now get the option to request more seasons but once I do pick a new season I get " This TV SHOW is already in Plex"

Also if you go to select episode all missing episodes get permanently marked and cannot untick their box.

**Comment by tidusjar** [comment]
> When I try to search for a new season of a show that already has some episodes on plex I now get the option to request more seasons but once I do pick a new season I get " This TV SHOW is already in Plex"
What option are you selecting in the UI? The select seasons or select episodes?

> Also if you go to select episode all missing episodes get permanently marked and cannot untick their box.
Missing episodes are ticked? In Sonarr, what are the status of the episodes? Monitored?

**Comment by chris243** [comment]
http://imgur.com/a/lNmHc made a couple of gifs showing what i mean.

On sonnar the show is monitored but also tried a non monitored season same result.

**Comment by tidusjar** [comment]
So, the first image, is that season `Monitored` in Sonarr?

Second image, it's not the Season that needs to be monitored, it's the individual episodes are monitored or has a file.

**Comment by chris243** [comment]
Yes the season is monitored. 
It seems on the episodes it is going by monitored status and not if the episode is actually there. I un monitored season 03 for example and now all episodes of season 03 are unchecked like the earlier episodes even though i don't actually have them.

**Comment by tidusjar** [comment]
True, I think I have found a bug though which I will fix.

Regarding the episodes, I understand that, but if they are already monitored, what is the point in requesting them?

**Comment by chris243** [comment]
Because sonnar wont search for monitored episodes by itself. It does but only for new episodes that aired recently. For old seasons you have to manually search for that season or episode.

**Comment by tidusjar** [comment]
Ok. I'll take a look at changing this.

**Comment by tidusjar** [comment]
Need more rework

**Comment by delphiactual** [comment]
If you add a specific episode, just kick off a manual search for it

**Comment by tidusjar** [comment]
@delphiactual I already do that, I just need to sort out my validation with what we can and cannot request

**Comment by tidusjar** [comment]
All reworked, can you try again now @chris243 with the latest build from: https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by tidusjar** [comment]
@chris243 Any luck? I'd like to get a release out :)

**Comment by chris243** [comment]
Still says show already on plex on the seasons part. It still says 1.9.0 so idk if I actually updated. Just re downloaded from that link you posted and overwrote over my current install.

**Comment by tidusjar** [comment]
You must have all the episodes in that season on Plex then? @chris243

**Comment by chris243** [comment]
No. I tried with shows that i only have a couple episodes and also ones where I'm only missing 1 season. Also tried with season monitored and unmonitored. Could this be just me somehow? It's really strange.

**Comment by tidusjar** [comment]
@chris243 are you able to jump on Gitter? 
https://gitter.im/tidusjar/PlexRequests.Net

**Comment by chris243** [comment]
Ok I'm there

**Comment by tidusjar** [comment]
@chris243 can you check now? I think it's all good and ready to release

**Comment by chris243** [comment]
Alright just tested so now it shows that it requests it fine but on sonarr logs it searches for specials for that show no matter what season I try. I'll be on for a couple more hours if you need me to test stuff. ill be on gitter

**Comment by tidusjar** [comment]
Really? Interesting. What show?
