### ISSUE TITLE
Feature: External Hosting via Google Drive Possible?

### ISSUE THREAD

**Issue by rjtort** [tidusjar/PlexRequests.Net#467]
Seeing as PlexRequests.net is on my Plex server, if the server is down, I/guests can't access the landing page that would tell them the Plex server is down or show a maintenance window. 

My thought was if I could place the PlexRequests.net folder in a Google Drive folder, then share the html page to my host forwarding site using the Google Drive public link, it would circumvent this road block. 

The issue I'm having is that I only see the .chtml files, and those just download as files when linked to in a web browser. If I link to the folder the way the direct method works (Ex. http://localhost: 3579/userlogin), it just goes to the folder level view in Google Drive's web view. 

Any ideas or suggestions?

**Comment by tidusjar** [comment]
The problem is that the .cshtml files are compiled at runtime and you cannot use them to view in the browser (they are not .html files). 

You need to run the .exe to view them, the only way you can get around this is to host the website (run the .exe on a different machine).

**Comment by rjtort** [comment]
Thanks for the quick reply and clarification.
