### ISSUE TITLE
[F REQ] Donate button removal

### ISSUE THREAD

**Issue by CodaAmok** [tidusjar/PlexRequests.Net#469]
Donate button removal for "my" users, I don't want them thinking it's me who is asking for the donation. I know it's obvious once you click the link and your name&photo appears but have you ever considered an option for "Admins" to remove this option for "non admin" users?

**Comment by tidusjar** [comment]
It's not displayed for non admin users.

**Comment by CodaAmok** [comment]
Sorry

**Comment by npan03** [comment]
Hi , I know this is really old but one of my requirements is that I have to get rid of the donate button. Any tips?

**Comment by pir8radio** [comment]
#nav-adminDonate {display: none;}

in the custom CSS area.

> Hi , I know this is really old but one of my requirements is that I have to get rid of the donate button. Any tips?
