### ISSUE TITLE
HTTPS redirects to HTTP - How to fix?

### ISSUE THREAD

**Issue by SoftBrok** [tidusjar/PlexRequests.Net#473]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

1.9.0

#### Operating System:

Docker container

#### Mono Version:

Standard for Docker image

#### Applicable Logs (from `/logs/` directory or the Admin page):

None Found

#### Reproduction Steps:

Setup NGINX SSL reverse proxy, set base URL, debug extensively, and find the software will force redirect to HTTP from HTTPS no matter what settings are applied.

**Comment by tidusjar** [comment]
Really? I know some people are running it through nginx and ssl fine. (I cannot really comment on this because my nginx knowledge is lacking(

**Comment by mescon** [comment]
Well, I just upgraded to 1.9 and this started happening for me too. It's the landing page after login that is redirected to http... for instance:
https://domain.com/request works fine, then when I log in, it redirects me to http://domain.com/request/landing (note it's now stripped the SSL).

**Comment by tidusjar** [comment]
I have a feeling I know what might be causing this. I'm looking at the actual HTTP context of PlexRequests, and as you say might not be correct... Need to investigate how to construct redirects without using the context

**Comment by tidusjar** [comment]
Anyone got a guide on how I can use SSL in my nginx conf so I can repro this?

**Comment by tidusjar** [comment]
https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.755/artifacts

**Comment by mescon** [comment]
Yep, this version works like a charm - logged in, logged out, entered admin area, clicked around for a bit without a problem. Thanks for the quick fix @tidusjar !
