### ISSUE TITLE
Can request season while it is already on Plex

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#474]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.0

#### Operating System:
Windows 10

#### Mono Version:
?

#### Applicable Logs (from `/logs/` directory or the Admin page):
N/A level: debug

#### Reproduction Steps:

I test to request TV program Brooklyn Nine-Nine (2013) season 1 but it is already on Plex. I can Request it while it should say: already available. No log entries. Already did a re-login on Plex and connectivity check was succesfull.

I have the same issue with requesting movies which already are on Plex.

**Comment by tidusjar** [comment]
Really?

For TV Shows do you have every single episode? (Also, awesome show).

And the movies thing.... I'll take a look

**Comment by Ruvetuve** [comment]
yeah got whole season. thanks, let me know if i can provide you more info.

**Comment by Ruvetuve** [comment]
Is the bug valid? Any progress on finding a solution? Let me know if I can help bringing more information.

**Comment by tidusjar** [comment]
I couldn't reproduce it. Do you have the advanced search on in th Plex settings?

**Comment by Ruvetuve** [comment]
Use Advanced Search is checked
Enable Episode Searching is unchecked

**Comment by Ruvetuve** [comment]
Didn't change anything, but now it says on a movie search: Available. So that's good. Series still same issue. S01 present, can still request.

**Comment by Ruvetuve** [comment]
Sonarr not enabled btw. So individual episode requests are disabled. Season check should work right?

**Comment by Ruvetuve** [comment]
Weird, shows are working now...doesn't to be a problam anymore... nothing changed though...

**Comment by tidusjar** [comment]
Is it possible that the browser cached the old JavaScript files? Version 1.8

**Comment by Ruvetuve** [comment]
yeah possible. Let's close the issue, ill keep monitoring.

**Comment by tidusjar** [comment]
Yeah I did start looking into that, There is a task for it.
