### ISSUE TITLE
How to update on Linux?

### ISSUE THREAD

**Issue by Jonn3y** [tidusjar/PlexRequests.Net#477]
A little tutorial would be nice :) on wiki!

**Comment by tidusjar** [comment]
If you followed this on the install http://www.htpcguides.com/install-plex-requests-net-ubuntu-14-x/

All you need to do is replace (I don't use Linux so If I wrote it, it would not make any sense). Everyone can edit the wiki so if you have an idea how to do it! ;)

**Comment by Jonn3y** [comment]
Do i lose the database when i update it?

**Comment by tidusjar** [comment]
No. the database is created by the application so there will be nothing to overwrite

**Comment by Jonn3y** [comment]
Okay thank you, got it.
1. Stop PlexRequests
2. Overwrite the files.
3. Run PlexRequests
=) thanks
