### ISSUE TITLE
Possible User Management Crash on Ubuntu 16.04

### ISSUE THREAD

**Issue by ratherDashing** [tidusjar/PlexRequests.Net#478]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9

#### Operating System:
Ubuntu 16.04

#### Mono Version:
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Collections.Generic.List`1' threw an exception. ---> System.Threading.ThreadAbortException:
  --- End of inner exception stack trace ---
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x414e49c0 + 0x00083> in <filename unknown>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x414e4550 + 0x0021a> in <filename unknown>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x414e4510 + 0x00028> in <filename unknown>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x414e4440 + 0x00061> in <filename unknown>:0
  at System.Threading.ThreadHelper.ThreadStart () <0x414e43b0 + 0x00039> in <filename unknown>:0

#### Reproduction Steps:

Randomly Crashes when setting params regarding the landing page.

**Comment by tidusjar** [comment]
Really? That's interesting. Never seen this before, can you accurately reproduce this crash?

**Comment by ratherDashing** [comment]
Not really.  What will happen is the landing page will just randomly stop working.  So I'll go in, disable the landing page and the various options (before login and notice).  Then hit submit.  I believe this is when this one happened.  I'll wait until the next time the landing page just randomly stops coming up and then try to really pay attention to what i'm clicking.

**Comment by tidusjar** [comment]
No one has ever reported anything with the landing page and I've not made any modifications to it this release so strange... the stacktrace unfortunately does not provide much information to go on.

**Comment by ratherDashing** [comment]
I got it to crash again.  Same Stack Trace.  I logged in as myself.  Logged out.  Went to the homepage.  I didn't see the landing page.  So I logged in.  Unchecked the landing page and the 3 options.  Logged out.  Logged back in.  Boom.

2016/08/19 15:08:48.370 PlexRequests.UI.Modules.UserLoginModule Debug: Username "username" attempting to login
2016/08/19 15:08:48.454 PlexRequests.UI.Modules.UserLoginModule Debug: Using password
2016/08/19 15:08:48.525 PlexRequests.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass
2016/08/19 15:08:49.416 PlexRequests.Api.ApiRequest Trace: Api Content Response:
2016/08/19 15:08:49.500 PlexRequests.Api.ApiRequest Trace: {"user":{"id":2341269,"uuid":"uuid","email":"warrenm83@hotmail.com","joined_at":"2014-04-02T18:38:33Z","username":"username","title":"username","thumb":"https://plex.tv/users/uuid/avatar","authToken":"authToken","authentication_token":"authToken","subscription":{"active":true,"status":"Active","plan":"lifetime","features":["sync","home","camera_upload","content_filter","pass","cloudsync","premium_music_metadata","lyrics","music_videos","trailers"]},"roles":{"roles":["plexpass"]},"entitlements":["ios","xbox_one","all","roku","android","xbox_360","windows","windows_phone"],"confirmedAt":"2014-04-03T14:58:33Z","forumId":234506,"rememberMe":false}}
2016/08/19 15:08:49.670 PlexRequests.UI.Modules.UserLoginModule Debug: Correct credentials, checking if the user is account owner or in the friends list
2016/08/19 15:08:49.994 PlexRequests.UI.Modules.UserLoginModule Debug: User is the account owner
2016/08/19 15:08:50.159 PlexRequests.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session.
2016/08/19 15:09:19.384 PlexRequests.UI.Modules.UserLoginModule Debug: Username "username" attempting to login
2016/08/19 15:09:19.496 PlexRequests.UI.Modules.UserLoginModule Debug: Using password
2016/08/19 15:09:19.689 PlexRequests.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass
2016/08/19 15:09:20.053 PlexRequests.Api.ApiRequest Trace: Api Content Response:
2016/08/19 15:09:20.137 PlexRequests.Api.ApiRequest Trace: {"user":{"id":2341269,"uuid":"uuid","email":"warrenm83@hotmail.com","joined_at":"2014-04-02T18:38:33Z","username":"username","title":"username","thumb":"https://plex.tv/users/uuid/avatar","authToken":"authToken","authentication_token":"authToken","subscription":{"active":true,"status":"Active","plan":"lifetime","features":["sync","home","camera_upload","content_filter","pass","cloudsync","premium_music_metadata","lyrics","music_videos","trailers"]},"roles":{"roles":["plexpass"]},"entitlements":["ios","xbox_one","all","roku","android","xbox_360","windows","windows_phone"],"confirmedAt":"2014-04-03T14:58:33Z","forumId":234506,"rememberMe":false}}
2016/08/19 15:09:20.275 PlexRequests.UI.Modules.UserLoginModule Debug: Correct credentials, checking if the user is account owner or in the friends list
2016/08/19 15:09:20.557 PlexRequests.UI.Modules.UserLoginModule Debug: User is the account owner
2016/08/19 15:09:20.646 PlexRequests.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session.
2016/08/19 15:09:57.426 PlexRequests.UI.Modules.UserLoginModule Debug: Username "username" attempting to login
2016/08/19 15:09:57.520 PlexRequests.UI.Modules.UserLoginModule Debug: Using password
2016/08/19 15:09:57.650 PlexRequests.UI.Modules.UserLoginModule Debug: Need to auth and also provide pass
2016/08/19 15:09:57.975 PlexRequests.Api.ApiRequest Trace: Api Content Response:
2016/08/19 15:09:58.250 PlexRequests.Api.ApiRequest Trace: {"user":{"id":2341269,"uuid":"uuid","email":"warrenm83@hotmail.com","joined_at":"2014-04-02T18:38:33Z","username":"username","title":"username","thumb":"https://plex.tv/users/uuid/avatar","authToken":"authToken","authentication_token":"authToken","subscription":{"active":true,"status":"Active","plan":"lifetime","features":["sync","home","camera_upload","content_filter","pass","cloudsync","premium_music_metadata","lyrics","music_videos","trailers"]},"roles":{"roles":["plexpass"]},"entitlements":["ios","xbox_one","all","roku","android","xbox_360","windows","windows_phone"],"confirmedAt":"2014-04-03T14:58:33Z","forumId":234506,"rememberMe":false}}
2016/08/19 15:09:58.398 PlexRequests.UI.Modules.UserLoginModule Debug: Correct credentials, checking if the user is account owner or in the friends list
2016/08/19 15:09:58.783 PlexRequests.UI.Modules.UserLoginModule Debug: User is the account owner
2016/08/19 15:09:58.900 PlexRequests.UI.Modules.UserLoginModule Debug: We are authenticated! Setting session.

**Comment by tidusjar** [comment]
Cannot reproduce this, can you upload a .gif showing me what you are doing? ShareX is a good tool.

**Comment by ratherDashing** [comment]
https://drive.google.com/file/d/0Bxif9mBa5m-zN0NFeUlWNDBRRjg/view?usp=sharing

**Comment by tidusjar** [comment]
I cannot reproduce this on the latest dev branch as I have fixed a few issues around it. Do you mind giving it a go?

**Comment by ratherDashing** [comment]
I'll give it a go when the next release is posted.  Right now I don't have a .Net build environment set up.  Thanks!

**Comment by tidusjar** [comment]
@ratherDashing You don't need one ;)

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.764/artifacts

**Comment by ratherDashing** [comment]
I can't get it to crash now (hopefully) so it looks like this is fixed!  Most of the times the landing page still doesn't come up before log in though even when configured like that.  The userlogin page seems to the default page.  If I log in, then go back to the default page, then I get the landing page.
