### ISSUE TITLE
Email Notifications Are Not Working

### ISSUE THREAD

**Issue by x-radeon** [tidusjar/PlexRequests.Net#480]
I can't get email notifications to work. This is the first time using Plex Requests. I've configured everything correctly for setup.

Enabled: Yes

Enable user email notifications: Yes

Enable SMTP Auth?: No

SMTP Host: mail.domain.tld

SMTP Port: 25

Email addresses are valid.

No username/password specified.

Plex Requests doesn't report any errors or issues when I hit 'Test' and I don't get much info from the logs when I set it to debug or trace. I use Exchange 2013 and it's on the same network as Plex Requests. I know my Exchange server can relay mail just fine since other application use it daily. I did run a packet capture on my Exchange server and I didn't see any packets coming from Plex Requests, so I'm guessing either I don't have something installed that allows emails to function or something is broken in this release. (It could be my server, but I doubt it because other applications on the same server can send email just fine e.g. Sonarr).

Let me know what other info you need from me.

#### Plex Requests.Net Version:
1.9.0

#### Operating System:
Windows Server 2012 R2 - Fully Patched

#### Mono Version:
Not sure, what ever is shipped in the .zip for the 1.9.0 release.

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Sent email notification test 	PlexRequests.UI.Modules.AdminModule	Info	8/19/2016 3:30:56 PM
```

#### Reproduction Steps:

Configure Email Notification settings - > Press Test.

**Comment by whitecollar17** [comment]
For the record, you didn't have smtp auth activated on youre exchange 2013 server?!?!?

**Comment by x-radeon** [comment]
The FrontendTransport responsible is setup to only allow my local network to relay anonymously. I don't allow any public address to relay anonymously, they can only send messages destined for users in my domain.

I should also add, I've tried port 25 and 465 (Not sure if 465 would work correctly since there's no SSL option).

**Comment by tidusjar** [comment]
Are you able to enable Authentication? If so does it work then?

**Comment by nightexcessive** [comment]
Mine attempts to send an email if I check the authentication box, but my smarthost doesn't support authentication.

**Comment by x-radeon** [comment]
I am able to send mail successfully if I enable SMTP authentication. I looked at your code, it looks solid, is there a bug with MailKit or something?

**Comment by tidusjar** [comment]
Sorry not had time to look at this yet, I don't know. As far as I am aware it should work.

**Comment by tidusjar** [comment]
Anyone tried the new build to confirm?

**Comment by tidusjar** [comment]
https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by x-radeon** [comment]
It looks like that dev build fixes the issue!

> This is just a test! Success!
