### ISSUE TITLE
Wizard detects Manually Specified Port Instead of 32400

### ISSUE THREAD

**Issue by jimphreak** [tidusjar/PlexRequests.Net#482]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

1.9

#### Operating System:

Ubuntu Server 16.04

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

This isn't a huge issue as you can just change the port back to 32400 but the wizard seems to detect the manually specified port in Plex which is the publicly accessed port we can specify for our remote users.  For most people I would assume they are setting up PlexRequests locally so yo would want the default Plex port of 32400 to be used since that's the only port the Plex server itself looks for.  Just figured I'd point this out as this could be an issue for some.

**Comment by tidusjar** [comment]
I just get this information from the Plex API. I know a lot of people use PR on different servers. But it's just to help with filling in the information faster, it still can be changed so I'm not going to worry too much about this.

Thanks for reporting it though
