### ISSUE TITLE
[Feature] Buffer user requests into a waiting queue when CP/Sonarr/plex is offline

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#483]
A feature request: if CP/sonnarr/plex is offline, place the user request into a waiting queue.
After CP/sonarr/plex is online again, send the request automatic.

**Comment by SuperPotatoMen** [comment]
can be a part of https://github.com/tidusjar/PlexRequests.Net/issues/633

**Comment by tidusjar** [comment]
Need to add a UI for the admin to see the failed requests
