### ISSUE TITLE
Headphones Error get error

### ISSUE THREAD

**Issue by seanvree** [tidusjar/PlexRequests.Net#485]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
Version:  1.9.0

#### Operating System:
Windows 10 Enterpirse

#### Applicable Logs (from `/logs/` directory or the Admin page):
Message	Area	Log Level	Date
System.Xml.XmlException: '>' is an unexpected token. The expected token is '"' or '''. Line 1, position 55. at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.DtdParserProxy.System.Xml.IDtdParserAdapter.Throw(Exception e) at System.Xml.DtdParser.Throw(Int32 curPos, String res, String[] args) at System.Xml.DtdParser.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2) at System.Xml.DtdParser.ParseExternalId(Token idTokenType, Token declType, String& publicId, String& systemId) at System.Xml.DtdParser.ParseInDocumentDtd(Boolean saveInternalSubset) at System.Xml.DtdParser.Parse(Boolean saveInternalSubset) at System.Xml.DtdParser.System.Xml.IDtdParser.ParseInternalDtd(IDtdParserAdapter adapter, Boolean saveInternalSubset) at System.Xml.XmlTextReaderImpl.ParseDtd() at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl() at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options) at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options) at RestSharp.Deserializers.XmlDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)

#### Reproduction Steps:

If you search for an album you'll get these errors in the Headphones log as well as the logs above:

2016-08-19 19:45:31	INFO	Searching for "None - None" since it was marked as wanted
2016-08-19 19:45:31	INFO	Searching for wanted albums
2016-08-19 19:45:31	INFO	Recieved API command: queueAlbum
2016-08-19 19:45:29	INFO	Searching for "None - None" since it was marked as wanted
2016-08-19 19:45:29	INFO	Searching for wanted albums
2016-08-19 19:45:29	INFO	Recieved API command: queueAlbum
2016-08-19 19:45:29	INFO	Release bb758b41-5870-4a0b-a989-12688a2d9d38 already exists in the database!
2016-08-19 19:45:28	INFO	Recieved API command: addAlbum
2016-08-19 19:45:28	INFO	Recieved API command: getIndex
2016-08-19 19:43:57	INFO	Writing configuration to file
2016-08-19 19:43:18	INFO	Recieved API command: getVersion
2016-08-19 19:43:10	INFO	Searching for "None - None" since it was marked as wanted
2016-08-19 19:43:10	INFO	Searching for wanted albums
Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
So you are searching and requesting something that already exists?

`2016-08-19 19:45:29 INFO Release bb758b41-5870-4a0b-a989-12688a2d9d38 already exists in the database!`

**Comment by seanvree** [comment]
Possibly this one, but this error shows up any time I request something from albums.  No results actually appear in search. If I search for an artist or album name, it just sits there and searches.

**Comment by seanvree** [comment]
Hey buddy! This can be closed.  It looks as if when you hit "request" on an album it takes a while for HP to parse all the artists releases. In this case I was searching for 2pac, so it had to go thru a lot of material.  

My bad.

**Comment by tidusjar** [comment]
That's more of a headphones issue

**Comment by smcpeck** [comment]
This is actually fixed with #1186
