### ISSUE TITLE
Choosing all seasons only tells Sonarr to download latest episodes

### ISSUE THREAD

**Issue by ZeroManArmy** [tidusjar/PlexRequests.Net#487]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page): None

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps: Request any TV series and choose all seasons

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by djs4000** [comment]
Looks like it might be more than just all seasons. It appears to add the show to sonarr just fine, but isn't toggling the "watched" status for any season but the last. Picking "First Season" or even selecting a season adds the show, but it is left unwatched in sonarr. That means sonarr wont look for and download the show properly.

**Comment by tidusjar** [comment]
I'll be looking into this tonight/tomorrow if time permits!

Thanks for the additional information :+1:

**Comment by whitecollar17** [comment]
Have the same problem. adding the serie is just fine. Sonnarr selects only the upcoming episode to monitor.
The rest is markt als unwatched

**Comment by tidusjar** [comment]
What version of Sonarr are you guys using?

Since I reported a bug to the Sonarr team where you couldn't unmonitored a series in one of the API calls. They may have fixed this and it may have broken something in my code. 

I should have time to look and fix this in a few hours.

**Comment by fash202** [comment]
Sonarr Ver. 2.0.0.4230 - Have the same issue, click "all seasons" and it adds the series and only monitors for new episodes. Doesn't search for old episodes or monitor any of the old episodes/seasons

**Comment by djs4000** [comment]
I am also using Sonarr Version 2.0.0.4230. Plexrequests.net version 1.9.0 all running on ubuntu 16.04 with Mono 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)

Let me know if I can provide any other info. and thanks for looking in to it.

**Comment by tidusjar** [comment]
Yeah I think you are running a build that they fixed the bug. I should be able to fix this quite easily

**Comment by fash202** [comment]
Lets hope its something simple! If it is any idea when you will be able to update?

**Comment by tidusjar** [comment]
Here is a build with the issue fixed if you want to try and early build:

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.757/artifacts

This will be in the next release if you want to wait (within the next few days, need to wrap up a few more bugs)

**Comment by Grimshad** [comment]
Oh, I posted an issue for this. I'm assuming you merged/deleted mine. Sorry for not checking for duplicates first. That's my bad.

**Comment by tidusjar** [comment]
@Grimshad , thats fine!

**Comment by Foebik** [comment]
So Im having the same issue. Was waiting on the new release instead of the hot fix version posted here. Any idea when it might be release? Or should I just go ahead and work with the hot fix version for now?

Thanks

**Comment by fash202** [comment]
Tested with hot fix, issue seems to be resolved for me! Great work =)

**Comment by tidusjar** [comment]
I'll be releasing either today or tomorrow
