### ISSUE TITLE
Couchpotato Setting Not Saving and unable to connect

### ISSUE THREAD

**Issue by Ralphman21** [tidusjar/PlexRequests.Net#489]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):
System.Net.WebException: Error getting response stream (InitRead): ReceiveFailure ---> System.NullReferenceException: Object reference not set to an instance of an object at System.Net.WebConnection.InitRead (System.Object state) <0x408c59e0 + 0x00098> in :0 --- End of inner exception stack trace --- at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x408ac900 + 0x0019f> in :0 at System.Net.HttpWebRequest.GetResponse () <0x408a2c80 + 0x00053> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x408a2530 + 0x00043> in :0

Exception when calling GetProfiles for CP

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

When in settings, I click on Couchpotato. Enter my Username and password. Click submit. Says saved.
Click Sonarr settings, then back onto Couchpotato Settings. Username is no longer saved, but has reverted back to my PLexrequests username and password. (which is different from Couchpotato)

If I Click Test Connection, it constantly spins, never giving a failed or success indicatrion but will crash after 30-60 seconds.

**Comment by tidusjar** [comment]
Can you send me a picture of your settings? (Blank out any personal information e.g. API key

**Comment by Ralphman21** [comment]
Hey,

Thank you for the response. I have just deleted everything and started fresh. Everything is working now. I'm not sure what I did differently on this install but it is working.

Is there a way I can delete the issue on Github or is that something you do.

**Comment by tidusjar** [comment]
I'll just close it :)

**Comment by Ralphman21** [comment]
Perfect. Thank you
