### ISSUE TITLE
Ability to change Admin password and user.

### ISSUE THREAD

**Issue by WinstonP** [tidusjar/PlexRequests.Net#49]
Title says it all. Or even multiple admins maybe?

**Comment by tidusjar** [comment]
Yeah it's possible!

**Comment by tidusjar** [comment]
All the backend work has been done, Also added the concept of claims, so we now have the ability to add non-user administrators (This will probably be the requesters, it will allow them to set up personal preferences to get notifications etc)

**Comment by tidusjar** [comment]
All finished. Currently we have the ability to change the password. But most of the backend work has been done to allow multiple users and stuff. That will be in a future release.
