### ISSUE TITLE
Safari Search not working

### ISSUE THREAD

**Issue by curlz620** [tidusjar/PlexRequests.Net#491]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps: iOS Safari search does not work. Entering in the movie title does not allow anything to come up. Hitting the Magnifying glass or pressing enter does not work. However, this function works fine on Android Chrome, or Firefox on mobile.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
This might be the same issue as #492

**Comment by curlz620** [comment]
I do not think it is a touchscreen issue since I cannot reproduce it on my Android Phone, Windows Surface Tablet. After work I will take a look on my Wife's iMac and see if its safari on there as well.

**Comment by fash202** [comment]
noticed this issue on my friends iPhone. Also had the problem on a Samsung Galaxy S7 using Dolphin Browser. Works fine on that phone using Chrome browser though.

**Comment by perspellemann** [comment]
I have the same issue. iPhone 6s+ with Chrome works, Safari doesn't.

**Comment by Collisionc** [comment]
This is the same issue as: https://github.com/tidusjar/PlexRequests.Net/issues/403

Some browsers have issues with setTimeout.

**Comment by tidusjar** [comment]
Build if anyone wants to confirm it's fixed: https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.759/artifacts

**Comment by ShepherdDimaloun** [comment]
i tested your build, but a friend of mine have still problems with searching, like above

**Comment by ewascome** [comment]
Tested and confirm that still have searching issues with Safari.  I think it is because of the use of arrow functions in your javascript.

**Comment by tidusjar** [comment]
What difference will that make? It looks to do the same thing?

**Comment by ewascome** [comment]
Safari Browser does not support Arrow Functions.  

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Browser_compatibility

**Comment by tidusjar** [comment]
OH!

**Comment by tidusjar** [comment]
New build with those changes https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by ShepherdDimaloun** [comment]
I can confirm it is working now, as @ewascome says, arrow functions doesnt work in all browsers, Internet Explorer doesnt support arrow functions too.

i noticed a small styling, maybe it is the way it should be but i think there needs to be a small gab between available and the other button.

![img_0030](https://cloud.githubusercontent.com/assets/20789139/18035175/534fadd2-6d50-11e6-96f4-ab14016e7312.PNG)

**Comment by tidusjar** [comment]
@ShepherdDimaloun It might be possible but I am not sure, since I wouldn't really know if you are on a mobile device and also If you have the app installed :disappointed:

**Comment by ShepherdDimaloun** [comment]
@tidusjar with javascript, it is possible to check what device you are using, even jQuery is capable of that.
I have developed a android app and it is possible to open an app with a html anchor element, dont know if plex app accept extra parameters. I dont know how it works for IOS.

**Comment by tidusjar** [comment]
Yeah I understand that I could detect it. But what would happen if the user doesn't have the app installed?

**Comment by ShepherdDimaloun** [comment]
here is the info about app links for Android: https://developer.android.com/training/app-links/index.html
