### ISSUE TITLE
Search button not working on touchscreens

### ISSUE THREAD

**Issue by justinerwin** [tidusjar/PlexRequests.Net#492]
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

When launching PlexRequests from an iPhone/iPad, after typing a term in the search bar, the magnifying glass button has no action after "clicking" it. Clicking and holding pops up the url to open in a new tab, but it does not search for what was typed.

**Comment by tidusjar** [comment]
It should search while typing, it waits 400 milliseconds and if there is no input then it will search, the magnifying glass doesn't do anything I don't think.

**Comment by fash202** [comment]
Mate said he had the same issue on his iphone. Also noticed that no results come up when using dolphin browser on android. Google chrome on the same device works though.

**Comment by tidusjar** [comment]
Ok thanks for the update. I'll see what I can do
