### ISSUE TITLE
UI Not loading fully

### ISSUE THREAD

**Issue by loeschj** [tidusjar/PlexRequests.Net#493]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.0

#### Operating System:
Ubuntu Server 16.04

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:
When i load the plexrequests.net site, it appears that not all of the CSS files are loading as the UI looks a little funky, this is occuring in Chrome, IE and also on Android. It isn't everytime that this occurs, sometimes a force refresh fixes it, other times it does not.
![2016-08-22 22_19_34-plex requests](https://cloud.githubusercontent.com/assets/16830558/17879417/7072877e-68b7-11e6-9fd3-cf2249b17ac9.png)

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
That is exteremly strange. If you are in windows, before you extracted are you sure you unblocked the .zip?

**Comment by loeschj** [comment]
I agree this is strange, and it isn't consistently occurring. I'm on Ubuntu Server, I ran unzip then copied the files from my tmp dir to the final location, permissions are good on all dir, sub dir and files

Sonetimes when it loads, works fine, others...I get the above

**Comment by tidusjar** [comment]
When this happens,  can you open the development tools in the browser (F12) and check the network tab, you should see all the .css files loading there, I suspect that some of them might be red (failed to load). If that is true can you click on it and post some screenshots of the results it shows you (when you click on it , it will have other tabs like response etc. )

**Comment by loeschj** [comment]
Will do, I also want to add that this us occurring on both direct IP:Port access as well as a reverseProxy SSL, I even changes it to become a non SSL reverseProxy and it still occurs.

**Comment by loeschj** [comment]
This error just came up, even though the UI loaded fine after the second force refresh.
![boostrapdatetimepicker](https://cloud.githubusercontent.com/assets/16830558/17897864/520f9e66-691b-11e6-91f4-c81c33fae589.png)

**Comment by tidusjar** [comment]
Interesting, that's a 3rd part library, but we only actually need that on one of the admin pages.
