### ISSUE TITLE
[Request] Create Users, or Use PIN to login

### ISSUE THREAD

**Issue by fash202** [tidusjar/PlexRequests.Net#494]
Im Trying to set it up so that the users have to login to make requests. The issue is I have a couple members in "My Home" as Managed Users. They dont have a password, But I can set a 4-digit pin for them.

Is there anyway to allow users to Auth. with the account and pin? and if not, can we get the option to create login accounts through the app.

**Comment by tidusjar** [comment]
The next thing I'll be working on is the ability to create local users. So that will solve your current issue
