### ISSUE TITLE
After upgrade, refusing to start

### ISSUE THREAD

**Issue by fcisler** [tidusjar/PlexRequests.Net#495]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.0

#### Operating System:
Windows 10 64 bit

#### Applicable Logs (from `/logs/` directory or the Admin page):

2016/08/23 09:49:12.998 PlexRequests.UI.Program Trace: Getting product version
2016/08/23 09:49:12.998 PlexRequests.UI.Program Info: Version: 1.9.0
2016/08/23 09:49:13.013 PlexRequests.Store.DbConfiguration Trace: Checking DB

#### Reproduction Steps:
I've given it several minutes to start. It never gets further then this. Normally run it via NSSM, but after upgrades I run first via administrator command prompt.

Removing plexrequests.sqlite allows the program to start . Why are these files 9 GB, with the journal file 4+ GB? This seems quite crazy to me.

**Comment by tidusjar** [comment]
There was a problem previously where the db kept growing due to the log level being set to Trace. This was fixed and I added in code to compress the db and you should expect it to be under 500kb

**Comment by tidusjar** [comment]
I think it was probably due to the new version attempting to clean up your database but because of the size it was taking a long time.
