### ISSUE TITLE
Plex Requests not connecting to SickRage or CouchPotato

### ISSUE THREAD

**Issue by Electronickss** [tidusjar/PlexRequests.Net#498]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page): 

See later comment

#### Reproduction Steps: Try to connect to providers

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Hi!
This is usually down to Plex Requests not being able to find the correct endpoint (settings incorrect). If you are beind a reverse proxy or have a base URL set in couchpotato you need to set it.

**Comment by Electronickss** [comment]
I do not have a reverse proxy nor am I using hostnames. Just IP's for now and I cannot seem to get that to work. I have added screenshots of the configurations and the respective application. I am hoping this is a layer 8 issue.

http://imgur.com/a/W2GKM

**Comment by Electronickss** [comment]
Logs moved to a seperate comment
http://pastebin.com/VzLU2QE7

**Comment by tidusjar** [comment]
Remove the base URL. That is only for reverse proxies.

**Comment by Electronickss** [comment]
Updated the screenshot album. Still seeing an issue with both after removing the url

**Comment by Electronickss** [comment]
Update: I figured out my couchpotato problem. Request api key was not working for me (the undefined error) and by manually grabbing it and entering it, I was able to connect it. Still haven't solved my SickRage issue yet though

**Comment by tidusjar** [comment]
Sorry for the late reply, What are your sickrage settings? Can you send a screenshot? (Blank out your api key etc)

**Comment by Electronickss** [comment]
I just figured out this morning, that without submitting my settings, that my api key was old and behind when I tried to test it. So saving the settings with the updated key then testing it later worked for me
