### ISSUE TITLE
Request new seasons/episodes for show that already exists in Plex

### ISSUE THREAD

**Issue by captainnapalm** [tidusjar/PlexRequests.Net#500]
Was very excited that users would be able to request additional seasons of a show, but found that if the show already exists in Plex, the user is unable to request additional seasons. For example, I have seasons 3 and 4 of a show, but a user wants season 1 and/or 2. When attempting to request the first season of the show, the user is told the show already exists in Plex.

Is there a way to determine, even if the show already exists in Plex, that not all seasons are available, and the user can then request those missing seasons?

**Comment by tidusjar** [comment]
I think this is a duplicate of #475 Can you confirm?

**Comment by captainnapalm** [comment]
Yes, it is. Sorry, thought I had searched thoroughly.

**Comment by tidusjar** [comment]
That's fine! I'll be looking at that bug later today
