### ISSUE TITLE
Autostart on OSX

### ISSUE THREAD

**Issue by iamhaller** [tidusjar/PlexRequests.Net#501]
Could somebody explain me how I should make plexrequest.net autostart on a mac?
I've tried creating a plist and loading that but that seems to fail. 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false />
    </dict>
    <key>Label</key>
    <string>plexrequests.job</string>
    <key>ProgramArguments</key>
    <array>
      <string>mono</string>
     
      <string>path to plexrequests.exe</string>
    </array>
    <key>RunAtLoad</key>
    <true />
    <key>AbandonProcessGroup</key>
    <true />
  </dict>
</plist>
```

**Comment by kamikasky** [comment]
#### Autostart on the Mac
1. Create a file called `net.tidusjar.plexrequests.plist` in your `~/Library/LaunchAgents` directory with the following content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<dict>
		<key>SuccessfulExit</key>
		<false/>
	</dict>
	<key>Label</key>
	<string>PlexRequests</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/mono</string>
		<string>PlexRequests.exe</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>WorkingDirectory</key>
	<string>/Users/kamikasky/Documents/PlexRequests/Release</string>
</dict>
</plist>
```
2. Open up Terminal and run `which mono` to get the absolute path of the mono executable. Make sure line 14 matches in the plist file.
3. Change line 20 to the absolute path of your PlexRequests folder.
4. In Terminal:
	
	To enable the daemon: `launchctl load ~/Library/LaunchAgents/net.tidusjar.plexrequests.plist`
	
	To disable the daemon: `launchctl unload ~/Library/LaunchAgents/net.tidusjar.plexrequests.plist`
5. Enjoy! This will automatically start PlexRequests when you login.

Alternatively, save the plist in `/Library/LaunchAgents` using administrative access and run the launchd commands with `sudo` as the prefix. Make sure your working directory is freely accessable by the root user. This should make the daemon start on machine boot without waiting the user to login.

**Comment by tidusjar** [comment]
Thanks for that @kamikasky !

**Comment by iamhaller** [comment]
Thank you! @kamikasky

**Comment by tidusjar** [comment]
Can someone add this into the wiki?

**Comment by kamikasky** [comment]
I have added some instructions to the wiki: https://github.com/tidusjar/PlexRequests.Net/wiki/Installing-on-Mac-OS-X

**Comment by tidusjar** [comment]
Thanks!

**Comment by ovq** [comment]
Oddly, the [Wiki Link](https://github.com/tidusjar/PlexRequests.Net/wiki/Installing-on-Mac-OS-X) works, but it's empty....
