### ISSUE TITLE
[BUG] Requesting TV Series with ALL only picks latest season

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/PlexRequests.Net#502]
#### Reproduction Steps:

Request TV Show with ALL seasons
It only picks the latest in sonarr the new TV Show only have monitored on the latest.

Proof:
Plex Request [http://i.imgur.com/pgZj27K.png](url)
Sonarr [http://i.imgur.com/gl11mwg.png](url)
Sonarr [http://i.imgur.com/s0O0uid.png](url)

**Comment by tidusjar** [comment]
Duplicate of #487
