### ISSUE TITLE
Requesting "All Seasons" on a TV show only requests the latest season

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#506]
I just noticed this when someone requested a rather large TV show (several seasons). The user requested show X, I got into the approvals section and approved it. "Seasons: All" was specified in the request. 

I get into Sonarr, go to the show, and I get that little orange dot next to every season except for the latest that says "Season not monitored"

I've seen it for multiple shows now.

#### Plex Requests.Net Version:
1.9.0

#### Operating System:
Ubuntu Server 15.10

#### Mono Version:
4.2.3

**Comment by tidusjar** [comment]
It has been fixed in the latest dev build. 
#487 

I'll push out a release this weekend
