### ISSUE TITLE
Upgrading to newest version unstable.

### ISSUE THREAD

**Issue by bear269** [tidusjar/PlexRequests.Net#508]
I recently installed the latest version of plexrequests, I started noticing my computer behaving strange turned out plexrequests was writing bak files that completely filled my ssd, creating over 7000 files
I had to turnoff the windows service plexrequests.net to stop the duplicate files being created every second

If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
What's your backup settings set to in the scheduled settings page?

**Comment by bear269** [comment]
I fixed it sorry, I checked services and had installed the service plexrequest, plexrequests and plexrequest.net.  I deleted all the services using nssm, confirmed they were all deleted in task manager services and reinstalled only one instance.

Sorry for the headaches

**Comment by bear269** [comment]
Thanks for the support I donated a couple bucks to your paypal

**Comment by tidusjar** [comment]
Haha not a problem. Much appreciated!
