### ISSUE TITLE
Sonarr Invalid Path, Invalid Path

### ISSUE THREAD

**Issue by DanAFC** [tidusjar/PlexRequests.Net#510]
#### Applicable Logs (from `/logs/` directory or the Admin page):
Invalid Path	PlexRequests.Api.SonarrApi

Invalid Path	PlexRequests.Api.SonarrApi

Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'PlexRequests.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at PlexRequests.Api.ApiRequest.ExecuteJson[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 123 at PlexRequests.Api.SonarrApi.<>c__DisplayClass7_1.b__2() in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 124 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at PlexRequests.Api.SonarrApi.AddSeries(Int32 tvdbId, String title, Int32 qualityId, Boolean seasonFolders, String rootPath, Int32 seasonCount, Int32[] seasons, String apiKey, Uri baseUrl, Boolean monitor, Boolean searchForMissingEpisodes) in C:\projects\requestplex\PlexRequests.Api\SonarrApi.cs:line 124

#### Reproduction Steps:

Requesting a new TV Show causes an Error stating 'Invalid path, Invalid path'

**Comment by tidusjar** [comment]
Can you please take a screenshot of your Sonarr settings?

**Comment by DanAFC** [comment]
Sure! Any part of the settings in particular?

**Comment by tidusjar** [comment]
Just the whole Sonarr settings (blank out your api key)

**Comment by DanAFC** [comment]
Thanks for taking a look. Much appreciated.
<img width="790" alt="screen shot 2016-08-30 at 19 00 42" src="https://cloud.githubusercontent.com/assets/2823499/18100773/2603201c-6ee4-11e6-8118-abb45598423c.png">

**Comment by tidusjar** [comment]
Sorry I meant the sonarr settings in Plex Requests! :)

**Comment by DanAFC** [comment]
<img width="558" alt="screen shot 2016-08-31 at 23 12 39" src="https://cloud.githubusercontent.com/assets/2823499/18148284/8d213bb6-6fd0-11e6-9dd7-4ebf1c64905f.png">

**Comment by tidusjar** [comment]
Is your "Root save directory for TV shows" correct?

**Comment by DanAFC** [comment]
I have multiple drives that I store Sonarr content on. Does this cater for
that or do I need to choose one drive only?

**Comment by tidusjar** [comment]
I guess you have a different drive per profile? We currently don't support that. It has been requested before

**Comment by DanAFC** [comment]
I have content spread across 3 drives. So some shows on drive X, some on
drive Y, some on drive Z.

**Comment by tidusjar** [comment]
Currently we do not support that setup. But are your shows on different drives using different Sonarr profiles? 

I am looking to add that functionality soon

**Comment by DanAFC** [comment]
Ah, ok thanks for the info!

No, when I fill a drive I just add another and point Sonarr to it. So each
drive would have a mix of profiles but show N will only be on drive X and
not on Y or Z.

**Comment by tidusjar** [comment]
Oh that's confusing, so it should work, just the that Root save directory for TV shows as the new drive?

**Comment by DanAFC** [comment]
I'll give that a shot this evening. Thanks so much for your help. Much
appreciated.

**Comment by DanAFC** [comment]
Adding a path for root save directory solved this. Thanks again. Keep it up!
