### ISSUE TITLE
Update script for Linux...

### ISSUE THREAD

**Issue by delphiactual** [tidusjar/PlexRequests.Net#512]
Below is a shell script written for linux that will auto-update your version of PlexRequests, the only required parameter is the version number.
Usage:

update_pr.sh 1.9.1

would upgrade plexrequests to version 1.9.1 automatically as long as the directories below are correct
Remember to chmod +x update_pr.sh

`update_pr.sh`
#!/bin/dash
if [ "$1" = "" ]
then
  echo "Usage: $0 <version number>"
  exit
fi
wget https://github.com/tidusjar/PlexRequests.Net/releases/download/v$1/PlexRequests.zip
sudo systemctl stop plexrequests.service
sudo unzip -o PlexRequests.zip -d /opt/PlexRequests
sudo systemctl start plexrequests.service
rm -f PlexRequests.zip

**Comment by tidusjar** [comment]
Can you add this as a new section on the wiki? 

Thanks!

**Comment by delphiactual** [comment]
Sure thing

**Comment by delphiactual** [comment]
Closed with [wiki]( https://github.com/tidusjar/PlexRequests.Net/wiki/Update-Script-for-Systemd) entry
