### ISSUE TITLE
Problem updating from 1.8.4 to 1.9.1

### ISSUE THREAD

**Issue by csy7550** [tidusjar/PlexRequests.Net#513]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

1.8.4 & 1.9.1

#### Operating System:

Windows 8.1 Pro

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

No matter what I do I get the new initial wizard after I update even though this should not affect old users?

**Comment by csy7550** [comment]
Solved!

1.8.4 -> 1.9.1 Does not work.

1.8.4 -> 1.9.0 -> 1.9.1 Works.

**Comment by tidusjar** [comment]
That would be to the migration code!
