### ISSUE TITLE
Requesting single episode not working

### ISSUE THREAD

**Issue by jrneulight** [tidusjar/PlexRequests.Net#514]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.1

#### Operating System:
Docker on unRAID (rogueosb)

#### Mono Version:
Not sure...using docker

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
{ "addOptions": { "ignoreEpisodesWithFiles": true, "ignoreEpisodesWithoutFiles": true, "searchForMissingEpisodes": false }, "title": "New Girl", "seasons": [], "rootFolderPath": "/tv", "qualityProfileId": 1, "seasonFolder": true, "monitored": false, "tvdbId": 248682, "tvRageId": 0, "cleanTitle": null, "imdbId": null, "titleSlug": "New Girl", "id": 0, "images": [] }	PlexRequests.Api.SonarrApi	Debug	8/30/2016 11:21:37 AM
Sonarr API Options:	PlexRequests.Api.SonarrApi	Debug	8/30/2016 11:21:37 AM
Seasons = [], out of 0 seasons	PlexRequests.Api.SonarrApi	Debug	8/30/2016 11:21:36 AM
Adding series New Girl	PlexRequests.Api.SonarrApi	Debug	8/30/2016 11:21:36 AM
```

#### Reproduction Steps:

When adding a show to PlexRequests by episode, they do not download. After checking Sonarr, the episodes that I requested have not been monitored or searched for. The latest season is monitored, even though I did not tell PlexRequests to do that. I am just looking to request a few specific episodes.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Did the series already exist in Sonarr before?

**Comment by tidusjar** [comment]
Just walked through the code and I cannot see anything that would cause this.

From your response it looks like the series did not exist before and we added it and set the monitored flag as false : ` "monitored": false`

Can you tell me what episodes were selected in what season to see if I can reproduce this issue?

**Comment by jrneulight** [comment]
The series did not already exist in Sonarr. I've tested it with multiple shows and episodes and all have caused the problem.

**Comment by tidusjar** [comment]
OK i'll take another look more indepth. What version of Sonarr are you running?

**Comment by jrneulight** [comment]
I'm on version 2.0.0.4230

**Comment by jrneulight** [comment]
So I've had a small revelation, If I add the season manually to Sonarr first with monitor set to "None", and then request the episode on PlexRequests, it monitors and downloads it. If I just add a new series to plex requests by selecting specific episodes, they do not get monitored or downloaded.

**Comment by tidusjar** [comment]
Thanks, that will probably narrow the issue down

**Comment by Ruvetuve** [comment]
Quick issue hijack, sry. Is it already possible to request a single episode with sonarr disabled?

**Comment by tidusjar** [comment]
Not currently but you can raise a feature request if you want.

**Comment by jrneulight** [comment]
Might have some more info to help. It seems that the entire series is not being monitored in Sonarr which means that it will not allow any episodes or seasons to be monitored. Just from glimpsing over the code, it could be around line 86 of SonarrApi.cs
![bug screenshot](https://cloud.githubusercontent.com/assets/3819404/18261909/ccbe4298-73ca-11e6-9f3c-b5f5e1405a75.png)

**Comment by tidusjar** [comment]
Thanks, there are unfortunately two different ways to monitor a series (Due to there is a bug in one of the Sonarr versions and I cannot tell who is using what version).

I should have some time to look at this later today.

**Comment by tidusjar** [comment]
Can you test this?

https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by jrneulight** [comment]
I've tested it and it seems like the series is being monitored properly now, but the episodes that I requested are still not being monitored or downloaded.

**Comment by jrneulight** [comment]
One more question, as I am using docker to test this (my only reliable platform). Should I expect the version number to change on the Admin/Status page when using a Dev build. Although I set Dev=1 in Docker, the version number does not change in the admin panel.

**Comment by tidusjar** [comment]
@jrneulight Thanks for the feedback, so episodes that you request using the episode checkboxes are not being monitored or being downloaded? For an existing or new series?

And I haven't changed the internal build number so currently it will be the same number.

**Comment by jrneulight** [comment]
I tried to download an episode from a non existent series and the series was now being monitored, but the episode was not monitored or downloaded.

**Comment by jrneulight** [comment]
So I've done a little more testing and digging with the Sonarr API. I've updated to the latest version today (2.0.0.4323), and found that the episode searches being send from PlexRequests were empty for a non-existing series. This is a snippet from the log: `{ "name": "EpisodeSearch", "body": { "episodeIds": [], "sendUpdatesToClient": true, "updateScheduledTask": true, "completionMessage": "Completed", "name": "EpisodeSearch", "trigger": "manual" }, "priority": "normal", "status": "queued", "queued": "2016-09-12T19:36:53.067982Z", "trigger": "manual", "state": "queued", "manual": true, "startedOn": "2016-09-12T19:36:53.067982Z", "sendUpdatesToClient": true, "updateScheduledTask": true, "id": 41216 }	PlexRequests.Api.ApiRequest	Trace	9/12/2016 12:36:53 PM`

The episodes are still not being monitored properly either, but on the latest version of Sonarr, that should not matter. Is it possible that the array of requested episodes is being lost somewhere in the code?

**Comment by tidusjar** [comment]
Hmmm. The episode ids should be passed in for the episodes you want to monitor (this was an episode request right?)

**Comment by jrneulight** [comment]
Yes, an episode request

**Comment by tidusjar** [comment]
Can you try this build please?

https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by jrneulight** [comment]
Hey! The magic fix! The episode is now being monitored and downloaded.

**Comment by tidusjar** [comment]
Excellent! I knew what I did wrong and felt like slapping myself.

**Comment by CallMeRev** [comment]
sorry to bump into a old closed issue , but i seem to have the exact same issue. i cant request a new episode of a series that hasnt been added before and i can on the already added .

**Comment by 2fst4u** [comment]
Another two year old bump but I still get this issue. Just tried requesting a single episode of a show that didn't exist in Sonarr and it didn't monitor it.

**Comment by tidusjar** [comment]
This is a closed issue, please open a new one.
