### ISSUE TITLE
Availability for TV Shows showing available when they are not.

### ISSUE THREAD

**Issue by Spydie88** [tidusjar/PlexRequests.Net#516]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.1

#### Operating System:
Windows 10

#### Mono Version:
I don't know

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Not sure how to reproduce this... 
Even when the Episode Catcher doesn't run it resets... I change them to unavailable, close the browser, go back to PR.net and it's back to Available.
I had transferred PR.net to another machine and it started happening. This afternoon I switched PR.net back to the server machine with PLEX on it and it is still happening...

**Comment by tidusjar** [comment]
Note: Request was made via "latest episodes"

**Comment by tidusjar** [comment]
I cannot reproduce this. No matter what I add, it's always unavailable unless it can find it on the server

**Comment by tidusjar** [comment]
Any more info @Spydie88 ?

**Comment by Spydie88** [comment]
It keeps doing it to me, no matter what. if it is in Sonarr it shows as available... even if it is not downloaded. When it's not in any of my libraries on my PLEX server.

**Comment by tidusjar** [comment]
So what if it is not on Sonarr? Does Sonarr think it has a file for it?

**Comment by HamilcarH** [comment]
I that issue as well, even when the show is not on sonarr

**Comment by tidusjar** [comment]
Is this issue still present?

**Comment by HamilcarH** [comment]
Seems fixed to me.

**Comment by SuperPotatoMen** [comment]
Fixed
