### ISSUE TITLE
Plex Availability Cacher Failing

### ISSUE THREAD

**Issue by taytortots** [tidusjar/PlexRequests.Net#517]
I am currently having an issue with the Plex Availability Cacher failing. It runs every 10 minutes and fails every time. I receive the below message in my logs (set to Warn) every 10 minutes because of that, too. Movies that have successfully downloaded and are added to Plex will not have their availability status updated on Plex Requests as a result of the failing scheduled job.

#### Plex Requests.Net Version:

1.9.1 (occurred on 1.9.0, too)

#### Operating System:

Ubuntu 16.04.1 LTS

#### Mono Version:

4.4.2

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
System.NullReferenceException: Object reference not set to an instance of an object at PlexRequests.Services.Jobs.PlexAvailabilityChecker.GetMovie (PlexRequests.Services.Models.PlexMovie[] plexMovies, System.String title, System.String year, System.String providerId) <0x40a6b600 + 0x00137> in :0 at PlexRequests.Services.Jobs.PlexAvailabilityChecker.IsMovieAvailable (PlexRequests.Services.Models.PlexMovie[] plexMovies, System.String title, System.String year, System.String providerId) <0x40a6b5c0 + 0x00023> in :0 at PlexRequests.Services.Jobs.PlexAvailabilityChecker.CheckAndUpdateAll () <0x4150a1b0 + 0x005df> in :0 at PlexRequests.Services.Jobs.PlexAvailabilityChecker.Execute (IJobExecutionContext context) <0x41509cf0 + 0x0001f> in :0
```

#### Reproduction Steps:

Issue has been occurring for the past few days. No changes to the configuration have been made for weeks other than updating to 1.9.1, but the issue was occurring before that, too.

PlexRequests is being run by a user with full permissions and ownership of the installation directory, so it's not a permission issue. Connections between Plex and CouchPotato return successfully.

**Comment by tidusjar** [comment]
Interesting, seems to be a bug in the Plex Availability checker.

I'll try and find out what is causing it.

**Comment by taytortots** [comment]
Sweet, let me know if you need anything else from me. Thanks!

**Comment by taytortots** [comment]
Wanted to provide an update on this. I changed my log level from Error to Fatal and cleared logs. After this, the Plex Availability checker started running as scheduled. I changed my log level back to Error and it's still working now.

I few days ago while I was having the issue but before I reported it, I cleared logs, but left the level at Error, so I'm somewhat confident in saying that clearing the logs wasn't what resolved the issue. It seems that simply changing the log level to Fatal and then back to Error resolved it?

I'm going to continue to monitor it to see if it starts to fail again, but it's run half a dozen times successfully today.

**Comment by tidusjar** [comment]
@taytortots any update?

**Comment by taytortots** [comment]
@tidusjar haven't had any issues with it running since my last post. Just checked now and it last ran a few minutes ago. Still not really not sure what would have changed to resolve it, though. I'd be half tempted to rollback to a previous checkpoint and investigate some more if I hadn't deleted them.
