### ISSUE TITLE
Update with out having to remove/reinstall?

### ISSUE THREAD

**Issue by camrun91** [tidusjar/PlexRequests.Net#524]
I am running this on Freebsd/Freenas. It works great the only issue is everytime there is an update I can't seem to get an update to take with out completely removing and reinstalling the application. This makes it so that I have to reset up the application and loose all past requests data. Is there a way to update that I am missing?

**Comment by delphiactual** [comment]
Did you see this in the Wiki(https://github.com/tidusjar/PlexRequests.Net/wiki/Update-Script-for-Systemd). I don't know what system (upstart, systemd) Freenas uses but you should be able to modify this script to work for you.

**Comment by taytortots** [comment]
Alternatively, you could always just make a backup of the SQLite database PlexRequests creates, wipe the install location, re-install with the new version, and then move the database back before starting the application.
