### ISSUE TITLE
[Feature] Add API endpoint with version information

### ISSUE THREAD

**Issue by Electronickss** [tidusjar/PlexRequests.Net#529]
Feature Request. Leave the update version number somewhere in a log file. I would like to add to the shell script that allowed for updating to be scheduled by cron so that my system can update automatically

**Comment by tidusjar** [comment]
Hmmm... Seems a bit messy. I can provide an Web API endpoint with that infomation?

**Comment by Electronickss** [comment]
That would probably be better

**Comment by tidusjar** [comment]
Added, waiting for release
Usage:
http://localhost:5379/api/version?apikey=**APIKEY**

You can find your API key in the settings
