### ISSUE TITLE
[Request] Auto Delete of Logs

### ISSUE THREAD

**Issue by Foebik** [tidusjar/PlexRequests.Net#530]
I was wondering if it would be possible to have a variable based on age or size of the logs, when meet will auto delete? I just cleared out 8.4GB of logs. It would be nice if there was some auto house keeping of these logs.

**Comment by tidusjar** [comment]
There is a schedule that will delete logs, it will only keep 7 days worth IIRC.

Please make sure your log level is set to `Error`. This will prevent your logs from getting filled up with useless information

**Comment by Foebik** [comment]
Understood, changes made (was on default from install). Will see how it works out. - Thanks
