### ISSUE TITLE
[FEATURE] Add donate button for non-admin users

### ISSUE THREAD

**Issue by tijmenvn** [tidusjar/PlexRequests.Net#533]
Love your work man! 

My request is to integrate an optional donate button which the admin can turn on or off for the regular users. I have a very large server and equally large userbase. And many of my users want to give something back once in a while. And if I just could redirect them to the donate button on the site with my own paypal.me adress, that would be great.

**Comment by tidusjar** [comment]
So a donate button for your users for your address?

Makes sense.

Thanks 😄

**Comment by ProtoJazz** [comment]
Ill try to get this in tonight.
