### ISSUE TITLE
1.8.4 - 1.9.1 Upgrade Issue

### ISSUE THREAD

**Issue by bjay1404** [tidusjar/PlexRequests.Net#534]
I upgrade from 1.8.4 to 1.9.1 and it looks like there is a reverse proxy issue. Note that I am hitting the requests url directly to rule that out. I copied the Sql lite file back in. Essentially - I did a clean install, then copied the file from 1.8.4 - Could somebody please help? 

#### Plex Requests.Net Version:
1.9.1

#### Operating System:
Ubuntu 16.04

#### Mono Version:

Mono JIT compiler version 4.4.2 (Stable 4.4.2.11/f72fe45 Fri Jul 29 09:58:49 UTC 2016)

#### Applicable Logs (from `/logs/` directory or the Admin page):

I can post the logs - but what do I scrub? 

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Can you upgrade to 1.9.0, run it, then upgrade to 1.9.1.

The issue is that the DB needs to be migrated, and I messed up the migration a tiny bit so need to go:

1.8.4 > 1.9.0 > 1.9.1

**Comment by bjay1404** [comment]
I think that worked!

**Comment by bjay1404** [comment]
Does this look okay?


DAEMON_NAME="PlexRequests.net"
DAEMON_USER=abc
DAEMON_PATH="/usr/bin/mono"
DAEMON_OPTS="PlexRequests.exe"
DAEMON_PWD="/opt/PlexRequests"
DAEMON_DESC=$(get_lsb_header_val $0 "Short-Description")
DAEMON_PID="/var/run/${DAEMON_NAME}.pid"
DAEMON_NICE=0
DAEMON_LOG='/var/log/plexrequests.net.log'

**Comment by tidusjar** [comment]
I have no idea mate, have you looked for the FAQ? Some people have put startup scripts in the FAQ
