### ISSUE TITLE
Unable to start service on Windows 10

### ISSUE THREAD

**Issue by BermudaLamb** [tidusjar/PlexRequests.Net#538]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

Latest version from GitHub

#### Operating System:

Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

No logs directory created
```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Run a command prompt as an Administrator

Install the PlexRequests.Net system service

nssm install PlexRequests.net "C:\PlexRequests.net\PlexRequests.exe
You will see this output incidating it installed correctly

Service "PlexRequests.net" installed successfully!
Set the home directory for the PlexRequests folder to the installation directory

nssm set PlexRequests.net AppDirectory "C:\PlexRequests.net"
You should see that it was set successfully

Set parameter "AppDirectory" for service "PlexRequests.net".
Now set the PlexRequests.net Windows system service to autostart on boot

nssm set PlexRequests.net Start SERVICE_AUTO_START
And that’s it, PlexRequests.net will autostart on Windows now

Set parameter "Start" for service "PlexRequests.net".
You can start the PlexRequests.net system service with this command if you don’t want to reboot.

nssm start PlexRequests.net
PlexRequests.net: Unexpected status SERVICE_STOPPED in response to START control.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
What happens when you manually run the .exe?

**Comment by BermudaLamb** [comment]
Starting Up! Please wait, this can usually take a few seconds.
Version: 1.9.1
Location of the database: C:\Program Files (x86)\PlexRequests\PlexRequests.sqlite
no configuration section <common/logging> found - suppressing logging output
Plex Requests is running on the following: http://+:3579/
All setup, Plex Requests is now ready!
Press any key to exit

---

I can open the browser page and go through the configuration process.  However, I don't see it showing up in the Channels. How do my friends use this?

**Comment by tidusjar** [comment]
This is not for use in the Plex Channels, for your friends to use this you need to open the website up on the firewall for them to access it.
