### ISSUE TITLE
Have port forwarded in router, unable to access via external ip:port

### ISSUE THREAD

**Issue by rrbailey89** [tidusjar/PlexRequests.Net#540]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

1.91
#### Operating System:
Windows

#### Reproduction Steps:

I have recently installed this app. I am trying to get it so that It can be accessed by family outside of my netowork. So it needs to function from my external IP. I have the port forwarded in my firewall and router and have restarted the app a few times and tried to access it again. I have no luck with this. I think its an issue with the app as I can access other applications from my external IP useing IP:PORT but not this one. I do not receive any error message on the page at all. This makes me think that it does not start on 0.0.0.0:PORT by default.

**Comment by rrbailey89** [comment]
Im dumb.. windows firewall was blocking me for some reason..

**Comment by tidusjar** [comment]
Please take a look at the FAQ, there is a section covering it :)
