### ISSUE TITLE
TV Shows .. no available tag?

### ISSUE THREAD

**Issue by rrbailey89** [tidusjar/PlexRequests.Net#542]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.1

#### Operating System:
Win 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

No televesion show, complete or not seems to have the "Available Tag" only the Issues button seems to show up.

**Comment by whitecollar17** [comment]
Double:

https://github.com/tidusjar/PlexRequests.Net/issues/528
