### ISSUE TITLE
override the machine identifier

### ISSUE THREAD

**Issue by DereckR** [tidusjar/PlexRequests.Net#544]
#### Reproduction Steps: None just click the links

Hello,

The view in Plex is not working it is calling the wrong "ID". There was a similar program I used plex email that had a feature like this and was pulling same way that would get the wrong ID. He had to re write where he gathered it from. Might want to check this out.

Plex Email Link:

https://github.com/jakewaldron/PlexEmail/issues/35

Thanks,
Dereck

**Comment by tidusjar** [comment]
Oh really? This is the "View In Plex button"?

**Comment by DereckR** [comment]
Yes there was a similar issue I had with plex email that would pull the
wrong server id from a database. Well after I updated and saw the button on
plex request clicked it and it pulls that old id. I had migrated from one
plex to new one afternoon time ago and it keeps that id some where lol.

**Comment by tidusjar** [comment]
Damn... Could I send you a few API endpoints and you return the response on here? Just so I can see what Plex is giving you?

**Comment by DereckR** [comment]
Yes sir I don't mind.

**Comment by DereckR** [comment]
If you enable DLNA server on your plex this will fix the issue.

**Comment by tidusjar** [comment]
Can you please navigate to this:
https://plex.tv/pms/servers.xml

and just replace any personal info with **Retracted** ?

**Comment by tidusjar** [comment]
Any news?

**Comment by ammadz** [comment]
If i may jump in to this thread, I could not get "View in Plex" to work. 
When I click "view in Plex", it connects to plex.tv (https://app.plex.tv/web/app#!/server//details/%2Flibrary%2Fmetadata%2F289) and the message says "You must be lost - this page doesn't exist".
@tidusjar this is what i get when navigate to servers.xml - (MediaContainer friendlyName="myPlex" identifier="com.plexapp.plugins.myplex" machineIdentifier="18f8879e37faad6dd8a93f703d816deb7b3bc68b" size="0")
Thanks

**Comment by tidusjar** [comment]
I think I'm going to add a field to override the machine identifier to resolve that

**Comment by ammadz** [comment]
Brilliant. Will wait for the update then. 
Cheers

**Comment by SuperPotatoMen** [comment]
@ammadz @DereckR will be released in version V1.10.0

**Comment by ammadz** [comment]
Thanks a lot.

**Comment by cardinalfan1** [comment]
Thanks for implementing this feature. I have not been able to get it to work unfortunately. I tried getting my machine identifier from this site: https://plex.tv/pms/servers.xml. When I click on the "View in Plex" button, it takes me to a "You must be lost / This page doesn't exist".

For reference, the URL it is trying to take me to is: https://app.plex.tv/web/app#!/server/c5e18006a738bcc48bfef87e78f2c2d629851904/details/%2Flibrary%2Fmetadata%2F663

I tried changing the %2F to  https://app.plex.tv/web/app#!/server/c5e18006a738bcc48bfef87e78f2c2d629851904/details//library/metadata/663
but this did not help either.

Any suggestions?
