### ISSUE TITLE
Sonarr searches for individual episodes instead of season packs

### ISSUE THREAD

**Issue by jvincent08** [tidusjar/PlexRequests.Net#546]
I'm using Plex Requests.NET version  1.9.2 and Sonarr 2.0.0.4326. When requesting a show in Plex Requests, Sonarr searches for the show's individual episodes instead of season packs and thus fails on trackers that don't keep episodes when the season is over. This must be an error on Plex Requests end because using Sonarr's own interface works fine.

**Comment by tidusjar** [comment]
Correct, there is an issue already raised about this.
https://github.com/tidusjar/PlexRequests.Net/issues/515#issuecomment-248305930

This is the next thing I will be fixing
