### ISSUE TITLE
[FEATURE] deny request after approval with email notification 

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/PlexRequests.Net#551]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

 1.9.2

I have my movie requests set so they are automatically accepted, but sometimes I can't get a particular movie. I want to be able to deny the request after approval with an email notification to the user stating the reason for the denial. At the moment the only option after approval is to remove the request.

**Comment by tidusjar** [comment]
This has been done, forgot to add it to the checkin note.

**Comment by Alosander** [comment]
Is this still available? I can't seem to find a "Deny" button after the request has been approved.
