### ISSUE TITLE
TV Show request incorrectly approved and available

### ISSUE THREAD

**Issue by fenichelar** [tidusjar/PlexRequests.Net#553]
#### Plex Requests.Net Version:
1.9.2

#### Operating System:
Ubuntu 14.04

#### Mono Version:
4.6.0

#### Applicable Logs (from `/logs/` directory or the Admin page):
Nothing was logged at the warn log level so nothing was recorded.

#### Reproduction Steps:
I have the last season of Two and a Half Men in my Plex and Sonarr Libraries. A user requested the first season. The request was approved and marked as available when I looked at the admin interface. I did not approve it, nor is it available. Sonarr also is not monitoring it.

Advanced search - on
Episode searching - off

Other TV Shows requested are working as expected. However, this is the first time I have had a season requested for a show where some season already exist. Is episode searching required for this to work correctly? I keep my Sonarr and Plex libraries exactly the same. I have 3000 episodes of TV shows, is this too much to handle episode searching?

Thanks!

**Comment by tidusjar** [comment]
I think I know what this problem is. I'll take a look into fixing it

**Comment by Unimatrix0** [comment]
I have this problem too.

**Comment by tidusjar** [comment]
Yeah not had time to actually fix it yet. Also @fenichelar I didn't answer your other question.

For episode searching, it depends on resources so if you have a beefy server then you should have no problem. I suggest you turn it on, restart PR.Net and then just wait a few mins and see what happens.

**Comment by fenichelar** [comment]
Thanks!

Is there any reason to enable episode search if I keep my Sonarr and Plex libraries perfectly synchronized?

**Comment by tidusjar** [comment]
It will help recognise Plex episodes when a user requests specific
episodes.
-- 
Thanks,
Jamie

**Comment by Flippage** [comment]
Getting the same issue.

Whether I set "Require approval of TV Show requests" on or off, I request a show, and it immediately becomes "Approved", gets added to Sonarr, but Sonarr doesn't monitor the right episodes.

No matter what I select, it basically always only monitors future episodes of the latest season.

Is there a fix coming soon?

**Comment by tidusjar** [comment]
@Flippage What you are describing is a different issue.

If you are using your admin account to request something it will always get approved straight away (Since you are the admin).

So if you select the first season option in the dropdown it will only monitor future episodes of the latest season? Can you raise a separate issue for this.

**Comment by whitecollar17** [comment]
Fixed in the release of 1.9.4
