### ISSUE TITLE
[BUG] Notification is sent when an item is "Mark Unavailable"

### ISSUE THREAD

**Issue by xtreme22886** [tidusjar/PlexRequests.Net#556]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9.2
#### Operating System:

Ubuntu 16.04.1 LTS
#### Mono Version:

Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Message Area    Log Level   Date
sending message to "X@gmail.com" from: "X@gmail.com" Are we authenticated: True PlexRequests.Services.Notification.EmailMessageNotification Info    9/26/2016 8:46:05 PM
This user is the Plex server owner  PlexRequests.Services.Notification.NotificationEngine   Info    9/26/2016 8:46:05 PM
Notifying user X    PlexRequests.Services.Notification.NotificationEngine   Info    9/26/2016 8:46:05 PM
Notifying Users Count 1 PlexRequests.Services.Notification.NotificationEngine   Debug   9/26/2016 8:46:05 PM
sending message to "X@gmail.com" from: "X@gmail.com" Are we authenticated: True PlexRequests.Services.Notification.EmailMessageNotification Info    9/26/2016 8:45:52 PM
This user is the Plex server owner  PlexRequests.Services.Notification.NotificationEngine   Info    9/26/2016 8:45:51 PM
Notifying user X    PlexRequests.Services.Notification.NotificationEngine   Info    9/26/2016 8:45:51 PM
Notifying Users Count 1 PlexRequests.Services.Notification.NotificationEngine   Debug   9/26/2016 8:45:51 PM
```
#### Reproduction Steps:
1. Have a user with valid email address
2. Have that user configured in PlexRequests.Net to receive notifications
3. Have that user requests something
4. Have the admin mark item as available
5. An email is sent to the requester telling them their item is ready
6. Admin marks the item as not available
7. An email is sent to the requester telling them their item is ready

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by xtreme22886** [comment]
Solution:

1. Have the email text changed to read something along the lings of '<movie> has been removed'.
2. Disable the email being sent when the admin clicks 'Mark Unavailable'...but then people may go looking for their item and it not being there and thinking the alert was a false alert (really it was but user don't know if we disable this email...)

xtreme

**Comment by SuperPotatoMen** [comment]
@xtreme22886 Fixed in the next release
