### ISSUE TITLE
Linking to Plex Functionality

### ISSUE THREAD

**Issue by cardinalfan1** [tidusjar/PlexRequests.Net#559]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Applicable Logs (from `/logs/` directory or the Admin page): N/A

```
Logs go here (Please make sure you remove any personal information from the logs)
```
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

I have two problems, not sure if they're related.
Briefly, I have a remote plex server (i.e. on a different server than my plexrequests server). Let's say its called: myplexserver.abc.com
So in the configuration options, that's what I've put into the Plex configuration settings. When you click "test connectivity", it seems to work fine.
1. When I search for a movie that's already available in my library, it says "Available". But when I click "view in Plex", it connects to plex.tv and the message says

Media not found.

The media you're trying to access doesn't seem to exist.
1. When I search for a TV show that I already have, but not all the episodes are downloaded... It doesn't seem to detect that I already have certain episodes that are downloaded but not others. Particularly, the episodes that are on my sonarr server are selected but the ones that are on my plex server aren't.

There might be a simple solution to all this, but let me know! 
Thanks for all your help

**Comment by cardinalfan1** [comment]
Just found out some more information:
I have two plex servers. It is able to connect to my remote plex server, but when trying to open the video file it tries to find it from the local server. How can I change this behavior? Thanks

**Comment by tidusjar** [comment]
Ok, for your first issue, we currently do not support two servers, I plan to add a overrride to how we get the server information (We user the machine identifier in Plex).

Second issue is that you do not have advanced episode searching enabled. Without this we are unable to see what episodes you have in Plex.
Now please note that if you have a large plex library and you enable episode searching, it potentially could make plex requests slow/unresponsive until it completes scanning the library (It's a very resource intensive task).

**Comment by cardinalfan1** [comment]
Ok cool. I actually do have episode searching enabled, but I guess it's only going to search one of the plex servers. 

I'm glad to hear about the override. I'll (im)patiently await the future update :) I'll close this thread. Thanks

**Comment by tidusjar** [comment]
I'll leave this open so I can do the work (and it's a reminder).

So you are pointing Plex Requests at one of your servers, but the episodes exist on the other server?
Yeah...

People have requested multi plex server support before, i've just not had the time to do it.

**Comment by cardinalfan1** [comment]
Yeah basically on the plex configuration in the admin settings I have plexrequests pointed at a remote plex server, where I would like to get all the information from and redirect to (Currently, plexrequests knows that the item exists on the remote server but isn't able to direct the user to it, or to do episode searching for it).

I also happen to have a local plex server on the same host as plexrequests, and plexrequests seems to try to redirect to that one.

Thanks!

**Comment by cardinalfan1** [comment]
I guess rereading my last comment, not sure if it made a lot of sense. 

Rather than to create a feature to accommodate multiple plex servers, it might be easier just to have the app be able to have all of the functionality it's supposed to with just the server specified in the plex section of the configuration options?

Hopefully that is a little more articulate.

**Comment by SuperPotatoMen** [comment]
machine identifier is ready in the last release (1.10.0)
