### ISSUE TITLE
Could not automatically get the API key : CouchPotato

### ISSUE THREAD

**Issue by Codgedodger** [tidusjar/PlexRequests.Net#561]
#### Applicable Logs (from `/logs/` directory or the Admin page):

"api_key": null, "success": false}	PlexRequests.Api.ApiRequest	Trace	10/1/2016 7:07:26 PM
Api Content Response:	PlexRequests.Api.ApiRequest	Trace	10/1/2016 7:07:26 PM

#### Reproduction Steps:

Go to add CouchPotato under Admin account. Try to get API for CouchPotato and error of Could not automatically get the API key appears. Have re-installed multiple times with same result.

**Comment by DanielsWrath** [comment]
Same issue, on Ubuntu 14.04
