### ISSUE TITLE
[FEATURE]  Turn off switch for season tv show request

### ISSUE THREAD

**Issue by whitecollar17** [tidusjar/PlexRequests.Net#563]
I like to turn of the ability to request a season request or/both episode request
Can you make a option in the admin panel to turn off the dropdown menu so you have the same request button like by the movies?

Reason: i like to have full tv shows on my plex not a part of a tv show :P

**Comment by ProtoJazz** [comment]
Seems like a neat next step for my next project. Ill give it a shot sometime this week

**Comment by tidusjar** [comment]
Nice!

There is some C# involved in this one, requires a new checkbox on the settings (Includes adding a new property into that settings class) and then pass down that settings into the UI (Handlebars)
