### ISSUE TITLE
1.9.3 Not Updating

### ISSUE THREAD

**Issue by jneljeff** [tidusjar/PlexRequests.Net#573]
No matter if I overwrite the directory or delete it entirely and copy the contents of PlexRequests.zip/Release to a new directory, I'm still on 1.9.2.  I'm using the zip from the update page within PlexRequests.

#### Plex Requests.Net Version:
1.9.2/1.9.3

#### Operating System:
Ubuntu Server

**Comment by fenichelar** [comment]
Same. I think the problem is actually that it is displaying the version 1.9.2. It actually is updated to 1.9.3. The recently added email feature is available.

**Comment by tidusjar** [comment]
Redownlod. It was my fault!

**Comment by fenichelar** [comment]
@tidusjar Resolved!

**Comment by jneljeff** [comment]
Fenichelar, that's what I thought, but I didn't see anything about sending recently added emails... I don't want to spam my users testing something that doesn't appear to be there.

**Comment by tidusjar** [comment]
@jneljeff you can test the recently added notification but pressing the button in the settings. It will only go to you.

**Comment by fenichelar** [comment]
@jneljeff @tidusjar Just a heads up. It appears to have sent the email immediately after upgrading.
