### ISSUE TITLE
Extra Space Lines in Recently Added Email

### ISSUE THREAD

**Issue by jneljeff** [tidusjar/PlexRequests.Net#574]
Recently Added email to users has a number of empty breaking spaces at the beginning of each category.  Tried with multiple email clients and accounts.

[http://imageshack.com/a/img924/4684/m9Sv80.png](http://imageshack.com/a/img924/4684/m9Sv80.png)

#### Plex Requests.Net Version:
1.9.3

#### Operating [System:](url)
Ubuntu Server

**Comment by tidusjar** [comment]
Oh wow that's strange! 

Is any content showing? Can you please forward to email to TidusJar@gmail.com

**Comment by jneljeff** [comment]
Sent.  On a side note, Identifying TV shows by their episode would be cool too... but one thing at a time :P

**Comment by tidusjar** [comment]
Yeah I did try to get the episodes and stuff, but I couldn't figure out a way to do it with Plex. I can keep looking though

**Comment by tidusjar** [comment]
Hi @jneljeff Can you please try it on this build?

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.837/artifacts

**Comment by jneljeff** [comment]
The lines under Movies are gone, but i still see a ton under Episodes.

**Comment by tidusjar** [comment]
Cool. Thanks, just wanted to make sure that would fix it. (I only did it for the movies)

So the lines are between each movies now?
