### ISSUE TITLE
Failed to obtain Plex libraries

### ISSUE THREAD

**Issue by wilsonic** [tidusjar/PlexRequests.Net#577]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.3

#### Operating System:
Ubuntu 16.04 Server

#### Mono Version:
4.2.3

#### Applicable Logs (from `/logs/` directory or the Admin page):

Logs go here (Please make sure you remove any personal information from the logs)
`Failed to obtain Plex libraries	PlexRequests.Services.Jobs.PlexAvailabilityChecker	Error	10/10/2016 9:50:31 AM
There has been a API Exception when attempting to get the Plex Libraries	PlexRequests.Api.PlexApi	Error	10/10/2016 9:50:31 AM
System.Net.WebException: The request timed out at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x4103d4d0 + 0x00197> in :0 at System.Net.HttpWebRequest.GetResponse () <0x410367c0 + 0x0005a> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x410363e0 + 0x00043> in :0	PlexRequests.Api.ApiRequest	Error	10/10/2016 9:50:31 AM
Exception when calling GetLibrarySections for Plex, Retrying 00:00:30	PlexRequests.Api.PlexApi	Error	10/10/2016 9:48:21 AM`

#### Reproduction Steps:
Please include any steps to reproduce the issue, this the request that is causing the problem etc.

I'm receiving the above errors when trying to get Library information from plex. I have checked the token, tried SSL on and off. Not sure what else to check. I couldn't see another similar issue when searching. Plex Settings page attached.
![untitled](https://cloud.githubusercontent.com/assets/10792609/19234089/3352c8c8-8f35-11e6-9c6e-62c8b1b8261f.png)

**Comment by tidusjar** [comment]
Can you make sure your Api Token is correct?

Click on an episode/movie and press Get Info, then View XML

In the URL you should see your Plex API key. Can you make sure that matches what's in your settings?

**Comment by wilsonic** [comment]
I get a different token depending on whether I sign in from plex.tv or local ip address. Does that matter?

**Comment by tidusjar** [comment]
Really? which one matches the one in Plex Requests?

**Comment by wilsonic** [comment]
I've tried both but using the local ip address made more sense to me. Neither seem to make a difference though.

**Comment by tidusjar** [comment]
Did you try both and then restart? (A restart is required since the services need the new settings, otherwise you will have to wait for the next scheduled run)

**Comment by wilsonic** [comment]
I'm running it in a docker so I restarted that. Do I need to do a full machine restart?

**Comment by tidusjar** [comment]
Docker restart should be fine. So if you manually specify the API key it still does not work... Did you previously use Plex Requests and this wasn't an issue?

**Comment by wilsonic** [comment]
Yeah still not working. I've been using it for a while but I have a feeling the plex scanning has never worked as occasionally I'll get things requested that I already have in Plex just not in sonarr.

**Comment by tidusjar** [comment]
Well the request is timing out, are you 100% sure Plex Requests can communicate with `10.1.1.1`?

**Comment by wilsonic** [comment]
The 'Test Connectivity' button returns a positive result. I can ping it and download the html from within the docker. Is there a command I can try in console that might simulate the api request?

**Comment by tidusjar** [comment]
Well Plex must be taking a long time to respond back, Can you turn off episode searching and then try again?

**Comment by wilsonic** [comment]
OK I've disabled Episode searching and restarted, I'm not seeing the error appear. Would it show up straight away or do I have to wait for the scheduled runs?

**Comment by tidusjar** [comment]
If you restart it would schedule straight away

**Comment by wilsonic** [comment]
Then it looks like it's fixed. Thanks so much for your quick and helpful responses!
