### ISSUE TITLE
Error sending recently added email

### ISSUE THREAD

**Issue by curlz620** [tidusjar/PlexRequests.Net#578]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
2016/10/10 08:40:38.002 PlexRequests.Api.ApiRequest Error: System.Runtime.Serialization.SerializationException: Invalid JSON string
   at RestSharp.SimpleJson.DeserializeObject(String json)
   at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content)
   at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw) System.Runtime.Serialization.SerializationException: Invalid JSON string
   at RestSharp.SimpleJson.DeserializeObject(String json)
   at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content)
   at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response)
   at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)


#### Reproduction Steps: When I try to send test email of recently added to admin email, i receive an error, however my regular emails are going through just fine.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
Is your Plex settings all upto date and you can connect fine?

**Comment by curlz620** [comment]
Like to my Plex server? Yes I can connect to that.

**Comment by tidusjar** [comment]
I mean the settings in Plex Requests, When you press the test button it works fine?

**Comment by curlz620** [comment]
Nope. It is throwing up an error now. I pulled a debug log of this process for you.

 PlexRequests.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags) at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) --- End of inner exception stack trace --- at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size) at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count) at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.TlsStream.CallProcessAuthentication(Object state) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result) at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size) at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size) at System.Net.ConnectStream.WriteHeaders(Boolean async) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request) --- End of inner exception stack trace --- at PlexRequests.Api.ApiRequest.ExecuteXml[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 103 at PlexRequests.Api.PlexApi.<>c__DisplayClass16_0.b__0() in C:\projects\requestplex\PlexRequests.Api\PlexApi.cs:line 138 at Polly.Policy.<>c__DisplayClass8_0`1.b__0() at Polly.RetrySyntax.<>c__DisplayClass14_0.b__1() at Polly.Retry.RetryEngine.Implementation[TResult](Func`1 action, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory) at Polly.RetrySyntax.<>c__DisplayClass14_1.b__0(Action action, Context context) at Polly.Policy.Execute[TResult](Func`1 action, Context context) at Polly.Policy.Execute[TResult](Func`1 action) at PlexRequests.Api.RetryHandler.Execute[T](Func`1 func, Action`2 action, TimeSpan[] timeSpan) in C:\projects\requestplex\PlexRequests.Api\RetryHandler.cs:line 53 at PlexRequests.Api.PlexApi.GetStatus(String authToken, Uri uri) in C:\projects\requestplex\PlexRequests.Api\PlexApi.cs:line 138 at PlexRequests.UI.Modules.ApplicationTesterModule.PlexTest() in C:\projects\requestplex\PlexRequests.UI\Modules\ApplicationTesterModule.cs:line 161

**Comment by csy7550** [comment]
I'm also getting this message when trying to send recently added test mail to admin.

Plex settings says OK and e-mail settings works.

System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)

**Comment by tidusjar** [comment]
Can you make sure your API Token is correct, 

You can manually view your api token in Plex by clicking `Get Info` on a movie/tv show and then press `View XML`. The token will be at the end of the address bar.

**Comment by csy7550** [comment]
Still the same. Enabled trace in the logging and sent you an email.

**Comment by curlz620** [comment]
My Token is not the same. I requested a new token in Plex Requests admin page, but it came up with an incorrect one.

**Comment by curlz620** [comment]
I disabled SSL and now I am getting a green box with, "Value cannot be null. Parameter name: source" after I attempt to send test admin email.

**Comment by tidusjar** [comment]
I've not had time to look into the logging you sent me yet, is there anything else in the logs for the above error?

**Comment by curlz620** [comment]
No, I cleared them to see. nothing else.

**Comment by curlz620** [comment]
Finally got it to generate a response in the logs. 

System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)	PlexRequests.Api.ApiRequest	Error	10/11/2016 8:40:15 AM

**Comment by RXWatcher1** [comment]
I am also seeing this issue on 1.9.4

I am running this on Ubuntu 16.04 with mono 4.6.1 and am using an apache reverse proxy with a base url of /request

**Comment by tidusjar** [comment]
It's something to do with what Plex is sending back, I have the trace logs that will help solve the issue, just not had time to look at them yet

**Comment by tidusjar** [comment]
Can someone with this problem try this build out?

https://ci.appveyor.com/project/tidusjar/requestplex/build/1.9.857/artifacts

There seems to be an issue either getting the metadata from Plex or getting extra information from TvMaze/TheMovieDb.

I have stopped it failing, if it encounters a problem, it will log and skip that movie/tv and continue.

So can someone try and post the log?

Should say something like:

`Exception when trying to process a TV Show, either in getting the metadata from Plex OR getting the information from TVMaze, Plex GUID = `

**Comment by curlz620** [comment]
I just tested it. Below are the logs from it, I may have hit send twice, wasn't paying much attention. Email came through though and it looks great! 

Exception when trying to process a TV Show, either in getting the metadata from Plex OR getting the information from TVMaze, Plex GUID = com.plexapp.agents.themoviedb://60735?lang=en	PlexRequests.Services.Jobs.RecentlyAdded	Error	10/18/2016 7:28:10 AM

PlexRequests.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw) --- End of inner exception stack trace --- at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 71 at PlexRequests.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\PlexRequests.Api\TvMazeApi.cs:line 87 at PlexRequests.Services.Jobs.RecentlyAdded.GenerateTvHtml(IEnumerable`1 tv, PlexSettings plexSettings, StringBuilder& sb) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 215	PlexRequests.Services.Jobs.RecentlyAdded	Error	10/18/2016 7:28:10 AM

System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)	PlexRequests.Api.ApiRequest	Error	10/18/2016 7:28:10 AM

Exception when trying to process a TV Show, either in getting the metadata from Plex OR getting the information from TVMaze, Plex GUID = com.plexapp.agents.themoviedb://60735?lang=en	PlexRequests.Services.Jobs.RecentlyAdded	Error	10/18/2016 7:27:56 AM

PlexRequests.Helpers.Exceptions.ApiRequestException: Error retrieving response. Check inner details for more info. ---> System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw) --- End of inner exception stack trace --- at PlexRequests.Api.ApiRequest.Execute[T](IRestRequest request, Uri baseUri) in C:\projects\requestplex\PlexRequests.Api\ApiRequest.cs:line 71 at PlexRequests.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\PlexRequests.Api\TvMazeApi.cs:line 87 at PlexRequests.Services.Jobs.RecentlyAdded.GenerateTvHtml(IEnumerable`1 tv, PlexSettings plexSettings, StringBuilder& sb) in C:\projects\requestplex\PlexRequests.Services\Jobs\RecentlyAdded.cs:line 215	PlexRequests.Services.Jobs.RecentlyAdded	Error	10/18/2016 7:27:56 AM

System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject(String json) at RestSharp.Deserializers.JsonDeserializer.FindRoot(String content) at RestSharp.Deserializers.JsonDeserializer.Deserialize[T](IRestResponse response) at RestSharp.RestClient.Deserialize[T](IRestRequest request, IRestResponse raw)	PlexRequests.Api.ApiRequest	Error	10/18/2016 7:27:56 AM

**Comment by tidusjar** [comment]
That helps! Looks like there were 2 movies that was stopping the process for you.

I'll figure out how and why that happened.

**Comment by curlz620** [comment]
Also, on this build when trying to save a setting. i.e. send email to admin or adjust landing page. I keep getting an error screen. It throws up a white page with the following text.

{"result":true,"message":null}

Currently on debug mode in logs and nothing is coming up. Just figured I would let you know.

**Comment by tidusjar** [comment]
OK i'll check that out. Thanks, do you have a base url set?

**Comment by RXWatcher1** [comment]
I haven't been able to find that exemption in the log but the emails are going out. When you do the "Send Test Email to Admin", who is it going to? The "Email Sender" or "Email recipient" as defined in the email  notification page? It's going to the "Email Sender". I have a dedicated gmail setup to send such notifications and it's going to that gmail account.

**Comment by tidusjar** [comment]
You are right, it's going to the Email Sender. I'll fix that. The test email will only go to the admin.

**Comment by curlz620** [comment]
No I do not have a base url, been on my list of things to get around to.

**Comment by tidusjar** [comment]
I found the issue. Looks like it got broken In a PR

**Comment by taytortots** [comment]
@tidusjar Just wanted to note that I have the same issue occurring, too. Logs are nearly identical to what others have reported. Glad you said you found a fix and I look forward to it being released!

**Comment by tidusjar** [comment]
You are welcome to give the dev build a go to make sure it fixes your issue? https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

**Comment by whitecollar17** [comment]
Fixed in the release of 1.9.4

**Comment by gabo77** [comment]
Just want to say I'm getting the "Value cannot be null. Parameter name: source" in a green box in the "Newsletter Settings" section. Email notifications are set, tested and working. I have not set any base URL. Connectivity with Plex is good. I'll provide you with logs if it can help!

**Comment by SuperPotatoMen** [comment]
@gabo77 pleas open a new issue with logs.
