### ISSUE TITLE
Requesting movie already in Plex gives error. 

### ISSUE THREAD

**Issue by WinstonP** [tidusjar/PlexRequests.Net#58]
Searched for a movie already in Plex and got a "Something went wrong" error.

**Comment by tidusjar** [comment]
Can you please post the relevant logs in the install directory

**Comment by WinstonP** [comment]
Sorry, Jamie, Looked in the .log file for "Something went Wrong" but i didn't find any instance of it. Is it safe to post the entire log file here? (Safe as in, there is no api keys/login creds in them)

**Comment by tidusjar** [comment]
No I wouldn't do that. Delete the current log, recreate the error and you should see it? Is all the settings correct e.g it can connect to plex?

**Comment by WinstonP** [comment]
Welp.. I'm an idiot. I had set it up, but only clicked Test Connectivity and not Submit, so my settings for plex connectivity weren't saved. Feel free to delete this...
