### ISSUE TITLE
Send notifications to admin when a new issue is created

### ISSUE THREAD

**Issue by kamikasky** [tidusjar/PlexRequests.Net#583]
I currently haven't found any way to get notifications besides following what requests people make. I allow requests to be added without approval so I don't get those notifications either. I'd like to have an option to send notifications when a new issue is created or when any request is made—regardless of whether I require approval

**Comment by tidusjar** [comment]
When a user makes a request OR raises an issue you should get a notification? Do you have your notifications set up?

**Comment by SuperPotatoMen** [comment]
no answer after 23 days
