### ISSUE TITLE
[Feature Request] Send Recently Added Email Notification based on Users Allowed Ratings

### ISSUE THREAD

**Issue by camwise** [tidusjar/PlexRequests.Net#585]
I love the new feature of sending out the Recently Added Email Notification to users.  However, I don't want all my users to be notified of All uploaded content.  I would rather only send the email out based on an individual's allowed ratings level in Plex.  For example, I share with several Teenagers that in Plex I've only approved for a PG-13 Rating and below.  I'd rather they not even know about the R or TV-MA stuff that is there.  Is this already a thing?  Possible?

**Comment by tidusjar** [comment]
For this I would need to work out what library you are sharing with your users and then this makes the recently added email user specific. For now I am trying to avoid that sort of complication. This maybe a feature in the future.
