### ISSUE TITLE
Poster placeholders

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#588]
Every now and then you run into a movie that doesn't load a poster (tvmaze or tmdb issue?). We should have a placeholder image for these cases.

![image](https://cloud.githubusercontent.com/assets/4528753/19324625/30ae68c6-9088-11e6-8c29-2646f170d2fc.png)

**Comment by whitecollar17** [comment]
This a bug https://github.com/tidusjar/PlexRequests.Net/issues/612
