### ISSUE TITLE
Feature Request: Logs in admin panel

### ISSUE THREAD

**Issue by WinstonP** [tidusjar/PlexRequests.Net#59]
Would be nice to see logs in the admin panel to easily see what errors come up. 

I also noticed that .log files are in the root directory. Would keep down on clutter if they were in a Logs folder. 

Thoughts?

**Comment by tidusjar** [comment]
Both good ideas!

**Comment by tidusjar** [comment]
Logs has been moved into a /logs/ directory. Just need to get it logging to the DB: https://github.com/NLog/NLog/issues/1319

**Comment by tidusjar** [comment]
All done really, we now have a new page in the settings called logs, It will show you the logs and also allow you to set a custom log level.

TODO: Styling and pagination.
