### ISSUE TITLE
Not able to Login and no mobile view via Safari-iPhone BUG

### ISSUE THREAD

**Issue by veritas2884** [tidusjar/PlexRequests.Net#593]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
We are authenticated! Setting session.	PlexRequests.UI.Modules.UserLoginModule	Debug	10/14/2016 4:09:33 AM
Friends list result = True	PlexRequests.UI.Modules.UserLoginModule	Debug	10/14/2016 4:09:33 AM
Correct credentials, checking if the user is account owner or in the friends list	PlexRequests.UI.Modules.UserLoginModule	Debug	10/14/2016 4:09:32 AM
{"user":{"id":722355,"uuid":"1bbf546d4aaab1de","email":"useremail","joined_at":"2013-02-18T21:40:56Z","username":"username","title":"username","thumb":"https://plex.tv/users/1bbf546d4aaab1de/avatar","authToken":"Sps6DwMML8mzepQqeHSy","authentication_token":"Sps6DwMML8mzepQqeHSy","subscription":{"active":false,"status":"Inactive","plan":null,"features":[]},"roles":{"roles":[]},"entitlements":["windows","windows_phone","ios"],"confirmedAt":"2016-08-13T19:20:38Z","forumId":null,"rememberMe":false}}	PlexRequests.Api.ApiRequest	Trace	10/14/2016 4:09:32 AM
Api Content Response:	PlexRequests.Api.ApiRequest	Trace	10/14/2016 4:09:32 AM
Need to auth and also provide pass	PlexRequests.UI.Modules.UserLoginModule	Debug	10/14/2016 4:09:31 AM
Using password	PlexRequests.UI.Modules.UserLoginModule	Debug	10/14/2016 4:09:31 AM
Username "username" attempting to login	PlexRequests.UI.Modules.UserLoginModule	Debug	10/14/2016 4:09:31 AM
```

#### Reproduction Steps:

Cannot login via mobile browser on iOS or Android, also does not show mobile view. Logging in from Desktop works great.

**Comment by veritas2884** [comment]
First, thanks for the hard work and awesome softeare.

Second,Any ideas or work arounds on this? My plex request users almost excursively request new stuff via mobile, so the lack of ability to log in makes this unusable. Which is a shame, because it is a fantastic interface with excellent features. However, I have to keep the original version running because of this show stopping bug.

**Comment by tidusjar** [comment]
Hi,

Thanks!

Now regarding this, I couldn't reproduce it. Could it have been your setup?

**Comment by veritas2884** [comment]
@tidusjar It is back again. I do not know why. But mobile devices are loading the regular page and are unable to log in.  Any ideas what could be causing this. I have tried on Android and iOS with the same result

**Comment by veritas2884** [comment]
@tidusjar Thanks for re-opening this. I sent you an email with a link to the site so you can see the issue in action. Please let me know if I can provide any logs.

**Comment by br3nn** [comment]
Hi, Not sire if this will reopen the case, 

But safari on my iOS device does not login in. It simply reloads the login page without any messages, 

Thought i would mention currently using opera / chrome on ios to login.

**Comment by SuperPotatoMen** [comment]
@br3nn  pleas open a new issue

**Comment by veritas2884** [comment]
@br3nn @SuperPotatoMen My setup was customer domain name with a landing page that allowed the user to get redirected to PlexRequests or PlexPY. The issue I was having is that I was masking the URL with domain name I was using to redirect. Once I took off the masking and just exposed the IP:PORT the login issue went way and the mobile version appeared on mobile devices. My guess is that the domain masking was somehow interfering with Plexrequest's ability to detect it was a mobile browser, but I'm not a doctor.

**Comment by SuperPotatoMen** [comment]
@veritas2884 maybe a header problem in you're proxy setup?

**Comment by veritas2884** [comment]
@SuperPotatoMen I don't know that much about HTML. I have a godaddy domain and there is an option to turn masking on or off. If I have have it on, it breaks mobile compatibility and mobile login ability. When I switch it off, everything works. I have also tried killed the landing page and just having the domain redirect directly to plexrequests. Same issue presents.

**Comment by br3nn** [comment]
Before i got chance to read this, i removed my masking, and bang on it working a treat
