### ISSUE TITLE
Cannot login into admin

### ISSUE THREAD

**Issue by naq90** [tidusjar/PlexRequests.Net#594]
I'm running plexrequests on ubuntu. When trying to login to the Admin page after typing in my user and password and hitting enter the page directs back and forth between admin and users on the website address bar but the page remains the same. Is there a way to fix this?

**Comment by leram84** [comment]
Have you tried just refreshing immediately after? For me, logging in on my nginx domain, I get a 404 error, but a refresh takes right into admin. Seems like its logging in and then redirecting.

**Comment by SuperPotatoMen** [comment]
Closed the issue after 5 days with no answer :(

**Comment by naq90** [comment]
So sorry for my late reply! I tried what @leram84 said, but it did not work. No matter what browser or OS I use the same thing happens. Should I try updating? How can I update PlexRequests via the command line?

**Comment by naq90** [comment]
Actually, never mind. I signed into my user profile then signed into admin and it worked fine. Will update normally. Sorry about that!
