### ISSUE TITLE
Sonarr Multiple Root save directories for TV shows

### ISSUE THREAD

**Issue by RacerBas** [tidusjar/PlexRequests.Net#595]
My media server is set up in such a way that it has a directory for Anime and a directory for TV Shows. 

I'm having the following inconvenience:
When I approve a series/anime it gets submitted to sonarr with the destination folder that is set in the plexrequest settings, but since I have multiple folders Anime ends up in the folder for TV Shows and I have to manually edit that.

What I would like to see is an option to select which folder the show should download too when approving a series/Anime.

**Comment by tidusjar** [comment]
There is already a task for this to be done :) #445

**Comment by RacerBas** [comment]
Ah I missed that.

Apologies
