### ISSUE TITLE
Can't seem to enter admin password on chrome mobile

### ISSUE THREAD

**Issue by tstormgit** [tidusjar/PlexRequests.Net#598]
#### Reproduction Steps: Can't login to admin with a password on android 6.0 chrome (current), works everywhere else. My pass has a symbol in it and using swiftkey for keyboard maybe that's the issue. Looking for a sanity check more than anything.

**Comment by tidusjar** [comment]
Have you tried using a different keyboard? 

Just wondering if the swiftkey keyboard is sending a slightly different symbol?

**Comment by tstormgit** [comment]
Yes, I tried again today. I tried 2 different keyboards, firefox and chrome. I tried doing "request desktop site" but I couldn't properly  enter credentials. Logged in just find on multiple desktops (firefox/chrome) with same creds.

**Comment by tstormgit** [comment]
I tried changing password to 1234 and I still couldn't log in. I'm thinking it may have to do with mobile version?

**Comment by tidusjar** [comment]
This still happening on the latest version?

**Comment by tstormgit** [comment]
I'll update tonight and get back to you.

**Comment by tstormgit** [comment]
I updated and at first I wasn't able to log in, so I noticed my keyboard was automatically adding a space after my username, so deleted the space and was able to log in. So I'm pretty sure that was it. But hey, sounds like you made some fixes and optimizations because of it so silver lining, right?

**Comment by tidusjar** [comment]
Hahaha.
