### ISSUE TITLE
Detecting movies in wanted list couchpotato 1.9.4

### ISSUE THREAD

**Issue by Nyghto** [tidusjar/PlexRequests.Net#600]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Reproduction Steps:

I'm getting requests again for movies that are already in my wanted list. Seems detection is broken. Doing a search for a movie that is already in my wanted list and I can request it. Before this was not possible. Anyone else facing same issue?

**Comment by tidusjar** [comment]
Can you go to the scheduled jobs admin page and check when the CouchPotato Cacher last run?

Also see if there are any error logs for the following text
`Exception when calling GetMovies for CP` 

(You can search on the Logs page)

**Comment by Nyghto** [comment]
Hey Tidusjar,

Thank you for your reply, i checked the status page, the last time the Cacher run was 
Tue Oct 25 2016 14:35:28 GMT+0200. I cannot find any errors in the logs with the text you provided.

**Comment by tidusjar** [comment]
And when you search for a movie that is in your CouchPotato list (not snatched just wanted) plex requests does not pick it up correctly?

Can you double check your CP settings in Plex Requests to make sure they are correct?

**Comment by Nyghto** [comment]
Yes, when a user or me search for a movie at plexrequest, that is already in my wanted list in CP, I can still request it.

![wanted-request](https://cloud.githubusercontent.com/assets/1236301/19726351/d6478bfc-9b8a-11e6-8155-6e183e88feb1.JPG)

When I click request and approve, I can see it beeing added again into CP, while it was already there, and CP starts searching for the movie.

There is not much more to config i guess? Does the base url need to be provided?

**Comment by Nyghto** [comment]
Update about my issue, seems resolved with latest update! I have just updated to 1.9.6 and now its detecting my wanted movies again from CP. So ticket can be closed :)

Cheers!

**Comment by tidusjar** [comment]
Yes sorry! I fixed it :)
