### ISSUE TITLE
Rework how we integrate with Plex

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#601]
It seems that we can easily use the PlexDB (plugin db) to get all the data plus more without bogging down the Plex API (Especially in the case of Episode Searching).

Provide two options, 

- Old existing way that will no longer be supported going forward (Using the Plex API)
- New way enabled by default, query the plex db.

- [ ] Create a switch in the UI so the user can specify API vs DB
- [ ] Change the Recently Added
- [ ] Add the DB Check into the wizard
- [ ] Change the PlexAvailabilityChecker

**Comment by whitecollar17** [comment]
"switch in the UI so the user can specify API vs DB " not visible in the admin panel?

**Comment by tidusjar** [comment]
I decided not to do this as it would limit people to have to run Plex Requests on the same server as Plex.
