### ISSUE TITLE
Remove theatrical release dates

### ISSUE THREAD

**Issue by leram84** [tidusjar/PlexRequests.Net#607]
Please reserve the big green tag for "available" instead of "released". For most plex users, "released" is useless information. Unless you're filling up your library with cam rips, its the dvd release date that matters, but beyond that, for users looking at this page NONE of that matters, the only thing they care about is has it been added to plex. So if you want to keep the theatrical release info, that's fine, but imo, the green bubble should be reserved for "available" (and maybe a red tag for not)

**Comment by whitecollar17** [comment]
I agree on this.  In the last version we have already change the labels so it is now possible to follow the progress of you're Request. I'm not sure if its possible to get dvd release information from a public website with a api. @tidusjar do you know?

**Comment by tidusjar** [comment]
It is possible, but the only thing about it is that it would be difficult to get the correct release date for the country you are interested in.
e.g. UK release date could differ from a US release date.

**Comment by leram84** [comment]
yeah, i get that.... that's why im generally just not really interested in that info to begin with. Plex release date is all that matters to me!! :)

**Comment by tidusjar** [comment]
Wait, so you do you mean by `Plex Release Date` ?

**Comment by whitecollar17** [comment]
Well I think the us dates are fine. Because you have then a good indicator

**Comment by leram84** [comment]
> it would be difficult to get the correct release date for the country you are interested in.

I think we all know the chinese release date is the only date that matters ;)) lol

> Wait, so you do you mean by Plex Release Date ?

I just meant the date i add it to plex

**Comment by SuperPotatoMen** [comment]
@leram84  I do not know what you're talking about :p

**Comment by tidusjar** [comment]
ok, So it's the date that it was added to your plex server?

**Comment by leram84** [comment]
yeah, lol, sorry, i don't actually mean you should include that info. I just meant that I, personally, don't care about theatrical release dates.

**Comment by SuperPotatoMen** [comment]
this will be fixed in https://github.com/tidusjar/PlexRequests.Net/issues/373
