### ISSUE TITLE
Email received for Plex Requests: New request has huge PLEX Rquest image/logo

### ISSUE THREAD

**Issue by jpenberthy** [tidusjar/PlexRequests.Net#608]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Not sure if any logs are applicable?
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Downloading the image sent, properties show image is sized to like 1920x700 something.

**Comment by whitecollar17** [comment]
Fixed in the release of 1.9.4

**Comment by jpenberthy** [comment]
That's not true, as I have 1.9.4

**Comment by whitecollar17** [comment]
Whoops, its fixed in the release of 1.9.5

**Comment by tidusjar** [comment]
I'll be releasing 1.9.5 tonight :)
