### ISSUE TITLE
Enabled Message Bug

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/PlexRequests.Net#610]
#### Plex Requests.Net Version:
1.9.3

#### Operating System:
Windows 10 Home

Whenever I save a notice message, the message I typed doesn't appear whenever I go back to that settings page.

**Comment by tidusjar** [comment]
Can you be a bit more specific? Enable notice? What's this?

**Comment by chrisausbun** [comment]
Sure no problem. 
![image](https://cloud.githubusercontent.com/assets/22944072/19647065/442ce0c6-99b1-11e6-839a-71d95374c25e.png)
As you can see, I have a notice message enabled and something typed there that displays when a user signs in, but it doesn't show what that is on this page.

**Comment by whitecollar17** [comment]
Fixed in the release of 1.9.4
