### ISSUE TITLE
Poster images not loading

### ISSUE THREAD

**Issue by fenichelar** [tidusjar/PlexRequests.Net#612]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.4

#### Operating System:
Ubuntu 14.04

#### Mono Version:
4.6.1

#### Applicable Logs (from `/logs/` directory or the Admin page):
N/A

#### Reproduction Steps:
On the request page:
![image](https://cloud.githubusercontent.com/assets/3437075/19652736/eecf62e6-99df-11e6-8b23-8d62005b9e3c.png)

The img src is the problem. Removing the duplicated portion fixes the issue. Some posters still load even though the url partially duplicated.

**Comment by whitecollar17** [comment]
@tidusjar Still broken on the last dev build

![image](https://cloud.githubusercontent.com/assets/2944704/19708225/450f1424-9b1d-11e6-8f8f-86ef80c9ec38.png)

IMG url goes to https://image.tmdb.org/t/p/w150/https://image.tmdb.org/t/p/w150//pes2HCVX60MNZZdUrKtgVNlv1ig.jpg
but it need to go  https://image.tmdb.org/t/p/w150//pes2HCVX60MNZZdUrKtgVNlv1ig.jpg

**Comment by whitecollar17** [comment]
@tidusjar Still broken on the last dev build

![image](https://cloud.githubusercontent.com/assets/2944704/19708302/d1bfba86-9b1d-11e6-867d-cce1681d8ade.png)


images url goes to https://image.tmdb.org/t/p/w150/https://image.tmdb.org/t/p/w150//pes2HCVX60MNZZdUrKtgVNlv1ig.jpg
but the images is on:  https://image.tmdb.org/t/p/w150//pes2HCVX60MNZZdUrKtgVNlv1ig.jpg

**Comment by luke-barnett** [comment]
@whitecollar17 have you confirmed that you've gotten a copy of the dev image that includes this change?

@tidusjar what is ETA for new release?

**Comment by tidusjar** [comment]
Olathe img URL will only be fixed fir new requests going forward. It's difficult to manage the existing ones as that URL is stored in the database with the request. 

New release will be in the next few days.

**Comment by whitecollar17** [comment]
@tidusjar, i delete the eurotrip in the request page and re-request it. Still look like the same like the bug.
Are you sure its still in the database even i delete it on the overview request page?

**Comment by tidusjar** [comment]
If you delete it from the request page then it should be removed. I'll take another look!

**Comment by whitecollar17** [comment]
tested the last fix, confirmed, we have now no problem anymore.

**Comment by whitecollar17** [comment]
Fix in in new version 1.9.5

**Comment by tijmenvn** [comment]
This bug is still present for me in 1.9.6

**Comment by tidusjar** [comment]
@tijmenvn For existing requests it is still a problem, but going forward it should no longer be an issue

**Comment by tijmenvn** [comment]
@tidusjar Copy that, didn't read the whole thread :X

**Comment by tidusjar** [comment]
That's fine! 😄
