### ISSUE TITLE
Not really an issue but I need some help

### ISSUE THREAD

**Issue by apperrault** [tidusjar/PlexRequests.Net#614]
Not really an issue, but I can't seem to figure out how to update from an older version.  I found, who knows when, an install guide and got an older version working.  Now, it looks like there are new features and I would love to give it a run, but I for the life of me cannot figure out how to update.  The entire directory structure is different it looks like.  Any help would be greatly appreciated.  The executables are not there any more either.

What am i missing here

thanks

app

If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

**Comment by tidusjar** [comment]
All you need to do is download the latest release from here: https://github.com/tidusjar/PlexRequests.Net/releases/latest

And then unblock the zip, extract where your old version is and then start the .exe as you usually would! :)

**Comment by apperrault** [comment]
I knew it was easy.  For some reason, I thought that I had installed it via GIT.  Apparently now

thanks.

Updated now

app
