### ISSUE TITLE
edit the settings from ssh

### ISSUE THREAD

**Issue by peelos** [tidusjar/PlexRequests.Net#616]
I changed the base url to request/ by mistake and now cannot access the gui - is it possible to edit the settings via SSH? if not, it would be useful in such a situation to avoid reinstalling and loosing the requests database

**Comment by tidusjar** [comment]
You can manually override the database by passing in a parameter e.g.

`PlexRequests.exe -b plexrequests`

Only use this to change your base url in your settings then run as normal

**Comment by peelos** [comment]
presumably that is for windows, rather than linux.. I overwrote the DB by using one of the backups in the /backup folder and manage to get far enough to change the URL in the gui.

thanks for a great application by the way, donation was made and another to come.

**Comment by tidusjar** [comment]
I always forget about the backups!!!
