### ISSUE TITLE
[Feature Request] watch file for requests

### ISSUE THREAD

**Issue by jaredbidlow** [tidusjar/PlexRequests.Net#617]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

I don't want to go through the trouble of making my server communicate with the outside world. However, I have a dropbox folder that syncs to my media server. I was wondering if it was possible to have Plex Requests monitor a file for requests, so that I could append a line to a dropbox file and have it requested. I would be fine with the backend choosing the most relevant result.

**Comment by tidusjar** [comment]
It's possible, but it does slightly defeat the purpose of this application. 

Why don't you want to expose the website to the outside world?

There is also an API into Plex Requests, so it is possible to write a separate application that will monitor the file and wait for changes then push it to PR using the API

**Comment by jaredbidlow** [comment]
My home media server is on a network with an AP to another router. I'm not entirely sure how to setup outgoing connections. Speeds are not necessarily great, and PlexRequests integrates with all. It would be a good sole purpose integration if I could get access. Http or API have to be set up for remote access. I'm looking at this tutorial:  http://www.htpcguides.com/configure-plexrequests-net-reverse-proxy-nginx-linux 
I will have to figure out connecting without touching the router settings.

**Comment by tidusjar** [comment]
Yeah, it sounds like you are limited to your network. I'm not sure how much help I can be at this point. If no one can get into your network then no one can get into Plex Requests.

Is there anything that I can do?
