### ISSUE TITLE
500 InternalServerError trying to login with plex username.

### ISSUE THREAD

**Issue by porksandwich** [tidusjar/PlexRequests.Net#621]
#### Applicable Logs (from `/logs/` directory or the Admin page):

![untitled](https://cloud.githubusercontent.com/assets/16330854/19790112/86ce7aa0-9c83-11e6-84af-5395f7eef12f.png)

#### Reproduction Steps:  

Upgrade from 1.9.4 to 1.9.5, launch plexrequests, attempt to login with your Plex username.

I can still get into the admin account, which is under the same username, I can still login to friend's usernames, as well as managed users.

I downgraded to 1.9.4, the issue disappeared, went back to 1.9.5 and it came back.

**Comment by tidusjar** [comment]
re download the latest release please :)
