### ISSUE TITLE
[Feature Request] Keep two instances synced

### ISSUE THREAD

**Issue by Electronickss** [tidusjar/PlexRequests.Net#623]
This would likely be a huge undertaking but it would be cool if I could run two instances of plexrequests and keep them in sync

**Comment by tidusjar** [comment]
Just wondering why you would do it? Load balancing?

**Comment by Electronickss** [comment]
That's exactly it

**Comment by tidusjar** [comment]
The main thing is that they would need to be both looking at the same database, so is there somewhere where they both can see the DB file?

**Comment by Electronickss** [comment]
Could two instances operate off one db file? An nfs share is not out of the question

**Comment by tidusjar** [comment]
Sorry nick. Forgot to reply to this. They should be able to. Hopefully there will be no locks but can't garuntee that.

**Comment by SuperPotatoMen** [comment]
I discussed this idea with @tidusjar but unfortunately we don't going to implementation this one. 
Maybe in the feature.
Feel free to do more request with nice idea's!
