### ISSUE TITLE
Recently Added Email Notification Error

### ISSUE THREAD

**Issue by causefx** [tidusjar/PlexRequests.Net#629]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9.6
#### Operating System:

Ubuntu
#### Mono Version:

newest
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
`System.NullReferenceException: Object reference not set to an instance of an object at PlexRequests.Helpers.StringHelper+d__3.MoveNext () <0x409b7320 + 0x000f7> in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Send (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.String html, PlexRequests.Core.SettingModels.PlexSettings plexSettings, Boolean testEmail) <0x422144b0 + 0x00469> in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, Boolean testEmail) <0x405626e0 + 0x00427> in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Execute (IJobExecutionContext context) <0x405502b0 + 0x0005f> in :0   PlexRequests.Services.Jobs.RecentlyAdded    Error   10/28/2016 6:10:38 PM`
```
#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

I can send the test email for Recently Added Email Notification and it goes over fine, but it never goes through by itself.

Any suggestions.

**Comment by tidusjar** [comment]
Can you send me a screenshot of your newsletter settings?

**Comment by tidusjar** [comment]
Is this still happening on the latest version?

**Comment by causefx** [comment]
1.9.6 - I will download the newest version today.

Newsletter:
![image](https://cloud.githubusercontent.com/assets/16184466/19974184/d3435966-a1a4-11e6-83ea-de2d1f67247f.png)

Email:
![image](https://cloud.githubusercontent.com/assets/16184466/19974203/e39ec020-a1a4-11e6-9018-e6b48a67ff9f.png)

**Comment by causefx** [comment]
more errors from yesterday:
![image](https://cloud.githubusercontent.com/assets/16184466/19974582/31895204-a1a6-11e6-8d84-e48d54cd4341.png)

Also, I just updated to the newest version, I will let you know how it goes.

**Comment by causefx** [comment]
Hi again, 
so after the update I still get an error:
![image](https://cloud.githubusercontent.com/assets/16184466/19976498/2d08eab2-a1ad-11e6-89fe-2b8207faa8e1.png)

**Comment by tidusjar** [comment]
Are you 100% sure it doesn't go through? The errors that you are showing me I am handing them and just continuing.

**Comment by SuperPotatoMen** [comment]
@tidusjar sometimes there is no poster art on plex. Is it possible that situation trigger this?

**Comment by tidusjar** [comment]
@SuperPotatoMen We get the poster art from other places e.g. TVMaze, TheMovieDb

**Comment by d1g1talweb** [comment]
I'm also getting a similar error and the newsletter does not send:
![image](https://cloud.githubusercontent.com/assets/23339773/20104313/827a9aa8-a59b-11e6-9c91-8e83a5f791dd.png)

**Comment by causefx** [comment]
Hi @tidusjar & @SuperPotatoMen so I did some more testing.  I went ahead and unchecked send to all friends and just typed in some email addresses and it worked.  I was thinking it may be due to me having a managed user on my list... maybe because managed users don't have email addresses.  What do you think?

**Comment by tidusjar** [comment]
I'm not sure what you mean by managed users, but it will send to your Plex Friends (see the Authentication page list)

**Comment by causefx** [comment]
Managed users are users that you create on your local account.

These "Users" dont have email's tied to them.

https://support.plex.tv/hc/en-us/articles/203948776-Managed-Users
From Plex Page:
![image](https://cloud.githubusercontent.com/assets/16184466/20105735/f40a5872-a58f-11e6-8c83-fb54f2b7dbcd.png)

**Comment by tidusjar** [comment]
We don't currently support "Managed Users" in that case then.

**Comment by causefx** [comment]
![image](https://cloud.githubusercontent.com/assets/16184466/20106106/435476fa-a591-11e6-92fd-1fb9ae306175.png)

![image](https://cloud.githubusercontent.com/assets/16184466/20106139/622b3384-a591-11e6-9947-6f6e11b4ba8e.png)

The only difference is the lack of username and email, maybe if we just filter out the results that are null on those parameters it may work.  If not it's okay.

**Comment by tidusjar** [comment]
Can you raise a new issue with this?

**Comment by causefx** [comment]
I sure can.  Again, these are just assumptions not sure if I am accurate at all :)

**Comment by SuperPotatoMen** [comment]
This is already Fixed in the other issue
