### ISSUE TITLE
I´m probably an idiot...

### ISSUE THREAD

**Issue by ofurpesi** [tidusjar/PlexRequests.Net#630]
But i can´t get the new version to start. I followed the guide (install as service) Everything goes smoothly, but the service does not start. Also, i cannot find the plexrequests,exe anywhere.

P.S. I unblocked the zip file before unzipping.

What am i doing wrong here?

**Comment by tidusjar** [comment]
Did you download it from the releases section? :)

**Comment by ofurpesi** [comment]
hahahahahah.....NO!

All fixed! Thanks for the quick response! Keep up the good work :)

**Comment by Ruvetuve** [comment]
You are an idiot :p

**Comment by ofurpesi** [comment]
You live you learn my friend :)

**Comment by Ruvetuve** [comment]
Hehe your issue title made me laugh, couldn't resist. You have a great weekend man :)

**Comment by ofurpesi** [comment]
You too :)
