### ISSUE TITLE
NOTICE to everyone using Plex Requests 

### ISSUE THREAD

**Issue by tidusjar** [tidusjar/PlexRequests.Net#631]
Hi all,

Just want to let you know that I won't be replying much to any issues/queries in the next week. 

Currently in hospital with my partner ready to give birth to our first child! 

Thanks,

Jamie

**Comment by SuperPotatoMen** [comment]
@tidusjar congratulations!

**Comment by csy7550** [comment]
Good luck!

You think you're tired after the first few weeks.. just relax, it gets worse 😂
