### ISSUE TITLE
Shows existing movie in plex db as to be requested

### ISSUE THREAD

**Issue by Ruvetuve** [tidusjar/PlexRequests.Net#632]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9.6
#### Operating System:

windows 10
#### Mono Version:

?
#### Applicable Logs (from `/logs/` directory or the Admin page):

n/a
#### Reproduction Steps:

Hi,

Ive had this error before, after an upgrade. When i search a movie which exists in Plex, it is still able to request it.

Ive closed my browser etc. Other browser shows the same issue. also authorized again and connectivity to plex works.

**Comment by Aireezz** [comment]
Plex Requests.Net Version: 1.9.6

Operating System: Ubuntu 16.04 LTS

Mono Version:  4.2.3

Applicable Logs (from /logs/ directory or the Admin page): N/A

Reproduction Steps: Search for movie or tv show that is on Plex Media Server, see that it is available to be requested.

Hello,

I also have this issue, but only since the new update. I've restarted both Plex, Plexrequests .net, and my machine. Not sure what to do.

**Comment by secdeath** [comment]
Plex Requests.Net Version: 1.9.6

Operating System: Debian 8.6

Mono Version: 4.6.1.5

Having same issue with Movies. With TV Shows it shows that the show is "Pending Approval" if it's already in my library for some reason as well. Seems like a very similar issue.

**Comment by secdeath** [comment]
Disregard my previous post. It looks as if it needed some significant time to possibly populate the PR's DB after my install? Seems like that was a logical reasoning.

**Comment by SuperPotatoMen** [comment]
@secdeath so the problem is resolved? It's now tagged with "on plex" ?

**Comment by secdeath** [comment]
@SuperPotatoMen for my issue yes. I can't say the same for the submitter. Thanks for the follow-up =]

**Comment by SuperPotatoMen** [comment]
@secdeath  You're welcome :+1: 
It's look like when you do a upgrade to a new version of plex request, its needed to reindexing all of the tv shows and movies on plex. @tidusjar  is that true?

@Aireezz is the problem also resolved for you after re indexing by plex request?

**Comment by Aireezz** [comment]
@SuperPotatoMen I'm not sure, nor can I check. I can't seem to get my PlexRequests.Net to boot... I posted a different issue and currently just trying to find a work around.

**Comment by SuperPotatoMen** [comment]
@Aireezz i keep this open for now to be sure its solved.

**Comment by tidusjar** [comment]
Yes, depending on the size of your Plex library, when Plex Requests starts
up we need to check all the content on Plex

**Comment by Aireezz** [comment]
Yes, also done. My mistake, my large library just takes forever.

**Comment by Ruvetuve** [comment]
Sorry didn't find the time to investigate this further. Checked at my side and i still have the original issue.

**Comment by SuperPotatoMen** [comment]
@Ruvetuve give it some time. How big is you're library?

**Comment by Ruvetuve** [comment]
pmed you the stats., New version has been running for 5 days.. so it should be indexed right?

**Comment by tidusjar** [comment]
As discussed on Gitter,

2 things to try,
Clear the logs, restart Plex request and monitor the scheduled jobs page until the Plex availability checker finishes, then post those logs here. 

Increase the scheduled job from 1 hour to 3 hours

**Comment by Ruvetuve** [comment]
Thanks. Ive set debug mode on, upgraded PlexRequests and restarted. Now it seems to work again.

Which timer do i need to increase exactly?
