### ISSUE TITLE
Better handle add future tv shows when tv maze don't have all of the information

### ISSUE THREAD

**Issue by leram84** [tidusjar/PlexRequests.Net#633]
> Our TV Provider (TVMaze) doesn't have a TheTVDBId for this TV Show :( We cannot add the TV Show automatically sorry! Please report this problem to the server admin so he/she can sort it out!

Instead of getting this message, would it be possible to say something like "this show hasn't been indexed yet, but has been reported to admin for manual processing", and then follow up by sending a notification to admin? Or maybe adding it to "issues"? just spitballing here, but my goal is to get this to not be a user issue, but an admin one. Just need the info passed along, and have the user not be presented with something that will make them think they need to call me :))

**Comment by SuperPotatoMen** [comment]
I agree.  I was already making a issue about this.  My sugestion is to make a waiting  queue instead. If tv maze don't have the information yes.  Try to automatically  add it every day on sonarr.  This issue is only by New tv shows with is not aired yes.

**Comment by leram84** [comment]
yeah, that would be even better. this way the user would think the show has been processed like any other... which as far as they are concerned, it has.

**Comment by SuperPotatoMen** [comment]
I think we need to prevent overal any error's on the end users (users who request something), so we need something to report any problems to the admin.

**Comment by SuperPotatoMen** [comment]
@leram84 fixed in the next release
