### ISSUE TITLE
Per User exemption from weekly movie and tv request limits

### ISSUE THREAD

**Issue by veritas2884** [tidusjar/PlexRequests.Net#634]
In the non- .net version of Plex requests there is the ability to allow certain users exemption from weekly movie and tv request limits. Is there a similar ability in your .net version?

All of the other enhancements makes this my hands down choice and as always, thanks for the great software. There are just a few users of my plex server I trust to add as many movies as they like and enjoyed the ability to let them bypass the limits.

**Comment by SuperPotatoMen** [comment]
Possible option for https://github.com/tidusjar/PlexRequests.Net/issues/218

**Comment by tidusjar** [comment]
There is an option added into release 1.10.0! So this has been completed in the latest release.
