### ISSUE TITLE
PlexRequests.Net no longer boots

### ISSUE THREAD

**Issue by Aireezz** [tidusjar/PlexRequests.Net#635]
Plex Requests.Net Version: 1.9.6

Operating System: Ubuntu 16.04 LTS

Mono Version: 4.3.2

Applicable Logs (from `/logs/` directory or the Admin page):

http://pastebin.com/hnJfiaVj

Reproduction Steps:

My plexrequests .net was running fine until it crashed when I tried to add a tv show. (Note I had been adding, removing, and editing things with PlexReqests.Net fine for weeks). Once it crashed I can't seem to get it to come back online. I don't know if this is on my end, or PlexRequests.Net, but I followed all the guides for installing, and the start up script, and like stated above had been running perfectly for weeks before. I pastebin the output for 

  systemctl status plexrequests

above hoping it will help. My startup script is also below incase you want to view that aswell.

Description=Systemd script to run PlexRequests as a service

After=network-online.target

[Service]
User=plexrequests
Group=media
Type=simple
Environment=statedir=/opt/PlexRequests/Release
ExecStart=/usr/bin/mono /opt/PlexRequests/Release/PlexRequests.exe

[Install]
WantedBy=multi-user.target

**Comment by tidusjar** [comment]
Are there any other logs? E.g. In the terminal?

**Comment by Aireezz** [comment]
That should be the only log.. that's the output in terminal. I'm not sure what other log would help. If you know of one I'd be happy to get it.

**Comment by seanvree** [comment]
I"m not sure if this is related as I'm on Windows, but mine no longer boots either.

I'm running PR as a service on WIndows 10.  This is what I get from the service error logs:

Faulting application name: PlexRequests.exe, version: 1.9.911.0, time stamp: 0x58130d4f
Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c291
Exception code: 0xe0434352
Fault offset: 0x000da6f2
Faulting process id: 0x5878
Faulting application start time: 0x01d234c0c30208ce
Faulting application path: C:\PlexRequests.net\PlexRequests.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d384f5e8-d7eb-43b9-b369-561b4afca642
Faulting package full name: 
Faulting package-relative application ID: 



Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: PlexRequests.exe
P2: 1.9.911.0
P3: 58130d4f
P4: Quartz
P5: 2.3.3.0
P6: ࡫㐀ﻵÿ
P7: unknown
P8: 㻻⑰谁Ⰱ숥
P9: 攀爀椀愀氀椀稀愀琀椀漀渀⸀一漀渀刀攀挀甀爀猀椀瘀攀吀礀瀀攀䰀漀愀搀椀渀最
P10: 

Attached files:

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_PlexRequests.exe_f565cb1569858481b6533c4fedf021a0e6895acb_810d7e17_67d8db76

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5fdc5acc-6021-4902-b3f2-9272d3edf43f
Report Status: 96
Hashed bucket:

**Comment by tidusjar** [comment]
What's the event below or next to that one?

**Comment by seanvree** [comment]
There isn't one. that's it.

**Comment by SuperPotatoMen** [comment]
Is there a log file available from plexrequest.net ? Its hard to say what's going on when there is no logs :(

**Comment by Aireezz** [comment]
This is my latests log @SuperPotatoMen

**Comment by SuperPotatoMen** [comment]
Look like you have the same issue: https://github.com/tidusjar/PlexRequests.Net/issues/622
