### ISSUE TITLE
[FEATURE REQUEST] A user-submittable Issues-With-[X]-Video Section

### ISSUE THREAD

**Issue by jpartain89** [tidusjar/PlexRequests.Net#639]
The biggest thing my family and friends want to be able to do is submit issues with specific movies/TV shows/home videos that they might be having as they come across them, rather than having to text or email me and then we hunt for the specific item....

Having a way to find, tag, notate the issue and then a comment section, where I can talk back with them, would be awesome...

**Comment by SuperPotatoMen** [comment]
There is already a report system?

**Comment by jpartain89** [comment]
And where would a user-submitted issue option be at? The issues page looks to be specific towards only requested items. Not towards already-downloaded items currently in our plex servers that could have issues

**Comment by SuperPotatoMen** [comment]
If you use the search function for request something you can hit the report button. :)

**Comment by jpartain89** [comment]
OOOHHH I totally see that part... BUT, being the devil's advocate, plus wanting this... What about those home videos or "home videos" that aren't searchable by the normal search parameters, but could possibly be pulled FROM the plex database?

**Comment by tidusjar** [comment]
Hmmm. That's a difficult one, it would mean we need a way of displaying all of your Plex content. 

I'm not sure about this one. I'll have a think about it. 

I can see a few benefits of showing the current Plex content...

**Comment by jpartain89** [comment]
My idea would be akin to [JohnnyWong16's PlexPy](https://github.com/JonnyWong16/plexpy) in that it displays the names and metadata of the items in our databases.

**Comment by leram84** [comment]
I've been wanting to find a way to do this for a while, but didn't think it really fell in the purview of prnet... but since it would solve a lot of little issues like this, what about a communication module? Since prnet already has all the user info, what about a way for users to just send plain text messages to admin and have replies show up to the user (maybe in the new usermanagement thing you're building) or via email notification. A simple way to communicate would be incredibly useful to a lot of prnet users i imagine?

**Comment by SuperPotatoMen** [comment]
@leram84 in my opion this is not in the scope of PR. But maybe @tidusjar has other plans to change it to a platform with a lot of more options then only a plex request site.

**Comment by leram84** [comment]
huh.... I thought his plan was to take over the world.... my mistake

**Comment by tidusjar** [comment]
I agree with SuperPotatoMen, but maybe in the future we could do something like this

**Comment by curlz620** [comment]
Just a thought here. What about the ability to have them simply make an issue. Like a ticket basically. Subject and Details. They could then say, "Home Video not playing, Hey Admin, our dog playing catch video is not working!" or they could say, "Plex Sucks! Admin, Plex sucks and is lagging all the time! Help!" Then we can post a response and say I deleted it, or stop using your crappy wifi and use ethernet. 
Just a thought, but I think this could help alleviate the issue of files that cannot be found and allow us to assist users with any issues, without being to robust. It also gives us a basic platform to test on. Then we can find out if users actually need that functionality or if it is something we want to pass on and let another program tackle.

**Comment by tidusjar** [comment]
Still not sure if that fits in with 'Plex Requests'. But yeah I can see it's use. Maybe we could do this, but it's not on the priority list.

**Comment by SuperPotatoMen** [comment]
Let us know If you have other ideas :) I close this one for now
