### ISSUE TITLE
[Feature Request] Toggle tv request types in settings

### ISSUE THREAD

**Issue by leram84** [tidusjar/PlexRequests.Net#642]
Basically i would like to remove all the options for adding episodes, seasons, latest season, etc for tv shows, so users don't even see those options. For me, i only want users to add entire shows. So i don't want there to be a drop down. I want the user to see a button just like for movies. click it, and the show is added. Obviously that's not for everyone, so adding toggles in settings would let everyone tailor these options to their liking.

**Comment by SuperPotatoMen** [comment]
hi! its already in there! https://github.com/tidusjar/PlexRequests.Net/issues/563
