### ISSUE TITLE
Integrate updates with repository/make it easy to update on Linux

### ISSUE THREAD

**Issue by ryanjoachim** [tidusjar/PlexRequests.Net#651]
Like the title suggests, it's a real hassle updating versions on Linux. Overwriting directories and files isn't as simply as copy/pasting, and it's just not as straightforward as it could be.

Obviously this is just a wish-list item.

**Comment by SuperPotatoMen** [comment]
Yeah, i'm agree on that. i discuss this already today with @tidusjar  .
We give a high priority to fix the auto updater, in the feature we like to release more small fixes instead of a big one.
https://github.com/tidusjar/PlexRequests.Net/issues/236
