### ISSUE TITLE
Posters not showing

### ISSUE THREAD

**Issue by rrbailey89** [tidusjar/PlexRequests.Net#652]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Win 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:
I upgraded plex requests, and have since refreshed the page several times upon restarting the service and can not seem to fix the poster image. Upon inspecting the element it seems for whatever reason the URL for the poster is being inserted twice into the code.

![](http://i.imgur.com/c9mEc1w.png)

**Comment by SuperPotatoMen** [comment]
Hi, we fixed this issue already in version 1.9.6.
Unfortunately is the fix only for new request. For the old one you got this error.

**Comment by rrbailey89** [comment]
This is interesting as posters were showing just fine before I updated to 1.9.6 :P

**Comment by SuperPotatoMen** [comment]
there are some changes on https://www.themoviedb.org/ .
They change the urls from the images.Can you delete it and request it again so we can make sure if its a fixed problem or not :D

**Comment by SuperPotatoMen** [comment]
This will be fixed in the new version. we going to repair the old urls in directly in the database from PR.net.
see issue: https://github.com/tidusjar/PlexRequests.Net/issues/657
