### ISSUE TITLE
Customize which Plex libraries are on the newsletter

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/PlexRequests.Net#655]
It would be super awesome if we could customize the newsletter that goes out for the recently added content. Unfortunately, the past couple newsletters that I've clicked send test to admin have been the same recently created movie library which I didn't want to include. I created a custom library for 007 movies, and now whenever I click send test, it only shows those movies for recently added movies. I've since had a couple other movies added to my kids movies library along with my main movies library and those aren't showing up. So, it would be very useful to be able to select the libraries in Plex to include in the newsletter email. Thanks for any possible support on this feature.

**Comment by Nvious1** [comment]
Possible Dupe to #626

**Comment by SuperPotatoMen** [comment]
Duplicate see #626 
This is a planned feature in version 2.0.
