### ISSUE TITLE
API Key not saving

### ISSUE THREAD

**Issue by delphiactual** [tidusjar/PlexRequests.Net#656]
#### Reproduction Steps:

- Generate PlexRequests.net API key
- Press `Submit`
- Reload page
- API key is blank.

writing the api key down from before the refresh and trying to use it results in an invalid api key error from pr,net.

**Comment by SuperPotatoMen** [comment]
Confirmed bug, same on windows platform. You can't copy  it also.

**Comment by SuperPotatoMen** [comment]
@delphiactual fixed in the dev branch, will be released in version 1.10.0
