### ISSUE TITLE
Unable to see Requests for approval

### ISSUE THREAD

**Issue by kingwoftam** [tidusjar/PlexRequests.Net#661]
Just installed 1.9.7 fresh on my QNAP NAS. Configured everything necessary. Searching for items is working great, if it exists in Plex, it advises me as so. Some users have requested items and I've been notified via Pushover. However when I go to Requests to approve them, I get nothing listed. My only option is to mass approve or mass delete, without any idea of what I'm approving or deleting.

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
QNAP

#### Mono Version:
4.4.2.11

#### Applicable Logs (from `/logs/` directory or the Admin page):

Nothing in the logs (cleared them, set level to Trace, went to requests page, checked log and empty currently)

#### Reproduction Steps:

User requests a movie or TV show (Admin receives notifications)
User checks Requests, both Movie or TV Show tabs return zero requests (but don't show the no requests icon)
Admin check Requests, both Movie or TV Show tabs return zero requests (but don't show the no requests icon)
Admin can chose to delete all (afterwhich the no requests icon will show) or approve all (afterwhich  the request will go to CouchPotato or Sonarr correctly)

**Comment by tidusjar** [comment]
So there are no items appearing in your Requests page?

Is there any errors in the development browser console? (Press F12 and then refresh the requests page)

**Comment by kingwoftam** [comment]
Absolutely nothing. Picked up the following when looking at the development console:
{statusCode: 500, message: "Something went horribly, horribly wrong while servicing your request.",…}
details
:
"Nancy.RequestExecutionException: Oh noes! ---> System.NullReferenceException: Object reference not set to an instance of an object↵  at PlexRequests.Helpers.DateTimeHelper.OffsetUTCDateTime (DateTime utcDateTime, Int32 minuteOffset) <0x40bebe10 + 0x00030> in <filename unknown>:0 ↵  at PlexRequests.UI.Modules.RequestsModule+<>c__DisplayClass43_1.<GetTvShows>b__6 (PlexRequests.Store.RequestedModel tv) <0x4119e3d0 + 0x00237> in <filename unknown>:0 ↵  at System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () <0x41996f90 + 0x001a5> in <filename unknown>:0 ↵  at System.Collections.Generic.List`1[T]..ctor (IEnumerable`1 collection) <0x7f1525311c60 + 0x001fb> in <filename unknown>:0 ↵  at System.Linq.Enumerable.ToList[TSource] (IEnumerable`1 source) <0x417ee770 + 0x00070> in <filename unknown>:0 ↵  at PlexRequests.UI.Modules.RequestsModule+<GetTvShows>d__43.MoveNext () <0x40bf1ac0 + 0x012b3> in <filename unknown>:0 ↵--- End of stack trace from previous location where exception was thrown ---↵  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f15253dab40 + 0x00029> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f15253d9c20 + 0x000b3> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f15253d9b80 + 0x00093> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f15253d9b30 + 0x0003a> in <filename unknown>:0 ↵  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () <0x7f15253d9f60 + 0x00017> in <filename unknown>:0 ↵  at PlexRequests.UI.Modules.RequestsModule+<<-ctor>b__0_2>d.MoveNext () <0x40bf14d0 + 0x00152> in <filename unknown>:0 ↵  --- End of inner exception stack trace ---↵  at Nancy.NancyEngine.InvokeOnErrorHook (Nancy.NancyContext context, Nancy.ErrorPipeline pipeline, System.Exception ex) <0x40bedb80 + 0x002c3> in <filename unknown>:0 "
message
:
"Something went horribly, horribly wrong while servicing your request."
statusCode
:
500

**Comment by kingwoftam** [comment]
<img width="448" alt="screen shot 2016-11-07 at 11 00 57 pm" src="https://cloud.githubusercontent.com/assets/20160000/20053659/7cde920a-a53e-11e6-886d-d51ca0415fe1.png">

**Comment by tidusjar** [comment]
Thanks, I think I know where this issue is, strange that it is only
happening for you. What browser are you using? Also can you try and log out
and log in with another browser and see if that does anything?

**Comment by kingwoftam** [comment]
Using Chrome, but the issue exists in Safari as well (I'm on a Mac).

I've logged in and out on those two browsers already. Will keep trying.

**Comment by kingwoftam** [comment]
Thanks for your app by the way, love it (other than this small issue of mine)

**Comment by kingwoftam** [comment]
@tidusjar Anything else I could do to fix this?

**Comment by tidusjar** [comment]
Could you send me your database (`plexrequests.sqlite`)?
 tidusjar@gmail.com

Would be quicker for me to fix it that way

**Comment by kingwoftam** [comment]
Thanks, have emailed you now

**Comment by kingwoftam** [comment]
As per my email, issue was on my side. All sorted and working great now. Thanks for your time and support.
