### ISSUE TITLE
Sonarr Unable to Authenticate or Connect

### ISSUE THREAD

**Issue by texastoastt** [tidusjar/PlexRequests.Net#662]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
centos-release-7-2.1511.el7.centos.2.10.x86_64

#### Mono Version:
4.6.1

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Deserialzing Object	PlexRequests.Api.ApiRequest	Trace	11/7/2016 3:44:28 PM
{ "error": "Unauthorized" }	PlexRequests.Api.ApiRequest	Trace	11/7/2016 3:44:28 PM
Api Content Response:	PlexRequests.Api.ApiRequest	Trace	11/7/2016 3:44:28 PM
Exception when calling GetProfiles for Sonarr, Retrying 00:00:10
```

#### Reproduction Steps:

When trying to configure Sonarr, it does not prompt for authentication credentials, and even when removing authentication from Sonarr, cannot connect.

**Comment by SuperPotatoMen** [comment]
@texastoastt  
Do you have set the api key from sonarr on plexrequest.net?

![image](https://cloud.githubusercontent.com/assets/2944704/20076312/3b35cafe-a538-11e6-9f3d-c3a5b7926ae1.png)

**Comment by texastoastt** [comment]
@SuperPotatoMen

 Yes, of course. The API key is set. In fact, i also refreshed the key and tried with a new one.

**Comment by SuperPotatoMen** [comment]
If you hit the button on "test connectivity", what error is popup in you'r logs?

**Comment by tidusjar** [comment]
Are you using a reverse proxy? Can you please send us a screenshot of your
settings (with the API key blanked out)

**Comment by pau1mc97** [comment]
Im getting the exact same issue after migrating sonarr over to a new machine. 

@tidusjar I have attached a screenshot of my settings if they can be of any hel 
![capture](https://cloud.githubusercontent.com/assets/23339001/20103481/1afae0d2-a5c2-11e6-86a9-179d6db80be5.PNG)

**Comment by SuperPotatoMen** [comment]
@pau1mc97 
You need to select a Quality Profile, other way sonarr doesn't know what to do

**Comment by pau1mc97** [comment]
@SuperPotatoMen 
When trying to get quality profiles it also times out. I have attached a screenshot of the logs 
![capture2](https://cloud.githubusercontent.com/assets/23339001/20104906/a743b082-a5c7-11e6-816d-bb42f90dac9d.PNG)

**Comment by tidusjar** [comment]
Are you sure 38082 is your port?

**Comment by pau1mc97** [comment]
@tidusjar  100% 
![image](https://cloud.githubusercontent.com/assets/23339001/20108741/fab3c682-a5d4-11e6-9685-eaa0751ef3fc.png)

**Comment by pau1mc97** [comment]
I've also just moved couchpotato over and it seems alright which seems to point to this being a sonarr update potentially? 

![image](https://cloud.githubusercontent.com/assets/23339001/20108990/081262ce-a5d6-11e6-8988-d25207f015d3.png)

**Comment by SuperPotatoMen** [comment]
Maybe that is the case? The port number is to high?  Can you change it to 1000?

**Comment by SuperPotatoMen** [comment]
Is it possible that you're firewall somehow blocking it?

**Comment by pau1mc97** [comment]
@SuperPotatoMen  Couldn't set it as low as 1000 as it wouldnt let me save due a port requirement not being met. tried 2000 instead however same issue 

![image](https://cloud.githubusercontent.com/assets/23339001/20109132/a42f98b6-a5d6-11e6-873e-d9e97a644951.png)

**Comment by tidusjar** [comment]
What's your Sonarr version?

**Comment by SuperPotatoMen** [comment]
Can you open the port manual on the Windows  firewall?

**Comment by pau1mc97** [comment]
Just got this error 

![image](https://cloud.githubusercontent.com/assets/23339001/20109264/320bdb7c-a5d7-11e6-8513-889911f9bfe5.png)

**Comment by SuperPotatoMen** [comment]
Yeah,  since the last big update from microsoft is is in some cases neded to open it anyway If you disable the firewall (it will re enable it selfie somehow).  Can you open the top port on your firewall from Windows?

**Comment by SuperPotatoMen** [comment]
I'm out of options,  maybe tidusjar van help?

**Comment by pau1mc97** [comment]
@SuperPotatoMen Added the port anyway to be safe but still getting the same. Thanks for the help though. Its just weird because i had it working with sonarr on a Virtual machine within the main plex server i have and everything worked perfectly with the requests running off a different machine now i moved requests over to the plex server and sonarr over to yet another machine and it seems to not want to play

**Comment by tidusjar** [comment]
I'll be home in a few hours, mind if I send you a link and then you post the results? (It's the same thing that Plex Requests would do)

**Comment by pau1mc97** [comment]
yeah that's fine thanks for your help. much appreciated

**Comment by tidusjar** [comment]
http://localhost:38082/api/system/status?apikey=YourAPIKey

**Comment by pau1mc97** [comment]
{
  "error": "Unauthorized"
}

**Comment by SuperPotatoMen** [comment]
can you reset your api key in sonarr? Look like there is something wrong on the site of sonarr

**Comment by pau1mc97** [comment]
reset it and getting the same result as before and the test still fails

**Comment by SuperPotatoMen** [comment]
i think you need to raise a issue for that by the sonarr. Best way you can do that is to go to https://forums.sonarr.tv/ and post this issue over there

**Comment by pau1mc97** [comment]
Cheers, Posted it there https://forums.sonarr.tv/t/sonarr-api-key-seems-to-be-bugged/12665

**Comment by SuperPotatoMen** [comment]
Sonarr problems :(
