### ISSUE TITLE
Request content only if not in existing library?

### ISSUE THREAD

**Issue by mushbuddygoose** [tidusjar/PlexRequests.Net#663]
Just installed this (previously was using Lokenz version). Its great! One question. Should a request that is already in your Plex library be allowed? How does it handle this? I tested a few requests of movies that i already have in plex and it PR is still grabbing the movie. I would have assumed it checks against the database first? Or perhaps is this granular as to check against quality of movie -- thus my quality setting in PR may be the reason?

**Comment by tidusjar** [comment]
It should pick it up! The very first time PR runs it can take a while to Index your library. Restart it and then wait around 5 minutes and try again :)

**Comment by mushbuddygoose** [comment]
Hmmm...restarted and waited an hour. Still seems to grab content already in my library. Any ideas what might cause this? Sorry for the hassle.

**Comment by mushbuddygoose** [comment]
Ok so odd behavior. Example. Top Gun is my Plex library and shows under Couchpotato. When I go to PR and request it, it processes a successful request (as if it's not in my library). The movie then disappears (I actually saw it remove itself) from couchpotato and shows up under the Manage tab as a movie being processed and downloaded. But still in my Plex library. I don't think the logs show anything other than a request and response to grab movie.

**Comment by tidusjar** [comment]
So it's not finding Top Gun correctly?

**Comment by mushbuddygoose** [comment]
To be clear, it finds the movie, but the request shows Requested! Vs saying something like already in library or whatever you have it indicate when a movie already exists. Tried it on 7 diff movies. All same behavior. 

I do have it set so no approval is necessary but I imagine that's irrelevant.

**Comment by tidusjar** [comment]
Sorry I'm a bit confused now. 

Do you mind posting some screenshots and explaining it?

**Comment by mushbuddygoose** [comment]
* My Plex library has 750 movies currently. Including for example Tommy Boy, top gun. 
1) Log into PR as a non-admin user (wife's account on Plex). 
2) brought to search screen. 
3) Search for a movie I know to be in my Plex Library (ie Tommy Boy)
4) Results returned show it found Tommy Boy and I hit Request (just as a test expecting it to tell me this movie is already in Plex)
5) Instead it shows "Requested"
6) Movie is removed from CP and added to Manage tab. It is fetched and begins downloading. 
7) again I would expect behavior to be nothing happens because movie already exists in Plex. 
![img_0279](https://cloud.githubusercontent.com/assets/16007273/20112405/3121806c-a5ba-11e6-8d53-3476fccc80ea.PNG)
![img_0280](https://cloud.githubusercontent.com/assets/16007273/20112406/31370626-a5ba-11e6-98da-594e9a99457c.PNG)

**Comment by tidusjar** [comment]
That's unusual. Is your Plex info in the settings all correct?

**Comment by mushbuddygoose** [comment]
I thought it was. But i noticed my token was different depending whether i logged in remotely or locally on my server machine. I changed the token to the local one and restarted. Seems to work fine now. Very strange. Sorry to bother you.

**Comment by tidusjar** [comment]
Strange, well glad it's sorted!"
