### ISSUE TITLE
Email Newsletter Error with Managed Users

### ISSUE THREAD

**Issue by causefx** [tidusjar/PlexRequests.Net#664]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Ubuntu 16.04

#### Mono Version:
Newest

#### Applicable Logs (from `/logs/` directory or the Admin page):
![image](https://cloud.githubusercontent.com/assets/16184466/20106471/8b7170c2-a592-11e6-91c8-ec7fd642ad18.png)

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

When PlexRequests tries to send out the newsletter it fails and write an error to the log.  I did some testing and thought that maybe the error was due to having a Managed User in my user lists.  I really can't delete that user as it is my sons account and don't want to lose all his history within PlexPy.  As you can see from the friends lists that Plex supplies from: https://plex.tv/pms/friends/all , the managed user has a null value for username and email:
![image](https://cloud.githubusercontent.com/assets/16184466/20106624/1258f4d4-a593-11e6-9171-fd520cfd04c3.png)

I also noticed that I have some users on my list that I am friends with but i'm not sharing anything with so I'm unsure if that has anything to do with it as well.  I will share with them and see if there is any change.

**Comment by causefx** [comment]
Line 255 of RecentlyAdded.cs

Would doing this fix it?

 `if (newletterSettings.SendToPlexUsers)
                {
                    var users = Api.GetUsers(plexSettings.PlexAuthToken);
                    if (users != null)
                    {
                        foreach (var user in users.User)
                        {
                            if (user.Email != null)
                              {
                                 message.Bcc.Add(new MailboxAddress(user.Username, user.Email));
                              }
                        }
                    }
                }`

**Comment by tidusjar** [comment]
Depends if the Managed Users are returned in that API Call

**Comment by causefx** [comment]
I would assume they are, if they aren't they code wouldn't hurt anything.

**Comment by causefx** [comment]
I went ahead and added shared libraries with the users that I wasn't sharing anything with and now I get this error:

![image](https://cloud.githubusercontent.com/assets/16184466/20144552/3211e908-a65a-11e6-9cbe-f2271b8065d3.png)

**Comment by tidusjar** [comment]
That might be because they don't have an email address :)

**Comment by causefx** [comment]
gotcha :)  thank you for all your help :)  you've got a great product.
