### ISSUE TITLE
403 error when entering the settings page after admin login

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#665]
If this is a bug report please make sure you have filled the following in:

#### Plex Requests.Net Version:
1.9.956 Dev version

#### Operating System:
Windows 10

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

#### Problem:

I try the last dev build for some testing if the systems are working. Running the 1.9.956 Dev version.
After you do a admin login (that is okay) and you click on the setting page, you got a 403 error from you browser.
Maybe forgot to add the migration code

**Comment by tidusjar** [comment]
Fixed. You will need to clear out your previous migration.

To do this you have 3 options:

1. Start with a new database
2. Send the database to me and I'll clear it out
3. Open up the database with SQLiteBrowser
   Browse to the `VersionInfo` table and delete the record with the `11000` version.
![image](https://cloud.githubusercontent.com/assets/6642220/20260599/4c4f7b36-aa52-11e6-8cad-30c9e91815f4.png)
