### ISSUE TITLE
Change HTTP Listener

### ISSUE THREAD

**Issue by llyenn** [tidusjar/PlexRequests.Net#666]
#### Mono Version: Mono JIT compiler version 4.6.1 (Stable 4.6.1.5/ef43c15 Wed Oct 12 09:10:37 UTC 2016)

I just got Plex Requests up and running today (yay!) along with everything else on a dedicated server. I took the time to secure everything using nginx as a reverse proxy, including Plex Requests. As part of that process, I changed the http listener for Sonarr, CP, Sab from either * or 0.0.0.0 to either localhost or 127.0.0.1, so that way you can't hit my server by public IP address:port, only www.mydomain.com/request I scrubbed through all the .config and xml files I could, and I can't seem to find where this is a configurable option, and it isn't in the gui. Any help would be appreciated.

Thanks for your awesome work!

**Comment by amizzo87** [comment]
Sorry to resurface an old issue, but I can't find any documentation on this change. Running Ubuntu 16.04, how do I start Ombi.exe with a specific HTTP Listener address (ie 127.0.0.1)?
