### ISSUE TITLE
[Feature Request] DVD Release Date

### ISSUE THREAD

**Issue by jpenberthy** [tidusjar/PlexRequests.Net#668]
Could you add for requested movies a DVD Release Date. I normally only get movies that have been released to DVD/Blu-ray.  The website I use is http://www.dvdsreleasedates.com/

**Comment by SuperPotatoMen** [comment]
Hi,  this feature is already planned in version 2.0.  Thanks for request it 👍 

See https://github.com/tidusjar/PlexRequests.Net/issues/373
