### ISSUE TITLE
PlexRequests.UI has stopped working

### ISSUE THREAD

**Issue by epoch71** [tidusjar/PlexRequests.Net#671]
**Plex Requests.Net Version:** 1.9.7

**Operating System:** Windows Server 2012 R2

**Applicable Logs:**

[2016-11-13.zip](https://github.com/tidusjar/PlexRequests.Net/files/587948/2016-11-13.zip)

**Reproduction Steps:**

- New install (extracted to C:\PlexRequests.Net)
- Attempted to launch the exe (as admin).
- Crashes with _PlexRequests.UI has stopped working_.
- .Net 4.5 feature is enabled.
- Apologies if I've missed something obvious on the install.

**Comment by tidusjar** [comment]
What's in the console?

**Comment by epoch71** [comment]
Hi

I'm sorry, not exactly sure what you mean.

Here's the problem details from the crash report:

`Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	PlexRequests.exe
  Problem Signature 02:	1.9.933.0
  Problem Signature 03:	581a7567
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c0eac
  Problem Signature 07:	4474
  Problem Signature 08:	16
  Problem Signature 09:	N3CTRYE2KN3C34SGL4ZQYRBFTE4M13NB
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	2057
  Additional Information 1:	5861
  Additional Information 2:	5861822e1919d7c014bbb064c64908b2
  Additional Information 3:	6ee2
  Additional Information 4:	6ee2432e64e99bdcea5e4be767a3b1a2
`

And a screenie of the crash.

![error](https://cloud.githubusercontent.com/assets/23437516/20247829/d0877ae0-a9ce-11e6-9c57-b650163ae422.png)

**Comment by tidusjar** [comment]
Did you unblock the zip file before extracting?

**Comment by epoch71** [comment]
Take me out at dawn and shoot me.

**Comment by epoch71** [comment]
All sorted - can't believe I missed that one.

Thanks for the brilliant, swift response.

Regards
epoch71

**Comment by tidusjar** [comment]
Hahaha no problem!
