### ISSUE TITLE
Email Requestor when request is filled?

### ISSUE THREAD

**Issue by seanvree** [tidusjar/PlexRequests.Net#674]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
Version:  1.9.7

#### Operating System:
Windows 10

Is there a way to email the requestor ONLY when the request is available on PLEX?

Thanks for the work man! Great stuff!!!

**Comment by tidusjar** [comment]
In your email settings there is an option called "Enable User Notifications".

Once enabled your users can go into Plex Requests and press the Bell icon (right of the search bar) and enable their notifications there.

Once a movie/Tv show becomes available on Plex, Plex Requests will identify that they requested this and send them an email notification stating that it's not available.

Hope that helps!

**Comment by seanvree** [comment]
@tidusjar ... I saw that, but when I do that, I get the error "Sorry, but this functionality is currently available  for users with Plex accounts"?? Obviously I have a plex account. 

Also, would there be a way to set this with the admin account for a "global" option so it's enabled by default for all users?

THX

**Comment by tidusjar** [comment]
This feature is aimed at users that log in with Plex Accounts (Not Managed Users etc).
You are seeing that as you are logged in with your Plex Requests Administrator account and not your Plex Account.

There is already an feature raised to enable it by default so i'll close this for now 😄

**Comment by seanvree** [comment]
@tidusjar ... I was logged on, but I had authentication disabled, so I enabled it and now it works.  Thanks for  clearing that up. 

Thanks!!!!
