### ISSUE TITLE
Newsletter not showing primary movie library

### ISSUE THREAD

**Issue by OracleDS** [tidusjar/PlexRequests.Net#676]
#### Operating System: Windows 7 Enterprise 64-bit

I have 2 movie libraries on my plex server. One labeled as default "Movies" and the other is labeled as "Children Movies". It seems that the newsletter will take the libraries in sorted order and just display 1 Movie/TV Show section. In my case, it will only show the recently added to "Children Movies'. If I rename the Children Movie folder to force the default Movie to be higher priority in the sorting list, it will not display the content at all. 

The first screenshot is a newsletter sorting the library displaying the Children Movies. The second screenshot is the forced sorting of the libraries to display the primary movie folder. 
https://gyazo.com/cd666cd8db05197c7314e92a01bda246
https://gyazo.com/7de7a76c50fe102cd2a8bfd3956048fd
 

Also, here's a dumb question or maybe not. What is the time interval on these newsletter emails being sent out?

**Comment by SuperPotatoMen** [comment]
Hi,

Time interval is weekly.

Other is issue is allready planned in version 2.0. See master issue #626
