### ISSUE TITLE
Better handle error message by request movie without a imdb id

### ISSUE THREAD

**Issue by torem** [tidusjar/PlexRequests.Net#677]
#### Plex Requests.Net Version:
Version: 1.9.7 Stable

#### Operating System:
rogueosb/docker-plexrequestsnet (on Ubuntu 16.04)

#### Reproduction Steps:
If requesting (with no approval needed) the movie "Mad Max: Fury Road - Black & Chrome" in PRN, I just get "Something went wrong adding the movie to CouchPotato! Please check your settings."

However, my settings are fine and the real reason can be seen when I try to add it manually in Couchpotato: "Can't add movie without imdb identifier."

Could this have been handled better by PRN, or doesn't the API response from Couchpotato contain enough information about the error?

**Comment by SuperPotatoMen** [comment]
@tidusjar  We have now a brand new queue system for tv shows in version 1.10 when tv maze don't have all the information yet. Can we extend this feature for movies?

Can be part of: https://github.com/tidusjar/PlexRequests.Net/issues/633

**Comment by tidusjar** [comment]
Actually, just looking at the code, it will add it into the queue and keep retrying, so there's not really any work to be done here.

**Comment by SuperPotatoMen** [comment]
@tidusjar so its allready in there. Is it possible to show in the admin panel the error why the system can't add it yet?

**Comment by tidusjar** [comment]
That's a good idea. Some of the errors will be from other systems and some I can write myself.

**Comment by SuperPotatoMen** [comment]
@tidusjar cool, can we add that by the 1.10 release?

**Comment by SuperPotatoMen** [comment]
Its allready in the new version its a part of this feature: https://github.com/tidusjar/PlexRequests.Net/issues/633

**Comment by tidusjar** [comment]
Yeah
