### ISSUE TITLE
Rework Plex Availability Checker for big library's

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#679]
Some users reporting that the update cyclus takes to mutch time.
A lot of request are marked "request possible" instead of available on the plex server.

We need to make a redesign how to handle large library's.

Issue reported from @bromanguydude @chrisausbun

**Comment by SuperPotatoMen** [comment]
@tidusjar I'm not sure if we can release it in the 1.10.0 version beceause that is already a big update.
Can we move this to a 1.10.X release?

**Comment by tidusjar** [comment]
@SuperPotatoMen Your choice, I think i'll be able to code this out today

**Comment by SuperPotatoMen** [comment]
@tidusjar I think,  release it in the 1.10.0 version :)

**Comment by SuperPotatoMen** [comment]
Ready in next release

**Comment by seanvree** [comment]
When is the next release that will fix this issue? Appreciate the hard work guys!

**Comment by tidusjar** [comment]
We will be pushing out a 'Beta' very soon, that we encourage everyone to jump onto.

**Comment by seanvree** [comment]
Not trying to be pushy here, but is "VERY SOON" like days? Weeks? . . . .

**Comment by tidusjar** [comment]
A week or two maybe, I don't want to give an exact date since i'm quite busy at home these days.

**Comment by SuperPotatoMen** [comment]
You can follow the release of 1.10.0 over here: https://github.com/tidusjar/PlexRequests.Net/milestone/7

**Comment by seanvree** [comment]
Wurd! Thanks guys

**Comment by seanvree** [comment]
Hey guys, thanks for the work! Looking forward to the release...question about this issue tho:

Does this "Bug" effect when a user requests something and it becomes available?  I'm seeing that it's not polling CP or PLEX at all, and I have to go in and manually make the movie 'availible". 

Thanks!
