### ISSUE TITLE
PR.net not polling  movie DB??

### ISSUE THREAD

**Issue by seanvree** [tidusjar/PlexRequests.Net#682]
So, i noticed that if I search for a movie that I know is in the CP db and on PLEX, PR.net doesn't detect that I have it and will request it.  If I then mark it as available, then all is good, but it's like it's not working for movies that I currently have.  

It works fine for TV and music. 

The scheduled jobs have all run in the past hour. I have Plex availability checker for 30 min, and CP Cacher at 60 min. 

So I'm assuming there is a problem connecting to the CP db?  If I go to settings, and test CP connectivity, it's good. 

This used to work, but I'm not sure when it changed.  

Thoughts?

#### Plex Requests.Net Version:
Version:  1.9.7

#### Operating System:
Windows 10

#### Mono Version:
n/a

#### Applicable Logs (from `/logs/` directory or the Admin page):

``` non
Logs go here (Please make sure you remove any personal information from the logs)
```

**Comment by csy7550** [comment]
Same here.. recently had a lot of requests of existing movies.

**Comment by SuperPotatoMen** [comment]
We are aware of this problem. It has our ttention. We don't look at CP but we look at the database of plex it self.

See main issue: https://github.com/tidusjar/PlexRequests.Net/issues/679

**Comment by SuperPotatoMen** [comment]
You can give Plex availability checker a higher value like 2 hours maybe its helps.
