### ISSUE TITLE
New user management system is unstable

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#690]
End users got errors that they have not the right permission for request a movie.
But plex request add the show to the failed queue. 

(end user has the right permission)

If i try it on my self, i got the error to.  If i go to the user mangement page, i got this page:

![image](https://cloud.githubusercontent.com/assets/2944704/20407520/081502d4-ad12-11e6-895e-da867f719957.png)

after a f5 the page is working,  but request something isn't possible

**Comment by tidusjar** [comment]
You sure that the user didn't have the 'Read Only' Permission?
That permission means that they cannot do anything on the system other than view

**Comment by tidusjar** [comment]
I also cannot reproduce the error you see above 😢

**Comment by SuperPotatoMen** [comment]
![image](https://cloud.githubusercontent.com/assets/2944704/20428990/5c87d902-ad8c-11e6-97e0-333eba163c8e.png)

**Comment by tidusjar** [comment]
AH it's a Plex User. I'll take another look

**Comment by SuperPotatoMen** [comment]
Whoops, i didn't say that, i'm sorry :(

**Comment by tidusjar** [comment]
This should now be fixed in the latest dev. You just need to delete the Plex Users table!

**Comment by tidusjar** [comment]
Or delete the migration row again
