### ISSUE TITLE
Plex Requests not booting when trying to verify with mono

### ISSUE THREAD

**Issue by justinglock40** [tidusjar/PlexRequests.Net#691]
http://pastebin.com/CjHC03Sp

Any idea what's causing this?

**Comment by delphiactual** [comment]
the user running plexrequests does not have write access to `/opt/PlexRequests/Release/PlexRequests.sqlite`

Ensure the user you are running plexrequests as has chowned /opt/PlexRequests

**Comment by justinglock40** [comment]
Tried that didn't work
