### ISSUE TITLE
[Feature Request] Prevent specific sections from being queried against

### ISSUE THREAD

**Issue by antoinesylvia** [tidusjar/PlexRequests.Net#692]
Great tool, thanks for all the hard work. I ran this request by the developer a few months ago on a random PlexRequests Reddit thread, wanted to create a formal request. I manually download movie trailers and it's a standalone PLEX section (utilizing movies scanner). If a user requests something like "Rogue One", Plex Requests will show the movie as "available" even though it's just a trailer, therefore the user can't submit that request and they head to my movies section thinking it's already there. I was wondering if there could be a method in the future the tool can skip a designated section like "Trailers" from being queried against. 
![capture](https://cloud.githubusercontent.com/assets/2508410/20458206/f812e6fa-ae63-11e6-9328-6694385b5ec1.PNG)

**Comment by tidusjar** [comment]
Hi!

Does this still happen with the latest version? Since we also check the
IMDb is (not sure how the trailers appear in Plex)

**Comment by antoinesylvia** [comment]
Thanks for the response. I was one release behind, the new one seems to have fixed the issue. Thanks.
![capturenew](https://cloud.githubusercontent.com/assets/2508410/20458351/841b7582-ae68-11e6-8ac5-f05e50e38ea4.PNG)

**Comment by tidusjar** [comment]
Excellent!!

I changed the way we lookup movies and tv shows so glad it's fixed.

**Comment by SuperPotatoMen** [comment]
Cool I close this one.  If you have other problems, Just rais a new issue
