### ISSUE TITLE
Nancy.RequestExecutionException: Oh noes! ---> System.IO.IOException: Too many open files

### ISSUE THREAD

**Issue by AlienXAXS** [tidusjar/PlexRequests.Net#693]
Hey, I keep getting this error after awhile of running PlexRequest.NET, any ideas what might be happening?

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Ubuntu 16.04.1 LTS

#### Mono Version:
4.6.2.7/08fd525

#### Applicable Logs (from `/logs/` directory or the Admin page):
My logs are just full of JSON, i dont think this would be helpful?
Why is Trace set as the log level by default, it seems a bit much?

#### Reproduction Steps:
Unsure, sometimes the application will just error out with "Too many open files" error.
When attempting to stop the service, it does not work, i have to use kill -9 <pid>

**Comment by tidusjar** [comment]
Hmm. Your log level shouldn't be trace! That's the issue. I'll make sure to
set this not to trace in the next update

**Comment by SuperPotatoMen** [comment]
Does it help @AlienXAXS ?

**Comment by AlienXAXS** [comment]
Apologies for not getting back so soon, yeah it seems much more stable now! Thank you. 


Sent from my Samsung device

-------- Original message --------

**Comment by SuperPotatoMen** [comment]
Cool
