### ISSUE TITLE
Added a FreeBSD install script to the wiki. Someone should probably check to make sure it doesn't do something terribly wrong

### ISSUE THREAD

**Issue by rfrowe** [tidusjar/PlexRequests.Net#695]
I wrote up a quick install script for a friend using FreeBSD so I thought I'd add it to this repo somehow. I was going to create an issue or something, but apparently I have permission to [edit the wiki](https://github.com/tidusjar/PlexRequests.Net/wiki)? 

Anyway, that script should install PlexRequests on FreeBSD and add a service to rc.d to start on boot. Probably. I didn't test it at all ¯\_(ツ)_/¯

**Comment by tidusjar** [comment]
Everyone can edit the wiki, I am still able to revert changes and monitor it so it's fine. 
So you are welcome to edit the wiki :)

**Comment by rfrowe** [comment]
@tidusjar haha yeah I just realized that a lot of public repos' wikis are editable 😛. I mostly work in private repos so I've never seen that before.

**Comment by topper59** [comment]
@rfrowe So I'm giving this a go, but when I try and enter the line 

`load_rc_config $name`

I get name: Undefined variable. 

It works when running the mono command, but what I really want is for it to start when the jail starts!

**Comment by rfrowe** [comment]
@topper59 That problem shouldn't be happening. The `name` variable is defined on the line 
```
name=plexrequests
```

But also I just noticed that there's a huge bug in the script. The heredoc line was `cat`ing the input *to the rc.d directory* which I imagine can't be good. It should be creating a file *in* the directory. 

```
# BAD
cat > /usr/local/etc/rc.d<< EOF

# Good 
cat > /usr/local/etc/rc.d/plexrequests << EOF
```

I have updated the script on the wiki page to reflect this change. Try again.

**Comment by topper59** [comment]
Yeah that's what I thought too, but I just ended up using the steps provided here:
https://forums.freenas.org/index.php?threads/plex-request-or-similar.42187/page-2#post-286946
and am able to start the program with a cronjob. It works just fine even if it isn't the "proper" way.
