### ISSUE TITLE
Newsletter sends every time the service starts.

### ISSUE THREAD

**Issue by jneljeff** [tidusjar/PlexRequests.Net#696]
This may be as intended, but it makes necessary restarts impossible without spamming my users.  Can this be disabled and placed on a set time/day of the week?  Is there a way to trigger this via a cronjob manually instead?

#### Reproduction Steps: Stop then start or restart the service

**Comment by tidusjar** [comment]
It runs via a CRON job that you can modify, you can see this in the scheduled jobs page in the settings.

**Comment by jneljeff** [comment]
Gotcha on the job scheduling, but it still fires on service start.  Can that be disabled?

**Comment by tidusjar** [comment]
If the CRON expression is set to fire when you start the application then it will start then, but it uses a cron expression to figure out when to fire it.

**Comment by jneljeff** [comment]
I guess I'm missing something because (using the cron generator linked on the settings page) I have it set for 0 0 12 ? * MON * (every monday at noon).  Even if it's Tuesday, I get an email shortly after restarting the service.

**Comment by tidusjar** [comment]
Really? that's strange... I'll have to take a look into it.

**Comment by jneljeff** [comment]
This may have been an issue with using the same PlexRequests.sqlite as previous versions.  I deleted and reconfigured and I haven't seen an email on start since.

**Comment by jneljeff** [comment]
Disregard last comment.  Still happening. My cron job to restart the service must not have fired until now.

**Comment by kamilkrzeminski** [comment]
+1

I have noticed the same issue. I have cron expression set to Fridays at 2pm, but I get newsletter emails in random moments. I'll post some logs tomorrow.

**Comment by kamilkrzeminski** [comment]
https://gist.githubusercontent.com/kamilkrzeminski/23f5781c6ce953f8778b37225ebd3a0a/raw/1e459de05da070f620e0377efa034844e5c8e2e5/plexrequests%2520log

I don't know if there's anything useful in this log file, but that's when newsletter was sent.

**Comment by jneljeff** [comment]
I'm not sure if it is relevant, but I found this in my logs relating to the newsletter last night...  I did not receive an email afterwards.

System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.OrderedEnumerable`2[TElement,TKey]..ctor (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Collections.Generic.IComparer`1[T] comparer, System.Boolean descending) [0x00016] in <63992662b765477a898ef49cdcc99ee2>:0 at System.Linq.Enumerable.OrderByDescending[TSource,TKey] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector) [0x00000] in <63992662b765477a898ef49cdcc99ee2>:0 at PlexRequests.Services.Jobs.RecentlyAdded.GenerateMovieHtml (PlexRequests.Api.Models.Plex.RecentlyAddedModel movies, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Text.StringBuilder sb) [0x0001e] in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x000bc] in :0 at PlexRequests.Services.Jobs.RecentlyAdded.Execute (Quartz.IJobExecutionContext context) [0x00016] in :0	PlexRequests.Services.Jobs.RecentlyAdded

**Comment by SuperPotatoMen** [comment]
Fixed
