### ISSUE TITLE
{Feature Request} Modify Email Header

### ISSUE THREAD

**Issue by Foebik** [tidusjar/PlexRequests.Net#698]
It would be nice to be able to edit the header to customize the news and update letters to fit my server (My Server Name). If you can't do it within the app, could you advised where the files are that I need to adjust manually (if possible)?

**Comment by tidusjar** [comment]
Hi, which letters are you referring to?

**Comment by Foebik** [comment]
Sorry, should have been more clear. There are two that I am aware of and use. 

1) Sends notifications that your request has been downloaded.
2) Weekly "What's New" letter.

**Comment by tidusjar** [comment]
Here is the Weekly whats new letter:
https://github.com/tidusjar/PlexRequests.Net/blob/master/PlexRequests.Services/Jobs/Templates/RecentlyAddedTemplate.html

Here is the notification template:
https://github.com/tidusjar/PlexRequests.Net/blob/master/PlexRequests.Core/Notification/Templates/BasicRequestTemplate.html

Note: Do not remove or edit anything in the `{Curly Brackets}` fields, this is how Plex Requests knows where to put the content.
