### ISSUE TITLE
Plex Episode Cacher not doing anything

### ISSUE THREAD

**Issue by TheBlackDrake** [tidusjar/PlexRequests.Net#699]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Server 2008 R2

#### Mono Version:
NA

#### Applicable Logs (from `/logs/` directory or the Admin page):

There is nothing in the logs that I can see
```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

It's a new installation. 
I try to change/set the interval of "Plex Episode Cacher (hours)"
But everytime I set it, save and refresh the page (or even restart plex)request) it resets to blank.
Same goes if I try to disable "Use advanced search" 
That setting is not stored either.
Everything else I'm able to change just fine.

Also, it doesn't seems to actually scan my plex database.
The schedule task page, say that Plex Episode Cacher last run was an hour ago, but still doesn't see my episodes)
Did I miss any step in the installation?

**Comment by tidusjar** [comment]
So the Plex Episode Cacher will go thought all the episodes in your Plex server and then store them in our database so we can quickly look things up (rather and querying Plex every time).

You should be able to see these if you download SQLiteBrowser and then open up the database (`PlexRequests.sqlite`). If you browse to the table PlexEpisodes, you should be able to see the content we found on your Plex Server.

The easiest way to see if it worked using the UI, is to search for a TV Show you know you have episodes for, then click the select episodes button, the episodes we found should be pre-ticked.

**Comment by TheBlackDrake** [comment]
well I did that, and there is none ticket.
I "added" a show I have everything of, but none was ticket off.

**Comment by tidusjar** [comment]
Are there any errors in your logs?

**Comment by TheBlackDrake** [comment]
Not that I have found no.
But still the weird part is that I can't change the scan interval. Tried 11 hours and 12 hours.

**Comment by TheBlackDrake** [comment]
![image](https://cloud.githubusercontent.com/assets/10724791/20556269/a07b3a18-b166-11e6-8f77-41504e5cc46e.png)

**Comment by tidusjar** [comment]
So if you change it and save it doesn't save it? If it's set to 0, by default we will run it every 11 hours.

**Comment by TheBlackDrake** [comment]
It say saved, but when I open the page again. it goes back to 0.
Well as the scheduled task say. it has run, but haven't gotten any data.
![image](https://cloud.githubusercontent.com/assets/10724791/20556422/47ecffc0-b167-11e6-836d-ecb7b1522b44.png)

And I don't see any memory usage on my server. nider any indication that it has grabbed anything.
Its 10:26 am now. so it ran this 16 min ago

**Comment by tidusjar** [comment]
And your settings to connect to Plex are all correct?

**Comment by TheBlackDrake** [comment]
hmm may be missing plex base url.
What should that be?

**Comment by TheBlackDrake** [comment]
but the again, I don't have base url on SickRage or CP, and those works fine.
I have the address, port and token correct

**Comment by tidusjar** [comment]
The base url is for users that are using a reverse proxy.

When you installed, you did unblock the .zip right?

**Comment by TheBlackDrake** [comment]
hmm not sure. Maybe I didn't 
Could that affect the settings. Even if the app seems to be working fine other than this issue?

**Comment by TheBlackDrake** [comment]
it did not have that option
![image](https://cloud.githubusercontent.com/assets/10724791/20558370/01bb7ffa-b170-11e6-819e-8a106b4557b3.png)

**Comment by TheBlackDrake** [comment]
that was wrong. it was the folder.. but still on the zip I had the same. just not read only. I also tried removing the read only attribute
Still the same

**Comment by TheBlackDrake** [comment]
I just noticed another thing. 
In the guide it say, not to user the path with c:\plexrequest\Release\plexrequest.exe.
Does that matter? even if I setup the service to point to the correct address?

**Comment by tidusjar** [comment]
Where does it say that in the guide? I'm scratching my head on this one, i
can't work out why it's not working...

**Comment by TheBlackDrake** [comment]
The absolute path to the PlexRequests.exe should be c:\PlexRequests.net\PlexRequests.exe and not c:\PlexRequests.net\Release\PlexRequests.exe

well me neither. doesn't make any sense.
If you want you can check out my request site.

**Comment by TheBlackDrake** [comment]
hmm something seems to have changed.
hold on while I check. seems like things start to work.

**Comment by TheBlackDrake** [comment]
okay it seems to see what shows/movies that are on plex. but not episodes.
and I still can't change the Plex Episode Cacher interval

**Comment by SuperPotatoMen** [comment]
@TheBlackDrake pleas edit your first post instead off message a lot

**Comment by SuperPotatoMen** [comment]
@TheBlackDrake are you running the 1.3.0 version of plex request?

**Comment by TheBlackDrak3** [comment]
Hi
No I'm running "Version 1.1.4.2757 "
Due to errors in newer versions. 
But looks like they have fixed the servercrash issue. So are planning on upgrading.

**Comment by tidusjar** [comment]
This will be fixed in the new version
