### ISSUE TITLE
Delete some Plex Request Settings

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#707]
Delete the settings in the admin panel beceause its already in the new usermangement system.

Require approval of Movie requests
Require approval of TV show requests
Require approval of Music requests
Users can view their own requests only
Users can view their own issues only
Current users that are allowed to authenticate:

**Comment by tidusjar** [comment]
Already done, Just need to remove them from the screen really

**Comment by SuperPotatoMen** [comment]
@tidusjar still on you're todo list? can i close this one?

**Comment by Aireezz** [comment]
I'm aware this is the wrong forum to post to post this on but how does on get the beta version? I'd like to try them out if I could.

**Comment by SuperPotatoMen** [comment]
Hi @Aireezz feel free to join the public beta and hunting on bugs.
I'm now busy to find some early bugs so we have not a lot of big problems in the beta release :)
ETA of the public beta is between now and 2 weeks.
You can download the development build over here: https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

Beaware: don't run the development build in a live situation, its not stable and ready yet for a live situation.
