### ISSUE TITLE
Release of 1.10.0

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#709]
**To do list for the big V1.10.0 release** 

- [x]  close all open issues for the 1.10.0 release
- [x]  Migration database test
- [x]  Test the new functions before launching public beta
- [x]  Confirm fixes before launching a public beta
- [x]  Write the patch notes
- [x]  Make a new wiki page explaining the differents between the update channels

**Comment by SuperPotatoMen** [comment]
Patch notes:

Hi there! This the SuperPotatomen helping out tidusjar on github.
I'm happy to announce we have a early christmas present for you guys. 
This is the big early access preview release of 1.10.0!

In this build we fixed 27 reported bugs, implementing 18 community idea's, closed 43 issues on github, make great new features and do big improvements on the request system.

The biggest new features is the User management, the Fault Queue, auto updater (hello again ;-)) and the introduction of the different update branches (Development, early access preview and stable)

We 

User management
You can manage every plexrequest user differently, give them the right permissions or deny something.
Multi admin, read only users and add new user accounts is now possible in the User management option!


Fault Queue feature
Sometimes isn't possible to add a brand new show or movie to sonarr/SickRage/CouchPotato because the information website tvmaze don't have all the information yet.
The request failed and the plex request user can't request that nicely show/movie.
In this release we store the request in the fault queue and try it every 24 hours to add it again.
The server admin will be receive also a email message.


Auto updater
finally it is back! No more manually downloading zip files and unrar the files.

different update branches
For better support, less bugs and make new features we introduce 3 different update branches:
Development, early access preview and stable.
The biggest differents between the 3 update branches is you can now easly helping us out with testing the new upcomming features and bug fixes.
if you like to have a more stable one and don't like to update a lot of time you can choose the stable branche.

Full patch notes:


Features added
- User management (create multiple admins, information page  about all of our Plex Users, Allow users to request tv shows, movies, or both per user)
- Fault Queue feature (Better handle add future tv shows/movies when tv maze don't have all of the information, Buffer user requests into a waiting queue when CP/Sonarr is offline)
- Auto updater
- different update branches
- override plex machine identifier
- Repair automatic brokenimages on the request page
- Change HTTP Listener
- Copy to clipboard feature for api key
- Sent a email notification when you deny a request after a approval.

Improvements:
- Better handle big plex library's so plex availability checker do his work mutch faster. 
- Newsletter supports now Managed Users under a plex pass account
- Change retry time when cp/sonarr gives a error

Bug fixed

- API Key not saving
- Notification is sent when an item is "Mark Unavailable" 
- Unable to see Requests for approval
- 403 error when entering the settings page after admin login (dev branch)
- Email Newsletter Error with Managed Users
- Crash on migration from 1.9.7 to 1.10.0 (dev branch)
- Crash on starting up plexrequest 1.10.0 (dev branch)
- Admin panel and usermanagement page doesn't work (dev branch)
- Management system doesn't support plex users
- Plexrequest doesn't send a email notification when a user changes his plex username account
- Recently Added Email Notification Error
- Landing page ingores the show before the login button
- Logs saved where mono command was run
- no favicon when using reserve proxy
- api key generation doesn't work (dev branch)
- migration error after starting up (dev branch)
- Dev branch keep saying there is a update (dev branch)
- Auto updater doesn't work
- Can not log out when on Logs page and sticky log level button
- Can't see the loading circle on the  the user management page dev branch)

**Comment by bobloadmire** [comment]
Hey awesome! One question though, Not seeing a 1.10 release in teh release section?

**Comment by taytortots** [comment]
@bobloadmire It isn't out yet. This is just detailing what will be included when it is ready.

**Comment by SuperPotatoMen** [comment]
Hi @bobloadmire  , that's right!
The 1.10 release is not ready yet for a big release. Tidusjar needs more time to fix the bugs in the currerent dev build.

**Comment by SuperPotatoMen** [comment]
@delphiactual

thank you for you're help on the wikipedia page 👍

**Comment by SuperPotatoMen** [comment]
1.10.0 has now available in the eap branch. I will post a patch note later on.
