### ISSUE TITLE
[Feature Request] Seperate directories for content types

### ISSUE THREAD

**Issue by jneljeff** [tidusjar/PlexRequests.Net#710]
In my library I have a separate directory for ended TV, but I know some people do this by necessity for things like Anime.  It would be nice to be able to separate requests based on status or type.

**Comment by SuperPotatoMen** [comment]
Hi,  I'm not totally sure what You are requesting here.

**Comment by jneljeff** [comment]
Yea, so we are able to set what directory PlexRequests tells Sonarr to save requested shows in, right?  It would be nice to be able to change that directory based on some sort of variable (such as if the series has ended or is continuing).  A more practical reason for a function like this would be the need to sort anime differently than traditional shows which is already supported by Sonarr and SickRage.

As of now, I have PlexRequests put shows in a special tv_requested folder to be moved to the correct library upon completion.  Having this done automatically would be one less thing to touch.

**Comment by SuperPotatoMen** [comment]
I get it! Is a populair Request.  You're not the first one :) We have already planned this feature in version 2.0

You can follow master issue for the progress: https://github.com/tidusjar/PlexRequests.Net/issues/445
