### ISSUE TITLE
Plexrequests is Running But Can't Connect

### ISSUE THREAD

**Issue by Aireezz** [tidusjar/PlexRequests.Net#711]
#### Applicable Logs (from `/logs/` directory or the Admin page):

http://pastebin.com/M8SBjmsG

#### Reproduction Steps:

I have to restart PR to be able to use it... quite often (at least once every 30 mins.) It works for a few minutes, then won't load any pages, or let me connect in a new tab (Just spins all day). The process says it is running and is fine, I looked through the log some but I'm not sure how to fix. Thanks!

**Comment by tidusjar** [comment]
Looks like we are unable to open the database for some reason:

```
Error: Mono.Data.Sqlite.SqliteException: Unable to open the database file
```

**Comment by Aireezz** [comment]
I saw that, but I'm not sure why or how to fix. The permissions are correct on the files, what do you suggest?

**Comment by tidusjar** [comment]
turn your AV off, start it up and see if it makes a difference? (Turn your av back on after testing this)

**Comment by Aireezz** [comment]
I don't have any AV, but for what ever reason it's working now. (Didn't
even restart PR) I'll monitor for a little bit to see if it returns

**Comment by SuperPotatoMen** [comment]
Strange :/  pleas open a new issue is you have it again or re-open this one.
