### ISSUE TITLE
API key keeps displaying incorrect values

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/PlexRequests.Net#720]
Plex Requests.Net Version: Development 1.10.1020

Operating System: Windows 10 Home

Reproduction Steps:

Whenever you navigate to the settings page it displays an incorrect API key every time, even after clicking refresh and submit. I've listed an example of the incorrect value below:
",a8d5e1429921495588b7a8c6cb6ba694,10c2d73a5177472fa3316037b397908f,eb424cae8b5a4c209f26a80724e38b38,5452eecf602d40f6b172c4780ea028a2,a08e06612680470895e2b55859860054"

Not too sure if affects any functionality since everything seems to be connected to my Plex Server just fine. I'm also very happy to say the querying works perfectly since I have a rather large Plex library of around 15TBs and several different libraries/categories.  

If any logs will help, please let me know and I'll post them to pastebin and post the link.

**Comment by tidusjar** [comment]
That's the Plex request API key. I did notice that, thanks for reporting it, I'll fix it ASAP!

**Comment by tidusjar** [comment]
After pressing refresh and reloading the page I can no longer recreate this. 

Do you know how to recreate this?

**Comment by chrisausbun** [comment]
I am getting this from when I navigate to the Plex Request settings page from any other Plex Requests page. For example, when I click refresh the API key is correct and then I click submit, then navigate to search, requests, issues, or even a different page in the settings, then when I navigate back to the page with the API key, it goes back to the incorrect value.


On Dec 8, 2016, at 6:11 AM, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


After pressing refresh and reloading the page I can no longer recreate this.

Do you know how to recreate this?

-

**Comment by chrisjace** [comment]
I am experiencing the exact same behavior experienced by Chris as well.

**Comment by tidusjar** [comment]
Ok. I'll fix that one tomorrow

**Comment by chrisausbun** [comment]
Ok awesome. Thanks @tidusjar.
