### ISSUE TITLE
Landing Page not working

### ISSUE THREAD

**Issue by lastb0isct** [tidusjar/PlexRequests.Net#721]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Reproduction Steps: Enable all the options on the Landing Page option page.

Logout and load the page, but only get shown the normal login page.  No Landing Page is displayed.

**Comment by SuperPotatoMen** [comment]
Hi, 

This is fixed already in the dev branch.  Pleas wait for the 1.10. 0 release. 

See mail issue https://github.com/tidusjar/PlexRequests.Net/issues/703
