### ISSUE TITLE
Newsletter not sending test email

### ISSUE THREAD

**Issue by lastb0isct** [tidusjar/PlexRequests.Net#722]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Applicable Logs (from `/logs/` directory or the Admin page):

Value cannot be null. Parameter name: source

#### Reproduction Steps:

- Verify test emails are working.
- Both options selected on Newsletter settings page
- Click "send test email to admin"
- Get following error: "Value cannot be null. Parameter name: source"
- Don't receive test email

I haven't verified if the actual update email is going to be sent out, but I want to see what it looks like.

**Comment by SuperPotatoMen** [comment]
https://github.com/tidusjar/PlexRequests.Net/issues/717
