### ISSUE TITLE
Check a different library/couchpotato for a request

### ISSUE THREAD

**Issue by topper59** [tidusjar/PlexRequests.Net#723]
Sorry if this has been asked before!

I have a Movie library in Plex and now a Request library in Plex. This is so requests go to their own space and don't interfere with my original library. I also have a separate couchpotato instance running just for the requests. As a result, the "requests couchpotato" and "requests library" are empty. If I request a movie that is currently in my normal movie library (and CP) it still goes through. Is there a way to check a different library/CP for duplicate movies?

**Comment by SuperPotatoMen** [comment]
Now the systeem is checking you plex database.   We aware of a problem with slow indexing Large databases.

Can you wait for the release of 1.10.0 and check if you have stil l this problem?

**Comment by topper59** [comment]
Sure thing, it's not urgent or anything. I've got about 550 movies in my main library

**Comment by SuperPotatoMen** [comment]
Hmmm maybe it is a bug because plexrequest don't check all libraries in the plex database.

@tidusjar can you look at this one?

**Comment by tidusjar** [comment]
I'll need to do some investigation into this one :( Not sure how the Plex API handles this,

**Comment by SuperPotatoMen** [comment]
Marked with priority tag,  because more endusers are reporting this problem

**Comment by tidusjar** [comment]
I'll take a look tonight, does anyone know how to create a new library?

**Comment by tidusjar** [comment]
Ok, so after looking at the code, it seems as long as the library is added correctly and have the correct metadata type (e.g. Movie or Tv Show) we should be picking it up.

E.g. I added a library containing Movies called "Test"
![image](https://cloud.githubusercontent.com/assets/6642220/21011854/22abe038-bd4b-11e6-9a83-88e89527b3b4.png)

**Comment by tidusjar** [comment]
I added some GoPro videos into that library and told Plex that the metadata is the new Starwars Rogue One. This is my result on searching:

![image](https://cloud.githubusercontent.com/assets/6642220/21012637/eaca423c-bd4e-11e6-9ae9-ff2928aaaf38.png)

**Comment by topper59** [comment]
It's working! Movies from both libraries show up as available, it must have just been some glitch when I first got plex requests up and running.

**Comment by chrisjace** [comment]
Tested and verified as working fine for me as well in 1.10.1041 (Mac OS X). Thx!

**Comment by SuperPotatoMen** [comment]
@topper59 to let work you "view in plex" option, you need to enable the option " DLNA" in you're plex settings. Other way, you need to set a plex identify token in the plex request  settings. other way it won't work.
