### ISSUE TITLE
Requests shows Available: 0 / 0

### ISSUE THREAD

**Issue by Dgameman1** [tidusjar/PlexRequests.Net#724]
Hey guys, when I look under requests in PlexRequests, I see that one of the accepted Requests shows

> Available: 0 / 0

I have them downloaded it manually and it's even showing up on Sonarr and Plex.

Any ideas?

#### Plex Requests.Net Version:
Branch: master
Version: 1.15.6

#### Operating System:
Ubuntu Server 16.04.1 LTS

#### Mono Version:
```
:~$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

#### Reproduction Steps:

Have a user request the walking dead and then approve it and manually download it from Sonarr

**Comment by tidusjar** [comment]
Can you upload a screen shot of what you mean?

**Comment by Dgameman1** [comment]
@tidusjar  Sure!

https://i.imgur.com/TbS720u.png

That is the image I am seeing.

It says that Available is 0/0

But I downloaded it episodes off of Sonarr and you can go ahead and watch it on my plex server right now.

So not sure what it means by Available 0/0

**Comment by tidusjar** [comment]
Sorry but you are using the meteor version of Plex Requests and not my .Ner version :)

**Comment by SuperPotatoMen** [comment]
@Dgameman1, best way you can open a issue over here: https://github.com/lokenx/plexrequests-meteor

**Comment by Dgameman1** [comment]
@tidusjar  Omg I'm so sorry
