### ISSUE TITLE
Handle duplicate usernames plex.tv - local accounts

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#727]
You can make now a local user with a same username of plex.tv.
However it isn't possible to manage the permissions of the plex.tv account.
The plex.tv account don't show up in the user management page and also not in your database table "plexusers"
This will be a problem if you make a admin account with the same username of a plex.tv account on the initial setup page.

**Comment by SuperPotatoMen** [comment]
related with https://github.com/tidusjar/PlexRequests.Net/issues/726

**Comment by tidusjar** [comment]
Note:

If a Plex.Tv user changes their name and we already have a local user with the same name, the Plex.Tv user will NOT inherit the local users permissions.

This is a security measure as anyone can change their Plex.Tv username and they could possibly end up inheriting admin permissions. 

So they will keep their current permissions.
