### ISSUE TITLE
Upgrading wipes settings

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#73]
Any information on upgrading would be great. I can't figure out what file contains the settings so anytime I upgrade I have to reconfigure.

The method I'm currently using to update is download the release zip and replacing all files.

**Comment by tidusjar** [comment]
replacing all the files should work. 

The settings are stored in a file called PlexRequests.sqlite

**Comment by curlz620** [comment]
Until this is changed with auto-update or something. maybe throw this up on the main page under installation? had to hunt for it.

**Comment by tedrock** [comment]
I found it in the FAQ thus why I closed this, I had no idea people were commenting on it.

**Comment by tidusjar** [comment]
I'll add it to the main page (readme)
