### ISSUE TITLE
Error displaying details for pending and resolved issues

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/PlexRequests.Net#730]
Plex Requests.Net Version: Development 1.10.1023

Operating System: Windows 10 Home

Reproduction Steps:

Whenever you click details for any pending or resolved issues it displays the following message below:

![details](https://cloud.githubusercontent.com/assets/22944072/20872625/ce57c6ee-ba54-11e6-8fbd-dd7a87c74a79.png)

If any logs will help, please let me know and I'll post them to pastebin and post the link.

**Comment by chrisausbun** [comment]
Just clicked on Details below the "We're sorry :-(" and this is what it displayed:

Error Details
Error compiling template: Views/Issues/Details.cshtml

Errors:
[CS1928] Line: 14 Column: 77 - 'Nancy.ViewEngines.Razor.HtmlHelpers' does not contain a definition for 'HasAnyPermission' and the best extension method overload 'PlexRequests.UI.Helpers.HtmlSecurityHelper.HasAnyPermission(Nancy.ViewEngines.Razor.HtmlHelpers, bool, params PlexRequests.Helpers.Permissions.Permissions[])' has some invalid arguments (show)
[CS1503] Line: 14 Column: 99 - Argument 2: cannot convert from 'PlexRequests.Helpers.Permissions.Permissions' to 'bool' (show)

Details:
@using System.Linq
@using PlexRequests.Core.Models
@using PlexRequests.Helpers
@using PlexRequests.Helpers.Permissions
@using PlexRequests.UI.Helpers
@{
    var baseUrl = Html.GetBaseUrl();
    var formAction = string.Empty;
    if (!string.IsNullOrEmpty(baseUrl.ToHtmlString()))
    {
        formAction = "/" + baseUrl.ToHtmlString();
    }

    var isAdmin = Html.HasAnyPermission(true, Permissions.Administrator) || Html.HasAnyPermission(Permissions.ManageRequests);

}
<h1>Details</h1>

<div class="row">
    <div class="col-md-3">
        <img src="@Model.PosterUrl" />
    </div>
    <div class="col-md-9">
        <h4>Issues For "@Model.Title"</h4>
    </div>
    @if (isAdmin)
    {
        <div class="col-md-1">

            @if (Model.IssueStatus == IssueStatus.PendingIssue)
            {
                <form action="@formAction/issues/resolvedUpdate" method="post">
                    <input id="issueId" name="issueId" value="@Model.Id" hidden="hidden" />
                    <button type="submit" id="@Model.Id" class="btn btn-sm btn-success-outline dropdown-toggle resolve">Resolve</button>
                </form>
            }
            @if (Model.IssueStatus == IssueStatus.ResolvedIssue)
            {
                <form action="@formAction/issues/remove" method="post" id="removeForm">
                    <input id="issueId" name="issueId" value="@Model.Id" hidden="hidden" />
                    <button type="submit" id="@Model.Id" class="btn btn-sm btn-danger-outline dropdown-toggle delete">Remove</button>
                </form>
            }
        </div>
    }
    <br />


</div>

<hr />

@foreach (var issue in Model.Issues)
{
    <div class="row">
        <div class="col-sm-11">
            <div><strong>Type:</strong> @StringHelper.ToCamelCaseWords(issue.Issue.ToString())</div>
            <div><strong>User Reported:</strong> @issue.UserReported</div>
            <div><strong>User Note:</strong> @issue.UserNote</div>
            <div><strong>Admin Note:</strong>@issue.AdminNote</div>
        </div>
        @if (isAdmin)
        {
            <div class="col-sm-1">
                <form action="@formAction/issues/clear" method="post">
                    <input name="issueId" value="@Model.Id" hidden="hidden" />
                    <input name="issue" value="@((int) issue.Issue)" hidden="hidden" />

                    <button type="submit" id="@Model.Id" class="btn btn-sm btn-info-outline dropdown-toggle">Clear</button>
                </form>
            </div>
            <div class="col-sm-1">
                <button id="@Model.Id" issue-select="4" class="note btn btn-sm btn-primary-outline dropdown-toggle" data-identifier="@Model.Id" data-issue="@((int) issue.Issue)" href="#" data-toggle="modal" data-target="#noteModal">Add Note</button>
            </div>
        }
    </div>
            <br />
            <hr />
}

<div class="modal fade" id="noteModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
                <h4 class="modal-title">Add a note</h4>
            </div>
            <form method="POST" action="@formAction/issues/addnote" id="noteForm">
                <div class="modal-body">
                    <input name="requestId" class="noteId" type="text" hidden="hidden" value="" />
                    <input name="issue" class="issue" type="text" hidden="hidden" value="" />
                    <textarea class="form-control form-control-custom" rows="3" id="noteArea" name="noteArea"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger-outline" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary-outline theNoteSaveButton" data-dismiss="modal">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

@Html.LoadIssueDetailsAssets()

Compilation Source:
//------------------------------------------------------------------------------
Line 1:	// <auto-generated>
Line 2:	//     This code was generated by a tool.
Line 3:	//     Runtime Version:4.0.30319.42000
Line 4:	//
Line 5:	//     Changes to this file may cause incorrect behavior and will be lost if
Line 6:	//     the code is regenerated.
Line 7:	// </auto-generated>
Line 8:	//------------------------------------------------------------------------------
Line 9:	
Line 10:	namespace RazorOutput {
Line 11:	    using Microsoft.CSharp.RuntimeBinder;
Line 12:	    using System;
Line 13:	    using System.IO;
Line 14:	    
Line 15:	    #line 1 "roo"
Line 16:	    using System.Linq;
Line 17:	    
Line 18:	    #line default
Line 19:	    #line hidden
Line 20:	    
Line 21:	    #line 2 "roo"
Line 22:	    using PlexRequests.Core.Models;
Line 23:	    
Line 24:	    #line default
Line 25:	    #line hidden
Line 26:	    
Line 27:	    #line 3 "roo"
Line 28:	    using PlexRequests.Helpers;
Line 29:	    
Line 30:	    #line default
Line 31:	    #line hidden
Line 32:	    
Line 33:	    #line 4 "roo"
Line 34:	    using PlexRequests.Helpers.Permissions;
Line 35:	    
Line 36:	    #line default
Line 37:	    #line hidden
Line 38:	    
Line 39:	    #line 5 "roo"
Line 40:	    using PlexRequests.UI.Helpers;
Line 41:	    
Line 42:	    #line default
Line 43:	    #line hidden
Line 44:	    using PlexRequests.UI.Models;
Line 45:	    
Line 46:	    
Line 47:	    public class RazorView : Nancy.ViewEngines.Razor.NancyRazorViewBase {
Line 48:	        
Line 49:	#line hidden
Line 50:	        
Line 51:	        public RazorView() {
Line 52:	        }
Line 53:	        
Line 54:	        public override void Execute() {
Line 55:	            
Line 56:	            #line 6 "roo"
Line 57:	  
    var baseUrl = Html.GetBaseUrl();
    var formAction = string.Empty;
    if (!string.IsNullOrEmpty(baseUrl.ToHtmlString()))
    {
        formAction = "/" + baseUrl.ToHtmlString();
    }

    var isAdmin = Html.HasAnyPermission(true, Permissions.Administrator) || Html.HasAnyPermission(Permissions.ManageRequests);


Line 58:	            
Line 59:	            #line default
Line 60:	            #line hidden
Line 61:	WriteLiteral("\n<h1>Details</h1>\n\n<div");
Line 62:	
Line 63:	WriteLiteral(" class=\"row\"");
Line 64:	
Line 65:	WriteLiteral(">\n    <div");
Line 66:	
Line 67:	WriteLiteral(" class=\"col-md-3\"");
Line 68:	
Line 69:	WriteLiteral(">\n        <img");
Line 70:	
Line 71:	WriteAttribute("src", Tuple.Create(" src=\"", 549), Tuple.Create("\"", 571)
Line 72:	            
Line 73:	            #line 21 "roo"
Line 74:	, Tuple.Create(Tuple.Create("", 555), Tuple.Create<System.Object, System.Int32>(Model.PosterUrl
Line 75:	            
Line 76:	            #line default
Line 77:	            #line hidden
Line 78:	, 555), false)
Line 79:	);
Line 80:	
Line 81:	WriteLiteral(" />\n    </div>\n    <div");
Line 82:	
Line 83:	WriteLiteral(" class=\"col-md-9\"");
Line 84:	
Line 85:	WriteLiteral(">\n        <h4>Issues For \"");
Line 86:	
Line 87:	            
Line 88:	            #line 24 "roo"
Line 89:	                   Write(Model.Title);
Line 90:	
Line 91:	            
Line 92:	            #line default
Line 93:	            #line hidden
Line 94:	WriteLiteral("\"</h4>\n    </div>\n");
Line 95:	
Line 96:	            
Line 97:	            #line 26 "roo"
Line 98:	    
Line 99:	            
Line 100:	            #line default
Line 101:	            #line hidden
Line 102:	            
Line 103:	            #line 26 "roo"
Line 104:	     if (isAdmin)
    {

Line 105:	            
Line 106:	            #line default
Line 107:	            #line hidden
Line 108:	WriteLiteral("        <div");
Line 109:	
Line 110:	WriteLiteral(" class=\"col-md-1\"");
Line 111:	
Line 112:	WriteLiteral(">\n\n");
Line 113:	
Line 114:	            
Line 115:	            #line 30 "roo"
Line 116:	            
Line 117:	            
Line 118:	            #line default
Line 119:	            #line hidden
Line 120:	            
Line 121:	            #line 30 "roo"
Line 122:	             if (Model.IssueStatus == IssueStatus.PendingIssue)
            {

Line 123:	            
Line 124:	            #line default
Line 125:	            #line hidden
Line 126:	WriteLiteral("                <form");
Line 127:	
Line 128:	WriteAttribute("action", Tuple.Create(" action=\"", 823), Tuple.Create("\"", 865)
Line 129:	            
Line 130:	            #line 32 "roo"
Line 131:	, Tuple.Create(Tuple.Create("", 832), Tuple.Create<System.Object, System.Int32>(formAction
Line 132:	            
Line 133:	            #line default
Line 134:	            #line hidden
Line 135:	, 832), false)
Line 136:	, Tuple.Create(Tuple.Create("", 843), Tuple.Create("/issues/resolvedUpdate", 843), true)
Line 137:	);
Line 138:	
Line 139:	WriteLiteral(" method=\"post\"");
Line 140:	
Line 141:	WriteLiteral(">\n                    <input");
Line 142:	
Line 143:	WriteLiteral(" id=\"issueId\"");
Line 144:	
Line 145:	WriteLiteral(" name=\"issueId\"");
Line 146:	
Line 147:	WriteAttribute("value", Tuple.Create(" value=\"", 936), Tuple.Create("\"", 953)
Line 148:	            
Line 149:	            #line 33 "roo"
Line 150:	, Tuple.Create(Tuple.Create("", 944), Tuple.Create<System.Object, System.Int32>(Model.Id
Line 151:	            
Line 152:	            #line default
Line 153:	            #line hidden
Line 154:	, 944), false)
Line 155:	);
Line 156:	
Line 157:	WriteLiteral(" hidden=\"hidden\"");
Line 158:	
Line 159:	WriteLiteral(" />\n                    <button");
Line 160:	
Line 161:	WriteLiteral(" type=\"submit\"");
Line 162:	
Line 163:	WriteAttribute("id", Tuple.Create(" id=\"", 1015), Tuple.Create("\"", 1029)
Line 164:	            
Line 165:	            #line 34 "roo"
Line 166:	, Tuple.Create(Tuple.Create("", 1020), Tuple.Create<System.Object, System.Int32>(Model.Id
Line 167:	            
Line 168:	            #line default
Line 169:	            #line hidden
Line 170:	, 1020), false)
Line 171:	);
Line 172:	
Line 173:	WriteLiteral(" class=\"btn btn-sm btn-success-outline dropdown-toggle resolve\"");
Line 174:	
Line 175:	WriteLiteral(">Resolve</button>\n                </form>\n");
Line 176:	
Line 177:	            
Line 178:	            #line 36 "roo"
Line 179:	            }

Line 180:	            
Line 181:	            #line default
Line 182:	            #line hidden
Line 183:	WriteLiteral("            ");
Line 184:	
Line 185:	            
Line 186:	            #line 37 "roo"
Line 187:	             if (Model.IssueStatus == IssueStatus.ResolvedIssue)
            {

Line 188:	            
Line 189:	            #line default
Line 190:	            #line hidden
Line 191:	WriteLiteral("                <form");
Line 192:	
Line 193:	WriteAttribute("action", Tuple.Create(" action=\"", 1249), Tuple.Create("\"", 1283)
Line 194:	            
Line 195:	            #line 39 "roo"
Line 196:	, Tuple.Create(Tuple.Create("", 1258), Tuple.Create<System.Object, System.Int32>(formAction
Line 197:	            
Line 198:	            #line default
Line 199:	            #line hidden
Line 200:	, 1258), false)
Line 201:	, Tuple.Create(Tuple.Create("", 1269), Tuple.Create("/issues/remove", 1269), true)
Line 202:	);
Line 203:	
Line 204:	WriteLiteral(" method=\"post\"");
Line 205:	
Line 206:	WriteLiteral(" id=\"removeForm\"");
Line 207:	
Line 208:	WriteLiteral(">\n                    <input");
Line 209:	
Line 210:	WriteLiteral(" id=\"issueId\"");
Line 211:	
Line 212:	WriteLiteral(" name=\"issueId\"");
Line 213:	
Line 214:	WriteAttribute("value", Tuple.Create(" value=\"", 1370), Tuple.Create("\"", 1387)
Line 215:	            
Line 216:	            #line 40 "roo"
Line 217:	, Tuple.Create(Tuple.Create("", 1378), Tuple.Create<System.Object, System.Int32>(Model.Id
Line 218:	            
Line 219:	            #line default
Line 220:	            #line hidden
Line 221:	, 1378), false)
Line 222:	);
Line 223:	
Line 224:	WriteLiteral(" hidden=\"hidden\"");
Line 225:	
Line 226:	WriteLiteral(" />\n                    <button");
Line 227:	
Line 228:	WriteLiteral(" type=\"submit\"");
Line 229:	
Line 230:	WriteAttribute("id", Tuple.Create(" id=\"", 1449), Tuple.Create("\"", 1463)
Line 231:	            
Line 232:	            #line 41 "roo"
Line 233:	, Tuple.Create(Tuple.Create("", 1454), Tuple.Create<System.Object, System.Int32>(Model.Id
Line 234:	            
Line 235:	            #line default
Line 236:	            #line hidden
Line 237:	, 1454), false)
Line 238:	);
Line 239:	
Line 240:	WriteLiteral(" class=\"btn btn-sm btn-danger-outline dropdown-toggle delete\"");
Line 241:	
Line 242:	WriteLiteral(">Remove</button>\n                </form>\n");
Line 243:	
Line 244:	            
Line 245:	            #line 43 "roo"
Line 246:	            }

Line 247:	            
Line 248:	            #line default
Line 249:	            #line hidden
Line 250:	WriteLiteral("        </div>\n");
Line 251:	
Line 252:	            
Line 253:	            #line 45 "roo"
Line 254:	    }

Line 255:	            
Line 256:	            #line default
Line 257:	            #line hidden
Line 258:	WriteLiteral("    <br />\n\n\n</div>\n\n<hr />\n\n");
Line 259:	
Line 260:	            
Line 261:	            #line 53 "roo"
Line 262:	 foreach (var issue in Model.Issues)
{

Line 263:	            
Line 264:	            #line default
Line 265:	            #line hidden
Line 266:	WriteLiteral("    <div");
Line 267:	
Line 268:	WriteLiteral(" class=\"row\"");
Line 269:	
Line 270:	WriteLiteral(">\n        <div");
Line 271:	
Line 272:	WriteLiteral(" class=\"col-sm-11\"");
Line 273:	
Line 274:	WriteLiteral(">\n            <div><strong>Type:</strong> ");
Line 275:	
Line 276:	            
Line 277:	            #line 57 "roo"
Line 278:	                                   Write(StringHelper.ToCamelCaseWords(issue.Issue.ToString()));
Line 279:	
Line 280:	            
Line 281:	            #line default
Line 282:	            #line hidden
Line 283:	WriteLiteral("</div>\n            <div><strong>User Reported:</strong> ");
Line 284:	
Line 285:	            
Line 286:	            #line 58 "roo"
Line 287:	                                            Write(issue.UserReported);
Line 288:	
Line 289:	            
Line 290:	            #line default
Line 291:	            #line hidden
Line 292:	WriteLiteral("</div>\n            <div><strong>User Note:</strong> ");
Line 293:	
Line 294:	            
Line 295:	            #line 59 "roo"
Line 296:	                                        Write(issue.UserNote);
Line 297:	
Line 298:	            
Line 299:	            #line default
Line 300:	            #line hidden
Line 301:	WriteLiteral("</div>\n            <div><strong>Admin Note:</strong>");
Line 302:	
Line 303:	            
Line 304:	            #line 60 "roo"
Line 305:	                                        Write(issue.AdminNote);
Line 306:	
Line 307:	            
Line 308:	            #line default
Line 309:	            #line hidden
Line 310:	WriteLiteral("</div>\n        </div>\n");
Line 311:	
Line 312:	            
Line 313:	            #line 62 "roo"
Line 314:	        
Line 315:	            
Line 316:	            #line default
Line 317:	            #line hidden
Line 318:	            
Line 319:	            #line 62 "roo"
Line 320:	         if (isAdmin)
        {

Line 321:	            
Line 322:	            #line default
Line 323:	            #line hidden
Line 324:	WriteLiteral("            <div");
Line 325:	
Line 326:	WriteLiteral(" class=\"col-sm-1\"");
Line 327:	
Line 328:	WriteLiteral(">\n                <form");
Line 329:	
Line 330:	WriteAttribute("action", Tuple.Create(" action=\"", 2137), Tuple.Create("\"", 2170)
Line 331:	            
Line 332:	            #line 65 "roo"
Line 333:	, Tuple.Create(Tuple.Create("", 2146), Tuple.Create<System.Object, System.Int32>(formAction
Line 334:	            
Line 335:	            #line default
Line 336:	            #line hidden
Line 337:	, 2146), false)
Line 338:	, Tuple.Create(Tuple.Create("", 2157), Tuple.Create("/issues/clear", 2157), true)
Line 339:	);
Line 340:	
Line 341:	WriteLiteral(" method=\"post\"");
Line 342:	
Line 343:	WriteLiteral(">\n                    <input");
Line 344:	
Line 345:	WriteLiteral(" name=\"issueId\"");
Line 346:	
Line 347:	WriteAttribute("value", Tuple.Create(" value=\"", 2228), Tuple.Create("\"", 2245)
Line 348:	            
Line 349:	            #line 66 "roo"
Line 350:	, Tuple.Create(Tuple.Create("", 2236), Tuple.Create<System.Object, System.Int32>(Model.Id
Line 351:	            
Line 352:	            #line default
Line 353:	            #line hidden
Line 354:	, 2236), false)
Line 355:	);
Line 356:	
Line 357:	WriteLiteral(" hidden=\"hidden\"");
Line 358:	
Line 359:	WriteLiteral(" />\n                    <input");
Line 360:	
Line 361:	WriteLiteral(" name=\"issue\"");
Line 362:	
Line 363:	WriteAttribute("value", Tuple.Create(" value=\"", 2305), Tuple.Create("\"", 2333)
Line 364:	            
Line 365:	            #line 67 "roo"
Line 366:	, Tuple.Create(Tuple.Create("", 2313), Tuple.Create<System.Object, System.Int32>((int) issue.Issue
Line 367:	            
Line 368:	            #line default
Line 369:	            #line hidden
Line 370:	, 2313), false)
Line 371:	);
Line 372:	
Line 373:	WriteLiteral(" hidden=\"hidden\"");
Line 374:	
Line 375:	WriteLiteral(" />\n\n                    <button");
Line 376:	
Line 377:	WriteLiteral(" type=\"submit\"");
Line 378:	
Line 379:	WriteAttribute("id", Tuple.Create(" id=\"", 2396), Tuple.Create("\"", 2410)
Line 380:	            
Line 381:	            #line 69 "roo"
Line 382:	, Tuple.Create(Tuple.Create("", 2401), Tuple.Create<System.Object, System.Int32>(Model.Id
Line 383:	            
Line 384:	            #line default
Line 385:	            #line hidden
Line 386:	, 2401), false)
Line 387:	);
Line 388:	
Line 389:	WriteLiteral(" class=\"btn btn-sm btn-info-outline dropdown-toggle\"");
Line 390:	
Line 391:	WriteLiteral(">Clear</button>\n                </form>\n            </div>\n");
Line 392:	
Line 393:	WriteLiteral("            <div");
Line 394:	
Line 395:	WriteLiteral(" class=\"col-sm-1\"");
Line 396:	
Line 397:	WriteLiteral(">\n                <button");
Line 398:	
Line 399:	WriteAttribute("id", Tuple.Create(" id=\"", 2580), Tuple.Create("\"", 2594)
Line 400:	            
Line 401:	            #line 73 "roo"
Line 402:	, Tuple.Create(Tuple.Create("", 2585), Tuple.Create<System.Object, System.Int32>(Model.Id
Line 403:	            
Line 404:	            #line default
Line 405:	            #line hidden
Line 406:	, 2585), false)
Line 407:	);
Line 408:	
Line 409:	WriteLiteral(" issue-select=\"4\"");
Line 410:	
Line 411:	WriteLiteral(" class=\"note btn btn-sm btn-primary-outline dropdown-toggle\"");
Line 412:	
Line 413:	WriteLiteral(" data-identifier=\"");
Line 414:	
Line 415:	            
Line 416:	            #line 73 "roo"
Line 417:	                                                                                                                                Write(Model.Id);
Line 418:	
Line 419:	            
Line 420:	            #line default
Line 421:	            #line hidden
Line 422:	WriteLiteral("\"");
Line 423:	
Line 424:	WriteLiteral(" data-issue=\"");
Line 425:	
Line 426:	            
Line 427:	            #line 73 "roo"
Line 428:	                                                                                                                                                        Write((int) issue.Issue);
Line 429:	
Line 430:	            
Line 431:	            #line default
Line 432:	            #line hidden
Line 433:	WriteLiteral("\"");
Line 434:	
Line 435:	WriteLiteral(" href=\"#\"");
Line 436:	
Line 437:	WriteLiteral(" data-toggle=\"modal\"");
Line 438:	
Line 439:	WriteLiteral(" data-target=\"#noteModal\"");
Line 440:	
Line 441:	WriteLiteral(">Add Note</button>\n            </div>\n");
Line 442:	
Line 443:	            
Line 444:	            #line 75 "roo"
Line 445:	        }

Line 446:	            
Line 447:	            #line default
Line 448:	            #line hidden
Line 449:	WriteLiteral("    </div>\n");
Line 450:	
Line 451:	WriteLiteral("            <br />\n");
Line 452:	
Line 453:	WriteLiteral("            <hr />\n");
Line 454:	
Line 455:	            
Line 456:	            #line 79 "roo"
Line 457:	}

Line 458:	            
Line 459:	            #line default
Line 460:	            #line hidden
Line 461:	WriteLiteral("\n<div");
Line 462:	
Line 463:	WriteLiteral(" class=\"modal fade\"");
Line 464:	
Line 465:	WriteLiteral(" id=\"noteModal\"");
Line 466:	
Line 467:	WriteLiteral(">\n    <div");
Line 468:	
Line 469:	WriteLiteral(" class=\"modal-dialog\"");
Line 470:	
Line 471:	WriteLiteral(">\n        <div");
Line 472:	
Line 473:	WriteLiteral(" class=\"modal-content\"");
Line 474:	
Line 475:	WriteLiteral(">\n            <div");
Line 476:	
Line 477:	WriteLiteral(" class=\"modal-header\"");
Line 478:	
Line 479:	WriteLiteral(">\n                <button");
Line 480:	
Line 481:	WriteLiteral(" type=\"button\"");
Line 482:	
Line 483:	WriteLiteral(" class=\"close\"");
Line 484:	
Line 485:	WriteLiteral(" data-dismiss=\"modal\"");
Line 486:	
Line 487:	WriteLiteral(" aria-hidden=\"true\"");
Line 488:	
Line 489:	WriteLiteral("><i");
Line 490:	
Line 491:	WriteLiteral(" class=\"fa fa-times\"");
Line 492:	
Line 493:	WriteLiteral("></i></button>\n                <h4");
Line 494:	
Line 495:	WriteLiteral(" class=\"modal-title\"");
Line 496:	
Line 497:	WriteLiteral(">Add a note</h4>\n            </div>\n            <form");
Line 498:	
Line 499:	WriteLiteral(" method=\"POST\"");
Line 500:	
Line 501:	WriteAttribute("action", Tuple.Create(" action=\"", 3269), Tuple.Create("\"", 3304)
Line 502:	            
Line 503:	            #line 88 "roo"
Line 504:	, Tuple.Create(Tuple.Create("", 3278), Tuple.Create<System.Object, System.Int32>(formAction
Line 505:	            
Line 506:	            #line default
Line 507:	            #line hidden
Line 508:	, 3278), false)
Line 509:	, Tuple.Create(Tuple.Create("", 3289), Tuple.Create("/issues/addnote", 3289), true)
Line 510:	);
Line 511:	
Line 512:	WriteLiteral(" id=\"noteForm\"");
Line 513:	
Line 514:	WriteLiteral(">\n                <div");
Line 515:	
Line 516:	WriteLiteral(" class=\"modal-body\"");
Line 517:	
Line 518:	WriteLiteral(">\n                    <input");
Line 519:	
Line 520:	WriteLiteral(" name=\"requestId\"");
Line 521:	
Line 522:	WriteLiteral(" class=\"noteId\"");
Line 523:	
Line 524:	WriteLiteral(" type=\"text\"");
Line 525:	
Line 526:	WriteLiteral(" hidden=\"hidden\"");
Line 527:	
Line 528:	WriteLiteral(" value=\"\"");
Line 529:	
Line 530:	WriteLiteral(" />\n                    <input");
Line 531:	
Line 532:	WriteLiteral(" name=\"issue\"");
Line 533:	
Line 534:	WriteLiteral(" class=\"issue\"");
Line 535:	
Line 536:	WriteLiteral(" type=\"text\"");
Line 537:	
Line 538:	WriteLiteral(" hidden=\"hidden\"");
Line 539:	
Line 540:	WriteLiteral(" value=\"\"");
Line 541:	
Line 542:	WriteLiteral(" />\n                    <textarea");
Line 543:	
Line 544:	WriteLiteral(" class=\"form-control form-control-custom\"");
Line 545:	
Line 546:	WriteLiteral(" rows=\"3\"");
Line 547:	
Line 548:	WriteLiteral(" id=\"noteArea\"");
Line 549:	
Line 550:	WriteLiteral(" name=\"noteArea\"");
Line 551:	
Line 552:	WriteLiteral("></textarea>\n                </div>\n                <div");
Line 553:	
Line 554:	WriteLiteral(" class=\"modal-footer\"");
Line 555:	
Line 556:	WriteLiteral(">\n                    <button");
Line 557:	
Line 558:	WriteLiteral(" type=\"button\"");
Line 559:	
Line 560:	WriteLiteral(" class=\"btn btn-danger-outline\"");
Line 561:	
Line 562:	WriteLiteral(" data-dismiss=\"modal\"");
Line 563:	
Line 564:	WriteLiteral(">Close</button>\n                    <button");
Line 565:	
Line 566:	WriteLiteral(" type=\"button\"");
Line 567:	
Line 568:	WriteLiteral(" class=\"btn btn-primary-outline theNoteSaveButton\"");
Line 569:	
Line 570:	WriteLiteral(" data-dismiss=\"modal\"");
Line 571:	
Line 572:	WriteLiteral(">Save changes</button>\n                </div>\n            </form>\n        </div>\n" +
Line 573:	"    </div>\n</div>\n\n");
Line 574:	
Line 575:	            
Line 576:	            #line 103 "roo"
Line 577:	Write(Html.LoadIssueDetailsAssets());
Line 578:	
Line 579:	            
Line 580:	            #line default
Line 581:	            #line hidden
Line 582:	        }
Line 583:	    }
Line 584:	}
Line 585:

**Comment by SuperPotatoMen** [comment]
Fixed
