### ISSUE TITLE
Whitelist is case sensitive. (similar to Issue #532)

### ISSUE THREAD

**Issue by jneljeff** [tidusjar/PlexRequests.Net#734]
Similar to issue #532, the whitelist only applies when a user logs in EXACTLY as it is written in the white list.

#### Plex Requests.Net Version:
1.9.7

#### Operating System:
Ubuntu 16.04

#### Reproduction Steps:

Add PLEX username to whitelist, log in with username in alternative case, request limitations are applied.

**Comment by SuperPotatoMen** [comment]
Hi,  in version 1.10.0 we are removing this option. You can manage the users in the brand new user management system
