### ISSUE TITLE
Search existing content across several Libraries?

### ISSUE THREAD

**Issue by chrisjace** [tidusjar/PlexRequests.Net#736]
when I search for movie, it does indicate if this movie is already available within one of my movie library, called NAS_Movies. However, I have several libraries, and if that movie was present within one of my other movie libraries, e.g. NAS_Films, it would not pick it up as already available. Is this intentional, i.e. scrapping of movie library being limited to 1 library only? 

Thanks for your clarification!

Rgds,
   Chrisjace

**Comment by SuperPotatoMen** [comment]
Hi,  we are investigate already this problem.  Thanks for reporting this. 
See main case: https://github.com/tidusjar/PlexRequests.Net/issues/723

**Comment by chrisjace** [comment]
Noted, will follow this within the main case.
Thanks!
