### ISSUE TITLE
Newsletter Settings - value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by chrisjace** [tidusjar/PlexRequests.Net#737]
Not sure if a bug, or whether I am missing something?
But I am getting a "value cannot be null. Parameter name: source" when trying to send e-mail within the Newsletter Settings area. Other E-mail notifications work fine, though.
Any idea how to resolve this?

Thanks!

**Comment by tidusjar** [comment]
A few people have this, I have been working on fixing issues with the newsletter, are you willing to try a dev build to confirm I have fixed the issue?

**Comment by chrisjace** [comment]
Noted, and thanks for the offer, but for now, I can leave wihout this feature. I'll wait that fix gets implemented into new upcoming release.

**Comment by chrisjace** [comment]
Could you just point me to the other tickets that were opened by other users to report that same issue? thx!

**Comment by tidusjar** [comment]
https://github.com/tidusjar/PlexRequests.Net/issues/717

**Comment by chrisjace** [comment]
Thx!
