### ISSUE TITLE
[Question] Upgrading to new releases, incl. Dev Builds, without loosing current DB and config?

### ISSUE THREAD

**Issue by chrisjace** [tidusjar/PlexRequests.Net#741]
Any chance to upgrade to new releases, incl. Dev Builds and EAPs, without loosing current DB and configuration? Even if manual steps are necessary (e.g. manual backup copy of current DB and config files), could you advise how to proceed? Thanks!

**Comment by tidusjar** [comment]
You should just be able to override everything in the folder.

The database file is `plexrequests.sqlite` and it is generated by Plex Requests, so that item is not in the .zip and will not get overwrote.

**Comment by chrisjace** [comment]
Thanks, worked fine indeed!
