### ISSUE TITLE
User Management Settings  disappears

### ISSUE THREAD

**Issue by SuperPotatoMen** [tidusjar/PlexRequests.Net#746]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:

Current Version:  1.10.1041

#### Operating System:
Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
no logs
```

#### Reproduction Steps:

If you click on "User Management Settings" it self, the option to click on it disappears. Also if you click on status

![image](https://cloud.githubusercontent.com/assets/2944704/21030118/2ef98ece-bd9d-11e6-8954-e586e72439b7.png)
![image](https://cloud.githubusercontent.com/assets/2944704/21030126/406e1652-bd9d-11e6-8b20-e4406c717603.png)

Other options are just fine:
![image](https://cloud.githubusercontent.com/assets/2944704/21030151/579b17bc-bd9d-11e6-9598-7346c2a4c71f.png)

**Comment by tidusjar** [comment]
Can you try clearing the cache? I cannot reproduce that from my end.

**Comment by tidusjar** [comment]
Any luck?

**Comment by SuperPotatoMen** [comment]
Nope I dont have time yet.  But i will clear my cache
