### ISSUE TITLE
[Feature Request] PlexRequests.Net and Plex Cloud

### ISSUE THREAD

**Issue by RXWatcher1** [tidusjar/PlexRequests.Net#751]
I'm part of the beta for Plex Cloud and I dont think it'll work with PlexRequests as you dont have a Plex Server hostname or IP to set within the PlexRequests app. It might take some rethinking to make this work so I thought I'd kick off a feature request to start brainstorming how to make it work.

Thank you!

**Comment by harroguk** [comment]
http://[PlexRequests.Net Site]/admin/plex

looks like you can specify a plex server by hostname or port there.

**Comment by RXWatcher1** [comment]
Going to close this. I did get it working. When you log into https://plex.tv/users/cpms there is a URL at the bottom. You enter that URL into plex requests including the https://, change the port to 443 and select SSL.
You can then authenticate to plex via Plex Requests.

**Comment by tidusjar** [comment]
Oh really? It works without any code changes (I wasn't expecting any but still)? nice!

**Comment by RXWatcher1** [comment]
yep..should document it somewhere though..it'll come up again...maybe in the wiki?

**Comment by tidusjar** [comment]
Yeah that would be good!
