### ISSUE TITLE
Auto-approve tv shows OR movies

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#76]
Hello,

I'd like to request a feature for allowing the admin to choose which section to auto-approve (TV shows or movies). Currently, you can only auto-approve everything, which is an annoyance because I would like to be able to auto-approve only movies and manual approve tv shows (movies are small... tv shows can be large). Thanks!

**Comment by tidusjar** [comment]
Great idea. It shall be done.

**Comment by tidusjar** [comment]
As you know, this has been done :) It will be in the next release now :+1:
