### ISSUE TITLE
Newsletter is only showing movies from the first Plex Library it detects

### ISSUE THREAD

**Issue by chrisausbun** [tidusjar/PlexRequests.Net#761]
#### Plex Requests.Net Version:
Dev 1.10.1060

#### Operating System:
Windows 10 Home

The Newsletter looks like it's only showing recently added items from the first Plex Movie Library it detects. My first Plex Library is "007 Movies" and they were all added at the same time, so it's showing all movies in only that library. The recently added TV shows seem to be working normally. It shows each episode like it should, but I don't know if that's because I only have one Library for TV shows.

I've listed a screenshot of all my Libraries below:

![plex libraries](https://cloud.githubusercontent.com/assets/22944072/21070980/f9f0b7ac-be46-11e6-9d60-5abbec755fcd.png)

**Comment by tidusjar** [comment]
Yeah I noticed this yesterday when I was working on it, I have fixed it but I thought I checked it in! Obviously not, i'll push a new Early access build out later today with the change
