### ISSUE TITLE
Google Analytics Fresh Install Error

### ISSUE THREAD

**Issue by JasonMeudt** [tidusjar/PlexRequests.Net#766]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
Any version from when you implemented Google Analytics
#### Operating System:
Win10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```

#### Reproduction Steps:
Fresh install on Win10...
![capture](https://cloud.githubusercontent.com/assets/10866095/21076954/3c3ec860-bf00-11e6-8fef-5af310636379.PNG)

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
Pleas confirm if this is the dev branch or stable branch
