### ISSUE TITLE
IIS Use

### ISSUE THREAD

**Issue by dabbers** [tidusjar/PlexRequests.Net#77]
Should provide us a way to install into an IIS instance. Or include instructions for us to do so ourselves (build -> deploy?).

**Comment by tidusjar** [comment]
The plan was to remove the dependency that is IIS. Since running things via IIS are usually platform specific. 

Why do you want to use IIS?

**Comment by dabbers** [comment]
You could split the resources to have a build type of asp.net website or executable. 
I already have IIS running which manages my websites. It is already setup with my firewalls. It already enables logging for access, already is an established service, and already works well. 
I suppose I could always reverse proxy the IIS host to the PlexRequest binding, but that requires the exe to be running in a user mode (as opposed to a service). 
Just my 2 cents. 

Date: Wed, 23 Mar 2016 00:03:16 -0700

**Comment by tidusjar** [comment]
I can see your point, but for now I think I'll just stick with the .exe, if there are more requests to allow it to be hosted in IIS then I'll reconsider. 

Thanks
