### ISSUE TITLE
Email notifications smtp username invalid

### ISSUE THREAD

**Issue by Fogest** [tidusjar/PlexRequests.Net#78]
I am trying to use Sendgrids SMTP to send email however I am being told by PlexRequest that my username is not valid. I assume this is because my username is not formatted like an email, however the sendgrid SMTP does not want an email in the username part of the connection.

**Comment by tidusjar** [comment]
Yes that is correct. 

I'll change this for the next release (in the next few days)

**Comment by tidusjar** [comment]
Fixed, this will be included in the next release.
