### ISSUE TITLE
Fresh Installation 

### ISSUE THREAD

**Issue by FunkMast3rFlex** [tidusjar/PlexRequests.Net#786]
So I have a Plex Server running on a Ubuntu 16.4 LTS system and in an effort to add to my server I decided to get PlexRequest.Net. The installation went fine but I dont know is it was something that I missed but I don't know where to go from here. I read the README.md but still nothing.

**Comment by tidusjar** [comment]
Errrrrr, what's the issue :smile:

**Comment by FunkMast3rFlex** [comment]
Yup thats the guide I followed and I even double checked everything. I tried reading other post to see if I could figure it out and they all seem to mention something about creating an account and logging as an admin. The only site I saw was http://plexrequest.com/ but that always returns my Plex.TV username as invalid nor will it let me create an account. Did I miss something?

**Comment by tidusjar** [comment]
Sorry, i'm still now following, what is the actual issue?

**Comment by FunkMast3rFlex** [comment]
How do I know if I did everything right? Where do I do to make manage requests? Where do I send my users if they want to make requests?

**Comment by SuperPotatoMen** [comment]
The software is a self hosting system. 

You after you start running it you need to open your browser and go to http://localhost/

**Comment by FunkMast3rFlex** [comment]
I went over my logs and found the issue. Service is running. Thanks.
