### ISSUE TITLE
Big security problem with admin login

### ISSUE THREAD

**Issue by bjonness406** [tidusjar/PlexRequests.Net#788]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.10.0
#### update Branch:
Stable

#### Operating System:
Docker

#### Reproduction Steps:

Don't enable user authentication and disable "require users to login with their passwords", so that everyone can login with any username they want, and without a password. 

After this, log out, then log in from the landing page (not the admin login), here you type in the username of admin. You are now logged in as the admin user, without typing the password as you would normaly do in the admin login page!
Now you have access to everything on plexrequest on the server, even the admin settings.

Logs:
```
We are authenticated! Setting session.	PlexRequests.UI.Modules.UserLoginModule	Debug	12/16/2016 1:59:51 PM

No need to auth	PlexRequests.UI.Modules.UserLoginModule	Debug	12/16/2016 1:59:51 PM

Username "Bjonness406" attempting to login	PlexRequests.UI.Modules.UserLoginModule	Debug	12/16/2016 1:59:51 PM
```

**Comment by SuperPotatoMen** [comment]
This is a BIG issue. Thanks for reporting. 
We need a Quick hotfix for this one @tidusjar

**Comment by tidusjar** [comment]
I agree. I'll fix this as soon as I get home and push out a new release

**Comment by bjonness406** [comment]
A way to fix this could be a checkbox to require a user(s) to login with their password on the user management page. So you can select only a few users to require passwords on login (like admin).

**Comment by tidusjar** [comment]
But the password field would be available for everyone? Even if they don't
need a password?

**Comment by porksandwich** [comment]
In the meantime, to bypass this issue, I created a new user with a separate name from my plex username, give it admin permissions, then stripped all permissions from the plex account username.

I don't use password authentication, and when trying to login with the new username, it doesn't allow me in without doing the proper admin login /w password.

I was actually going to report this, just had not got around to it yet.

**Comment by tidusjar** [comment]
Would you guys be against me removing the option to have no authentication?

**Comment by porksandwich** [comment]
My concern is local users.  I share mine with several family members for fast user switching.  Would there be a way to force them to set their own password upon first login?

**Comment by tidusjar** [comment]
Well you would create the users in the new user management section and set their passwords for them
they could then change it later on in their settings

**Comment by tidusjar** [comment]
Can you please try out the early access build to confirm this is fixed for you?

**Comment by porksandwich** [comment]
Still allowing me into the admin section without a password.

My old admin account was the same username as my plex account, this is the one allowing me into the admin section without authentication.

The new admin account with a separate name must login via the admin portal to get the proper privileges.

**Comment by bjonness406** [comment]
> Would you guys be against me removing the option to have no authentication?

I would be against it, since I only use it for me and some my friends. 
I like it so they can sign in with every username they want, then it gets easier for them to request things, not having to login every time with right username and password. 

If there was a way to still keep having this feature I would love it, but I would fully understand you if you removed it.

**Comment by tidusjar** [comment]
That's the thing, i'm not sure how I can keep it, since I want to merge the login screens as now there is not much sense in having two different ones... But I can't because it allows authentication without a password. I could have 2 different tabs (like on the search for movies or tv shows)

**Comment by tidusjar** [comment]
@porksandwich I'll take another look

**Comment by bjonness406** [comment]
I get your point.

A idea is to check up against the existing users when loggin in (even if "enable user authentication" is disabled), and deny access if password is not typed in on admin user.

This works fine then I have user authentication enabled, existing users login in the normal way (but only with the pre-created accounts). If they try to login with the admin username, they are not allowed. 
It should be like this also then the "enable user authentication" option is disabled.


On long term, it would be nice if users with no password get logged right in, and users with password got forwared to a new page requesting for the password to (or a dropdown menu). 
Right now if you enable user authentication, but disable "require users to login with their passwords", and create a new user with a password, they will need to login from the admin panel, if not they will get an error.

**Comment by tidusjar** [comment]
@porksandwich  can you try the new eap build now?

**Comment by porksandwich** [comment]
It was still letting me in.

I deleted the local admin account of the same username, stripped the permissions of the plex user.  Then I tried to recreate my same local account under the same username - but it wouldn't let me due to having a conflicting name (it already exists duh).

I'm guessing having a local account and plex account of the same name was causing some sort of permissions issues/conflict with the accounts.

However, if a Plex user is granted administrator privileges, it still allows you to login without authentication.  

Local users (created in user management) who have a password, do need to login via the admin portal rather than the primary landing page portal - even if they don't have admin privileges.

Is this the intended function?  I can see why you want to force passwords and unify that login.

I rather like @bjonness406 idea of checking against a preexisting userlist.

**Comment by tidusjar** [comment]
Ah ok,
There shouldn't be two accounts with the same name...
I think @bjonness406 has gave me a good idea with that. Have that preexisting list, if no auth is turned on, only show the username field, but if the user is in the list that needs the password, then show a password field after they enter their username.

I'll take *another* look at this issue, sorry about this

**Comment by porksandwich** [comment]
Just to clarify, the initial bug reported appears to have been solved for me.

**Comment by porksandwich** [comment]
And yeah @tidusjar, I'm guessing I had two accounts with the same name since back in the day (I was an early adopter) it let me create an admin account under the same username as my plex account.  I've been using that same db for a while now and it's oddly been functioning perfectly until this latest update.

Thanks for all your hard work!

**Comment by tidusjar** [comment]
It seems to be working for me:

http://i.imgur.com/YBp8h4t.gifv

**Comment by porksandwich** [comment]
Yeah, I double checked.  When I moved to the new EAP build, I use a DB copy with had enable user authentication checked.  So all of the above behavior is when that is enabled, and password authentication is disabled like this.

![capture](https://cloud.githubusercontent.com/assets/16330854/21281326/c18143aa-c3b9-11e6-9fe5-953f8baf658a.PNG)


When I un-check user authentication, the it functions as intended. 

My bad. :)

**Comment by tidusjar** [comment]
So everything is ok?

**Comment by porksandwich** [comment]
Yes indeed.
