### ISSUE TITLE
Notifications tab not displaying on v1.10.0

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#791]
#### Reproduction Steps: Sign in as any user, click the little notification bell tab on the search page. It won't show the options.
I checked the markup, I don't even see an element with the id "NotificationsTab" so it's not even getting to the client.

![image](https://cloud.githubusercontent.com/assets/4528753/21276591/b7445304-c397-11e6-9233-457a42159f7c.png)

**Comment by tidusjar** [comment]
Ah, must have forgot to remove the bell. My bad.

Notifications are managed in the User Management section now.
