### ISSUE TITLE
Reporting issues on TV shows

### ISSUE THREAD

**Issue by Drewster727** [tidusjar/PlexRequests.Net#792]
When a user goes to report an issue on a TV show, I would like to propose that we require either a comment or a choice of either a specific episode or specific season.

Example:
ShowXYZ Season 2 Episode 5 has a playback issue. 
Currently, the user can go in and just report a playback issue and the admin has no idea which season or episode is having the problem.
We need to force them to put in a comment, or even better, force them to choose a specific season of episodes or specific episode so we know which items to resolve.

**Comment by SuperPotatoMen** [comment]
Hi,

This is already a planned feature.  See master issue: https://github.com/tidusjar/PlexRequests.Net/issues/443
