### ISSUE TITLE
Run Window

### ISSUE THREAD

**Issue by bromanguydude** [tidusjar/PlexRequests.Net#795]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)

#### Plex Requests.Net Version:
1.10

#### Operating System:
Windows 10 Ultimate

#### Reproduction Steps:

Seems like after updating to the newest version the PlexRequests.exe cmd box needs to stay running in order for PlexRequests to be accessible. If the box is closed then PlexRequests is no longer running.

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by SuperPotatoMen** [comment]
In older versions that was also necessary, this not a bug.
