### ISSUE TITLE
Enable issue reporting on all media in Plex

### ISSUE THREAD

**Issue by ZeroManArmy** [tidusjar/PlexRequests.Net#799]
I have a completely automated system with multiple users who are requesting things constantly. Sometimes movies or TV shows download and they say 1080p but they aren't and have stupid issues. I don't have time to vent all the issues one by one. 

If I could direct everyone to go to the requests system and submit a ticket for anything on the server, I could start to resolve the issues without having to do it myself. 

Right now the system only allows for issues to reported for current requests.

**Comment by tidusjar** [comment]
If they search for the movie, it will show available and a button to report
the issue, does that help?

**Comment by ZeroManArmy** [comment]
That works well enough. I will inform my users to do that! Thanks!
