### ISSUE TITLE
Unable to grab all TVdb IDs

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#80]
It appears PlexRequests cannot grab the TVdb ID 100% of the time which leads to a "Bad Request"
Here are the log sections when you try to approve these bad requests:
Manually approving request: http://pastebin.com/wqf2QPEx
Auto approval: http://pastebin.com/uFFS0Gx5 

I was able to reproduce the error with the following shows:
[Wynonna Earp](https://thetvdb.com/?tab=series&id=305582 )
[The Girlfriend Experience](https://thetvdb.com/?tab=series&id=297346)
[Hunters](https://thetvdb.com/?tab=series&id=304962)
As you can see they all do have IDs.

At first I thought it was because they are unreleased but shows such as [Rush Hour
](https://thetvdb.com/?tab=series&id=298368) work

**Comment by tidusjar** [comment]
Interesting. Good find. 

We are not using TheTvDb api, in the 1.4.x release we switched to us ring TVMaze. 

I shall take a look into this.

**Comment by tidusjar** [comment]
It seems that TVMaze doesn't have the TheTVDB id's for any of those shows. I've just reported it to the TVMaze guys.

I think I might have to look into querying both the TVMaze api and if I cannot find any results, fallback to TheTvDB somehow.

**Comment by tedrock** [comment]
Could you possible include a more graceful way to handle the failure? The show currently gets added as "Bad Request (1)" so you have no idea what show it was and it will block all other ID missing requests (you get a message the request already exists).

**Comment by tidusjar** [comment]
Well since the request is separated from the search it's difficult without changing quite a few of the components, we pass the TVDB id when requesting and that is all, if it doesn't have it, it's difficult to know what was requested. So I could potentially block the request and say it's TVMaze fault and they need to fix it? 

Opinion?
