### ISSUE TITLE
Newsletter not working on cronjob.  Test is OK.

### ISSUE THREAD

**Issue by jneljeff** [tidusjar/PlexRequests.Net#809]
Sending the test newsletter works fine, but nothing goes out during cronjob.  See logs below.

#### Plex Requests.Net Version:
1.10.1

#### update Branch:

Stable

#### Operating System:

Ubuntu 16.04

#### Applicable Logs (from `/logs/` directory or the Admin page):

Message	Area	Log Level	Date
System.NullReferenceException: Object reference not set to an instance of an object at PlexRequests.Helpers.StringHelper+d__3.MoveNext () [0x00058] in <8bd4401c79bd407da1610ab2695e1159>:0 at PlexRequests.Services.Jobs.RecentlyAdded.Send (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.String html, PlexRequests.Core.SettingModels.PlexSettings plexSettings, System.Boolean testEmail) [0x00123] in <161ff1dc4dee4612ba5a780816422c6d>:0 at PlexRequests.Services.Jobs.RecentlyAdded.Start (PlexRequests.Core.SettingModels.NewletterSettings newletterSettings, System.Boolean testEmail) [0x00433] in <161ff1dc4dee4612ba5a780816422c6d>:0 at PlexRequests.Services.Jobs.RecentlyAdded.Execute (Quartz.IJobExecutionContext context) [0x00027] in <161ff1dc4dee4612ba5a780816422c6d>:0	PlexRequests.Services.Jobs.RecentlyAdded	Error	12/18/2016 2:30:12 PM
Created Plain/HTML MIME body	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:12 PM
Entering Send	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:12 PM
Loaded the template	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:12 PM
Finished Generating TV HTML	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:12 PM
Started Generating TV HTML	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:07 PM
Finished Generating Movie HTML	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:07 PM
Started Generating Movie HTML	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:00 PM
Got RecentlyAdded Movies	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:00 PM
Got RecentlyAdded TV Shows	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:00 PM
Filtered sections for Movies	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:00 PM
Filtered sections for TV	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:00 PM
Getting Plex Library Sections	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:00 PM
Got Plex Settings	PlexRequests.Services.Jobs.RecentlyAdded	Debug	12/18/2016 2:30:00 PM

**Comment by SuperPotatoMen** [comment]
Pleas use our bug report form layout and open a new issue.
