### ISSUE TITLE
TV Show URLs are using TVdb IDs for TMDB

### ISSUE THREAD

**Issue by tedrock** [tidusjar/PlexRequests.Net#81]
When you click on the title of a TV show it takes you to https://www.themoviedb.org/tv/298368 but that's actually the TVdb ID it's using (https://thetvdb.com/?tab=series&id=298368) so you get a failed search.

The correct ID for the above show is 65367 (https://www.themoviedb.org/tv/65367)

**Comment by tidusjar** [comment]
This has been fixed in the next release
The bug was #67
