### ISSUE TITLE
Not able to request future TV Shows

### ISSUE THREAD

**Issue by Ublala** [tidusjar/PlexRequests.Net#816]
When there is a request for a movie that is not released yet, one can just request it and it gets added to the list so that when it is available the request is filled.

I noticed that when one wants to request a TV Show that is not yet available PlexRequests.Net gives an error that something went wrong.

It seems it is not possible to request future TV Shows, is this intentional?

Examples: Beyond, Legion, Marvel's Iron Fist

**Comment by tidusjar** [comment]
Can you please provide an example of a TV show that does this?

**Comment by SuperPotatoMen** [comment]
Pleas open a new issue and use our bug report format.
