### ISSUE TITLE
Not receiving pushbullet notifciations for TV shows requested.

### ISSUE THREAD

**Issue by heartisall** [tidusjar/PlexRequests.Net#87]
I'm receiving notifications for movies just fine, but I logged in today and noticed several tv series were requested over the past few days that I wasn't notified of.

**Comment by tidusjar** [comment]
Really? That's strange, are you able to request a tv show and not get a notification now?

**Comment by heartisall** [comment]
Odd I just closed Plex requests and reopened it, logged in as one of my users and requested something and now It's working. I'll chalk it up as a fluke for now.

**Comment by tidusjar** [comment]
Hmm strange. I'm not sure why that would happen, There is 0 difference for notifying for movies or TV shows... I'll close this for now but if it happens again please let me know.
