### ISSUE TITLE
Start PlexRequests on boot (mono)

### ISSUE THREAD

**Issue by Codehhh** [tidusjar/PlexRequests.Net#90]
Mono flag to disable "Press any key to exit" to allow PlexRequests.Net to auto start on headless Debian server?

If there is another way to start "mono PlexRequests.exe" on boot this is not necessary.

**Comment by tidusjar** [comment]
What version are you running? I just release v1.5.0 that has better startup options for Linux.

**Comment by Codehhh** [comment]
Wow, that's some good timing! I've been trying to get it to autostart for the past couple of days! 
Got it working perfectly after a little bit of tinkering.
