### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by curlz620** [tidusjar/PlexRequests.Net#91]
I recently set plexrequests .net up and ran into an internal 500 error when attempting to access it. I unblocked the application and attempted to launch as an admin, but still run into this problem. Is there something during installation I am missing?

**Comment by tidusjar** [comment]
When you download the .zip file you should unblock the zip. Windows blocks .zips from unknown sources. That's it really. I've mentioned it in the FAQ and on the readme. 

So try and unblock the whole zip?

**Comment by curlz620** [comment]
Thank you! 
I guess i misunderstood. I unblocked just the application after it was extracted. Thanks for the quick reply.
