### ISSUE TITLE
Pushover Notifications not working

### ISSUE THREAD

**Issue by curlz620** [tidusjar/PlexRequests.Net#93]
I set up pushover and am able to test the same account using Plex Requests Meteor, but on .net it seems to not be working. I registered a new app within pushover just in case, but I cannot get it to send a notification. I even tried my wife's plex account to see if it wouldn't send notifications to the admin, but this didn't work either.

This also brings up the idea of adding a test button to the notification settings pages to test if it is set up properly.

**Comment by tidusjar** [comment]
There is a logs folder in the install directory, are there any errors? And i'm assuming it's enabled?

**Comment by curlz620** [comment]
2016/03/25 18:45:49.666 PlexRequests.UI.Program Trace: Getting product version
2016/03/25 18:45:49.682 PlexRequests.UI.Program Info: Version: 1.5.0
2016/03/25 18:45:49.682 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/03/25 18:45:49.682 PlexRequests.Store.DbConfiguration Trace: DB doesn't exist, creating a new one
2016/03/25 18:46:57.112 PlexRequests.UI.Program Trace: Getting product version
2016/03/25 18:46:57.112 PlexRequests.UI.Program Info: Version: 1.5.0
2016/03/25 18:46:57.112 PlexRequests.Store.DbConfiguration Trace: Checking DB
2016/03/25 19:15:04.200 PlexRequests.UI.Program Trace: Getting product version
2016/03/25 19:15:04.200 PlexRequests.UI.Program Info: Version: 1.5.0
2016/03/25 19:15:04.200 PlexRequests.Store.DbConfiguration Trace: Checking DB


I did a quick reboot just in case you can see it in the logs. otherwise it doesn't seem to even show my requests. i requested 3 movies and 1 tv show.

**Comment by tidusjar** [comment]
Are you looking in the settings or the `/logs` folder in the install directory?

And you got it enabled and also the Api Key is the app key and the User Token is the user key right?

**Comment by curlz620** [comment]
that is the from /logs folder in the file 2016-03-25 

I believe the logs are enabled. i double checked and clicked debug then submit and rerequested a movie. Yes I checked the User and API key a few times, they are correct. I also tried error as well for the log level. either way it doesn't make a change to the log file.

**Comment by tidusjar** [comment]
Can you jump on gitter? https://gitter.im/tidusjar/PlexRequests.Net

**Comment by tidusjar** [comment]
This bug has now been fixed. I'll raise a separate issue for the test buttons.
